# Sorting

In [1]:
import pandas as pd

.sort_values(
    by,
    axis=0,
    ascending=True,
    inplace=False,
    kind='quicksort',
    na_position='last',
    ignore_index=False,
    key=None
)

## PART 1: Series Sorting

In [2]:
s = pd.Series([120, 450, 300, 800, 150, 220, 90, 600, 700, 50])

In [3]:
s

0    120
1    450
2    300
3    800
4    150
5    220
6     90
7    600
8    700
9     50
dtype: int64

#### 1. Sort values ascending

In [4]:
s.sort_values()

9     50
6     90
0    120
4    150
5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

#### 2. Sort values descending

In [5]:
s.sort_values(ascending=False)

3    800
8    700
7    600
1    450
2    300
5    220
4    150
0    120
6     90
9     50
dtype: int64

#### 3. Get top 5 highest values

In [7]:
s.sort_values(ascending=False).head()

3    800
8    700
7    600
1    450
2    300
dtype: int64

In [8]:
s.nlargest(5)

3    800
8    700
7    600
1    450
2    300
dtype: int64

#### 4. Get bottom 3 smallest values

In [9]:
s.sort_values().head(3)

9     50
6     90
0    120
dtype: int64

In [10]:
s.nsmallest(3)

9     50
6     90
0    120
dtype: int64

#### 5. Sort values and reset index

In [11]:
s.sort_values()

9     50
6     90
0    120
4    150
5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

In [12]:
s.sort_values().reset_index()

   index    0
0      9   50
1      6   90
2      0  120
3      4  150
4      5  220
5      2  300
6      1  450
7      7  600
8      8  700
9      3  800

In [13]:
s.sort_values().reset_index(drop=True)

0     50
1     90
2    120
3    150
4    220
5    300
6    450
7    600
8    700
9    800
dtype: int64

#### 6. Sort values and keep original index

In [14]:
s.sort_values()

9     50
6     90
0    120
4    150
5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

#### 7. Sort values but place NaN at the end

In [15]:
s.sort_values( na_position='last')

9     50
6     90
0    120
4    150
5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

In [17]:
s2 = pd.Series([22,1,13,24,17,None,22, 0, None,11])

In [18]:
s2

0    22.0
1     1.0
2    13.0
3    24.0
4    17.0
5     NaN
6    22.0
7     0.0
8     NaN
9    11.0
dtype: float64

In [19]:
s2.sort_values(na_position='last')

7     0.0
1     1.0
9    11.0
2    13.0
4    17.0
0    22.0
6    22.0
3    24.0
5     NaN
8     NaN
dtype: float64

#### 8. Sort values based on absolute difference from mean

In [20]:
mean_value = s.mean()
sorted_s = s.sort_values(key=lambda x : abs(x-mean_value))
sorted_s

2    300
1    450
5    220
4    150
0    120
7    600
6     90
9     50
8    700
3    800
dtype: int64

#### 9. Sort values based on remainder when divided by 10

In [22]:
s.sort_values(key=lambda x:x%10)

0    120
1    450
2    300
3    800
4    150
5    220
6     90
7    600
8    700
9     50
dtype: int64

#### 10. Sort values and remove duplicates

In [23]:
s3 = pd.Series([40, 10, 20, 10, 30, 40, 50])
s3

0    40
1    10
2    20
3    10
4    30
5    40
6    50
dtype: int64

In [26]:
s3.sort_values().drop_duplicates()

1    10
2    20
4    30
0    40
6    50
dtype: int64

In [30]:
s3.sort_values().drop_duplicates().reset_index(drop=True)

0    10
1    20
2    30
3    40
4    50
dtype: int64

#### 11. Sort values based on custom condition (even numbers first, then odd)

In [31]:
s.sort_values(key=lambda x: x % 2)

0    120
1    450
2    300
3    800
4    150
5    220
6     90
7    600
8    700
9     50
dtype: int64

In [33]:
s4 = pd.Series([7, 2, 9, 4, 11, 6, 3, 8])

In [34]:
s4.sort_values(key=lambda x: x%2)

1     2
3     4
7     8
5     6
2     9
0     7
4    11
6     3
dtype: int64

#### 12. Sort values in descending order but keep index aligned

In [36]:
s.sort_values(ascending=False)

3    800
8    700
7    600
1    450
2    300
5    220
4    150
0    120
6     90
9     50
dtype: int64

#### 13. Rank values and sort based on rank

In [39]:
s.rank().sort_values()

9     1.0
6     2.0
0     3.0
4     4.0
5     5.0
2     6.0
1     7.0
7     8.0
8     9.0
3    10.0
dtype: float64

#### 14. Sort values within a rolling window

In [40]:
s.rolling(window=3).apply(lambda x: sorted(x)[-1])

0      NaN
1      NaN
2    450.0
3    800.0
4    800.0
5    800.0
6    220.0
7    600.0
8    700.0
9    700.0
dtype: float64

#### 15. Filter employees earning above department average salary

In [47]:
mean_val = s.mean()
s[s > mean_val].sort_values()

1    450
7    600
8    700
3    800
dtype: int64

## 16. Sort values based on distance from mean

In [48]:
s.sort_values(key=lambda x: abs(x - x.mean()))

2    300
1    450
5    220
4    150
0    120
7    600
6     90
9     50
8    700
3    800
dtype: int64

#### 17. Sort values closest to median first

In [49]:
s.sort_values(key = lambda x : abs(x- s.median()))

2    300
5    220
4    150
0    120
6     90
1    450
9     50
7    600
8    700
3    800
dtype: int64

#### 18. Sort only values greater than 200

In [50]:
s[s>200].sort_values()

5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

#### 19. Sort based on square of values

In [53]:
s.sort_values(key =lambda a : a**2)

9     50
6     90
0    120
4    150
5    220
2    300
1    450
7    600
8    700
3    800
dtype: int64

#### 20.  Sort values and return top 25%

In [54]:
s.sort_values(ascending=False).head(int(len(s) * 0.25))

3    800
8    700
dtype: int64

#

## 🔹 PART 2: DataFrame Sorting

In [55]:
df = pd.read_csv("col_row-dataset.csv")

In [58]:
df.sample(5)

      id  name   age     city   salary department  experience
167  168  John  23.0     Pune  40000.0    Finance         3.0
77    78  Sita  21.0    Delhi  40000.0    Finance         1.0
447  448  Ravi  21.0  Chennai  60000.0         HR         8.0
375  376   Anu  18.0  Chennai  60000.0         IT         4.0
41    42   Anu  22.0      NaN  50000.0    Finance         7.0

#### 1. Sort by age ascending

In [59]:
df['age'].sort_values()

24     18.0
23     18.0
465    18.0
38     18.0
472    18.0
       ...
437     NaN
444     NaN
469     NaN
490     NaN
491     NaN
Name: age, Length: 500, dtype: float64

In [61]:
df.sort_values(by='age').head(10)

      id   name   age       city   salary department  experience
24    25   Amit  18.0  Bangalore  40000.0  Marketing         NaN
23    24  Kiran  18.0     Mumbai      NaN    Finance         NaN
465  466    Anu  18.0       Pune  40000.0    Finance         4.0
38    39  Kiran  18.0  Hyderabad  20000.0      Sales         4.0
472  473    Anu  18.0       Pune      NaN      Sales         2.0
416  417  Kiran  18.0  Bangalore  40000.0  Marketing         8.0
68    69   Amit  18.0      Delhi  20000.0         IT         3.0
75    76   John  18.0     Mumbai      NaN         HR         7.0
419  420   Amit  18.0     Mumbai  30000.0  Marketing         NaN
84    85   Ravi  18.0    Chennai      NaN      Sales         4.0

#### 2. Sort by salary descending

In [64]:
df.sort_values(by ='salary',ascending= False).head(154)

      id   name   age       city   salary department  experience
498  499   Ravi  21.0        NaN  60000.0  Marketing         4.0
1      2  Kiran  21.0        NaN  60000.0         IT         7.0
473  474   Amit  25.0  Bangalore  60000.0         IT         7.0
466  467    Anu  19.0       Pune  60000.0      Sales         6.0
44    45   Ravi  24.0      Delhi  60000.0         IT         3.0
..   ...    ...   ...        ...      ...        ...         ...
417  418  Kiran  25.0      Delhi  50000.0         HR         4.0
422  423   John  25.0  Bangalore  50000.0  Marketing         NaN
423  424   Neha  23.0     Mumbai  50000.0    Finance         4.0
196  197   John  22.0    Chennai  50000.0         IT         1.0
481  482   Sita  24.0     Mumbai  50000.0    Finance         6.0

[154 rows x 7 columns]

#### 3. Sort by name alphabetically

In [69]:
df.sort_values(by="name").head()

      id  name   age       city   salary department  experience
181  182  Amit   NaN    Chennai  40000.0      Sales         8.0
385  386  Amit  23.0      Delhi  50000.0      Sales         2.0
419  420  Amit  18.0     Mumbai  30000.0  Marketing         NaN
212  213  Amit  21.0      Delhi  20000.0      Sales         NaN
267  268  Amit  20.0  Hyderabad  30000.0         HR         6.0

In [70]:
df.sort_values(by="name").tail()

      id  name   age       city   salary department  experience
297  298  Sita  23.0  Bangalore  40000.0  Marketing         2.0
437  438  Sita   NaN      Delhi  30000.0         IT         4.0
346  347  Sita  22.0    Chennai  60000.0  Marketing         NaN
290  291  Sita  20.0       Pune      NaN         IT         3.0
455  456  Sita  23.0       Pune      NaN      Sales         8.0

#### 4. Sort by city

In [76]:
df.sort_values(by = 'city')

      id   name   age       city   salary department  experience
102  103  Kiran  25.0  Bangalore  60000.0      Sales         NaN
442  443   John  22.0  Bangalore      NaN         HR         NaN
266  267   Neha  20.0  Bangalore  40000.0         IT         NaN
268  269   Sita  24.0  Bangalore      NaN      Sales         3.0
444  445   Neha   NaN  Bangalore  30000.0         HR         6.0
..   ...    ...   ...        ...      ...        ...         ...
462  463   Neha  20.0        NaN  40000.0  Marketing         6.0
467  468   Amit  19.0        NaN  50000.0         HR         7.0
495  496   Neha  24.0        NaN  40000.0    Finance         7.0
496  497   Ravi  24.0        NaN      NaN  Marketing         6.0
498  499   Ravi  21.0        NaN  60000.0  Marketing         4.0

[500 rows x 7 columns]

#### 5. Sort by experience

In [80]:
df.sort_values(by ='experience')

      id   name   age       city   salary department  experience
26    27   Neha  22.0      Delhi  50000.0      Sales         1.0
27    28   John  24.0  Hyderabad  50000.0         HR         1.0
449  450   Sita  19.0      Delhi  20000.0         IT         1.0
46    47   Amit  20.0     Mumbai  50000.0    Finance         1.0
410  411   Neha  24.0  Hyderabad      NaN    Finance         1.0
..   ...    ...   ...        ...      ...        ...         ...
454  455   Amit  19.0      Delhi  40000.0  Marketing         NaN
461  462   Ravi  20.0    Chennai  40000.0  Marketing         NaN
463  464  Kiran  19.0     Mumbai      NaN         HR         NaN
487  488   Amit  19.0  Bangalore  30000.0      Sales         NaN
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

[500 rows x 7 columns]

#### 6. Sort by salary then age

In [82]:
df.sort_values(by =["salary",'age']).head(15)

      id   name   age       city   salary department  experience
38    39  Kiran  18.0  Hyderabad  20000.0      Sales         4.0
68    69   Amit  18.0      Delhi  20000.0         IT         3.0
127  128   Sita  18.0       Pune  20000.0      Sales         7.0
271  272   Ravi  18.0  Hyderabad  20000.0      Sales         2.0
327  328   Neha  18.0     Mumbai  20000.0         IT         3.0
55    56   Amit  19.0      Delhi  20000.0         IT         8.0
118  119  Kiran  19.0       Pune  20000.0         IT         2.0
240  241    Anu  19.0     Mumbai  20000.0      Sales         3.0
296  297   Neha  19.0       Pune  20000.0      Sales         6.0
340  341  Kiran  19.0      Delhi  20000.0  Marketing         4.0
359  360   Ravi  19.0        NaN  20000.0  Marketing         7.0
373  374   Sita  19.0      Delhi  20000.0      Sales         NaN
396  397   Amit  19.0     Mumbai  20000.0         HR         4.0
406  407    Anu  19.0    Chennai  20000.0    Finance         1.0
449  450   Sita  19.0      Delhi  20000.0         IT         1.0

In [83]:
df.sort_values(by =["salary",'age']).tail(15)

      id   name   age       city  salary department  experience
496  497   Ravi  24.0        NaN     NaN  Marketing         6.0
66    67   Sita  25.0    Chennai     NaN         IT         7.0
164  165   John  25.0  Bangalore     NaN    Finance         NaN
193  194    Anu  25.0      Delhi     NaN         HR         6.0
361  362    Anu  25.0  Bangalore     NaN    Finance         1.0
395  396   Ravi  25.0       Pune     NaN         HR         1.0
415  416   Amit  25.0        NaN     NaN      Sales         6.0
486  487  Kiran  25.0  Hyderabad     NaN         HR         1.0
12    13   Amit   NaN    Chennai     NaN         IT         2.0
40    41   John   NaN     Mumbai     NaN      Sales         7.0
133  134   Ravi   NaN  Hyderabad     NaN  Marketing         2.0
239  240   Ravi   NaN     Mumbai     NaN  Marketing         4.0
247  248   John   NaN        NaN     NaN         HR         8.0
250  251    Anu   NaN    Chennai     NaN         IT         1.0
378  379   Neha   NaN    Chennai     NaN         IT         7.0

#### 7. Sort by department then experience

In [84]:
df.sort_values(by=['department','experience'])

      id   name   age       city   salary department  experience
46    47   Amit  20.0     Mumbai  50000.0    Finance         1.0
77    78   Sita  21.0      Delhi  40000.0    Finance         1.0
93    94   Neha  22.0        NaN  40000.0    Finance         1.0
169  170   Neha  24.0     Mumbai  60000.0    Finance         1.0
184  185   John   NaN     Mumbai  50000.0    Finance         1.0
..   ...    ...   ...        ...      ...        ...         ...
282  283   Ravi  24.0  Hyderabad  30000.0      Sales         NaN
294  295  Kiran  22.0  Bangalore  30000.0      Sales         NaN
373  374   Sita  19.0      Delhi  20000.0      Sales         NaN
443  444   Neha  19.0      Delhi  40000.0      Sales         NaN
487  488   Amit  19.0  Bangalore  30000.0      Sales         NaN

[500 rows x 7 columns]

#### 8. Sort by city then name

In [85]:
df.sort_values(by=['city','name'])

      id  name   age       city   salary department  experience
2      3  Amit  23.0  Bangalore      NaN  Marketing         2.0
19    20  Amit  19.0  Bangalore  60000.0  Marketing         8.0
24    25  Amit  18.0  Bangalore  40000.0  Marketing         NaN
61    62  Amit  21.0  Bangalore  30000.0  Marketing         7.0
79    80  Amit  21.0  Bangalore  50000.0      Sales         4.0
..   ...   ...   ...        ...      ...        ...         ...
130  131  Sita   NaN        NaN  30000.0  Marketing         2.0
152  153  Sita  23.0        NaN      NaN    Finance         7.0
166  167  Sita  19.0        NaN  60000.0  Marketing         5.0
377  378  Sita   NaN        NaN  20000.0    Finance         7.0
445  446  Sita  20.0        NaN  20000.0         HR         6.0

[500 rows x 7 columns]

#### 9. Sort by salary (NaN last)

In [86]:
df.sort_values(by='salary').tail()

      id   name   age       city  salary department  experience
468  469  Kiran  24.0  Hyderabad     NaN         IT         6.0
472  473    Anu  18.0       Pune     NaN      Sales         2.0
486  487  Kiran  25.0  Hyderabad     NaN         HR         1.0
488  489   Neha  21.0       Pune     NaN         IT         2.0
496  497   Ravi  24.0        NaN     NaN  Marketing         6.0

#### 10. Sort by multiple columns with different order

In [88]:
df.sort_values(by=['department', 'salary'],ascending=[True, False])

      id   name   age       city   salary department  experience
7      8   John  25.0  Bangalore  60000.0    Finance         3.0
8      9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
15    16   Sita  22.0      Delhi  60000.0    Finance         5.0
18    19    Anu  21.0       Pune  60000.0    Finance         NaN
90    91   Neha  19.0    Chennai  60000.0    Finance         NaN
..   ...    ...   ...        ...      ...        ...         ...
407  408   Neha  18.0    Chennai      NaN      Sales         5.0
415  416   Amit  25.0        NaN      NaN      Sales         6.0
452  453    Anu  23.0  Hyderabad      NaN      Sales         6.0
455  456   Sita  23.0       Pune      NaN      Sales         8.0
472  473    Anu  18.0       Pune      NaN      Sales         2.0

[500 rows x 7 columns]

#### 11. Get top 10 highest salary rows

In [91]:
df.nlargest(10,columns='salary')

    id   name   age       city   salary department  experience
1    2  Kiran  21.0        NaN  60000.0         IT         7.0
7    8   John  25.0  Bangalore  60000.0    Finance         3.0
8    9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
15  16   Sita  22.0      Delhi  60000.0    Finance         5.0
18  19    Anu  21.0       Pune  60000.0    Finance         NaN
19  20   Amit  19.0  Bangalore  60000.0  Marketing         8.0
20  21   Ravi  22.0    Chennai  60000.0         HR         NaN
37  38   John  19.0       Pune  60000.0         IT         8.0
44  45   Ravi  24.0      Delhi  60000.0         IT         3.0
48  49   Neha  19.0        NaN  60000.0         IT         7.0

#### 12. Get lowest 5 experience rows

In [92]:
df.nsmallest(5,columns='experience')

    id  name   age       city   salary department  experience
6    7  Ravi  24.0    Chennai  30000.0         HR         1.0
26  27  Neha  22.0      Delhi  50000.0      Sales         1.0
27  28  John  24.0  Hyderabad  50000.0         HR         1.0
45  46  Ravi  21.0     Mumbai  20000.0  Marketing         1.0
46  47  Amit  20.0     Mumbai  50000.0    Finance         1.0

#### 13. Sort employees by salary within department

In [94]:
df.sort_values(by=['department', 'salary'])

      id   name   age       city   salary department  experience
54    55   Sita  23.0       Pune  20000.0    Finance         3.0
129  130   John  20.0        NaN  20000.0    Finance         2.0
146  147   John  24.0  Bangalore  20000.0    Finance         6.0
161  162    Anu  23.0      Delhi  20000.0    Finance         3.0
217  218  Kiran  20.0  Hyderabad  20000.0    Finance         4.0
..   ...    ...   ...        ...      ...        ...         ...
407  408   Neha  18.0    Chennai      NaN      Sales         5.0
415  416   Amit  25.0        NaN      NaN      Sales         6.0
452  453    Anu  23.0  Hyderabad      NaN      Sales         6.0
455  456   Sita  23.0       Pune      NaN      Sales         8.0
472  473    Anu  18.0       Pune      NaN      Sales         2.0

[500 rows x 7 columns]

#### 14. Sort employees by experience within city

In [95]:
df.sort_values(by=['experience','city'])

      id   name   age       city   salary department  experience
153  154    Anu  22.0  Bangalore  60000.0         IT         1.0
249  250   Neha  22.0  Bangalore  50000.0         IT         1.0
251  252   John  20.0  Bangalore  50000.0      Sales         1.0
272  273  Kiran  22.0  Bangalore  50000.0    Finance         1.0
356  357   John  25.0  Bangalore  40000.0         HR         1.0
..   ...    ...   ...        ...      ...        ...         ...
313  314   Amit  18.0       Pune      NaN         HR         NaN
333  334   Ravi  18.0       Pune  50000.0  Marketing         NaN
450  451  Kiran  24.0       Pune  40000.0         HR         NaN
199  200   Neha  24.0        NaN  20000.0         HR         NaN
388  389   John  21.0        NaN  50000.0  Marketing         NaN

[500 rows x 7 columns]

#### 15. Sort dataset by length of names

In [96]:
df.sort_values(by='name', key=lambda x: x.str.len())

      id   name   age       city   salary department  experience
17    18    Anu  18.0      Delhi      NaN  Marketing         5.0
18    19    Anu  21.0       Pune  60000.0    Finance         NaN
31    32    Anu  19.0        NaN      NaN         HR         2.0
465  466    Anu  18.0       Pune  40000.0    Finance         4.0
466  467    Anu  19.0       Pune  60000.0      Sales         6.0
..   ...    ...   ...        ...      ...        ...         ...
497  498  Kiran  20.0     Mumbai  20000.0         IT         4.0
340  341  Kiran  19.0      Delhi  20000.0  Marketing         4.0
446  447  Kiran  21.0      Delhi  60000.0  Marketing         4.0
341  342  Kiran  23.0    Chennai  40000.0  Marketing         3.0
416  417  Kiran  18.0  Bangalore  40000.0  Marketing         8.0

[500 rows x 7 columns]

#### 16. Sort dataset by salary difference from mean

In [97]:
df.sort_values(by='salary', key=lambda x: abs(x-x.mean()))

      id   name   age       city   salary department  experience
499  500   John  23.0     Mumbai  40000.0    Finance         NaN
3      4   John  25.0     Mumbai  40000.0  Marketing         NaN
495  496   Neha  24.0        NaN  40000.0    Finance         7.0
476  477   John  23.0    Chennai  40000.0    Finance         8.0
47    48   Sita   NaN    Chennai  40000.0         IT         8.0
..   ...    ...   ...        ...      ...        ...         ...
468  469  Kiran  24.0  Hyderabad      NaN         IT         6.0
472  473    Anu  18.0       Pune      NaN      Sales         2.0
486  487  Kiran  25.0  Hyderabad      NaN         HR         1.0
488  489   Neha  21.0       Pune      NaN         IT         2.0
496  497   Ravi  24.0        NaN      NaN  Marketing         6.0

[500 rows x 7 columns]

#### 17. Sort by salary/experience ratio

In [99]:
df.sort_values(by='salary',key=lambda x: df['salary'] / df['experience'])

      id   name   age       city   salary department  experience
55    56   Amit  19.0      Delhi  20000.0         IT         8.0
360  361  Kiran  21.0  Hyderabad  20000.0    Finance         8.0
174  175  Kiran  20.0  Hyderabad  20000.0         HR         8.0
401  402   Neha  23.0  Hyderabad  20000.0         HR         8.0
367  368   John  21.0  Hyderabad  20000.0         HR         8.0
..   ...    ...   ...        ...      ...        ...         ...
486  487  Kiran  25.0  Hyderabad      NaN         HR         1.0
487  488   Amit  19.0  Bangalore  30000.0      Sales         NaN
488  489   Neha  21.0       Pune      NaN         IT         2.0
496  497   Ravi  24.0        NaN      NaN  Marketing         6.0
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

[500 rows x 7 columns]

#### 18. Sort departments by average salary

In [101]:
df.groupby('department')['salary'].mean().sort_values(ascending=False)

department
Finance      42100.000000
Marketing    40454.545455
Sales        40389.610390
IT           38902.439024
HR           36621.621622
Name: salary, dtype: float64

#### 19. Sort cities by employee count

In [103]:
df.groupby('city')['name'].count()

city
Bangalore    79
Chennai      75
Delhi        79
Hyderabad    73
Mumbai       69
Pune         73
Name: name, dtype: int64

#### 20. Sort by most frequent names

In [107]:
df['name'].value_counts().sort_values(ascending=False)

name
John     88
Amit     83
Kiran    72
Ravi     69
Neha     64
Sita     64
Anu      60
Name: count, dtype: int64