# Data Cleaning Practice 1

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data_cleaning_ds1.csv')

In [3]:
data

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
0,1,Danielle,25.0,25000.0,NaN,Delhi,4.0,john21@yang.com
1,2,Anthony,30.0,35000.0,NaN,Bangalore,2.0,williamjohnson@baldwin.net
2,3,Robert,40.0,25000.0,IT,Bangalore,4.0,lisa02@hotmail.com
3,4,Roberto,30.0,65000.0,Marketing,Bangalore,4.0,jasongallagher@gmail.com
4,5,Christopher,40.0,35000.0,Sales,Hyderabad,5.0,melanie94@blair.com
...,...,...,...,...,...,...,...,...
96,97,Jacqueline,40.0,NaN,NaN,Mumbai,5.0,mcdanielsandra@hotmail.com
97,98,Brittany,40.0,65000.0,IT,Delhi,5.0,owilson@hernandez.com
98,99,Gabriel,30.0,55000.0,Marketing,Hyderabad,NaN,scott74@hotmail.com
99,100,richard,45.0,55000.0,Sales,NaN,4.0,mkim@gmail.com
100,6,Teresa,22.0,75000.0,HR,NaN,7.0,arnoldmaria@hotmail.com

#

#

In [5]:
df = data.copy()

#

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  101 non-null    int64
 1   Name         101 non-null    object
 2   Age          87 non-null     float64
 3   Salary       85 non-null     float64
 4   Department   85 non-null     object
 5   City         83 non-null     object
 6   Experience   85 non-null     float64
 7   Email        101 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 6.4+ KB

#

In [9]:
df.dtypes

Employee_ID      int64
Name            object
Age            float64
Salary         float64
Department      object
City            object
Experience     float64
Email           object
dtype: object

In [10]:
df.isnull().sum()

Employee_ID     0
Name            0
Age            14
Salary         16
Department     16
City           18
Experience     16
Email           0
dtype: int64

In [14]:
df['Department'].unique()

array([nan, 'IT', 'Marketing', 'Sales', 'HR', 'Finance'], dtype=object)

In [15]:
df['City'].unique()

array(['Delhi', 'Bangalore', 'Hyderabad', nan, 'Mumbai', 'Pune'],
      dtype=object)

In [17]:
df.duplicated().sum()

np.int64(1)

In [18]:
df = df.drop_duplicates()

In [19]:
df.duplicated().sum()

np.int64(0)

#

In [21]:
df['Employee_ID'].duplicated().sum()

np.int64(1)

In [22]:
df[df['Employee_ID'].duplicated() == True]

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
54,20,William,35.0,55000.0,NaN,NaN,8.0,richard48@gmail.com

In [23]:
df[df['Employee_ID'] == 20]

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
19,20,stacey,NaN,35000.0,NaN,Pune,7.0,wcabrera@cannon.net
54,20,William,35.0,55000.0,NaN,NaN,8.0,richard48@gmail.com

In [25]:
df = df.drop_duplicates(subset='Employee_ID')

In [26]:
df[df['Employee_ID'] == 20]

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
19,20,stacey,NaN,35000.0,NaN,Pune,7.0,wcabrera@cannon.net

In [27]:
df[df['Employee_ID'].duplicated() == True]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Salary, Department, City, Experience, Email]
Index: []

# Extra Spaces

In [30]:
df.head()

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
0,1,Danielle,25.0,25000.0,NaN,Delhi,4.0,john21@yang.com
1,2,Anthony,30.0,35000.0,NaN,Bangalore,2.0,williamjohnson@baldwin.net
2,3,Robert,40.0,25000.0,IT,Bangalore,4.0,lisa02@hotmail.com
3,4,Roberto,30.0,65000.0,Marketing,Bangalore,4.0,jasongallagher@gmail.com
4,5,Christopher,40.0,35000.0,Sales,Hyderabad,5.0,melanie94@blair.com

In [34]:
ob_col = df.select_dtypes(include='object').columns

In [35]:
ob_col

Index(['Name', 'Department', 'City', 'Email'], dtype='object')

In [36]:
for col in ob_col:
    df[col] = df[col].str.strip()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9688\1465158120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip()

In [37]:
df["Name"] = df["Name"].str.title()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_9688\1192047857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Name"] = df["Name"].str.title()

In [43]:
df.loc[:,"Name"] = df["Name"].str.title()

In [44]:
df['Name'] = df['Name'].str.replace(r'[^A-Za-z]','',regex=True)

In [46]:
df['Name'] = df['Name'].str.replace(r'^\s*$','',regex=True)

#

In [47]:
df['Department'].unique()

array([nan, 'IT', 'Marketing', 'Sales', 'HR', 'Finance'], dtype=object)

In [48]:
df.loc[:,"Email"] = df["Email"].str.lower()

In [49]:
df['Email'] = df['Email'].str.replace(r'^\s*$','',regex=True)

In [50]:
df.head()

,Employee_ID,Name,Age,Salary,Department,City,Experience,Email
0,1,Danielle,25.0,25000.0,NaN,Delhi,4.0,john21@yang.com
1,2,Anthony,30.0,35000.0,NaN,Bangalore,2.0,williamjohnson@baldwin.net
2,3,Robert,40.0,25000.0,IT,Bangalore,4.0,lisa02@hotmail.com
3,4,Roberto,30.0,65000.0,Marketing,Bangalore,4.0,jasongallagher@gmail.com
4,5,Christopher,40.0,35000.0,Sales,Hyderabad,5.0,melanie94@blair.com

#

#

# Missing Values

In [52]:
df.isna().sum()

Employee_ID     0
Name            0
Age            14
Salary         16
Department     15
City           16
Experience     16
Email           0
dtype: int64

In [54]:
(df.isna().mean())*100

Employee_ID     0.000000
Name            0.000000
Age            14.141414
Salary         16.161616
Department     15.151515
City           16.161616
Experience     16.161616
Email           0.000000
dtype: float64

In [55]:
df['Age'].unique()

array([25., 30., 40., 22., nan, 45., 28., 35.])

In [61]:
df['Department'].unique()

array([nan, 'IT', 'Marketing', 'Sales', 'HR', 'Finance'], dtype=object)

In [62]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [63]:
df['Department'].unique()

array(['IT', 'Marketing', 'Sales', 'HR', 'Finance'], dtype=object)

In [64]:
df['Department'].isna().sum()

np.int64(0)

In [65]:
df['Age'] = df.groupby('Department')['Age'].transform(lambda x: x.fillna(x.median()))

In [67]:
df.isna().sum()

Employee_ID     0
Name            0
Age             0
Salary         16
Department      0
City           16
Experience     16
Email           0
dtype: int64

In [68]:
df['Salary'] = df.groupby('Department')['Salary'].transform(lambda x: x.fillna(x.median()))

In [70]:
df['Salary'].isna().sum()

np.int64(0)

In [71]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [72]:
df.isnull().sum()

Employee_ID     0
Name            0
Age             0
Salary          0
Department      0
City            0
Experience     16
Email           0
dtype: int64

In [73]:
df['Experience'] = df.groupby('Department')['Experience'].transform(lambda x: x.fillna(x.median()))

In [74]:
df.isna().sum()

Employee_ID    0
Name           0
Age            0
Salary         0
Department     0
City           0
Experience     0
Email          0
dtype: int64

#

#

# Check Valid Email

In [76]:
df['Email']

0                john21@yang.com
1     williamjohnson@baldwin.net
2             lisa02@hotmail.com
3       jasongallagher@gmail.com
4            melanie94@blair.com
                 ...
95        mhayes@carter-hall.com
96    mcdanielsandra@hotmail.com
97         owilson@hernandez.com
98           scott74@hotmail.com
99                mkim@gmail.com
Name: Email, Length: 99, dtype: object

In [77]:
df[~df["Email"].str.contains(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$', na=False)]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Salary, Department, City, Experience, Email]
Index: []

#

# Datatypes

In [79]:
df.dtypes

Employee_ID      int64
Name            object
Age              int64
Salary         float64
Department      object
City            object
Experience     float64
Email           object
dtype: object

In [78]:
df["Age"] = df["Age"].astype(int)

In [83]:
df['Experience'].unique()

array([4. , 2. , 5. , 7. , 5.5, 4.5, 8. , 3. , 1. ])

In [84]:
df.describe()

       Employee_ID        Age        Salary  Experience
count    99.000000  99.000000     99.000000   99.000000
mean     50.454545  31.070707  48080.808081    4.207071
std      29.155555   6.664332  16655.376510    1.954861
min       1.000000  22.000000  25000.000000    1.000000
25%      25.500000  26.000000  35000.000000    3.000000
50%      50.000000  30.000000  45000.000000    4.000000
75%      75.500000  35.000000  65000.000000    5.000000
max     100.000000  45.000000  75000.000000    8.000000

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  99 non-null     int64
 1   Name         99 non-null     object
 2   Age          99 non-null     int64
 3   Salary       99 non-null     float64
 4   Department   99 non-null     object
 5   City         99 non-null     object
 6   Experience   99 non-null     float64
 7   Email        99 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 7.0+ KB