# Pandas Data straucture

In [1]:
import pandas as pd

In [14]:
import numpy as np

## ---Series---

#### 1. Create a Series from list [1, 2, 3, 4, 5].

In [6]:
my_list =[1, 2, 3, 4, 5]
s1 = pd.Series(my_list)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

#### 2. Create a Series with values [10, 20, 30] and index a, b, c.

In [7]:
s2 = pd.Series([10,20,30],index=['a','b','c'])
s2

a    10
b    20
c    30
dtype: int64

#### 3. Create a Series from dictionary:
{"x": 5, "y": 10, "z": 15}

In [8]:
my_d = {"x": 5, "y": 10, "z": 15}
my_d

{'x': 5, 'y': 10, 'z': 15}

In [9]:
s3 = pd.Series(my_d)
s3

x     5
y    10
z    15
dtype: int64

#### 4. Create a Series with value 100 repeated 4 times.

In [11]:
s4 = pd.Series(100,index=range(4))
s4

0    100
1    100
2    100
3    100
dtype: int64

#### 5. Print the value at index b.

In [12]:
s5 = pd.Series([10,20,30],index=['a','b','c'])
s5['b']

np.int64(20)

In [13]:
s5[1]

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_22324\2238760857.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s5[1]

np.int64(20)

#### 6. Print all values greater than 15.

In [17]:
np.random.seed(42)
ar1 = np.random.randint(1,25,8)
s6 = pd.Series(ar1)
s6

0     7
1    20
2    15
3    11
4     8
5    21
6     7
7    19
dtype: int32

In [18]:
s6[s6>15]

1    20
5    21
7    19
dtype: int32

#### 7. Create a Series from a NumPy array.

In [19]:
a = np.arange(10)
s7 = pd.Series(a)
s7

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

#### 8. Add 5 to all elements in a Series.

In [20]:
s7+5

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

#### 9. Convert a list [2,4,6,8] into Series and multiply all values by 2.

In [22]:
l1 = [2,4,6,8]
s9 = pd.Series(l1)
s9

0    2
1    4
2    6
3    8
dtype: int64

In [23]:
s9*2

0     4
1     8
2    12
3    16
dtype: int64

#### 10. Create a Series from a tuple (1, 2, 3, 4).

In [24]:
t1 = tuple((2,4,6,8))
s10 = pd.Series(t1)
s10

0    2
1    4
2    6
3    8
dtype: int64


#### 11. Create a Series  with  float values [1.5, 2.5, 3.5] .

In [30]:
s11 = pd.Series( [1.5, 2.5, 3.5])
s11

0    1.5
1    2.5
2    3.5
dtype: float64

#### 12. Update the index labels to p, q, r.

In [28]:
s11.index = ['p', 'q', 'r']
s11

p    1.5
q    2.5
r    3.5
dtype: float64

#### 13. Create a Series with boolean values [True, False, True].

In [33]:
s13 = pd.Series([1,0,1,0],dtype= bool)

In [34]:
s13

0     True
1    False
2     True
3    False
dtype: bool

#### 14. Create a Series using custom index ["p", "q", "r", "s"] and values [10, 20, 30, 40].

In [35]:
s14 = pd.Series([10,20,30,40], index=["p", "q", "r", "s"])
s14

p    10
q    20
r    30
s    40
dtype: int64

#### 15. Create a Series from a dictionary and specify index order manually.

In [36]:
my_dd2 = {"a": 10, "b": 20, "c": 30}

s15 = pd.Series(my_dd2, index=["c", "a", "b"])
s15

c    30
a    10
b    20
dtype: int64

#### 16 . Create a Series with string values ["A", "B", "C"].

In [38]:
s16 = pd.Series(["A", "B", "C"])
s16

0    A
1    B
2    C
dtype: object

#### 17. Create a Series with missing values (None or NaN).

In [39]:
s17 = pd.Series([1,2,None,4,np.nan,11])
s17

0     1.0
1     2.0
2     NaN
3     4.0
4     NaN
5    11.0
dtype: float64

In [44]:
sa17 = pd.Series(index=[1,2,3])
sa17

1   NaN
2   NaN
3   NaN
dtype: float64

#### 18. Create an empty Series.

In [45]:
s18 = pd.Series()
s18

Series([], dtype: object)

In [46]:
sa18 = pd.Series(dtype=float)
sa18

Series([], dtype: float64)

#### 19. Create a Series with index starting from 1 instead of 0.

In [48]:
s19 = pd.Series([10, 20, 30, 40], index=[1, 2, 3, 4])
print(s19)

1    10
2    20
3    30
4    40
dtype: int64

In [50]:
sa19 = pd.Series([6,7,8,5,4,3,2])
sa19.index = range(1,len(sa19)+1)
sa19

1    6
2    7
3    8
4    5
5    4
6    3
7    2
dtype: int64

#### 20. Create a Series using a scalar value 50 with index ["a", "b", "c"].

In [51]:
s20 = pd.Series(50,index=['a','b','c'])
s20

a    50
b    50
c    50
dtype: int64

#

## ---DataFrame----

#### 1. Create a DataFrame from a dictionary with columns Name and Marks.

In [52]:
myd1 = {"Name":["Jack","Sham","David","Sachin"],"Marks":[88,79,68,90]}
myd1

{'Name': ['Jack', 'Sham', 'David', 'Sachin'], 'Marks': [88, 79, 68, 90]}

In [55]:
df1 = pd.DataFrame(myd1)
df1

     Name  Marks
0    Jack     88
1    Sham     79
2   David     68
3  Sachin     90

#### 2.Create a DataFrame from a list of lists with columns Name, Age.

In [59]:
nested_list = [["David", 22],["Roy", 21],["Shyam", 23]]
nested_list

[['David', 22], ['Roy', 21], ['Shyam', 23]]

In [60]:
df2 = pd.DataFrame(nested_list)
df2

       0   1
0  David  22
1    Roy  21
2  Shyam  23

In [61]:
df2 = pd.DataFrame(nested_list,columns=["Name","Age"])
df2

    Name  Age
0  David   22
1    Roy   21
2  Shyam   23

In [62]:
df2.columns=['NAME','AGE']
df2

    NAME  AGE
0  David   22
1    Roy   21
2  Shyam   23

#### 3. Create a DataFrame from a list of dictionaries.

In [63]:
li_dict = [{"Name":"Sham","Age":21},
            {"Name": "jack","Age":20},
           {"Name": "Sam","Age":19}
          ]
li_dict

[{'Name': 'Sham', 'Age': 21},
 {'Name': 'jack', 'Age': 20},
 {'Name': 'Sam', 'Age': 19}]

In [64]:
df3 = pd.DataFrame(li_dict)

In [65]:
df3

   Name  Age
0  Sham   21
1  jack   20
2   Sam   19

#### 4. Create an empty DataFrame.

In [66]:
df4 = pd.DataFrame()
df4

Empty DataFrame
Columns: []
Index: []

#### 5. Create a DataFrame with only one column.

In [68]:
df5 = pd.DataFrame([1,2,3,4],columns=["Values"])
df5

   Values
0       1
1       2
2       3
3       4

#### 6. Create a DataFrame with custom index row1, row2, row3.

In [69]:
df6 = pd.DataFrame([1,2,3,4],columns=["Values"],index=['r1','r2','r3','r4'])
df6

    Values
r1       1
r2       2
r3       3
r4       4

#### 7. Create a DataFrame from a 2D list:

In [70]:
lis_2d = [["Virat",37,"RCB"],
          ["Rohit",38,"MI"] ,
          ["Shreyas ",31,"PK"],
          ["MS",44,"CSK"]
         ]
lis_2d

[['Virat', 37, 'RCB'],
 ['Rohit', 38, 'MI'],
 ['Shreyas ', 31, 'PK'],
 ['MS', 44, 'CSK']]

In [71]:
df7 = pd.DataFrame(lis_2d,columns=["Name","Age","Team"])

In [72]:
df7

       Name  Age Team
0     Virat   37  RCB
1     Rohit   38   MI
2  Shreyas    31   PK
3        MS   44  CSK

#### 8. Create a DataFrame from a dictionary of lists with 3 columns.

In [73]:
dict_li= { "City": ["Belgaum", "Bangalore", "Pune"],
           "Temperature": [28, 30, 27],
           "Humidity": [65, 70, 60]
         }
dict_li

{'City': ['Belgaum', 'Bangalore', 'Pune'],
 'Temperature': [28, 30, 27],
 'Humidity': [65, 70, 60]}

In [74]:
df8 = pd.DataFrame(dict_li)
df8

        City  Temperature  Humidity
0    Belgaum           28        65
1  Bangalore           30        70
2       Pune           27        60

#### 9. Create a DataFrame from a dictionary of Series.`

In [75]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([40, 50, 60])

dict_s = { "A": s1, "B": s2 }
df9 = pd.DataFrame(dict_s)
df9

    A   B
0  10  40
1  20  50
2  30  60

#### 10. Create a DataFrame using a NumPy 2D array and assign column names.

In [76]:
arr2d= np.array([[1, 2, 3],[4, 5, 6]])

df10 = pd.DataFrame(arr2d, columns=["A", "B", "C"])

In [77]:
df10

   A  B  C
0  1  2  3
1  4  5  6

#### 11.Create a DataFrame with mixed data types (int, float, string).

In [78]:
mix_d= { "ID": [1, 2, 3],    
       "Name": ["Omkar", "Ram", "Shyam"] ,
        "Score": [85.5, 90.0, 78.5],
    }
mix_d = pd.DataFrame(mix_d)
mix_d

   ID   Name  Score
0   1  Omkar   85.5
1   2    Ram   90.0
2   3  Shyam   78.5

In [81]:
mix_d.dtypes

ID         int64
Name      object
Score    float64
dtype: object

#### 12. Create a DataFrame and set custom column names.

In [82]:
df12 = pd.DataFrame([[1, 2], [3, 4]], columns=["A", "B"])

In [83]:
df12

   A  B
0  1  2
1  3  4

#### 13. Create a DataFrame with missing values (None or NaN).

In [84]:
mis_data = { "A": [1, 2, None],
         "B": [4, np.nan, 6]
       }
df13 = pd.DataFrame(mis_data)

In [85]:
df13

     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0

#### 14. Create a DataFrame with index starting from 1.

In [86]:
df13.index = np.arange(1,len(df13)+1)
df13

     A    B
1  1.0  4.0
2  2.0  NaN
3  NaN  6.0

#### 15 .Create a DataFrame with columns A, B. Rename them to X, Y.

In [87]:
df15 = pd.DataFrame([[1, 2], [3, 4]], columns=["A", "B"])
df15

   A  B
0  1  2
1  3  4

In [88]:
df15.columns = ["X", "Y"]
df15

   X  Y
0  1  2
1  3  4

#### 16. Create a DataFrame and convert all column names to uppercase.

In [89]:
df16 = pd.DataFrame([[1, 2]], columns=["name", "marks"])
df16

   name  marks
0     1      2

In [91]:
df16.columns = df16.columns.str.upper()
df16

   NAME  MARKS
0     1      2

#### 17. Create a DataFrame and convert all column names to uppercase.

In [92]:
df17 = pd.DataFrame([[1, 2]], columns=["NAME", "MARKS"])
df17

   NAME  MARKS
0     1      2

In [93]:
df17.columns = df17.columns.str.lower()
df17

   name  marks
0     1      2