# Data Cleaning 8

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('messy_data7.csv')

In [4]:
df= data.copy(deep=True)

#

In [5]:
df.head()

,Employee_ID,Employee_Name,Attendance_Status,Check_In_Time,Work_Location,Hours_Worked
0,1000.0,Rahul,PRESENT,25:30,Bangalore City,NaN
1,NaN,NaN,NaN,10:15,bengaluru,10.0
2,NaN,Sneha,Present,NaN,NaN,26.0
3,1002.0,Amit,absent,25:30,bengaluru,NaN
4,NaN,Amit,Present,09:00,NaN,10.0

In [6]:
df.tail()

,Employee_ID,Employee_Name,Attendance_Status,Check_In_Time,Work_Location,Hours_Worked
495,NaN,Rahul,present,NaN,Bangalore City,NaN
496,1495.0,NaN,NaN,09:00,BLR,9.0
497,1496.0,NaN,present,08:45,bengaluru,7.5
498,NaN,Rahul,PRESENT,09:00,NaN,26.0
499,1498.0,Priya,P,09:00,Bangalore,26.0

In [7]:
df.shape

(500, 6)

In [8]:
df.dtypes

Employee_ID          float64
Employee_Name         object
Attendance_Status     object
Check_In_Time         object
Work_Location         object
Hours_Worked         float64
dtype: object

In [9]:
df.isnull().sum()

Employee_ID          247
Employee_Name        114
Attendance_Status    127
Check_In_Time        143
Work_Location        165
Hours_Worked         134
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(5)

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Employee_ID,253.0,1250.944664,147.346439,1000.0,1122.0,1247.0,1373.0,1498.0
Hours_Worked,366.0,9.983607,8.514195,-2.0,7.5,9.0,10.0,26.0

In [15]:
for col in df.columns:
    print(df[col].unique()[:10])
    print()

[1000.   nan 1002. 1004. 1006. 1008. 1010. 1017. 1019. 1020.]

['Rahul' nan 'Sneha' 'Amit' 'Priya' ' sneha ' 'Ravi']

['PRESENT' nan 'Present' 'absent' 'present' 'Absent' 'P']

['25:30' '10:15' nan '09:00' '08:45' '9 AM']

['Bangalore City' 'bengaluru' nan 'BLR' 'Bangalore']

[ nan 10.  26.   9.   7.5 -2.   8. ]

#

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df['Employee_ID'] = df['Employee_ID'].astype('Int64')

In [18]:
df['Employee_ID'] = df['Employee_ID'].astype('str')

In [19]:
df['Employee_ID'].head()

0    1000
1    <NA>
2    <NA>
3    1002
4    <NA>
Name: Employee_ID, dtype: object

#

In [21]:
df['Employee_Name'] = df['Employee_Name'].astype(str).str.strip().str.title()

In [22]:
df['Employee_Name'].unique()

array(['Rahul', 'Nan', 'Sneha', 'Amit', 'Priya', 'Ravi'], dtype=object)

In [23]:
df['Employee_Name'] = df['Employee_Name'].replace({'':'Unknown','None':'Unknown'})

In [24]:
df['Employee_Name'].unique()

array(['Rahul', 'Nan', 'Sneha', 'Amit', 'Priya', 'Ravi'], dtype=object)

In [26]:
df['Employee_Name'] = df['Employee_Name'].fillna('Unknown')

In [27]:
df['Attendance_Status'].unique()

array(['PRESENT', nan, 'Present', 'absent', 'present', 'Absent', 'P'],
      dtype=object)

In [29]:
df['Attendance_Status'] = df['Attendance_Status'].replace({
    'present':'Present',
    'PRESENT':'Present',
    'P':'Present',
    'absent':'Absent'
})

In [30]:
df['Attendance_Status'] = df['Attendance_Status'].fillna('Unknown')

In [31]:
df['Attendance_Status'].unique()

array(['Present', 'Unknown', 'Absent'], dtype=object)

In [32]:
df['Work_Location'].unique()

array(['Bangalore City', 'bengaluru', nan, 'BLR', 'Bangalore'],
      dtype=object)

In [33]:
df['Work_Location'] = df['Work_Location'].replace({'bengaluru':'Bangalore','BLR':'Bangalore','Bangalore City':'Bangalore'})

In [34]:
df['Work_Location'].unique()

array(['Bangalore', nan], dtype=object)

In [35]:
df['Work_Location'].isnull().sum()

np.int64(165)

In [36]:
df['Work_Location'] = df['Work_Location'].fillna('Unknown')

In [37]:
df['Work_Location'].isnull().sum()

np.int64(0)

#

In [38]:
df['Hours_Worked'] = pd.to_numeric(df['Hours_Worked'], errors='coerce')

In [39]:
df['Hours_Worked'].head()

0     NaN
1    10.0
2    26.0
3     NaN
4    10.0
Name: Hours_Worked, dtype: float64

In [40]:
df.loc[(df['Hours_Worked'] < 0) | (df['Hours_Worked'] > 24), 'Hours_Worked'] = np.nan

In [41]:
df['Hours_Worked'] = df['Hours_Worked'].fillna(df['Hours_Worked'].median())

In [42]:
df['Hours_Worked'].head()

0     9.0
1    10.0
2     9.0
3     9.0
4    10.0
Name: Hours_Worked, dtype: float64

#

In [47]:
df['Check_In_Time'] = pd.to_datetime(data['Check_In_Time'], errors='coerce').dt.time

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_22320\3606251774.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Check_In_Time'] = pd.to_datetime(data['Check_In_Time'], errors='coerce').dt.time

In [48]:
df['Check_In_Time']

0           NaT
1      10:15:00
2           NaT
3           NaT
4      09:00:00
         ...
495         NaT
496    09:00:00
497    08:45:00
498    09:00:00
499    09:00:00
Name: Check_In_Time, Length: 495, dtype: object

In [49]:
df = df.dropna(subset=['Employee_ID'])

In [50]:
df.isnull().sum()

Employee_ID            0
Employee_Name          0
Attendance_Status      0
Check_In_Time        278
Work_Location          0
Hours_Worked           0
dtype: int64