# Data Cleaning Practice 7

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('messy_data8.csv')

In [3]:
df = data.copy()

#

In [4]:
df.shape

(200, 6)

In [5]:
df.head()

             Name      Age          City Department     Salary    Join_Date
0   Michael Moore    23.74        Denver         IT   32850.35          NaN
1    Sarah Wilson    28.45   Los Angeles        NaN   80804.99   08-16-2021
2  Donald Jackson    50.51     Charlotte      Legal   73990.97   2022-07-23
3    Donald White   4637.0      San Jose  Marketing  $51751.27   2019/06/23
4    Joseph Moore  $1921.0  Philadelphia        NaN        NaN  10-Apr-2023

In [6]:
df.tail()

,Name,Age,City,Department,Salary,Join_Date
195,Anthony Moore,28.98,San Francisco,Customer Support,129586.07,2015-02-04
196,Nancy White,27.77,Oklahoma City,Marketing,NaN,unknown
197,Richard Lopez,38.0,Indianapolis,IT,60694.7,2022-05-06
198,Thomas Martin,40.07,Houston,DESIGN,109014.8,08/04/20
199,Margaret Lee,47.83,Houston,DESIGN,122103.45,"May 15, 2023"

In [7]:
df.sample(10)

,Name,Age,City,Department,Salary,Join_Date
71,Robert Lee,30.89,Louisville,Operations,NaN,31/02/2023
110,John Moore,55.91,Charlotte,HR,NaN,16/10/2021
31,William Jones,-3581.0,Chicago,PRODUCT,45471.7,2021-09-13
151,Karen Lopez,51.76,Charlotte,PRODUCT,114556.07,16/12/2020
104,Donald Moore,NaN,San Francisco,Customer Supoort,88691.62,"March 22, 2019"
141,NaN,53.13,San Jose,Legal,96791.83,05/01/2020
144,Richard Rodriguez,40.1,NaN,IT,106597.63,16.10.2023
120,Jessica Thomas,23.93,Jacksonville,Sales,106085.48,07-07-2016
43,William Jones,-3581.0,Chicago,PRODUCT,45471.7,2021-09-13
61,Richard Perez,59.01,Dallas,Marketing,119811.22,not available

In [8]:
df.dtypes

Name          object
Age           object
City          object
Department    object
Salary        object
Join_Date     object
dtype: object

In [9]:
df.duplicated().sum()

np.int64(7)

In [10]:
df.isnull().any()

Name          True
Age           True
City          True
Department    True
Salary        True
Join_Date     True
dtype: bool

In [11]:
df.isnull().sum()

Name          14
Age           16
City          13
Department    17
Salary        24
Join_Date     14
dtype: int64

In [12]:
df.describe(include='all').T

           count unique             top freq
Name         186    158  James Williams    3
Age          184    175           47.83    2
City         187     74         Chicago    9
Department   183     45              HR   15
Salary       176    171       110096.22    2
Join_Date    186    176         unknown    4

In [16]:
for col in df.columns:
    print('Column :',col, "Total Unique : ", df[col].nunique())
    print(df[col].unique()[:10])
    print()

Column : Name Total Unique :  158
['Michael Moore' 'Sarah Wilson' 'Donald Jackson' 'Donald White'
 'Joseph Moore' 'James Williams' 'Margaret Lee' 'Charles Davis'
 '  BETTY SMITH  ' 'Linda Thomas']

Column : Age Total Unique :  175
['23.74' '28.45' '50.51' '4637.0' '$1921.0' '60.25' '47.83' '27.36' '34.5'
 '64.06']

Column : City Total Unique :  74
['Denver' 'Los Angeles' 'Charlotte' 'San Jose' 'Philadelphia' 'portland'
 'Houston' 'SAN DIEGO' nan 'Detroit']

Column : Department Total Unique :  45
['IT' nan 'Legal' 'Marketing' 'CUSTOMER SUPPORT' 'DESIGN' 'Operathons'
 'HR' '  IT  ' 'MAMKETING']

Column : Salary Total Unique :  171
['32850.35' '80804.99' '73990.97' '$51751.27' nan '110096.22' '122103.45'
 '65416.87' '77682.6' '124083.77']

Column : Join_Date Total Unique :  176
[nan '08-16-2021' '2022-07-23' '2019/06/23' '10-Apr-2023' '23.07.2016'
 'May 15, 2023' '2020-09-30' '05/30/21' '07-Oct-2024']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        186 non-null    object
 1   Age         184 non-null    object
 2   City        187 non-null    object
 3   Department  183 non-null    object
 4   Salary      176 non-null    object
 5   Join_Date   186 non-null    object
dtypes: object(6)
memory usage: 9.5+ KB

#

In [18]:
df = df.drop_duplicates()

In [19]:
df.dropna(subset='Name',inplace=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_29744\271151142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset='Name',inplace=True)

In [20]:
df['Age'].unique()

array(['23.74', '28.45', '50.51', '4637.0', '$1921.0', '60.25', '47.83',
       '27.36', '34.5', '64.06', '63.11', '24.38', '37.88', '61.28',
       '38.5', '$33.44', nan, '23.57', '29.82', '19.46', '48.91', '49.5',
       '34.0', '49.18', '43.38', '2870.0', '48.98', '19.36', '-3581.0',
       '39.48', '63.26', '23.96', '18.92', '31.29', '63.38', '53.0',
       '32.35', '22.07', '40.45', '44.4', '62.43', '32.91', '27.26',
       '62.25', '41.38', '33.15', '19.3', '20.8', '32.69', '$52.84',
       '29.94', '57.44', '59.01', '39.4', '40.65', '22.38', '50.28',
       '47.11', '59.96', '57.19', '33.78', '30.89', '62.69', '32.52',
       '26.54', '51.15', '53.82', '40.78', '28.69', '52.29', '33.33',
       '41.35', '57.11', '38.18', '27.9', '63.9', '32.03', '61.33',
       '42.56', '34.56', '55.79', '64.1', '30.9', '42.95', '46.73',
       '58.64', '40.11', '24.8', '35.82', '37.7', '63.41', '-5698.0',
       '55.91', '55.13', '34.22', '45.74', '45.47', '24.98', '0.0446',
       '58.03', '23.93', '49.39', '63.68', '38.84', '-4607.0', '47.87',
       '20.93', '45.02', '39.15', '$51.78', '42.44', '26.53', '24.57',
       '38.7', '38.06', '38.21', '52.53', '38.64', '57.82', '25.18',
       '29.8', '53.55', '40.1', '21.22', '32.5', '57.5', '51.76', '60.48',
       '57.23', '30.43', '20.52', '49.72', '$59.52', '23.99', '33.61',
       '45.2', '47.13', '48.36', '45.62', '46.08', '37.93', '34.04',
       '$28.54', '45.82', '23.38', '52.18', '63.3', '40.83', '-2153.0',
       '64.26', '62.54', '43.59', '31.79', '23.7', '44.26', '55.25',
       '19.18', '33.19', '28.98', '27.77', '38.0', '40.07'], dtype=object)

In [26]:
df['Age'] = df['Age'].replace(r'[^0-9.]','',regex=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_29744\93931229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].replace(r'[^0-9.]','',regex=True)

In [27]:
df['Age'] = pd.to_numeric(df['Age'],errors='coerce').round()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_29744\3405718879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = pd.to_numeric(df['Age'],errors='coerce').round()

In [28]:
df['Age'].head()

0      24.0
1      28.0
2      51.0
3    4637.0
4    1921.0
Name: Age, dtype: float64

In [30]:
df.loc[(df['Age']<0)|(df['Age']>110),'Age'] = np.nan

In [31]:
df['Age'].head()

0    24.0
1    28.0
2    51.0
3     NaN
4     NaN
Name: Age, dtype: float64

In [32]:
df['Age'] = df['Age'].astype('Int64')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_29744\1150615803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].astype('Int64')

In [33]:
df['Department'].unique()

array(['IT', nan, 'Legal', 'Marketing', 'CUSTOMER SUPPORT', 'DESIGN',
       'Operathons', '  IT  ', 'MAMKETING', 'Sales', 'R&D', 'Product',
       'Operations', 'Finance', 'Engineering', 'HR', 'PRODUCT',
       '  marketing  ', 'MARKETING', 'Design', '  Marketing  ',
       '  Finance  ', 'Customer Support', '  R&D  ', 'legal', '  Legal  ',
       'ENGINEERING', 'customer support', 'Engineerinj', 'r&d', 'FZNANCE',
       'hr', '  Operationp  ', 'product', 'Customer Supoort',
       'engineering', '  Product  ', '  Sales  ', '  Design  ',
       '  CustomerrSupport  ', 'marketing', 'DEZIGN', '  r&d  ',
       '  dekign  '], dtype=object)

In [35]:
df['Department'].str.strip().str.title().unique()

array(['It', nan, 'Legal', 'Marketing', 'Customer Support', 'Design',
       'Operathons', 'Mamketing', 'Sales', 'R&D', 'Product', 'Operations',
       'Finance', 'Engineering', 'Hr', 'Engineerinj', 'Fznance',
       'Operationp', 'Customer Supoort', 'Customerrsupport', 'Dezign',
       'Dekign'], dtype=object)

In [36]:
dept_map={
    'Mamketing' : 'Marketing', 
    'Operathons' : 'Operations',  
    'Operationp' : 'Operations',
    'Customer Supoort' : 'Customer Support', 
    'Customerrsupport': 'Customer Support',
    'Engineerinj' : 'Engineering',
    'Dezign' : 'Design',
    'Dekign' : 'Design', 
    'Fznance' : 'Finance'
}

In [37]:
df['Department'].str.strip().str.title().replace(dept_map).unique()

array(['It', nan, 'Legal', 'Marketing', 'Customer Support', 'Design',
       'Operations', 'Sales', 'R&D', 'Product', 'Finance', 'Engineering',
       'Hr'], dtype=object)

In [38]:
df['Department'] = df['Department'].str.strip().str.title().replace(dept_map)

In [40]:
df['Department'].fillna(df['Department'].mode()[0]).unique()

array(['It', 'Customer Support', 'Legal', 'Marketing', 'Design',
       'Operations', 'Sales', 'R&D', 'Product', 'Finance', 'Engineering',
       'Hr'], dtype=object)

In [41]:
df['Department'] =df['Department'].fillna(df['Department'].mode()[0])

In [43]:
df['Age'] = df['Age'].fillna(df.groupby('Department')['Age'].transform(lambda a : a.mode()[0]))

In [44]:
df.columns

Index(['Name', 'Age', 'City', 'Department', 'Salary', 'Join_Date'], dtype='object')

In [45]:
df['Salary'].unique()[:20]

array(['32850.35', '80804.99', '73990.97', '$51751.27', nan, '110096.22',
       '122103.45', '65416.87', '77682.6', '124083.77', '134062.68',
       '94828.48', '45385.82', '147540.09', '118310.38', '84135.08',
       '47897.34', '109436.39', '76488.67', '48831.28'], dtype=object)

In [47]:
df['Salary'].unique()[-20:]

array(['50398.4', '46.96486', '63782.09', '44133.78', '92075.23',
       '34733.34', '97522.05', '80456.71', '118965.0', '71435.23',
       '129704.42', '53101.49', '83546.45', '52798.11', '90467.21',
       '69826.02', '97001.31', '129586.07', '60694.7', '109014.8'],
      dtype=object)

In [48]:
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

In [49]:
df.dtypes

Name           object
Age             Int64
City           object
Department     object
Salary        float64
Join_Date      object
dtype: object

In [50]:
df['Salary'] = df['Salary'].fillna(df.groupby('Department')['Salary'].transform(lambda s : s.median()))

In [51]:
df['Join_Date'].unique()[:20]

array([nan, '08-16-2021', '2022-07-23', '2019/06/23', '10-Apr-2023',
       '23.07.2016', 'May 15, 2023', '2020-09-30', '05/30/21',
       '04-28-2019', '2017-01-23', '07.07.2020', 'September 10, 2022',
       '27.05.2016', '27/07/2024', 'unknown', '22-Dec-2015', '05-29-2021',
       '25.08.2018', '12-29-2018'], dtype=object)

In [53]:
pd.to_datetime( df['Join_Date'],format='mixed',errors='coerce').unique()[:20]

<DatetimeArray>
[                'NaT', '2021-08-16 00:00:00', '2022-07-23 00:00:00',
 '2019-06-23 00:00:00', '2023-04-10 00:00:00', '2016-07-23 00:00:00',
 '2023-05-15 00:00:00', '2020-09-30 00:00:00', '2021-05-30 00:00:00',
 '2019-04-28 00:00:00', '2017-01-23 00:00:00', '2020-07-07 00:00:00',
 '2022-09-10 00:00:00', '2016-05-27 00:00:00', '2024-07-27 00:00:00',
 '2015-12-22 00:00:00', '2021-05-29 00:00:00', '2018-08-25 00:00:00',
 '2018-12-29 00:00:00', '2017-03-28 00:00:00']
Length: 20, dtype: datetime64[ns]

In [54]:
df['Join_Date'] = pd.to_datetime( df['Join_Date'],format='mixed',errors='coerce')

In [55]:
df['Join_Date'] = df['Join_Date'].fillna(df.groupby('Department')['Join_Date'].transform(lambda d : d.mode()))

In [56]:
df.dtypes

Name                  object
Age                    Int64
City                  object
Department            object
Salary               float64
Join_Date     datetime64[ns]
dtype: object

In [57]:
df.isnull().sum()

Name           0
Age            0
City          13
Department     0
Salary         0
Join_Date     18
dtype: int64

In [58]:
df['City'].unique()[:20]

array(['Denver', 'Los Angeles', 'Charlotte', 'San Jose', 'Philadelphia',
       'portland', 'Houston', 'SAN DIEGO', nan, 'San Diego', 'COLUMBUS',
       'Seattle', 'Las Vegas', '  FORT WORTH  ', 'Detroip', 'Chicago',
       'New York', 'El Paso', 'Houtton', 'philadelphia'], dtype=object)

In [59]:
df['City'].unique()[-20:]

array(['LAS VEGAS', 'FORT WORTH', 'DENVER', 'HOUSTON', 'San Antonio',
       'Jhcksonville', '  San Anvonio  ', '  Las Vegas  ', 'mouisville',
       'Chicayo', 'Jackponville', 'Charlotye', 'washington',
       '  Phoenix  ', 'Dallag', '  Jacksonville  ', 'new york', 'boston',
       'INDIANAPOLIS', 'PHOENIO'], dtype=object)

In [60]:
df['City'].nunique()

71

In [61]:
df['City'].unique()

array(['Denver', 'Los Angeles', 'Charlotte', 'San Jose', 'Philadelphia',
       'portland', 'Houston', 'SAN DIEGO', nan, 'San Diego', 'COLUMBUS',
       'Seattle', 'Las Vegas', '  FORT WORTH  ', 'Detroip', 'Chicago',
       'New York', 'El Paso', 'Houtton', 'philadelphia', 'Jacksonville',
       'columbus', 'Columbus', '  Chicago  ', 'oklahoma city',
       '  oklahoma city  ', 'Austin', 'Detroit', 'Houstjn', 'Phoenix',
       'Washington', '  Portland  ', 'COLXMBUS', '  Baltimore  ',
       'Milwaukee', 'Oklahoma City', '  Washington  ', 'Indianapolis',
       'Dallas', 'BALTIMORE', 'Nashville', 'Louisville', 'Fort Worth',
       'OklahomajCity', 'SAN ANTONIO', 'jacksonville', 'Houuton',
       'Boston', 'Baltimore', 'cashville', 'San Francisco', 'san jose',
       'LAS VEGAS', 'FORT WORTH', 'DENVER', 'HOUSTON', 'San Antonio',
       'Jhcksonville', '  San Anvonio  ', '  Las Vegas  ', 'mouisville',
       'Chicayo', 'Jackponville', 'Charlotye', 'washington',
       '  Phoenix  ', 'Dallag', '  Jacksonville  ', 'new york', 'boston',
       'INDIANAPOLIS', 'PHOENIO'], dtype=object)

In [62]:
df['City'].str.title().nunique()

54

In [64]:
df['City'].str.strip().str.title().nunique()

45

In [65]:
df['City'].str.strip().str.title().unique()

array(['Denver', 'Los Angeles', 'Charlotte', 'San Jose', 'Philadelphia',
       'Portland', 'Houston', 'San Diego', nan, 'Columbus', 'Seattle',
       'Las Vegas', 'Fort Worth', 'Detroip', 'Chicago', 'New York',
       'El Paso', 'Houtton', 'Jacksonville', 'Oklahoma City', 'Austin',
       'Detroit', 'Houstjn', 'Phoenix', 'Washington', 'Colxmbus',
       'Baltimore', 'Milwaukee', 'Indianapolis', 'Dallas', 'Nashville',
       'Louisville', 'Oklahomajcity', 'San Antonio', 'Houuton', 'Boston',
       'Cashville', 'San Francisco', 'Jhcksonville', 'San Anvonio',
       'Mouisville', 'Chicayo', 'Jackponville', 'Charlotye', 'Dallag',
       'Phoenio'], dtype=object)

In [66]:
city_map = {
    'Detroip': 'Detroit',
    'Houtton': 'Houston',
    'Houstjn': 'Houston',
    'Houuton': 'Houston',
    'Colxmbus': 'Columbus',
    'Oklahomajcity': 'Oklahoma City',
    'Cashville': 'Nashville',
    'Jhcksonville': 'Jacksonville',
    'Jackponville': 'Jacksonville',
    'San Anvonio': 'San Antonio',
    'Mouisville': 'Louisville',
    'Chicayo': 'Chicago',
    'Charlotye': 'Charlotte',
    'Dallag': 'Dallas',
    'Phoenio': 'Phoenix'
}

In [67]:
df['City'] = df['City'].fillna(df.groupby('Department')['City'].transform(lambda c : c.mode()))

In [68]:
df.isnull().sum()

Name           0
Age            0
City          12
Department     0
Salary         0
Join_Date     18
dtype: int64

In [69]:
df['Join_Date'] = df['Join_Date'].fillna(df.groupby('City')['Join_Date'].transform(lambda d : d.mode()))

In [70]:
df.isnull().sum()

Name           0
Age            0
City          12
Department     0
Salary         0
Join_Date     18
dtype: int64

In [71]:
df['City'] = df['City'].fillna('Unknown')

In [72]:
df['Join_Date'] = df['Join_Date'].fillna(df.groupby('City')['Join_Date'].transform(lambda d : d.mode()))

In [73]:
df.isnull().sum()

Name           0
Age            0
City           0
Department     0
Salary         0
Join_Date     18
dtype: int64

In [74]:
df[df['Join_Date'].isnull()]

,Name,Age,City,Department,Salary,Join_Date
16,William Anderson,33,FORT WORTH,Sales,84135.08,NaT
18,Joseph Taylor,24,Chicago,Product,47897.34,NaT
26,James White,43,columbus,Engineering,49127.45,NaT
41,Elizabeth Wilson,53,Phoenix,Sales,141884.38,NaT
51,John Perez,41,Columbus,Marketing,131757.82,NaT
61,Richard Perez,59,Dallas,Marketing,119811.22,NaT
68,Charles Miller,60,Philadelphia,Operations,-4486474.00,NaT
71,Robert Lee,31,Louisville,Operations,77682.60,NaT
72,William Taylor,63,Chicago,Engineering,130624.38,NaT
95,Robert Perez,64,Washington,Product,42835.38,NaT
111,Linda Jackson,55,FORT WORTH,R&D,104287.94,NaT
121,Daniel Brown,49,Jhcksonville,Marketing,49799.66,NaT
122,Lisa Hernandez,64,Unknown,Customer Support,46800.20,NaT
123,David Brown,39,Los Angeles,Engineering,112248.62,NaT
126,David Miller,48,Chicago,Operations,49012.21,NaT
159,Susan Johnson,24,Boston,Customer Support,57149.07,NaT
176,Mark Smith,52,boston,Sales,63782.09,NaT
196,Nancy White,28,Oklahoma City,Marketing,113956.49,NaT

In [77]:
df.head(20)

,Name,Age,City,Department,Salary,Join_Date
0,Michael Moore,24,Denver,It,32850.35,2017-01-23
1,Sarah Wilson,28,Los Angeles,Customer Support,80804.99,2021-08-16
2,Donald Jackson,51,Charlotte,Legal,73990.97,2022-07-23
3,Donald White,31,San Jose,Marketing,113956.49,2019-06-23
4,Joseph Moore,41,Philadelphia,Customer Support,88691.62,2023-04-10
5,James Williams,60,portland,Customer Support,110096.22,2016-07-23
6,Margaret Lee,48,Houston,Design,122103.45,2023-05-15
7,Charles Davis,27,SAN DIEGO,It,65416.87,2021-05-30
8,BETTY SMITH,34,Unknown,Operations,77682.60,2020-09-30
9,Linda Thomas,64,San Jose,It,124083.77,2021-05-30
11,Sarah Brown,63,Seattle,It,134062.68,2019-04-28
12,Mary Perez,24,San Diego,It,94828.48,2017-01-23
13,Betty Moore,38,COLUMBUS,Customer Support,45385.82,2020-07-07
14,Matthew Miller,61,Seattle,It,147540.09,2022-09-10
15,Richard Brown,38,Las Vegas,Marketing,118310.38,2016-05-27
16,William Anderson,33,FORT WORTH,Sales,84135.08,NaT
17,Thomas Taylor,19,Detroip,R&D,97001.31,2024-07-27
18,Joseph Taylor,24,Chicago,Product,47897.34,NaT
19,Linda Jones,30,New York,Operations,109436.39,2015-12-22
20,Anthony White,19,El Paso,Finance,76488.67,2021-05-29