# Fake News Text Cleaning

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Fake.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [5]:
data.isna().any().any()

np.False_

In [6]:
data.describe(include='all')

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [7]:
data.ndim

2

In [8]:
data.shape

(23481, 4)

In [10]:
data.duplicated().any()

np.True_

In [12]:
data.duplicated().sum()

np.int64(3)

#

In [13]:
df = data.copy()

In [14]:
df = df.drop_duplicates()

In [15]:
df.duplicated().any()

np.False_

In [16]:
df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [17]:
df.tail()

,title,text,subject,date
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [18]:
df.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [20]:
pd.to_datetime(df['date'],format='mixed',errors='coerce')

0       2017-12-31
1       2017-12-31
2       2017-12-30
3       2017-12-29
4       2017-12-25
           ...
23476   2016-01-16
23477   2016-01-16
23478   2016-01-15
23479   2016-01-14
23480   2016-01-12
Name: date, Length: 23478, dtype: datetime64[ns]

In [21]:
df['date'] = pd.to_datetime(df['date'],format='mixed',errors='coerce')

In [22]:
df['date'].head()

0   2017-12-31
1   2017-12-31
2   2017-12-30
3   2017-12-29
4   2017-12-25
Name: date, dtype: datetime64[ns]

In [25]:
df['date'].dtypes.name

'datetime64[ns]'

In [26]:
df['date'].isna().any()

np.True_

In [27]:
df['date'].isna().sum()

np.int64(10)

In [35]:
df[df['date'].isna()]

,title,text,subject,date
9358,https://100percentfedup.com/served-roy-moore-v...,https://100percentfedup.com/served-roy-moore-v...,politics,NaT
15507,https://100percentfedup.com/video-hillary-aske...,https://100percentfedup.com/video-hillary-aske...,politics,NaT
15508,https://100percentfedup.com/12-yr-old-black-co...,https://100percentfedup.com/12-yr-old-black-co...,politics,NaT
15839,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,politics,NaT
15840,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,politics,NaT
17432,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,Government News,NaT
17433,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,Government News,NaT
18933,Homepage,[vc_row][vc_column width= 1/1 ][td_block_trend...,left-news,NaT
21869,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,left-news,NaT
21870,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,left-news,NaT

In [36]:
df2 = data.copy()

In [37]:
df2= df2.drop_duplicates()

In [38]:
df2[df['date'].isna()]

,title,text,subject,date
9358,https://100percentfedup.com/served-roy-moore-v...,https://100percentfedup.com/served-roy-moore-v...,politics,https://100percentfedup.com/served-roy-moore-v...
15507,https://100percentfedup.com/video-hillary-aske...,https://100percentfedup.com/video-hillary-aske...,politics,https://100percentfedup.com/video-hillary-aske...
15508,https://100percentfedup.com/12-yr-old-black-co...,https://100percentfedup.com/12-yr-old-black-co...,politics,https://100percentfedup.com/12-yr-old-black-co...
15839,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,politics,https://fedup.wpengine.com/wp-content/uploads/...
15840,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,politics,https://fedup.wpengine.com/wp-content/uploads/...
17432,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,Government News,https://fedup.wpengine.com/wp-content/uploads/...
17433,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,Government News,https://fedup.wpengine.com/wp-content/uploads/...
18933,Homepage,[vc_row][vc_column width= 1/1 ][td_block_trend...,left-news,MSNBC HOST Rudely Assumes Steel Worker Would N...
21869,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,left-news,https://fedup.wpengine.com/wp-content/uploads/...
21870,https://fedup.wpengine.com/wp-content/uploads/...,https://fedup.wpengine.com/wp-content/uploads/...,left-news,https://fedup.wpengine.com/wp-content/uploads/...

In [43]:
df = df.dropna(subset='date')

In [44]:
df.isna().any()

title      False
text       False
subject    False
date       False
dtype: bool

#

#### 1. Remove leading and trailing spaces from all text columns.

In [48]:
text_col = df.select_dtypes(include=object).columns

In [50]:
df[text_col] = df[text_col].apply(lambda col : col.str.strip())

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_24804\1213420943.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[text_col] = df[text_col].apply(lambda col : col.str.strip())

In [51]:
df[text_col].head()

,title,text,subject
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News

#### 2. Convert all news titles to lowercase.

In [52]:
df['title'] = df['title'].str.lower()
df.head()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_24804\4288255960.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.lower()

,title,text,subject,date
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25

#### 3. Remove duplicate spaces from article text.

In [53]:
df['text'] = df['text'].str.replace(r'\s+',' ',regex=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_24804\2599859233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].str.replace(r'\s+',' ',regex=True)

In [54]:
df.head()

,title,text,subject,date
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25

#

#### 4. Find articles containing ALL CAPS words.
###### BREAKING NEWS 
###### URGENT
###### SHOCKING

In [56]:
df2[df2['title'].str.contains(r'[A-Z]{2,}',regex=True,na=False)]

,title,text,subject,date
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
...,...,...,...,...
23469,BOILER ROOM: As the Frogs Slowly Boil – EP #40,Tune in to the Alternate Current Radio Network...,Middle-east,"January 20, 2016"
23470,Arizona Rancher Protesting in Oregon is Target...,RTOne of the most visible members of the armed...,Middle-east,"January 20, 2016"
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"

#### 5. Remove newline (\n) characters from text column.

In [60]:
df['text'] = df['text'].str.replace(r'\n','',regex = True)

In [61]:
df['text']

0        Donald Trump just couldn t wish all Americans ...
1        House Intelligence Committee Chairman Devin Nu...
2        On Friday, it was revealed that former Milwauk...
3        On Christmas day, Donald Trump announced that ...
4        Pope Francis used his annual Christmas Day mes...
                               ...
23476    21st Century Wire says As 21WIRE reported earl...
23477    21st Century Wire says It s a familiar theme. ...
23478    Patrick Henningsen 21st Century WireRemember w...
23479    21st Century Wire says Al Jazeera America will...
23480    21st Century Wire says As 21WIRE predicted in ...
Name: text, Length: 23468, dtype: object

#### 6. Remove tab (\t) spaces from text.

In [62]:
df['text'] = df['text'].str.replace(r'\t','',regex = True)

In [63]:
df['text']

0        Donald Trump just couldn t wish all Americans ...
1        House Intelligence Committee Chairman Devin Nu...
2        On Friday, it was revealed that former Milwauk...
3        On Christmas day, Donald Trump announced that ...
4        Pope Francis used his annual Christmas Day mes...
                               ...
23476    21st Century Wire says As 21WIRE reported earl...
23477    21st Century Wire says It s a familiar theme. ...
23478    Patrick Henningsen 21st Century WireRemember w...
23479    21st Century Wire says Al Jazeera America will...
23480    21st Century Wire says As 21WIRE predicted in ...
Name: text, Length: 23468, dtype: object

#### 7. Count number of words in each article.

In [82]:
df['word_count'] = df['text'].str.split().str.len()

In [83]:
df.head()

,title,text,subject,date,word_count,title_char_count
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69

In [84]:
df.iloc[0,1]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and the very dishonest fake news media. The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year, President Angry Pants tweeted. 2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America! Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year! Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress. Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me? Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish?? Marlene (@marlene399) December 31, 2017You can t just say happy new year? Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love! Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his enemies and haters for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President? Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down. Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters? Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.'

#

#### 8. Count number of characters in each title.

In [88]:
df['title_char_count'] = df['title'].str.len()

In [89]:
df.head()

,title,text,subject,date,word_count,title_char_count
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69

#

#### 9. Find titles containing numbers.
###### 10 Reasons Why...
###### 2024 Election...

In [92]:
df[df['title'].str.contains(r'\d+',regex=True,na=False)]

,title,text,subject,date,word_count,title_char_count
12,bad news for trump — mitch mcconnell says no t...,Republicans have had seven years to come up wi...,News,2017-12-21,388,75
23,cnn calls it: a democrat will represent alabam...,Alabama is a notoriously deep red state. It s ...,News,2017-12-12,270,92
38,john mccain wanted another 74 twitter follower...,All Senator John McCain wanted to achieve on t...,News,2017-12-05,652,90
52,americans once elected a president after he wa...,After an awful campaign filled with hateful rh...,News,2017-11-29,420,84
55,sean hannity is throwing a stage-4 temper tant...,We re not sure why Fox News host Sean Hannity ...,News,2017-11-28,494,85
...,...,...,...,...,...,...
23464,episode #119 – sunday wire: ‘you know the dril...,Episode #119 of SUNDAY WIRE SHOW finally resum...,Middle-east,2016-01-24,204,87
23469,boiler room: as the frogs slowly boil – ep #40,Tune in to the Alternate Current Radio Network...,Middle-east,2016-01-20,185,46
23477,justice? yahoo settles e-mail privacy class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,2016-01-16,297,81
23479,how to blow $700 million: al jazeera america f...,21st Century Wire says Al Jazeera America will...,Middle-east,2016-01-14,456,67
23480,10 u.s. navy sailors held by iranian military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,2016-01-12,874,81

#### 10. Find articles containing URLs.

In [93]:
df[df['text'].str.contains(r'http\S+|www\S+',regex=True,na=False)]

,title,text,subject,date,word_count,title_char_count
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77
16,the internet brutally mocks disney’s new trump...,A new animatronic figure in the Hall of Presid...,News,2017-12-19,455,74
19,republican senator gets dragged for going afte...,Senate Majority Whip John Cornyn (R-TX) though...,News,2017-12-16,435,62
27,watch: fox host calls for a ‘cleansing’ of the...,Judge Jeanine Pirro has continued her screamy ...,News,2017-12-10,463,94
...,...,...,...,...,...,...
23426,bombshell: classified nato report praises russ...,21st Century Wire says This latest bombshell r...,Middle-east,2016-03-06,407,97
23440,watch as trump gatecrashes glenn beck’s cruz c...,21st Century Wire says One TV personality Trum...,Middle-east,2016-02-24,240,67
23463,"eyewitness says feds ambushed bundys, 100 shot...",Patrick Henningsen 21st Century Wire UPDATE: 1...,Middle-east,2016-01-27,2560,105
23465,‘there’ll be boots on the ground’: us making n...,21st Century Wire says Various parties in Wash...,Middle-east,2016-01-23,475,88
23479,how to blow $700 million: al jazeera america f...,21st Century Wire says Al Jazeera America will...,Middle-east,2016-01-14,456,67

#### 11. Remove URLs from articles.
###### ex : 
###### https://abc.com
###### http://news.com

In [95]:
df['text'] = df['text'].str.replace(r'http\S+|www\S+','',regex=True)

In [96]:
df['text'].head()

0    Donald Trump just couldn t wish all Americans ...
1    House Intelligence Committee Chairman Devin Nu...
2    On Friday, it was revealed that former Milwauk...
3    On Christmas day, Donald Trump announced that ...
4    Pope Francis used his annual Christmas Day mes...
Name: text, dtype: object

#### 12. Extract all URLs from text column.

In [99]:
df['text'].str.findall(r'http\S+|www\S+')

0        []
1        []
2        []
3        []
4        []
         ..
23476    []
23477    []
23478    []
23479    []
23480    []
Name: text, Length: 23468, dtype: object

In [100]:
df['text'].str.findall(r'http\S+|www\S+').empty

False

In [103]:
df['text'].str.findall(r'http\S+|www\S+').sample(10)

19369    []
21553    []
13517    []
8731     []
3443     []
3435     []
22349    []
14305    []
7291     []
13594    []
Name: text, dtype: object

In [105]:
df['urls'] = df['text'].str.findall(r'http\S+|www\S+')

In [106]:
df.head()

,title,text,subject,date,word_count,title_char_count,urls
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78,[]
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68,[]
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89,[]
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77,[]
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69,[]

In [107]:
df['urls'] = df['urls'].str.replace(r'\[\]','',regex=True)

In [108]:
df.head()

,title,text,subject,date,word_count,title_char_count,urls
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78,NaN
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68,NaN
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89,NaN
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77,NaN
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69,NaN

In [109]:
df['urls'].isna().mean()*100

np.float64(100.0)

In [111]:
df.drop(columns='urls',inplace=True)

In [112]:
df.head()

,title,text,subject,date,word_count,title_char_count
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69

#

#### 13. Find titles containing repeated punctuation.
Breaking!!!
What???

In [113]:
df[df['title'].str.contains(r'[!?]{2,}',regex=True,na=False)]

,title,text,subject,date,word_count,title_char_count
1369,fox news staffers call sean hannity massive em...,"Sean Hannity, in his desperation to show that ...",News,2017-05-22,468,92
1396,conservatives bashed obama for ‘bowing’ to sau...,Long before presidential scandals were as seri...,News,2017-05-20,382,81
9207,doctor mentioned in hillary email released by ...,"54-year-old Dr. Dean Lorich, Associate Directo...",politics,2017-12-13,1476,142
10482,“what a wuss!” cnn political hack attacks trum...,CNN s Ana Navarro becomes totally unhinged in ...,politics,2017-07-03,220,111
11583,she’s b-a-a-a-ckkkk!! hillary makes crazy vide...,Hey President Trump how s that Hillary email i...,politics,2017-02-24,47,135
11718,time traveler nancy pelosi says she just can’t...,,politics,2017-02-07,0,82
11955,barbra streisand and chris matthews on trump e...,BARBRA MOCKS TRUMP AT A CLINTON FUNDRAISER:,politics,2017-01-10,7,107
15215,say what?! muslim women can now cover their fa...,"Soooo ah, what s the point of the picture?Not ...",politics,2015-09-11,334,103
15548,a president who’s unserious and undignified…do...,America deserves so much better and should get...,politics,2015-06-22,694,84
15693,(video) did he just say that?! obama downplays...,,politics,2015-05-15,0,76
15874,no toilet paper?! socialism is in its final st...,Socialism doesn t work but I guess Venezuela d...,politics,2015-04-06,368,73
17105,watch fox news anchor hammer mitch mcconnell: ...,Bill Hemmer let Mitch McConnell have it but Mc...,Government News,2015-09-11,102,66
17168,(video) breaking environmental laws?! city off...,Florida government official is serious about t...,Government News,2015-07-26,255,106
17237,"feds issue terror alert for july 4th…wait, i t...",FBI and Homeland Security are sending out warn...,Government News,2015-06-28,325,88
17278,hud asks for $4 billion more after spending mi...,The news broke this week that Obama wants to e...,Government News,2015-06-12,1244,76
17418,trey gowdy to dea chief on misconduct: “what t...,,Government News,2015-04-14,0,73
17458,no toilet paper?! socialism is in its final st...,Socialism doesn t work but I guess Venezuela d...,Government News,2015-04-06,368,73
17523,doctor mentioned in hillary email released by ...,"54-year-old Dr. Dean Lorich, Associate Directo...",left-news,2017-12-13,1476,142
19092,she’s b-a-a-a-ckkkk!! hillary makes crazy vide...,Hey President Trump how s that Hillary email i...,left-news,2017-02-24,47,135
19180,time traveler nancy pelosi says she just can’t...,,left-news,2017-02-07,0,82
20770,shameful! air force veteran ousted from collea...,OBAMA S AMERICA: Why do you think people are l...,left-news,2016-04-06,573,117
20922,say what?! ny public school students pledge al...,This is just another example of how public sch...,left-news,2016-03-04,204,80
21645,(video) obama supporters sign petition to nuke...,These people will support just about anything ...,left-news,2015-06-15,11,96
21907,no toilet paper?! socialism is in its final st...,Socialism doesn t work but I guess Venezuela d...,left-news,2015-04-06,368,73
22167,what?! john mccain says rand paul is “working ...,21st Century Wire says The fake news continues...,US_News,2017-03-16,80,56
22608,boiler room – ep #50 – 1 year anniversary extr...,Tune in to the Alternate Current Radio Network...,US_News,2016-03-31,180,57
22950,what?! john mccain says rand paul is “working ...,21st Century Wire says The fake news continues...,Middle-east,2017-03-16,80,56
23391,boiler room – ep #50 – 1 year anniversary extr...,Tune in to the Alternate Current Radio Network...,Middle-east,2016-03-31,180,57

#### 14. Remove special characters from titles.

In [115]:
df['title'] = df['title'].str.replace(r'[!?]{2,}','' ,regex=True)

#### 15. Find articles containing email addresses.

In [116]:
df[df['text'].str.contains(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', regex=True,na=True)]

Empty DataFrame
Columns: [title, text, subject, date, word_count, title_char_count]
Index: []

#### 16. Extract all years from date column. 
2016
2017
2018

In [117]:
df['date'].dtype.name

'datetime64[ns]'

In [119]:
df['year'] = df['date'].dt.year

In [120]:
df.head()

,title,text,subject,date,word_count,title_char_count,year
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78,2017
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68,2017
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89,2017
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77,2017
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69,2017

In [121]:
df.sample(5)

,title,text,subject,date,word_count,title_char_count,year
12670,tough message from serious women who don’t use...,The women in this video are serious minded vot...,politics,2016-10-21,188,124,2016
11812,fake news alert! cnn finally releases actual p...,As we pointed out throughout the months leadin...,politics,2017-01-25,868,160,2017
1777,report: trump still seething like a child beca...,"We all remember how, in February, TIME Magazin...",News,2017-04-15,347,99,2017
6016,nc students pull racist prank on their classma...,Students at a North Carolina high school have ...,News,2016-06-05,369,85,2016
7620,leave it to ellen degeneres to perfectly mock ...,When thinking about who you d likely want as t...,News,2016-03-08,290,79,2016

#### 17. Find titles containing percentages.

In [122]:
df[df['title'].str.contains(r'\d+%',regex=True,na=False)]

,title,text,subject,date,word_count,title_char_count,year
318,billion dollar company tells employees how the...,You may not be familiar with the name Unilever...,News,2017-09-25,399,99,2017
1351,"under the gop’s health care bill, premiums cou...",If you are a low-income earner and over 64 yea...,News,2017-05-26,702,98,2017
4851,trump is literally polling at 0% with black pe...,Donald Trump s recent African-American outreac...,News,2016-08-30,676,64,2016
5160,70% of republican high rollers want trump out ...,Donald Trump has been an absolute nightmare fo...,News,2016-08-06,447,80,2016
5475,a whopping 0% of black voters in ohio and penn...,"That s right, according to the latest NBC News...",News,2016-07-14,365,68,2016
...,...,...,...,...,...,...,...
21875,update: 40% of victim’s skull is missing…no ne...,"UPDATE: Robert Barnes, the white homeless man ...",left-news,2015-04-11,877,189,2015
22184,breaking: wikileaks says less than 1% of vault...,21st Century Wire says Just 24 hours after the...,US_News,2017-03-08,240,57,2017
22302,gingrich: trump will repeal 60-70% of obama’s ...,21st Century Wire says In a recent interview f...,US_News,2016-12-28,670,62,2016
22967,breaking: wikileaks says less than 1% of vault...,21st Century Wire says Just 24 hours after the...,Middle-east,2017-03-08,240,57,2017
23085,gingrich: trump will repeal 60-70% of obama’s ...,21st Century Wire says In a recent interview f...,Middle-east,2016-12-28,670,62,2016

#### 18. Find articles containing dollar amounts.

In [123]:
df[df['title'].str.contains(r'\$\d+',regex=True,na=False)]

,title,text,subject,date,word_count,title_char_count,year
132,someone tried to cash in on antifa with these ...,History has shown that one of the most cost-ef...,News,2017-11-06,538,86,2017
223,hustler owner is so fed up with trump that he ...,Donald Trump is a danger to the nation and the...,News,2017-10-14,316,96,2017
292,trump’s hhs secretary stole over $1 million fr...,Donald Trump ran and won on a platform of drai...,News,2017-09-29,329,82,2017
296,watch: adviser who wrote trump’s tax plan says...,"Gary Cohn, a Goldman Sachs recruit, now servin...",News,2017-09-28,505,91,2017
351,we can’t afford to feed the poor but we’re spe...,The military s budget is being massively expan...,News,2017-09-19,657,88,2017
...,...,...,...,...,...,...,...
23358,epic fail: anti-trump movement spent $75 milli...,21st Century Wire says The system is running o...,Middle-east,2016-05-06,206,62,2016
23394,the moment ben affleck realized that ‘batman v...,21st Century Wire says Does Hollywood do anyth...,Middle-east,2016-03-26,84,80,2016
23419,darpa spending $62 million to create military ...,21st Century Wire says Science fiction is now ...,Middle-east,2016-03-09,292,53,2016
23477,justice? yahoo settles e-mail privacy class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,2016-01-16,297,81,2016
23479,how to blow $700 million: al jazeera america f...,21st Century Wire says Al Jazeera America will...,Middle-east,2016-01-14,456,67,2016

#### 19. Extract quoted text from articles.

In [124]:
df['quoted_text'] = df['text'].str.findall(r'"(.*?)"')

In [125]:
df.head()

,title,text,subject,date,word_count,title_char_count,year,quoted_text
0,donald trump sends out embarrassing new year’s...,Donald Trump just couldn t wish all Americans ...,News,2017-12-31,495,78,2017,[]
1,drunk bragging trump staffer started russian c...,House Intelligence Committee Chairman Devin Nu...,News,2017-12-31,305,68,2017,[]
2,sheriff david clarke becomes an internet joke ...,"On Friday, it was revealed that former Milwauk...",News,2017-12-30,580,89,2017,[]
3,trump is so obsessed he even has obama’s name ...,"On Christmas day, Donald Trump announced that ...",News,2017-12-29,444,77,2017,[]
4,pope francis just called out donald trump duri...,Pope Francis used his annual Christmas Day mes...,News,2017-12-25,420,69,2017,[]

In [126]:
df.dtypes

title                       object
text                        object
subject                     object
date                datetime64[ns]
word_count                   int64
title_char_count             int64
year                         int32
quoted_text                 object
dtype: object

In [127]:
df['quoted_text'] = df['quoted_text'].str.replace('[]','')

In [128]:
df['quoted_text'].empty

False

In [130]:
df['quoted_text'].isna().all()

np.True_

In [131]:
df.drop(columns='quoted_text',inplace=True)

#### 20. Find longest article.

In [132]:
df.loc[df['word_count'].idxmax()]

title               media tripwire? ping pong pizza conspiracy pro...
text                Funny how secrets travel. I d start to believe...
subject                                                       US_News
date                                              2016-12-28 00:00:00
word_count                                                       8135
title_char_count                                                   98
year                                                             2016
Name: 22303, dtype: object

#### 21. Find shortest article.

In [134]:
df.loc[df['word_count'].idxmin()]

title               take our poll: who do you think president trum...
text
subject                                                      politics
date                                              2017-05-10 00:00:00
word_count                                                          0
title_char_count                                                   83
year                                                             2017
Name: 10923, dtype: object