# String Cleaning in Pandas

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('string_dataset.csv')

In [3]:
data.head()

,customer_id,full_name,email,phone_number,city,salary,review_text
0,1001,JOHN DOE,JOHN@GMAIL.COM,+91-9876543210,Bengaluru,"₹50,000",Great service!
1,1002,alice smith,alice@yahoo.com,98765 43211,MUMBAI,"₹60,500",very GOOD product
2,1003,RAVI KUMAR,RAVI@OUTLOOK.COM,(987)654-3212,delhi,"₹45,000",Average experience
3,1004,Neha Sharma,neha.sharma@gmail.COM,9876543213,Chennai,"₹70,000",excellent support!!
4,1005,michael Brown,michael#gmail.com,98765-43214,Hyderabad,"₹55,500",bad delivery

In [4]:
data.dtypes

customer_id      int64
full_name       object
email           object
phone_number    object
city            object
salary          object
review_text     object
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   20 non-null     int64
 1   full_name     20 non-null     object
 2   email         20 non-null     object
 3   phone_number  20 non-null     object
 4   city          20 non-null     object
 5   salary        20 non-null     object
 6   review_text   20 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.2+ KB

#

#### 1. Remove leading and trailing spaces from full_name column.

In [7]:
df1 = data.copy()

In [8]:
df1['full_name'].head()

0         JOHN DOE
1     alice smith
2     RAVI KUMAR
3    Neha   Sharma
4    michael Brown
Name: full_name, dtype: object

In [9]:
df1['full_name'] = df1['full_name'].strip()

AttributeError: 'Series' object has no attribute 'strip'

In [10]:
df1['full_name'] = df1['full_name'].str.strip()

In [12]:
df1['full_name'].head()

0         JOHN DOE
1      alice smith
2       RAVI KUMAR
3    Neha   Sharma
4    michael Brown
Name: full_name, dtype: object

In [16]:
print(repr(df1['full_name'][0]))

'JOHN DOE'

In [17]:
df1['full_name'].head().tolist()

['JOHN DOE', 'alice smith', 'RAVI KUMAR', 'Neha   Sharma', 'michael Brown']

#

#### 2. Convert all names into title case.

In [18]:
df1['full_name'] = df1['full_name'].str.title()

In [21]:
df1['full_name'].head()

0         John Doe
1      Alice Smith
2       Ravi Kumar
3    Neha   Sharma
4    Michael Brown
Name: full_name, dtype: object

#

#### 3. Convert all email addresses to lowercase.

In [22]:
df1['email'].head()

0           JOHN@GMAIL.COM
1           alice@yahoo.com
2          RAVI@OUTLOOK.COM
3    neha.sharma@gmail.COM
4         michael#gmail.com
Name: email, dtype: object

In [23]:
df1['email'] = df1['email'].str.lower()

In [24]:
df1['email'].head()

0           john@gmail.com
1           alice@yahoo.com
2          ravi@outlook.com
3    neha.sharma@gmail.com
4         michael#gmail.com
Name: email, dtype: object

#

#### 4. Find rows containing invalid email formats.

In [25]:
invalid_emails = df1[ ~df1['email'].str.contains(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',regex=True, na=False)]
print(invalid_emails[['full_name', 'email']])

        full_name                   email
0        John Doe         john@gmail.com
1     Alice Smith         alice@yahoo.com
3   Neha   Sharma  neha.sharma@gmail.com
4   Michael Brown       michael#gmail.com
6     Arjun-Patil           arjun@company
7       Sara Khan    sara.khan@gmail.com
11      Kiran Rao          kiranrao@gmail
14     Pooja@Shah        pooja@@gmail.com
18     Sunil Naik   sunil.naik@gmail.com

In [26]:
df1['email'] = df1['email'].str.strip()

In [27]:
invalid_emails = df1[ ~df1['email'].str.contains(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',regex=True, na=False)]
print(invalid_emails[['full_name', 'email']])

        full_name              email
4   Michael Brown  michael#gmail.com
6     Arjun-Patil      arjun@company
11      Kiran Rao     kiranrao@gmail
14     Pooja@Shah   pooja@@gmail.com

#

#### 5. Remove special characters from phone_number.

In [28]:
df1['phone_number'].head()

0    +91-9876543210
1       98765 43211
2     (987)654-3212
3        9876543213
4       98765-43214
Name: phone_number, dtype: object

In [55]:
df1['clean_phone'] = (df1['phone_number'].str.replace(r'[^0-9]', '', regex=True).str[-10:])

In [56]:
df1['clean_phone']

0     9876543210
1     9876543211
2     9876543212
3     9876543213
4     9876543214
5     9876543215
6     9876543216
7     9876543217
8     9876543218
9     9876543219
10    9876543220
11    9876543221
12    9876543222
13    9876543223
14    9876543224
15    9876543225
16    9876543226
17    9876543227
18    9876543228
19    9876543229
Name: clean_phone, dtype: object

#

#### 6. Extract only numeric digits from phone_number.

In [57]:
df1['digits_only'] = df1['phone_number'].str.extract(r'(\d+)')

In [58]:
df1['digits_only']

0             91
1          98765
2            987
3     9876543213
4          98765
5             91
6     9876543216
7          98765
8     9876543218
9          98765
10    9876543220
11            98
12    9876543222
13    9876543223
14    9876543224
15         98765
16    9876543226
17    9876543227
18    9876543228
19    9876543229
Name: digits_only, dtype: object

#

#### 7. Standardize city names into proper title format.

In [59]:
df1['city']

0      Bengaluru
1          MUMBAI
2           delhi
3        Chennai
4       Hyderabad
5            pune
6       BENGALURU
7        kolkata
8           Delhi
9         MUMBAI
10      hyderabad
11           PUNE
12      bengaluru
13        Chennai
14         Delhi
15         Mumbai
16        Kolkata
17      HYDERABAD
18          Pune
19      Bengaluru
Name: city, dtype: object

In [60]:
df1['city'] = df1['city'].str.title()

In [61]:
df1['city']

0      Bengaluru
1          Mumbai
2           Delhi
3        Chennai
4       Hyderabad
5            Pune
6       Bengaluru
7        Kolkata
8           Delhi
9         Mumbai
10      Hyderabad
11           Pune
12      Bengaluru
13        Chennai
14         Delhi
15         Mumbai
16        Kolkata
17      Hyderabad
18          Pune
19      Bengaluru
Name: city, dtype: object

#

#### 8. Remove currency symbols and commas from salary column.

In [62]:
df1['salary']

0     ₹50,000
1     ₹60,500
2     ₹45,000
3     ₹70,000
4     ₹55,500
5     ₹40,000
6     ₹90,000
7     ₹62,000
8     ₹58,000
9     ₹47,500
10    ₹80,000
11    ₹65,000
12    ₹72,500
13    ₹38,000
14    ₹41,000
15    ₹59,500
16    ₹83,000
17    ₹77,000
18    ₹52,500
19    ₹69,000
Name: salary, dtype: object

In [63]:
df1['salary'] = df1['salary'].str.replace(r'[^0-9]','')

In [64]:
df1['salary']

0     ₹50,000
1     ₹60,500
2     ₹45,000
3     ₹70,000
4     ₹55,500
5     ₹40,000
6     ₹90,000
7     ₹62,000
8     ₹58,000
9     ₹47,500
10    ₹80,000
11    ₹65,000
12    ₹72,500
13    ₹38,000
14    ₹41,000
15    ₹59,500
16    ₹83,000
17    ₹77,000
18    ₹52,500
19    ₹69,000
Name: salary, dtype: object

In [65]:
df1['salary'] = df1['salary'].str.replace(r'[^0-9]','',regex=True)

In [66]:
df1['salary']

0     50000
1     60500
2     45000
3     70000
4     55500
5     40000
6     90000
7     62000
8     58000
9     47500
10    80000
11    65000
12    72500
13    38000
14    41000
15    59500
16    83000
17    77000
18    52500
19    69000
Name: salary, dtype: object

#

#### 9. Convert salary column into integer datatype.

In [67]:
df1['salary'].dtype

dtype('O')

In [69]:
df1['salary'].dtype.name

'object'

In [70]:
df1['salary']= df1['salary'].astype('Int64')

In [72]:
df1['salary'].dtype.name

'Int64'

In [73]:
df1['salary'].head()

0    50000
1    60500
2    45000
3    70000
4    55500
Name: salary, dtype: Int64

#

#### 10. Find customers using Gmail accounts.

In [78]:
gmail_users = df1[df1['email'].str.strip().str.lower().str.endswith('@gmail.com', na=False)]
print(gmail_users[['full_name', 'email']])

          full_name                  email
0          John Doe         john@gmail.com
3     Neha   Sharma  neha.sharma@gmail.com
5       Priya Reddy  priya_reddy@gmail.com
7         Sara Khan    sara.khan@gmail.com
8       Rohit Verma     rohit123@gmail.com
9     Anjali  Singh       anjali@gmail.com
12      Sneha Joshi      sneha.j@gmail.com
13          Amit123      amit123@gmail.com
14       Pooja@Shah       pooja@@gmail.com
15  Rahul  Kulkarni      rahul.k@gmail.com
17      Akash_Patel        akash@gmail.com
18       Sunil Naik   sunil.naik@gmail.com

#

#### 11. Count length of each customer name.

In [80]:
df1['name_length'] = df1['full_name'].str.len()

In [83]:
df1[['full_name','name_length']]

          full_name  name_length
0          John Doe            8
1       Alice Smith           11
2        Ravi Kumar           10
3     Neha   Sharma           13
4     Michael Brown           13
5       Priya Reddy           11
6       Arjun-Patil           11
7         Sara Khan            9
8       Rohit Verma           11
9     Anjali  Singh           13
10     David Miller           12
11        Kiran Rao            9
12      Sneha Joshi           11
13          Amit123            7
14       Pooja@Shah           10
15  Rahul  Kulkarni           15
16     Meena   Iyer           12
17      Akash_Patel           11
18       Sunil Naik           10
19       Fatima Ali           10

#

#### 12. Extract first names from full_name column.

In [84]:
df1['full_name'] = df1['full_name'].str.replace(r'[^a-zA-Z]',' ')

In [85]:
df1['full_name']

0            John Doe
1         Alice Smith
2          Ravi Kumar
3       Neha   Sharma
4       Michael Brown
5         Priya Reddy
6         Arjun-Patil
7           Sara Khan
8         Rohit Verma
9       Anjali  Singh
10       David Miller
11          Kiran Rao
12        Sneha Joshi
13            Amit123
14         Pooja@Shah
15    Rahul  Kulkarni
16       Meena   Iyer
17        Akash_Patel
18         Sunil Naik
19         Fatima Ali
Name: full_name, dtype: object

In [88]:
df1['first_name'] = df1['full_name'].str.split(' ')

In [89]:
df1['first_name']

0             [John, Doe]
1          [Alice, Smith]
2           [Ravi, Kumar]
3      [Neha, , , Sharma]
4        [Michael, Brown]
5          [Priya, Reddy]
6           [Arjun-Patil]
7            [Sara, Khan]
8          [Rohit, Verma]
9       [Anjali, , Singh]
10        [David, Miller]
11           [Kiran, Rao]
12         [Sneha, Joshi]
13              [Amit123]
14           [Pooja@Shah]
15    [Rahul, , Kulkarni]
16      [Meena, , , Iyer]
17          [Akash_Patel]
18          [Sunil, Naik]
19          [Fatima, Ali]
Name: first_name, dtype: object

In [90]:
df1['first_name'] = df1['full_name'].str.split().str.get(0)
print(df1[['full_name', 'first_name']])

          full_name   first_name
0          John Doe         John
1       Alice Smith        Alice
2        Ravi Kumar         Ravi
3     Neha   Sharma         Neha
4     Michael Brown      Michael
5       Priya Reddy        Priya
6       Arjun-Patil  Arjun-Patil
7         Sara Khan         Sara
8       Rohit Verma        Rohit
9     Anjali  Singh       Anjali
10     David Miller        David
11        Kiran Rao        Kiran
12      Sneha Joshi        Sneha
13          Amit123      Amit123
14       Pooja@Shah   Pooja@Shah
15  Rahul  Kulkarni        Rahul
16     Meena   Iyer        Meena
17      Akash_Patel  Akash_Patel
18       Sunil Naik        Sunil
19       Fatima Ali       Fatima

In [96]:
df1['full_name'] = df1['full_name'].str.replace(r'[^a-zA-Z]','',regex=True)

In [94]:
df1['full_name']

0           JohnDoe
1        AliceSmith
2         RaviKumar
3        NehaSharma
4      MichaelBrown
5        PriyaReddy
6        ArjunPatil
7          SaraKhan
8        RohitVerma
9       AnjaliSingh
10      DavidMiller
11         KiranRao
12       SnehaJoshi
13             Amit
14        PoojaShah
15    RahulKulkarni
16        MeenaIyer
17       AkashPatel
18        SunilNaik
19        FatimaAli
Name: full_name, dtype: object

In [98]:
## mistake

In [99]:
df1['full_name'] = df1['full_name'].str.replace(r'(?<!^)([A-Z])',r' \1',regex=True)
print(df1['full_name'])

0           John  Doe
1        Alice  Smith
2         Ravi  Kumar
3        Neha  Sharma
4      Michael  Brown
5        Priya  Reddy
6        Arjun  Patil
7          Sara  Khan
8        Rohit  Verma
9       Anjali  Singh
10      David  Miller
11         Kiran  Rao
12       Sneha  Joshi
13               Amit
14        Pooja  Shah
15    Rahul  Kulkarni
16        Meena  Iyer
17       Akash  Patel
18        Sunil  Naik
19        Fatima  Ali
Name: full_name, dtype: object

In [100]:
df1['first_name'] = df1['full_name'].str.split().str.get(0)
print(df1[['full_name', 'first_name']])

          full_name first_name
0         John  Doe       John
1      Alice  Smith      Alice
2       Ravi  Kumar       Ravi
3      Neha  Sharma       Neha
4    Michael  Brown    Michael
5      Priya  Reddy      Priya
6      Arjun  Patil      Arjun
7        Sara  Khan       Sara
8      Rohit  Verma      Rohit
9     Anjali  Singh     Anjali
10    David  Miller      David
11       Kiran  Rao      Kiran
12     Sneha  Joshi      Sneha
13             Amit       Amit
14      Pooja  Shah      Pooja
15  Rahul  Kulkarni      Rahul
16      Meena  Iyer      Meena
17     Akash  Patel      Akash
18      Sunil  Naik      Sunil
19      Fatima  Ali     Fatima

#

#### 13. Find rows where review_text contains the word 'good'.

In [101]:
df1['review_text']

0         Great service!
1       very GOOD product
2     Average experience
3     excellent support!!
4            bad delivery
5               Loved it
6         WORST packaging
7          Quick response
8           nice quality
9           Too expensive
10     Highly recommended
11         Not satisfied
12               amazing
13                   Good
14        Okay experience
15     Excellent Product
16     poor customer care
17          Fast shipping
18       Value for money
19          Best purchase
Name: review_text, dtype: object

In [102]:
good_reviews = df1[df1['review_text'].str.contains('good',case=False,na=False)]

In [103]:
good_reviews

,customer_id,full_name,email,phone_number,city,salary,review_text,clean_phone,digits_only,name_length,first_name
1,1002,Alice Smith,alice@yahoo.com,98765 43211,Mumbai,60500,very GOOD product,9876543211,98765,11,Alice
13,1014,Amit,amit123@gmail.com,abc9876543223,Chennai,38000,Good,9876543223,9876543223,7,Amit

#

#### 14. Remove duplicate spaces inside full_name.

In [104]:
df1['full_name'] = df1['full_name'].str.replace(r'\s+',' ',regex=True)
df1['full_name']

0           John Doe
1        Alice Smith
2         Ravi Kumar
3        Neha Sharma
4      Michael Brown
5        Priya Reddy
6        Arjun Patil
7          Sara Khan
8        Rohit Verma
9       Anjali Singh
10      David Miller
11         Kiran Rao
12       Sneha Joshi
13              Amit
14        Pooja Shah
15    Rahul Kulkarni
16        Meena Iyer
17       Akash Patel
18        Sunil Naik
19        Fatima Ali
Name: full_name, dtype: object

#

#### 15. Create a cleaned_full_name column using method chaining.

In [105]:
df1['cleaned_full_name'] = (df1['full_name'].str.replace(r'[^A-Za-z ]', ' ', regex=True).str.replace(r'\s+', ' ', regex=True).str.strip().str.title())

In [106]:
df1['cleaned_full_name']

0           John Doe
1        Alice Smith
2         Ravi Kumar
3        Neha Sharma
4      Michael Brown
5        Priya Reddy
6        Arjun Patil
7          Sara Khan
8        Rohit Verma
9       Anjali Singh
10      David Miller
11         Kiran Rao
12       Sneha Joshi
13              Amit
14        Pooja Shah
15    Rahul Kulkarni
16        Meena Iyer
17       Akash Patel
18        Sunil Naik
19        Fatima Ali
Name: cleaned_full_name, dtype: object

#

#### 16. Find rows containing uppercase text.

In [107]:
uppercase_rows = df1[df1['full_name'].str.isupper()]
uppercase_rows

Empty DataFrame
Columns: [customer_id, full_name, email, phone_number, city, salary, review_text, clean_phone, digits_only, name_length, first_name, cleaned_full_name]
Index: []

In [109]:
uppercase_rows.empty

True

#

#### 17. Replace invalid symbols in email addresses.

In [114]:
df2 = data.copy()

In [118]:
df2['email'] = (df2['email'].str.strip().str.lower())
df2['email'] = df2['email'].str.replace('#','@',regex=False)

In [121]:
df2['email'] = df1['email'].str.replace(r'@+','@',regex=True)

In [122]:
df2['email']

0            john@gmail.com
1           alice@yahoo.com
2          ravi@outlook.com
3     neha.sharma@gmail.com
4         michael@gmail.com
5     priya_reddy@gmail.com
6             arjun@company
7       sara.khan@gmail.com
8        rohit123@gmail.com
9          anjali@gmail.com
10        david@outlook.com
11           kiranrao@gmail
12        sneha.j@gmail.com
13        amit123@gmail.com
14          pooja@gmail.com
15        rahul.k@gmail.com
16     meena_iyer@yahoo.com
17          akash@gmail.com
18     sunil.naik@gmail.com
19       fatima@outlook.com
Name: email, dtype: object

#

#### 18. Remove numbers from full_name column.

In [123]:
df2['full_name']

0            JOHN DOE
1        alice smith
2        RAVI KUMAR
3       Neha   Sharma
4       michael Brown
5        PRIYA reddy
6         Arjun-patil
7          Sara Khan
8         rohit VERMA
9       ANJALI  SINGH
10       David Miller
11          kiran Rao
12        sneha Joshi
13            Amit123
14         Pooja@Shah
15    Rahul  Kulkarni
16       MEENA   IYER
17        akash_patel
18        Sunil Naik
19         Fatima Ali
Name: full_name, dtype: object

In [124]:
# df2['full_name'] = df2['full_name'].str.replace(r'[^a-zA-Z]','',regex = True)
df2['full_name'] = df2['full_name'].str.replace(r'/d+','',regex=True)

In [125]:
df2['full_name']

0            JOHN DOE
1        alice smith
2        RAVI KUMAR
3       Neha   Sharma
4       michael Brown
5        PRIYA reddy
6         Arjun-patil
7          Sara Khan
8         rohit VERMA
9       ANJALI  SINGH
10       David Miller
11          kiran Rao
12        sneha Joshi
13            Amit123
14         Pooja@Shah
15    Rahul  Kulkarni
16       MEENA   IYER
17        akash_patel
18        Sunil Naik
19         Fatima Ali
Name: full_name, dtype: object

In [127]:
df2['full_name'] = df2['full_name'].str.replace(r'\d+', '', regex=True)

In [128]:
df2['full_name']

0            JOHN DOE
1        alice smith
2        RAVI KUMAR
3       Neha   Sharma
4       michael Brown
5        PRIYA reddy
6         Arjun-patil
7          Sara Khan
8         rohit VERMA
9       ANJALI  SINGH
10       David Miller
11          kiran Rao
12        sneha Joshi
13               Amit
14         Pooja@Shah
15    Rahul  Kulkarni
16       MEENA   IYER
17        akash_patel
18        Sunil Naik
19         Fatima Ali
Name: full_name, dtype: object

#

#### 19. Extract email domains from email column.

In [130]:
df2['domain'] = df1['email'].str.extract(r'@(.+)')

In [131]:
df2['domain']

0       gmail.com
1       yahoo.com
2     outlook.com
3       gmail.com
4       gmail.com
5       gmail.com
6         company
7       gmail.com
8       gmail.com
9       gmail.com
10    outlook.com
11          gmail
12      gmail.com
13      gmail.com
14      gmail.com
15      gmail.com
16      yahoo.com
17      gmail.com
18      gmail.com
19    outlook.com
Name: domain, dtype: object

In [136]:
df2['email'].str.split('@').str.get(1)

0       gmail.com
1       yahoo.com
2     outlook.com
3       gmail.com
4       gmail.com
5       gmail.com
6         company
7       gmail.com
8       gmail.com
9       gmail.com
10    outlook.com
11          gmail
12      gmail.com
13      gmail.com
14      gmail.com
15      gmail.com
16      yahoo.com
17      gmail.com
18      gmail.com
19    outlook.com
Name: email, dtype: object

#