# Data Type Handling

In [1]:
import pandas as pd 
import numpy as np

In [4]:
data = pd.read_csv('datatype_handling.csv')

In [5]:
data.sample(10)

,employee_id,name,age,salary,joining_date,department,is_active,rating
268,1269,Sita,25,25000,15-02-2024,Sales,NaN,4.2
200,1201,Ravi,25,NaN,2023/03/20,Finance,no,NaN
265,1266,Amit,25,NaN,NaN,IT,no,NaN
278,1279,Neha,25,40000,2024-01-10,Sales,False,3.5
145,1146,John,NaN,25000,NaN,Sales,no,3.5
287,1288,Sita,25,55000,invalid_date,HR,True,NaN
293,1294,John,unknown,40000,2023/03/20,Finance,NaN,5
290,1291,Neha,25,50000,2024-01-10,Finance,NaN,3.5
183,1184,Ravi,NaN,55000,NaN,IT,NaN,4.2
80,1081,Sita,31,50000,NaN,HR,NaN,4.8

In [6]:
df = data.copy()

#### 1. Check datatype of all columns

In [7]:
df.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

#### 2. Check datatype of salary column

In [9]:
df['salary'].dtype.name

'object'

#### 3. Count how many object columns exist

In [11]:
print((df.dtypes == 'object').sum())

7

#### 4. Select only numeric columns

In [12]:
df.select_dtypes(include='number')

     employee_id
0           1001
1           1002
2           1003
3           1004
4           1005
..           ...
295         1296
296         1297
297         1298
298         1299
299         1300

[300 rows x 1 columns]

#### 5. Select only string/object columns

In [14]:
df.select_dtypes(include='object').columns

Index(['name', 'age', 'salary', 'joining_date', 'department', 'is_active',
       'rating'],
      dtype='object')

#### 6. Convert age to numeric

In [15]:
df['age'] = pd.to_numeric(df["age"])

ValueError: Unable to parse string "unknown" at position 0

In [16]:
df['age'] = pd.to_numeric(df["age"], errors='coerce')

In [17]:
df['age'].dtype.name

'float64'

#### 7. Convert salary to numeric

In [18]:
df['salary'] = pd.to_numeric(df['salary'],errors='coerce')

In [19]:
df['salary'].dtype

dtype('float64')

#### 8. Convert joining_date to datetime

In [20]:
df['joining_date'] = pd.to_datetime(df['joining_date'])

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_19660\313696224.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['joining_date'] = pd.to_datetime(df['joining_date'])

ValueError: time data "2024-01-10" doesn't match format "%d-%m-%Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [23]:
df['joining_date'] = pd.to_datetime(df['joining_date'],errors='coerce')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_19660\1160629233.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['joining_date'] = pd.to_datetime(df['joining_date'],errors='coerce')

In [27]:
df['joining_date'].head(10)

0   2024-02-15
1          NaT
2          NaT
3   2024-02-15
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: joining_date, dtype: datetime64[ns]

#### 9. Check memory usage of dataframe

In [28]:
df.memory_usage(deep=True)

Index             132
employee_id      2400
name            15900
age              2400
salary           2400
joining_date     2400
department      15864
is_active       14335
rating          14468
dtype: int64

#### 10. Convert department to category datatype

In [29]:
df['department'] = df['department'].astype('category')

In [30]:
df.dtypes

employee_id              int64
name                    object
age                    float64
salary                 float64
joining_date    datetime64[ns]
department            category
is_active               object
rating                  object
dtype: object

####

#### 11. Convert invalid salary values to NaN

In [31]:
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

#### 12. Convert invalid dates to NaT

In [32]:
df['joining_date'] = pd.to_datetime(df['joining_date'],errors = 'coerce')

In [33]:
df.head()

   employee_id  name   age   salary joining_date department is_active rating
0         1001  John   NaN  25000.0   2024-02-15    Finance     False    3.5
1         1002  Sita   NaN  25000.0          NaT      Sales        no    3.5
2         1003  Neha  22.0      NaN          NaT    Finance      True      5
3         1004  Sita   NaN  50000.0   2024-02-15         IT        no    NaN
4         1005  Sita   NaN  50000.0          NaT      Sales       NaN    3.5

In [34]:
data.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating
0,1001,John,unknown,25000,15-02-2024,Finance,False,3.5
1,1002,Sita,unknown,25000,2024-01-10,Sales,no,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
3,1004,Sita,NaN,50000,15-02-2024,IT,no,NaN
4,1005,Sita,unknown,50000,invalid_date,Sales,NaN,3.5

#### 13. Convert is_active into boolean datatype

In [35]:
df['is_active'] = df['is_active'].astype(bool)

In [36]:
df['is_active'].dtype

dtype('bool')

In [37]:
df['is_active'].head()

0    True
1    True
2    True
3    True
4    True
Name: is_active, dtype: bool

In [71]:
df3 = data.copy()

In [72]:
df3.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [67]:
df3.head(10)

,employee_id,name,age,salary,joining_date,department,is_active,rating
0,1001,John,unknown,25000,15-02-2024,Finance,False,3.5
1,1002,Sita,unknown,25000,2024-01-10,Sales,no,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
3,1004,Sita,NaN,50000,15-02-2024,IT,no,NaN
4,1005,Sita,unknown,50000,invalid_date,Sales,NaN,3.5
5,1006,Ravi,28,NaN,2024-01-10,Finance,True,4.8
6,1007,Neha,31,50000,2024-01-10,Finance,NaN,NaN
7,1008,Neha,22,55000,NaN,IT,False,4.8
8,1009,Neha,31,not_available,invalid_date,Finance,True,3.5
9,1010,Sita,unknown,50000,2024-01-10,Finance,NaN,3.5

In [78]:
df3['is_active'] = df['is_active'].replace({'yes': 1,'no': 0})

In [79]:
df3.head(10)

,employee_id,name,age,salary,joining_date,department,is_active,rating
0,1001,John,unknown,25000,15-02-2024,Finance,True,3.5
1,1002,Sita,unknown,25000,2024-01-10,Sales,True,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
3,1004,Sita,NaN,50000,15-02-2024,IT,True,NaN
4,1005,Sita,unknown,50000,invalid_date,Sales,True,3.5
5,1006,Ravi,28,NaN,2024-01-10,Finance,True,4.8
6,1007,Neha,31,50000,2024-01-10,Finance,True,NaN
7,1008,Neha,22,55000,NaN,IT,True,4.8
8,1009,Neha,31,not_available,invalid_date,Finance,True,3.5
9,1010,Sita,unknown,50000,2024-01-10,Finance,True,3.5

In [80]:
df3.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active         bool
rating          object
dtype: object

In [81]:
df4 = data.copy()
df4.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [82]:
df4['is_active'] = df4['is_active'].map({ 'yes': 1,'no': 0, True: 1, False: 0})

In [83]:
df4.dtypes

employee_id       int64
name             object
age              object
salary           object
joining_date     object
department       object
is_active       float64
rating           object
dtype: object

In [84]:
df4['is_active'] = df4['is_active'].astype(bool)

In [85]:
df4.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating
0,1001,John,unknown,25000,15-02-2024,Finance,True,3.5
1,1002,Sita,unknown,25000,2024-01-10,Sales,False,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
3,1004,Sita,NaN,50000,15-02-2024,IT,False,NaN
4,1005,Sita,unknown,50000,invalid_date,Sales,True,3.5

#### 14. Find columns with object datatype

In [86]:
df.select_dtypes(include='object').columns

Index(['name', 'rating'], dtype='object')

#### 15. Find columns with numeric datatype

In [87]:
df.select_dtypes(include='number').columns

Index(['employee_id', 'age', 'salary'], dtype='object')

#### 16. Automatically infer better datatypes

In [88]:
df2 = data.copy()

In [89]:
df2.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [90]:
df2 = df2.infer_objects()

In [91]:
df2.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [92]:
df2 = df2.convert_dtypes()

In [93]:
df2.dtypes

employee_id              Int64
name            string[python]
age             string[python]
salary          string[python]
joining_date    string[python]
department      string[python]
is_active       string[python]
rating          string[python]
dtype: object

#### 17. Use convert_dtypes() on full dataframe

In [109]:
df6 = data.copy()
df6.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [96]:
df6 = df6.convert_dtypes()
df6.dtypes

employee_id              Int64
name            string[python]
age             string[python]
salary          string[python]
joining_date    string[python]
department      string[python]
is_active       string[python]
rating          string[python]
dtype: object

#### 18.  Convert multiple columns together

In [97]:
df7 = data.copy()
df7.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

df7 = df7.astype({'department': 'category', 'rating':'float'})
ValueError: could not convert string to float: 'bad': Error while type casting for column 'rating'

In [100]:
df7.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating
0,1001,John,unknown,25000,15-02-2024,Finance,False,3.5
1,1002,Sita,unknown,25000,2024-01-10,Sales,no,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
3,1004,Sita,NaN,50000,15-02-2024,IT,no,NaN
4,1005,Sita,unknown,50000,invalid_date,Sales,NaN,3.5

In [101]:
df7.tail()

,employee_id,name,age,salary,joining_date,department,is_active,rating
295,1296,Sita,28,55000,2024-01-10,IT,NaN,4.2
296,1297,Sita,unknown,55000,NaN,Sales,False,NaN
297,1298,Neha,22,25000,2023/03/20,HR,False,3.5
298,1299,John,NaN,not_available,2023/03/20,Sales,yes,3.5
299,1300,Amit,31,50000,2024-01-10,Finance,NaN,3.5

In [103]:
df7.sample(10)

,employee_id,name,age,salary,joining_date,department,is_active,rating
192,1193,John,25,55000,invalid_date,HR,NaN,3.5
115,1116,Sita,NaN,25000,15-02-2024,Sales,True,5
91,1092,Amit,28,50000,NaN,Finance,False,NaN
65,1066,John,25,25000,2024-01-10,Finance,no,NaN
157,1158,Sita,31,25000,invalid_date,Finance,yes,NaN
207,1208,Neha,22,40000,15-02-2024,HR,False,5
149,1150,John,31,NaN,invalid_date,Finance,True,NaN
140,1141,Amit,NaN,not_available,2023/03/20,IT,yes,5
4,1005,Sita,unknown,50000,invalid_date,Sales,NaN,3.5
298,1299,John,NaN,not_available,2023/03/20,Sales,yes,3.5

In [104]:
df7['rating'].unique()

array(['3.5', '5', nan, '4.8', '4.2', 'bad'], dtype=object)

In [106]:
df7['rating'] = df7['rating'].replace('bad' , 1)

In [107]:
df7 = df7.astype({'department': 'category', 'rating':'float'})

In [108]:
df7.dtypes

employee_id        int64
name              object
age               object
salary            object
joining_date      object
department      category
is_active         object
rating           float64
dtype: object

#### 19. Extract year from joining_date

In [110]:
df8 = data.copy()

In [111]:
df8['joining_date'].dt.year

AttributeError: Can only use .dt accessor with datetimelike values

In [112]:
df8['joining_date'] = pd.to_datetime(df8['joining_date'],errors = 'coerce')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_19660\1087840459.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df8['joining_date'] = pd.to_datetime(df8['joining_date'],errors = 'coerce')

In [118]:
df8['year'] = df8['joining_date'].dt.year

In [119]:
df8.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating,year
0,1001,John,unknown,25000,2024-02-15,Finance,False,3.5,2024.0
1,1002,Sita,unknown,25000,NaT,Sales,no,3.5,NaN
2,1003,Neha,22,not_available,NaT,Finance,True,5,NaN
3,1004,Sita,NaN,50000,2024-02-15,IT,no,NaN,2024.0
4,1005,Sita,unknown,50000,NaT,Sales,NaN,3.5,NaN

#### 20. Extract month from joining_date

In [120]:
df8['month'] = df8['joining_date'].dt.month

In [121]:
df8.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating,year,month
0,1001,John,unknown,25000,2024-02-15,Finance,False,3.5,2024.0,2.0
1,1002,Sita,unknown,25000,NaT,Sales,no,3.5,NaN,NaN
2,1003,Neha,22,not_available,NaT,Finance,True,5,NaN,NaN
3,1004,Sita,NaN,50000,2024-02-15,IT,no,NaN,2024.0,2.0
4,1005,Sita,unknown,50000,NaT,Sales,NaN,3.5,NaN,NaN

df8= df8.astype({'year': int, 'month':int})
IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'year'

In [124]:
df8= df8.astype({'year':'Int64', 'month':'Int64'})

In [125]:
df8.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating,year,month
0,1001,John,unknown,25000,2024-02-15,Finance,False,3.5,2024,2
1,1002,Sita,unknown,25000,NaT,Sales,no,3.5,<NA>,<NA>
2,1003,Neha,22,not_available,NaT,Finance,True,5,<NA>,<NA>
3,1004,Sita,NaN,50000,2024-02-15,IT,no,NaN,2024,2
4,1005,Sita,unknown,50000,NaT,Sales,NaN,3.5,<NA>,<NA>

#### 21. Find non-numeric values in salary

In [128]:
df8[pd.to_numeric(df8['salary'], errors='coerce').isnull()]
# coerce :   Invalid → NaN

,employee_id,name,age,salary,joining_date,department,is_active,rating,year,month
2,1003,Neha,22,not_available,NaT,Finance,True,5,<NA>,<NA>
5,1006,Ravi,28,NaN,NaT,Finance,True,4.8,<NA>,<NA>
8,1009,Neha,31,not_available,NaT,Finance,True,3.5,<NA>,<NA>
10,1011,John,unknown,NaN,NaT,IT,False,5,<NA>,<NA>
15,1016,Ravi,25,NaN,2024-02-15,HR,False,5,2024,2
...,...,...,...,...,...,...,...,...,...,...
284,1285,Amit,unknown,NaN,2024-02-15,Sales,no,3.5,2024,2
288,1289,Neha,28,NaN,2024-02-15,IT,no,bad,2024,2
291,1292,Amit,unknown,not_available,NaT,Sales,False,4.2,<NA>,<NA>
294,1295,John,NaN,NaN,NaT,HR,True,4.2,<NA>,<NA>
298,1299,John,NaN,not_available,NaT,Sales,yes,3.5,<NA>,<NA>

#### 22. Replace invalid rating values with NaN

In [129]:
df8['rating'] = pd.to_numeric(df8['rating'], errors='coerce')

In [130]:
df8.head()

,employee_id,name,age,salary,joining_date,department,is_active,rating,year,month
0,1001,John,unknown,25000,2024-02-15,Finance,False,3.5,2024,2
1,1002,Sita,unknown,25000,NaT,Sales,no,3.5,<NA>,<NA>
2,1003,Neha,22,not_available,NaT,Finance,True,5.0,<NA>,<NA>
3,1004,Sita,NaN,50000,2024-02-15,IT,no,NaN,2024,2
4,1005,Sita,unknown,50000,NaT,Sales,NaN,3.5,<NA>,<NA>

#### 23. Convert age to nullable integer (Int64)

In [131]:
df8['age'] = pd.to_numeric(df8['age'], errors='coerce').astype('Int64')

In [132]:
df8.dtypes

employee_id              int64
name                    object
age                      Int64
salary                  object
joining_date    datetime64[ns]
department              object
is_active               object
rating                 float64
year                     Int64
month                    Int64
dtype: object

#### 24. Detect datetime columns programmatically

In [133]:
df9 = data.copy()
for col in df9.columns:
    if is_datetime64_any_dtype(df[col]):
        print(col)

NameError: name 'is_datetime64_any_dtype' is not defined

In [135]:
from pandas.api.types import is_datetime64_any_dtype
for col in df9.columns:
    if is_datetime64_any_dtype(df9[col]):
        print(col)

In [136]:
df.dtypes

employee_id              int64
name                    object
age                    float64
salary                 float64
joining_date    datetime64[ns]
department            category
is_active                 bool
rating                  object
dtype: object

In [137]:
for col in df.columns:
    if is_datetime64_any_dtype(df[col]):
        print(col)

joining_date

#### 25. Detect numeric columns programmatically

In [138]:
from pandas.api.types import is_numeric_dtype

for col in df9.columns:
    if is_numeric_dtype(df9[col]):
        print(col)

employee_id

In [139]:
df9.dtypes

employee_id      int64
name            object
age             object
salary          object
joining_date    object
department      object
is_active       object
rating          object
dtype: object

In [141]:
num_cols = ['age','salary','rating']
for col in num_cols:
    df9[col] = pd.to_numeric(df9[col],errors='coerce')

In [142]:
df9.dtypes

employee_id       int64
name             object
age             float64
salary          float64
joining_date     object
department       object
is_active        object
rating          float64
dtype: object

In [143]:
for col in df9.columns:
    if is_numeric_dtype(df9[col]):
        print(col)

employee_id
age
salary
rating

#### 26.  Detect string columns programmatically

In [144]:
from pandas.api.types import is_string_dtype

for col in df9.columns:
    if is_string_dtype(df9[col]):
        print(col)

name
department

#### 27. Convert all object columns to category

In [146]:
for col in df9.select_dtypes(include='object'):
    df9[col] = df9[col].astype('category')

In [147]:
df9.dtypes

employee_id        int64
name            category
age              float64
salary           float64
joining_date    category
department      category
is_active       category
rating           float64
dtype: object

#### 28. Convert all possible columns to optimized datatypes

In [148]:
df10 = data.copy()

In [149]:
df10 = df10.convert_dtypes()

In [150]:
df10.dtypes

employee_id              Int64
name            string[python]
age             string[python]
salary          string[python]
joining_date    string[python]
department      string[python]
is_active       string[python]
rating          string[python]
dtype: object

#### 29. Create datatype summary table

In [151]:
df10.dtypes.reset_index(name='datatype')

          index        datatype
0   employee_id           Int64
1          name  string[python]
2           age  string[python]
3        salary  string[python]
4  joining_date  string[python]
5    department  string[python]
6     is_active  string[python]
7        rating  string[python]

#### 30. Find rows where date conversion failed

In [153]:
df11 = data.copy()
temp = pd.to_datetime(df11['joining_date'], errors='coerce')

df11[temp.isnull()]

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_19660\1876374928.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  temp = pd.to_datetime(df11['joining_date'], errors='coerce')

,employee_id,name,age,salary,joining_date,department,is_active,rating
1,1002,Sita,unknown,25000,2024-01-10,Sales,no,3.5
2,1003,Neha,22,not_available,2024-01-10,Finance,True,5
4,1005,Sita,unknown,50000,invalid_date,Sales,NaN,3.5
5,1006,Ravi,28,NaN,2024-01-10,Finance,True,4.8
6,1007,Neha,31,50000,2024-01-10,Finance,NaN,NaN
...,...,...,...,...,...,...,...,...
295,1296,Sita,28,55000,2024-01-10,IT,NaN,4.2
296,1297,Sita,unknown,55000,NaN,Sales,False,NaN
297,1298,Neha,22,25000,2023/03/20,HR,False,3.5
298,1299,John,NaN,not_available,2023/03/20,Sales,yes,3.5
299,1300,Amit,31,50000,2024-01-10,Finance,NaN,3.5