
# Adding & Removing Columns in Pandas DataFrame

In [1]:
import pandas as pd

In [5]:
data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Amit", "Sara", "John", "Priya", "David", "Neha", "Ali", "Rohan"],
    "Department": ["IT", "HR", "IT", "Sales", "Finance", "HR", "IT", "Sales"],
    "Salary": [55000, 48000, 62000, 45000, 70000, 51000, 58000, 47000],
    "Experience": [2, 4, 5, 1, 8, 3, 6, 2],
    "Bonus": [5000, 4000, 6000, 3000, 8000, 4500, 6500, 3500]
}

In [6]:
data

{'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108],
 'Name': ['Amit', 'Sara', 'John', 'Priya', 'David', 'Neha', 'Ali', 'Rohan'],
 'Department': ['IT', 'HR', 'IT', 'Sales', 'Finance', 'HR', 'IT', 'Sales'],
 'Salary': [55000, 48000, 62000, 45000, 70000, 51000, 58000, 47000],
 'Experience': [2, 4, 5, 1, 8, 3, 6, 2],
 'Bonus': [5000, 4000, 6000, 3000, 8000, 4500, 6500, 3500]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   EmployeeID   Name Department  Salary  Experience  Bonus
0         101   Amit         IT   55000           2   5000
1         102   Sara         HR   48000           4   4000
2         103   John         IT   62000           5   6000
3         104  Priya      Sales   45000           1   3000
4         105  David    Finance   70000           8   8000
5         106   Neha         HR   51000           3   4500
6         107    Ali         IT   58000           6   6500
7         108  Rohan      Sales   47000           2   3500

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  8 non-null      int64
 1   Name        8 non-null      object
 2   Department  8 non-null      object
 3   Salary      8 non-null      int64
 4   Experience  8 non-null      int64
 5   Bonus       8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

#

In [10]:
df1 = df.copy()

#

# 1 — Basic Column Adding

### 1. Add a new column called Country with value "India" for all rows.

In [11]:
df1['Conntry'] = 'India'

In [12]:
df1

   EmployeeID   Name Department  Salary  Experience  Bonus Conntry
0         101   Amit         IT   55000           2   5000   India
1         102   Sara         HR   48000           4   4000   India
2         103   John         IT   62000           5   6000   India
3         104  Priya      Sales   45000           1   3000   India
4         105  David    Finance   70000           8   8000   India
5         106   Neha         HR   51000           3   4500   India
6         107    Ali         IT   58000           6   6500   India
7         108  Rohan      Sales   47000           2   3500   India

### 2. Add a column Tax which is 10% of Salary.

In [15]:
df1['Tax'] = df1['Salary']*0.10

In [16]:
df1

   EmployeeID   Name Department  Salary  Experience  Bonus Conntry     Tax
0         101   Amit         IT   55000           2   5000   India  5500.0
1         102   Sara         HR   48000           4   4000   India  4800.0
2         103   John         IT   62000           5   6000   India  6200.0
3         104  Priya      Sales   45000           1   3000   India  4500.0
4         105  David    Finance   70000           8   8000   India  7000.0
5         106   Neha         HR   51000           3   4500   India  5100.0
6         107    Ali         IT   58000           6   6500   India  5800.0
7         108  Rohan      Sales   47000           2   3500   India  4700.0

### 3. Add a column TotalSalary using: Salary + Bonus

In [17]:
df1['Total Salary'] = df1['Salary'] + df1['Bonus']

In [18]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary
0,101,Amit,IT,55000,2,5000,India,5500.0,60000
1,102,Sara,HR,48000,4,4000,India,4800.0,52000
2,103,John,IT,62000,5,6000,India,6200.0,68000
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000
4,105,David,Finance,70000,8,8000,India,7000.0,78000
5,106,Neha,HR,51000,3,4500,India,5100.0,55500
6,107,Ali,IT,58000,6,6500,India,5800.0,64500
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500

### 4. Add a column ExperienceLevel.
Condition:
Experience >= 5 → Senior  
Otherwise → Junior

In [19]:
import numpy as np

In [20]:
df1["ExperienceLevel"] = np.where(df1["Experience"] >= 5, "Senior", "Junior")

In [21]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior

### 5. Add a column SalaryAfterTax.
Formula:  
Salary - Tax

In [22]:
df1['SalaryAfterTax']= df1['Salary'] - df1['Tax']

In [23]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel,SalaryAfterTax
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior,49500.0
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior,43200.0
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior,55800.0
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior,40500.0
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior,63000.0
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior,45900.0
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior,52200.0
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior,42300.0

In [24]:
df1.iloc[:,-4:]

      Tax  Total Salary ExperienceLevel  SalaryAfterTax
0  5500.0         60000          Junior         49500.0
1  4800.0         52000          Junior         43200.0
2  6200.0         68000          Senior         55800.0
3  4500.0         48000          Junior         40500.0
4  7000.0         78000          Senior         63000.0
5  5100.0         55500          Junior         45900.0
6  5800.0         64500          Senior         52200.0
7  4700.0         50500          Junior         42300.0

### 6. Add a column MonthlySalary.

Formula:

Salary / 12

In [25]:
df1['Monthly Salary'] = df1['Salary']/12

In [26]:
df1.iloc[:,-3:]

  ExperienceLevel  SalaryAfterTax  Monthly Salary
0          Junior         49500.0     4583.333333
1          Junior         43200.0     4000.000000
2          Senior         55800.0     5166.666667
3          Junior         40500.0     3750.000000
4          Senior         63000.0     5833.333333
5          Junior         45900.0     4250.000000
6          Senior         52200.0     4833.333333
7          Junior         42300.0     3916.666667

In [28]:
df1.loc[:,['Salary','Monthly Salary']]

   Salary  Monthly Salary
0   55000     4583.333333
1   48000     4000.000000
2   62000     5166.666667
3   45000     3750.000000
4   70000     5833.333333
5   51000     4250.000000
6   58000     4833.333333
7   47000     3916.666667

### 7. Add a column NameLength containing length of employee names.

In [29]:
df1["Name Length"] = df1["Name"].str.len()

In [30]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel,SalaryAfterTax,Monthly Salary,Name Length
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior,49500.0,4583.333333,4
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior,43200.0,4000.000000,4
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior,55800.0,5166.666667,4
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior,40500.0,3750.000000,5
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior,63000.0,5833.333333,5
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior,45900.0,4250.000000,4
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior,52200.0,4833.333333,3
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior,42300.0,3916.666667,5

### 8. Add a column DepartmentCode.

Mapping:

IT → 1
HR → 2
Sales → 3
Finance → 4

In [31]:
mapping = {  "IT": 1, "HR": 2, "Sales": 3,"Finance": 4 }
df1["Department Code"] = df1["Department"].map(mapping)

In [32]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel,SalaryAfterTax,Monthly Salary,Name Length,Department Code
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior,49500.0,4583.333333,4,1
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior,43200.0,4000.000000,4,2
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior,55800.0,5166.666667,4,1
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior,40500.0,3750.000000,5,3
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior,63000.0,5833.333333,5,4
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior,45900.0,4250.000000,4,2
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior,52200.0,4833.333333,3,1
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior,42300.0,3916.666667,5,3

In [33]:
df1.iloc[:,[0,1,2,-1]]

   EmployeeID   Name Department  Department Code
0         101   Amit         IT                1
1         102   Sara         HR                2
2         103   John         IT                1
3         104  Priya      Sales                3
4         105  David    Finance                4
5         106   Neha         HR                2
6         107    Ali         IT                1
7         108  Rohan      Sales                3

### 9. Add a column IncrementedSalary.

Increase every salary by 15%.

In [35]:
df1["Incremented Salary"] = df1["Salary"] * 1.15

In [36]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel,SalaryAfterTax,Monthly Salary,Name Length,Department Code,Incremented Salary
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior,49500.0,4583.333333,4,1,63250.0
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior,43200.0,4000.000000,4,2,55200.0
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior,55800.0,5166.666667,4,1,71300.0
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior,40500.0,3750.000000,5,3,51750.0
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior,63000.0,5833.333333,5,4,80500.0
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior,45900.0,4250.000000,4,2,58650.0
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior,52200.0,4833.333333,3,1,66700.0
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior,42300.0,3916.666667,5,3,54050.0

In [37]:
df1.iloc[:,[0,1,3,7,-1]]

   EmployeeID   Name  Salary     Tax  Incremented Salary
0         101   Amit   55000  5500.0             63250.0
1         102   Sara   48000  4800.0             55200.0
2         103   John   62000  6200.0             71300.0
3         104  Priya   45000  4500.0             51750.0
4         105  David   70000  7000.0             80500.0
5         106   Neha   51000  5100.0             58650.0
6         107    Ali   58000  5800.0             66700.0
7         108  Rohan   47000  4700.0             54050.0

### 10. Add a column Rank.

Ranks based on highest salary.

In [40]:
df1["Rank"] = df1["Salary"].rank(ascending=False)

In [41]:
df1

,EmployeeID,Name,Department,Salary,Experience,Bonus,Conntry,Tax,Total Salary,ExperienceLevel,SalaryAfterTax,Monthly Salary,Name Length,Department Code,Incremented Salary,Rank
0,101,Amit,IT,55000,2,5000,India,5500.0,60000,Junior,49500.0,4583.333333,4,1,63250.0,4.0
1,102,Sara,HR,48000,4,4000,India,4800.0,52000,Junior,43200.0,4000.000000,4,2,55200.0,6.0
2,103,John,IT,62000,5,6000,India,6200.0,68000,Senior,55800.0,5166.666667,4,1,71300.0,2.0
3,104,Priya,Sales,45000,1,3000,India,4500.0,48000,Junior,40500.0,3750.000000,5,3,51750.0,8.0
4,105,David,Finance,70000,8,8000,India,7000.0,78000,Senior,63000.0,5833.333333,5,4,80500.0,1.0
5,106,Neha,HR,51000,3,4500,India,5100.0,55500,Junior,45900.0,4250.000000,4,2,58650.0,5.0
6,107,Ali,IT,58000,6,6500,India,5800.0,64500,Senior,52200.0,4833.333333,3,1,66700.0,3.0
7,108,Rohan,Sales,47000,2,3500,India,4700.0,50500,Junior,42300.0,3916.666667,5,3,54050.0,7.0

In [42]:
df1.iloc[:,[0,1,-1]]

   EmployeeID   Name  Rank
0         101   Amit   4.0
1         102   Sara   6.0
2         103   John   2.0
3         104  Priya   8.0
4         105  David   1.0
5         106   Neha   5.0
6         107    Ali   3.0
7         108  Rohan   7.0

#

#

# 2 — Column Insert

In [56]:
df2 = df.copy()

### 11. Insert a new column Gender at position 2.
Values : ["M", "F", "M", "F", "M", "F", "M", "M"]

In [57]:
df2.iloc[:,:3]

   EmployeeID   Name Department
0         101   Amit         IT
1         102   Sara         HR
2         103   John         IT
3         104  Priya      Sales
4         105  David    Finance
5         106   Neha         HR
6         107    Ali         IT
7         108  Rohan      Sales

In [58]:
df2.insert(2, "Gender", ["M", "F", "M", "F", "M", "F", "M", "M"])

In [50]:
df2

   EmployeeID   Name Gender Department  Salary  Experience  Bonus
0         101   Amit      M         IT   55000           2   5000
1         102   Sara      F         HR   48000           4   4000
2         103   John      M         IT   62000           5   6000
3         104  Priya      F      Sales   45000           1   3000
4         105  David      M    Finance   70000           8   8000
5         106   Neha      F         HR   51000           3   4500
6         107    Ali      M         IT   58000           6   6500
7         108  Rohan      M      Sales   47000           2   3500

### 12. Insert a column Age at first position.
Values:  [25, 28, 32, 24, 40, 29, 35, 26]

In [59]:
df2.insert(0, "Age", [25, 28, 32, 24, 40, 29, 35, 26])

In [60]:
df2

   Age  EmployeeID   Name Gender Department  Salary  Experience  Bonus
0   25         101   Amit      M         IT   55000           2   5000
1   28         102   Sara      F         HR   48000           4   4000
2   32         103   John      M         IT   62000           5   6000
3   24         104  Priya      F      Sales   45000           1   3000
4   40         105  David      M    Finance   70000           8   8000
5   29         106   Neha      F         HR   51000           3   4500
6   35         107    Ali      M         IT   58000           6   6500
7   26         108  Rohan      M      Sales   47000           2   3500

### 13. Insert a column PerformanceScore after Bonus column.
Values: [88, 76, 91, 69, 95, 80, 90, 72]

In [61]:
bonus_p = df.columns.get_loc("Bonus") + 1
scores = [88, 76, 91, 69, 95, 80, 90, 72]
df2.insert(bonus_p, "PerformanceScore", scores)

In [62]:
df2

,Age,EmployeeID,Name,Gender,Department,Salary,PerformanceScore,Experience,Bonus
0,25,101,Amit,M,IT,55000,88,2,5000
1,28,102,Sara,F,HR,48000,76,4,4000
2,32,103,John,M,IT,62000,91,5,6000
3,24,104,Priya,F,Sales,45000,69,1,3000
4,40,105,David,M,Finance,70000,95,8,8000
5,29,106,Neha,F,HR,51000,80,3,4500
6,35,107,Ali,M,IT,58000,90,6,6500
7,26,108,Rohan,M,Sales,47000,72,2,3500

### 14. Insert a column Email.
Format: name@company.com

In [65]:
df2["Email"] = df2["Name"].str.lower() + "@company.com"

In [68]:
df2.loc[:,['Name','Email']]

    Name              Email
0   Amit   amit@company.com
1   Sara   sara@company.com
2   John   john@company.com
3  Priya  priya@company.com
4  David  david@company.com
5   Neha   neha@company.com
6    Ali    ali@company.com
7  Rohan  rohan@company.com

#

#

# Level 3 — Removing Columns

In [69]:
df3 = df.copy()

In [70]:
df3

   EmployeeID   Name Department  Salary  Experience  Bonus
0         101   Amit         IT   55000           2   5000
1         102   Sara         HR   48000           4   4000
2         103   John         IT   62000           5   6000
3         104  Priya      Sales   45000           1   3000
4         105  David    Finance   70000           8   8000
5         106   Neha         HR   51000           3   4500
6         107    Ali         IT   58000           6   6500
7         108  Rohan      Sales   47000           2   3500

### 15. Remove column Bonus.

In [71]:
df3 = df3.drop(columns=["Bonus"])

In [72]:
df3

   EmployeeID   Name Department  Salary  Experience
0         101   Amit         IT   55000           2
1         102   Sara         HR   48000           4
2         103   John         IT   62000           5
3         104  Priya      Sales   45000           1
4         105  David    Finance   70000           8
5         106   Neha         HR   51000           3
6         107    Ali         IT   58000           6
7         108  Rohan      Sales   47000           2

### 16. Remove columns:
Experience  
Department

In [73]:
df3.drop(columns=["Experience", "Department"])

   EmployeeID   Name  Salary
0         101   Amit   55000
1         102   Sara   48000
2         103   John   62000
3         104  Priya   45000
4         105  David   70000
5         106   Neha   51000
6         107    Ali   58000
7         108  Rohan   47000

In [74]:
df3

   EmployeeID   Name Department  Salary  Experience
0         101   Amit         IT   55000           2
1         102   Sara         HR   48000           4
2         103   John         IT   62000           5
3         104  Priya      Sales   45000           1
4         105  David    Finance   70000           8
5         106   Neha         HR   51000           3
6         107    Ali         IT   58000           6
7         108  Rohan      Sales   47000           2

In [75]:
df3.drop(columns=["Experience", "Department"],inplace=True)

In [76]:
df3

   EmployeeID   Name  Salary
0         101   Amit   55000
1         102   Sara   48000
2         103   John   62000
3         104  Priya   45000
4         105  David   70000
5         106   Neha   51000
6         107    Ali   58000
7         108  Rohan   47000

### 17. Remove the first column using indexing.

In [77]:
df3 = df3.iloc[:, 1:]

In [78]:
df3

    Name  Salary
0   Amit   55000
1   Sara   48000
2   John   62000
3  Priya   45000
4  David   70000
5   Neha   51000
6    Ali   58000
7  Rohan   47000

### 18. Remove the last column using indexing.

In [79]:
df3 = df3.iloc[:, :-1]

In [80]:
df3

    Name
0   Amit
1   Sara
2   John
3  Priya
4  David
5   Neha
6    Ali
7  Rohan

### 19. Remove all columns except:
Name  
Salary

In [81]:
df4 = df.copy()

In [82]:
df4

   EmployeeID   Name Department  Salary  Experience  Bonus
0         101   Amit         IT   55000           2   5000
1         102   Sara         HR   48000           4   4000
2         103   John         IT   62000           5   6000
3         104  Priya      Sales   45000           1   3000
4         105  David    Finance   70000           8   8000
5         106   Neha         HR   51000           3   4500
6         107    Ali         IT   58000           6   6500
7         108  Rohan      Sales   47000           2   3500

In [83]:
df4 = df4[["Name", "Salary"]]

In [84]:
df4

    Name  Salary
0   Amit   55000
1   Sara   48000
2   John   62000
3  Priya   45000
4  David   70000
5   Neha   51000
6    Ali   58000
7  Rohan   47000

### 20. Remove columns whose datatype is object.

In [85]:
df5 = df.copy()

In [87]:
ob_cols = df5.select_dtypes(include="object").columns

In [89]:
ob_cols

Index(['Name', 'Department'], dtype='object')

In [90]:
df5 = df5.drop(columns=ob_cols)

In [91]:
df5

   EmployeeID  Salary  Experience  Bonus
0         101   55000           2   5000
1         102   48000           4   4000
2         103   62000           5   6000
3         104   45000           1   3000
4         105   70000           8   8000
5         106   51000           3   4500
6         107   58000           6   6500
7         108   47000           2   3500

#

#

# 4 — Intermediate

### 21. Create a new column SalaryCategory.
Condition:  
Salary > 60000 → High  
Salary between 50000 and 60000 → Medium  
Otherwise → Low

In [92]:
df6 = df.copy()

In [95]:
conditions = [df6["Salary"] > 60000, (df6["Salary"] >= 50000) & (df6["Salary"] <= 60000)]
choices = ["High", "Medium"]
df6["SalaryCategory"] = np.select(conditions, choices, default="Low")

In [96]:
df6

   EmployeeID   Name Department  Salary  Experience  Bonus SalaryCategory
0         101   Amit         IT   55000           2   5000         Medium
1         102   Sara         HR   48000           4   4000            Low
2         103   John         IT   62000           5   6000           High
3         104  Priya      Sales   45000           1   3000            Low
4         105  David    Finance   70000           8   8000           High
5         106   Neha         HR   51000           3   4500         Medium
6         107    Ali         IT   58000           6   6500         Medium
7         108  Rohan      Sales   47000           2   3500            Low

### 22. Create a column NetIncome.
Formula: Salary + Bonus - Tax

In [97]:
df6["Tax"] = df6["Salary"] * 0.10

In [98]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax
0,101,Amit,IT,55000,2,5000,Medium,5500.0
1,102,Sara,HR,48000,4,4000,Low,4800.0
2,103,John,IT,62000,5,6000,High,6200.0
3,104,Priya,Sales,45000,1,3000,Low,4500.0
4,105,David,Finance,70000,8,8000,High,7000.0
5,106,Neha,HR,51000,3,4500,Medium,5100.0
6,107,Ali,IT,58000,6,6500,Medium,5800.0
7,108,Rohan,Sales,47000,2,3500,Low,4700.0

In [99]:
df6["NetIncome"] = df6["Salary"] + df6["Bonus"] - df6["Tax"]

In [100]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0
2,103,John,IT,62000,5,6000,High,6200.0,61800.0
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0

### 23. Add a column PromotionEligible.
Condition: Experience >= 5 AND Salary > 55000

In [101]:
df6["PromotionEligible"] = ((df6["Experience"] >= 5) &(df6["Salary"] > 55000))

In [102]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome,PromotionEligible
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0,False
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0,False
2,103,John,IT,62000,5,6000,High,6200.0,61800.0,True
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0,False
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0,True
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0,False
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0,True
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0,False

### 24. Add a column YearlyBonusPercent.
Formula:  (Bonus / Salary) * 100

In [103]:
df6["YearlyBonusPercent"] = (df6["Bonus"] / df6["Salary"]) * 100

In [104]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome,PromotionEligible,YearlyBonusPercent
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0,False,9.090909
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0,False,8.333333
2,103,John,IT,62000,5,6000,High,6200.0,61800.0,True,9.677419
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0,False,6.666667
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0,True,11.428571
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0,False,8.823529
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0,True,11.206897
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0,False,7.446809

### 25. Remove duplicate columns if any exist.

In [105]:
df6["Salary_Copy"] = df6["Salary"]

In [106]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome,PromotionEligible,YearlyBonusPercent,Salary_Copy
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0,False,9.090909,55000
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0,False,8.333333,48000
2,103,John,IT,62000,5,6000,High,6200.0,61800.0,True,9.677419,62000
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0,False,6.666667,45000
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0,True,11.428571,70000
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0,False,8.823529,51000
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0,True,11.206897,58000
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0,False,7.446809,47000

In [107]:
df.columns.duplicated()

array([False, False, False, False, False, False, False])

In [116]:
df6 = df6.loc[:, ~df6.columns.duplicated()]

In [117]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome,PromotionEligible,YearlyBonusPercent,Salary_Copy
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0,False,9.090909,55000
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0,False,8.333333,48000
2,103,John,IT,62000,5,6000,High,6200.0,61800.0,True,9.677419,62000
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0,False,6.666667,45000
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0,True,11.428571,70000
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0,False,8.823529,51000
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0,True,11.206897,58000
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0,False,7.446809,47000

In [118]:
df6.columns

Index(['EmployeeID', 'Name', 'Department', 'Salary', 'Experience', 'Bonus',
       'SalaryCategory', 'Tax', 'NetIncome', 'PromotionEligible',
       'YearlyBonusPercent', 'Salary_Copy'],
      dtype='object')

In [120]:
df6 = df6.drop(columns='Salary_Copy')

In [121]:
df6

,EmployeeID,Name,Department,Salary,Experience,Bonus,SalaryCategory,Tax,NetIncome,PromotionEligible,YearlyBonusPercent
0,101,Amit,IT,55000,2,5000,Medium,5500.0,54500.0,False,9.090909
1,102,Sara,HR,48000,4,4000,Low,4800.0,47200.0,False,8.333333
2,103,John,IT,62000,5,6000,High,6200.0,61800.0,True,9.677419
3,104,Priya,Sales,45000,1,3000,Low,4500.0,43500.0,False,6.666667
4,105,David,Finance,70000,8,8000,High,7000.0,71000.0,True,11.428571
5,106,Neha,HR,51000,3,4500,Medium,5100.0,50400.0,False,8.823529
6,107,Ali,IT,58000,6,6500,Medium,5800.0,58700.0,True,11.206897
7,108,Rohan,Sales,47000,2,3500,Low,4700.0,45800.0,False,7.446809