# Pandas applymap()

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Math": [78, 45, 90, 66],
    "Science": [88, 55, 92, 70],
    "English": [81, 35, 95, 60]
})

In [4]:
df

   Math  Science  English
0    78       88       81
1    45       55       35
2    90       92       95
3    66       70       60

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     4 non-null      int64
 1   Science  4 non-null      int64
 2   English  4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

#

### 1. Multiply every student mark in the DataFrame by 2 using applymap().

In [8]:
df1 = df.copy()

In [9]:
df1.applymap(lambda x : x*2)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3355706560.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x : x*2)

   Math  Science  English
0   156      176      162
1    90      110       70
2   180      184      190
3   132      140      120

In [10]:
df1*2

   Math  Science  English
0   156      176      162
1    90      110       70
2   180      184      190
3   132      140      120

### 2. Add 5 grace marks to every subject mark using applymap().

In [11]:
df1.applymap(lambda x : x+5)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1025669645.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x : x+5)

   Math  Science  English
0    83       93       86
1    50       60       40
2    95       97      100
3    71       75       65

### 3. Convert every student mark into its square value using applymap().

In [13]:
df1.applymap( lambda x : x*x)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\4078001024.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap( lambda x : x*x)

   Math  Science  English
0  6084     7744     6561
1  2025     3025     1225
2  8100     8464     9025
3  4356     4900     3600

### 4. Convert every mark into a string format like "78 Marks" using applymap().

In [15]:
df1.applymap(lambda m : str(m)+' Marks')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\324112354.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : str(m)+' Marks')

       Math   Science   English
0  78 Marks  88 Marks  81 Marks
1  45 Marks  55 Marks  35 Marks
2  90 Marks  92 Marks  95 Marks
3  66 Marks  70 Marks  60 Marks

In [16]:
df1.map(lambda x : str(x)+' Marks')

       Math   Science   English
0  78 Marks  88 Marks  81 Marks
1  45 Marks  55 Marks  35 Marks
2  90 Marks  92 Marks  95 Marks
3  66 Marks  70 Marks  60 Marks

### 5. Add a percentage symbol after every value in the DataFrame.

In [17]:
df1.applymap(lambda x : str(x)+'%')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\2565991325.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x : str(x)+'%')

  Math Science English
0  78%     88%     81%
1  45%     55%     35%
2  90%     92%     95%
3  66%     70%     60%

In [18]:
df1.map(lambda x : str(x)+'%')

  Math Science English
0  78%     88%     81%
1  45%     55%     35%
2  90%     92%     95%
3  66%     70%     60%

### 6. Convert all numeric values into floating-point numbers using applymap().

In [19]:
df1.applymap(lambda m : float(m))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1760645385.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : float(m))

   Math  Science  English
0  78.0     88.0     81.0
1  45.0     55.0     35.0
2  90.0     92.0     95.0
3  66.0     70.0     60.0

### 7. Check whether each mark is even or odd and return "Even" or "Odd".

In [20]:
df1.applymap(lambda m : "Even" if m%2 ==0 else "Odd")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1928645069.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : "Even" if m%2 ==0 else "Odd")

   Math Science English
0  Even    Even     Odd
1   Odd     Odd     Odd
2  Even    Even     Odd
3  Even    Even    Even

In [22]:
df1.applymap(lambda m : str(m)+ "-Even" if m%2 ==0 else str(m)+ "-Odd")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\2331732370.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : str(m)+ "-Even" if m%2 ==0 else str(m)+ "-Odd")

      Math  Science  English
0  78-Even  88-Even   81-Odd
1   45-Odd   55-Odd   35-Odd
2  90-Even  92-Even   95-Odd
3  66-Even  70-Even  60-Even

### 8. Replace every mark greater than 75 with "Excellent" and remaining marks with "Average".

In [24]:
df1.applymap(lambda m : 'Excellent' if m > 75 else 'Average')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\4089285276.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : 'Excellent' if m > 75 else 'Average')

        Math    Science    English
0  Excellent  Excellent  Excellent
1    Average    Average    Average
2  Excellent  Excellent  Excellent
3    Average    Average    Average

### 9. Convert every mark into a currency-like format using the ₹ symbol.

In [25]:
df1.applymap(lambda  m : '$'+str(m))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\682818356.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda  m : '$'+str(m))

  Math Science English
0  $78     $88     $81
1  $45     $55     $35
2  $90     $92     $95
3  $66     $70     $60

### 10. Subtract 10 from every value present in the DataFrame.

In [27]:
df1.applymap(lambda m : m-10)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\282292571.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda m : m-10)

   Math  Science  English
0    68       78       71
1    35       45       25
2    80       82       85
3    56       60       50

### 11. Multiply only even marks by 10 while keeping odd marks unchanged.

In [28]:
df1.applymap(lambda a : a*10 if a%10 ==0 else a)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3366124251.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a : a*10 if a%10 ==0 else a)

   Math  Science  English
0    78       88       81
1    45       55       35
2   900       92       95
3    66      700      600

In [31]:
df1.applymap(lambda a : if a%10  a*10  )

SyntaxError: invalid syntax (99655403.py, line 1)

### 12.  Replace all negative values in the DataFrame with 0 using applymap().

In [34]:
df1.applymap(lambda a : 0 if a < 0 else a)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3883058805.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a : 0 if a < 0 else a)

   Math  Science  English
0    78       88       81
1    45       55       35
2    90       92       95
3    66       70       60

### 13. Convert every value into its absolute value using applymap().

In [36]:
df1.applymap(lambda a : abs(a))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1822028710.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a : abs(a))

   Math  Science  English
0    78       88       81
1    45       55       35
2    90       92       95
3    66       70       60

### 14. Find the square root of every numeric value using applymap().

In [38]:
import numpy as np

In [39]:
df1.applymap(lambda a : np.sqrt(a))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3104696210.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a : np.sqrt(a))

       Math   Science   English
0  8.831761  9.380832  9.000000
1  6.708204  7.416198  5.916080
2  9.486833  9.591663  9.746794
3  8.124038  8.366600  7.745967

In [40]:
df1.applymap(np.sqrt)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1627681314.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(np.sqrt)

       Math   Science   English
0  8.831761  9.380832  9.000000
1  6.708204  7.416198  5.916080
2  9.486833  9.591663  9.746794
3  8.124038  8.366600  7.745967

### 15. Round all decimal values in the DataFrame to 2 decimal places.

In [42]:
df1.applymap(lambda x: round(x, 2))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\2977594163.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x: round(x, 2))

   Math  Science  English
0    78       88       81
1    45       55       35
2    90       92       95
3    66       70       60

In [43]:
df2 = pd.DataFrame({'A':[67.89, 98.56, 30.788, 9.876], 'B':[89.987,78.963, 67.829,81.1]})

In [44]:
df2

        A       B
0  67.890  89.987
1  98.560  78.963
2  30.788  67.829
3   9.876  81.100

In [45]:
df2.applymap(lambda x: round(x, 2))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\731221406.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2.applymap(lambda x: round(x, 2))

       A      B
0  67.89  89.99
1  98.56  78.96
2  30.79  67.83
3   9.88  81.10

### 16. Convert marks greater than or equal to 35 into "Pass" and below 35 into "Fail".

In [46]:
df1.applymap(lambda x: "Pass" if x >= 35 else "Fail")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\545994994.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x: "Pass" if x >= 35 else "Fail")

   Math Science English
0  Pass    Pass    Pass
1  Pass    Pass    Pass
2  Pass    Pass    Pass
3  Pass    Pass    Pass

### 17. Replace all marks above 90 with "Topper" and remaining marks with "Normal".

In [49]:
df1.applymap(lambda a : "Topper" if a > 90 else "Normal")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1613263556.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a : "Topper" if a > 90 else "Normal")

     Math Science English
0  Normal  Normal  Normal
1  Normal  Normal  Normal
2  Normal  Topper  Topper
3  Normal  Normal  Normal

### 18. Convert all values greater than 80 into boolean True and remaining values into False.

In [51]:
df1.applymap(lambda a: a > 80)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\2598582831.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda a: a > 80)

    Math  Science  English
0  False     True     True
1  False    False    False
2   True     True     True
3  False    False    False

### 19. Replace marks divisible by 5 with "Divisible by 5".

In [53]:
df1.applymap(lambda x: "Divisible by 5" if x % 5 == 0 else x)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\4274581712.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x: "Divisible by 5" if x % 5 == 0 else x)

             Math         Science         English
0              78              88              81
1  Divisible by 5  Divisible by 5  Divisible by 5
2  Divisible by 5              92  Divisible by 5
3              66  Divisible by 5  Divisible by 5

### 20. Classify all values into:

"Low" for marks below 40
"Medium" for marks between 40 and 75
"High" for marks above 75

In [58]:
def classify(m):
    if m < 40:
        return "Low"
    elif m <= 75:
        return "Medium"
    else:
        return "High"

In [59]:
df1.applymap(classify)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\2696778888.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(classify)

     Math Science English
0    High    High    High
1  Medium  Medium     Low
2    High    High    High
3  Medium  Medium  Medium

#

#

In [61]:
salary_df = pd.DataFrame({
    "Salary": [25000, 50000, 75000],
    "Bonus": [5000, 7000, 9000]
})

In [62]:
salary_df

   Salary  Bonus
0   25000   5000
1   50000   7000
2   75000   9000

### 21. Convert all salary values in a salary DataFrame into "₹50,000" format using applymap().

In [69]:
salary_df.applymap(lambda x: "${:,.0f}".format(x))

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3297222762.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  salary_df.applymap(lambda x: "${:,.0f}".format(x))

    Salary   Bonus
0  $25,000  $5,000
1  $50,000  $7,000
2  $75,000  $9,000

### 22. Convert all temperature values into Celsius format.

In [70]:
temp_df = pd.DataFrame({
    "Morning": [25, 28],
    "Evening": [30, 32]
})

In [71]:
temp_df

   Morning  Evening
0       25       30
1       28       32

In [74]:
temp_df.applymap(lambda t : str(t) + "C")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\1930655487.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  temp_df.applymap(lambda t : str(t) + "C")

  Morning Evening
0     25C     30C
1     28C     32C

### 23. Convert all discount values into "20% OFF" format.

In [75]:
discount_df = pd.DataFrame({
    "Mobile": [10, 20],
    "Laptop": [15, 25]
})

In [76]:
discount_df

   Mobile  Laptop
0      10      15
1      20      25

In [77]:
discount_df.applymap(lambda d: str(d) + "% OFF")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3722507039.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  discount_df.applymap(lambda d: str(d) + "% OFF")

    Mobile   Laptop
0  10% OFF  15% OFF
1  20% OFF  25% OFF

### 24. In an attendance DataFrame, replace:
1 with "Present" ,  
0 with "Absent"

In [78]:
attendance_df = pd.DataFrame({
    "Day1": [1, 0, 1],
    "Day2": [0, 1, 1]
})

In [79]:
attendance_df

   Day1  Day2
0     1     0
1     0     1
2     1     1

In [85]:
attendance_df.applymap(lambda a: 'Present' if a == 1 else "Absent ")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3882630332.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  attendance_df.applymap(lambda a: 'Present' if a == 1 else "Absent ")

      Day1     Day2
0  Present  Absent
1  Absent   Present
2  Present  Present

### 25. Convert all product ratings:
4 and above → "Good",   
Below 4 → "Bad"

In [86]:
rating_df = pd.DataFrame({
    "Product1": [5, 3, 4],
    "Product2": [2, 4, 5]
})

In [87]:
rating_df

   Product1  Product2
0         5         2
1         3         4
2         4         5

In [91]:
rating_df.applymap(lambda a: "Good" if a >= 4 else "Bad")

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_11168\3485528523.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  rating_df.applymap(lambda a: "Good" if a >= 4 else "Bad")

  Product1 Product2
0     Good      Bad
1      Bad     Good
2     Good     Good