# Reshaping Data in Pandas

In [1]:
import pandas as pd

## Pandas  pivot()

In [2]:
data = {
    'Date': ['2025-01-01','2025-01-01','2025-01-02','2025-01-02','2025-01-03','2025-01-03'],
    'Product': ['Laptop','Mouse','Laptop','Mouse', 'Laptop','Mouse'],
    'Sales': [ 50000,2000, 55000,2500, 60000,3000]
}

In [5]:
df = pd.DataFrame(data)

In [7]:
df.head()

         Date Product  Sales
0  2025-01-01  Laptop  50000
1  2025-01-01   Mouse   2000
2  2025-01-02  Laptop  55000
3  2025-01-02   Mouse   2500
4  2025-01-03  Laptop  60000

In [8]:
df.columns

Index(['Date', 'Product', 'Sales'], dtype='object')

In [9]:
df.dtypes

Date       object
Product    object
Sales       int64
dtype: object

### 1. Convert Product into columns using pivot().

In [10]:
pv = df.pivot()

TypeError: DataFrame.pivot() missing 1 required keyword-only argument: 'columns'

In [12]:
pv = df.pivot(columns='Product')

In [13]:
pv

               Date                Sales
Product      Laptop       Mouse   Laptop   Mouse
0        2025-01-01         NaN  50000.0     NaN
1               NaN  2025-01-01      NaN  2000.0
2        2025-01-02         NaN  55000.0     NaN
3               NaN  2025-01-02      NaN  2500.0
4        2025-01-03         NaN  60000.0     NaN
5               NaN  2025-01-03      NaN  3000.0

In [16]:
pv1 = df.pivot(index='Date',columns='Product',values='Sales')

In [17]:
pv1

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [18]:
df.pivot(columns='Product',values='Sales')

Product   Laptop   Mouse
0        50000.0     NaN
1            NaN  2000.0
2        55000.0     NaN
3            NaN  2500.0
4        60000.0     NaN
5            NaN  3000.0

### 2. Keep: Date as rows , Product as columns, Sales as values

In [21]:
pv2 = df.pivot(index= 'Date', columns='Product',values='Sales')

In [22]:
pv2

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

### 3. Show only Laptop sales after pivot.

In [23]:
pv2

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [25]:
pv2['Laptop']

Date
2025-01-01    50000
2025-01-02    55000
2025-01-03    60000
Name: Laptop, dtype: int64

#

### 4. Show only Mouse sales after pivot.

In [26]:
pv4 = df.pivot(index='Date',columns='Product',values='Sales')

In [27]:
pv4

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [28]:
print(pv4['Mouse'])

Date
2025-01-01    2000
2025-01-02    2500
2025-01-03    3000
Name: Mouse, dtype: int64

### 5. Find Laptop sales on 2025-01-02.

In [30]:
pv5 = df.pivot(index= 'Date', columns='Product', values='Sales')

In [31]:
pv5

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [37]:
print(pv5.loc['2025-01-03', 'Laptop'])

60000

### 6. Find Mouse sales on 2025-01-03.

In [38]:
pv6 = df.pivot(index='Date', columns='Product',values='Sales')

In [39]:
pv6

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [40]:
print(pv6.loc['2025-01-03', 'Mouse'])

3000

### 7. Calculate total sales per day after pivot.

In [41]:
pv7 = df.pivot(index='Date',columns='Product',values='Sales')
pv7

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [42]:
pv7['Total'] = pv7.sum(axis=1)
pv7

Product     Laptop  Mouse  Total
Date
2025-01-01   50000   2000  52000
2025-01-02   55000   2500  57500
2025-01-03   60000   3000  63000

### 8. Find highest selling product each day.

In [43]:
pv8 = df.pivot(index='Date',columns='Product',values='Sales')

In [44]:
pv8

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [51]:
pv8.idxmax(axis=1)

Date
2025-01-01    Laptop
2025-01-02    Laptop
2025-01-03    Laptop
dtype: object

In [52]:
pv8[['Laptop','Mouse']].idxmax(axis=1)

Date
2025-01-01    Laptop
2025-01-02    Laptop
2025-01-03    Laptop
dtype: object

### 9. Find lowest selling product each day.

In [54]:
pv8.idxmin()

Product
Laptop    2025-01-01
Mouse     2025-01-01
dtype: object

In [55]:
pv8[['Laptop','Mouse']].idxmin()

Product
Laptop    2025-01-01
Mouse     2025-01-01
dtype: object

In [56]:
pv8[['Laptop','Mouse']].idxmin(axis=1)

Date
2025-01-01    Mouse
2025-01-02    Mouse
2025-01-03    Mouse
dtype: object

In [59]:
pv8.idxmin(axis=1)

Date
2025-01-01    Mouse
2025-01-02    Mouse
2025-01-03    Mouse
dtype: object

### 10. Check shape before pivot.
### Check shape after pivot.

In [60]:
df.shape

(6, 3)

In [65]:
pv

               Date                Sales
Product      Laptop       Mouse   Laptop   Mouse
0        2025-01-01         NaN  50000.0     NaN
1               NaN  2025-01-01      NaN  2000.0
2        2025-01-02         NaN  55000.0     NaN
3               NaN  2025-01-02      NaN  2500.0
4        2025-01-03         NaN  60000.0     NaN
5               NaN  2025-01-03      NaN  3000.0

In [66]:
pv.shape

(6, 4)

In [67]:
pv2

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [68]:
pv2.shape

(3, 2)

### 11. Print only pivoted column names.

In [70]:
pv11 = df.pivot(columns='Product')

In [71]:
pv11.columns

MultiIndex([( 'Date', 'Laptop'),
            ( 'Date',  'Mouse'),
            ('Sales', 'Laptop'),
            ('Sales',  'Mouse')],
           names=[None, 'Product'])

In [72]:
pv8.columns

Index(['Laptop', 'Mouse'], dtype='object', name='Product')

In [74]:
list(pv8.columns)

['Laptop', 'Mouse']

### 12. Reset index after pivot.

In [75]:
pv12 = df.pivot(index='Date',columns='Product')

In [76]:
pv12

            Sales
Product    Laptop Mouse
Date
2025-01-01  50000  2000
2025-01-02  55000  2500
2025-01-03  60000  3000

In [77]:
pv12.reset_index()

               Date  Sales
Product             Laptop Mouse
0        2025-01-01  50000  2000
1        2025-01-02  55000  2500
2        2025-01-03  60000  3000

### 13. Convert pivot result into CSV file.

In [82]:
pv13 = df.pivot(index='Date',columns='Product',values='Sales')

In [83]:
pv13

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [84]:
pv13.to_csv('sales_report.csv')

In [85]:
pp13 = pd.read_csv('sales_report.csv')

In [86]:
pp13

         Date  Laptop  Mouse
0  2025-01-01   50000   2000
1  2025-01-02   55000   2500
2  2025-01-03   60000   3000

### 14. Identify: original format . pivoted format

In [87]:
print(df)

         Date Product  Sales
0  2025-01-01  Laptop  50000
1  2025-01-01   Mouse   2000
2  2025-01-02  Laptop  55000
3  2025-01-02   Mouse   2500
4  2025-01-03  Laptop  60000
5  2025-01-03   Mouse   3000

In [89]:
print(pv13)

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

### 15. Find average sales per day after pivot.

In [90]:
pv15 = df.pivot(index='Date',columns='Product',values='Sales')

In [91]:
pv15

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [92]:
pv15[['Laptop','Mouse']].mean(axis=1)

Date
2025-01-01    26000.0
2025-01-02    28750.0
2025-01-03    31500.0
dtype: float64

### 16. Add new column:  Total = Laptop + Mouse

In [93]:
pv16 = df.pivot(index='Date',columns='Product',values='Sales')
pv16

Product     Laptop  Mouse
Date
2025-01-01   50000   2000
2025-01-02   55000   2500
2025-01-03   60000   3000

In [95]:
pv16['Total'] = pv16['Laptop'] + pv16['Mouse']
pv16

Product     Laptop  Mouse  Total
Date
2025-01-01   50000   2000  52000
2025-01-02   55000   2500  57500
2025-01-03   60000   3000  63000

### 17. Print all sales values greater than 50000 after pivot.

In [97]:
pv17 = df.pivot(index='Date',columns='Product',values='Sales')

In [99]:
pv17[pv17 > 50000]

Product      Laptop  Mouse
Date
2025-01-01      NaN    NaN
2025-01-02  55000.0    NaN
2025-01-03  60000.0    NaN

#

#

### A.  In Student Data  : Convert Subjects should become columns.

In [104]:
dataA = {
    'Student': ['A','A','B','B'],
    'Subject': ['Math','Science','Math','Science'],
    'Marks': [90,85,78,88]
}
dfA = pd.DataFrame(dataA)
print('-------DataFrame ---------')
print(dfA)
pvA = dfA.pivot(index='Student',columns='Subject',values='Marks')
print()
print('----After Pivot---')
print(pvA)

-------DataFrame ---------
  Student  Subject  Marks
0       A     Math     90
1       A  Science     85
2       B     Math     78
3       B  Science     88

----After Pivot---
Subject  Math  Science
Student
A          90       85
B          78       88

### B. In Hospital Daily Patients data :  Departments become columns.

In [107]:
hospital_data = {
    'Date': ['1-Jan','1-Jan','2-Jan','2-Jan'],
    'Department': ['Cardio','ENT','Cardio','ENT'],
    'Patients': [45,30,50,28]
}

dfB = pd.DataFrame(hospital_data)
print('-------DataFrame ---------')
print(dfB)
pvB = dfB.pivot(
    index='Date',
    columns='Department',
    values='Patients'
)
print()
print('--Pivote conversion -------------')
print(pvB)

-------DataFrame ---------
    Date Department  Patients
0  1-Jan     Cardio        45
1  1-Jan        ENT        30
2  2-Jan     Cardio        50
3  2-Jan        ENT        28

--Pivote conversion -------------
Department  Cardio  ENT
Date
1-Jan           45   30
2-Jan           50   28

In [ ]:
C. In  Website Traffic Data : Sources become columns.

In [108]:
web_data = {
    'Date': ['Mon','Mon','Mon'],
    'Source': ['Google','Instagram','YouTube'],
    'Visitors': [5000,3200,4100]
}

dfC = pd.DataFrame(web_data)

pvC = dfC.pivot(
    index='Date',
    columns='Source',
    values='Visitors'
)

print("---DF---")
print(dfC)
print()
print(pvC)

---DF---
  Date     Source  Visitors
0  Mon     Google      5000
1  Mon  Instagram      3200
2  Mon    YouTube      4100

Source  Google  Instagram  YouTube
Date
Mon       5000       3200     4100

### D. Employee data : Employees become columns.

In [111]:
emp_data = {
    'Date': ['Mon','Mon','Tue','Tue'],
    'Employee': ['Rahul','Amit','Rahul','Amit'],
    'Status': ['P','A','P','P']
}

dfD = pd.DataFrame(emp_data)

pvD = dfD.pivot(index='Date',columns='Employee',values='Status')
print(dfD)
print()
print(pvD)

  Date Employee Status
0  Mon    Rahul      P
1  Mon     Amit      A
2  Tue    Rahul      P
3  Tue     Amit      P

Employee Amit Rahul
Date
Mon         A     P
Tue         P     P

### E. Cricket Data :  Players become columns.

In [112]:
cr_data = {
    'Match': ['Match1','Match1','Match2','Match2'],
    'Player': ['Virat','Rohit','Virat','Rohit'],
    'Runs': [80,45,70,95]
}

dfE = pd.DataFrame(cr_data)

pvE = dfE.pivot(index='Match',columns='Player',values='Runs')
print(dfE)
print()
print(pvE)

    Match Player  Runs
0  Match1  Virat    80
1  Match1  Rohit    45
2  Match2  Virat    70
3  Match2  Rohit    95

Player  Rohit  Virat
Match
Match1     45     80
Match2     95     70