## Pandas Slicing and Selecting

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"Name":["Ram","Sham","Pramod","Raj","Kallapa"],"age":[22,23,25,26,20],"city":list("ABCDE"), "Code":[101,104,103,105,111]}, index = ["row1",'row2','row3','row4','row5'])
df

         Name  age city  Code
row1      Ram   22    A   101
row2     Sham   23    B   104
row3   Pramod   25    C   103
row4      Raj   26    D   105
row5  Kallapa   20    E   111

#### 1: Select a slice of rows and all columns using .loc

In [4]:
df.loc['row3':'row5',:]

         Name  age city  Code
row3   Pramod   25    C   103
row4      Raj   26    D   105
row5  Kallapa   20    E   111

#### 2: Select a slice of rows and a slice of columns using .loc

In [5]:
df.loc['row3':'row5','Name':'city']

         Name  age city
row3   Pramod   25    C
row4      Raj   26    D
row5  Kallapa   20    E

#### 3: Select the last row using .loc

In [6]:
df.loc[['row4']]

     Name  age city  Code
row4  Raj   26    D   105

In [7]:
df.loc['row4']

Name    Raj
age      26
city      D
Code    105
Name: row4, dtype: object

In [9]:
df.loc[[df.index[-1]]]

         Name  age city  Code
row5  Kallapa   20    E   111


#### 4.  Select first three rows using .loc

In [10]:
df.loc[df.index[:3]]

        Name  age city  Code
row1     Ram   22    A   101
row2    Sham   23    B   104
row3  Pramod   25    C   103

####  5.Select rows using .loc with a boolean index

In [12]:
df.loc[df['age']>22]

        Name  age city  Code
row2    Sham   23    B   104
row3  Pramod   25    C   103
row4     Raj   26    D   105

## 2. Position-based Indexing with .iloc

#### 16: Select a single value from a Series using .iloc

In [13]:
s1 = pd.Series(list("ABCD"),index=list("1234"))
s1

1    A
2    B
3    C
4    D
dtype: object

In [14]:
print(s1.iloc[1])
print(s1.loc['1']) # labels are object type S0 different output

B
A

#### 7: Select multiple values from a Series using .iloc with a list of positions

In [15]:
s1.iloc[[1,3,0]]

2    B
4    D
1    A
dtype: object

#### 8: Select a range of positions from a Series using .iloc

In [16]:
s1.iloc[0::2]

1    A
3    C
dtype: object

#### 9: Select a single row from a DataFrame using .iloc

In [17]:
df1 =pd.DataFrame({"Products":['pen','book','pencil','mouse'], "price":[10,30,5,100],"Stock":[80,29,120,25]})
df1

  Products  price  Stock
0      pen     10     80
1     book     30     29
2   pencil      5    120
3    mouse    100     25

In [18]:
df1.iloc[2]

Products    pencil
price            5
Stock          120
Name: 2, dtype: object

In [19]:
df1.iloc[[2]]

  Products  price  Stock
2   pencil      5    120

#### 10.  Select multiple rows from a DataFrame using .iloc with a list of positions

In [20]:
df1.iloc[[1,3]]

  Products  price  Stock
1     book     30     29
3    mouse    100     25

#### 11: Select a single column from a DataFrame using .iloc

In [22]:
df1.iloc[:,2]

0     80
1     29
2    120
3     25
Name: Stock, dtype: int64

In [23]:
df1.iloc[:,[2]]

   Stock
0     80
1     29
2    120
3     25

#### 12: Select multiple columns from a DataFrame using .iloc

In [25]:
# df1.iloc[:,[1,3]]  IndexError: positional indexers are out-of-bounds
df1.iloc[:,[1,0]]

   price Products
0     10      pen
1     30     book
2      5   pencil
3    100    mouse

#### 13: Select specific rows and columns from a DataFrame using .iloc

In [26]:
df1.iloc[[1,3],[0,2]]

  Products  Stock
1     book     29
3    mouse     25

#### 14: Select a row by position and column by position using .iloc

In [28]:
df1.iloc[0,1]

np.int64(10)

In [29]:
print(df1.iloc[0,1])

10

#### 15: Select non-contiguous rows and columns using .iloc

In [31]:
df1.iloc[::2,::2]

  Products  Stock
0      pen     80
2   pencil    120

#### 16: Select a slice of rows and all columns using .iloc

In [32]:
df1.iloc[-3:,:]

  Products  price  Stock
1     book     30     29
2   pencil      5    120
3    mouse    100     25

In [34]:
df1.iloc[-3:]

  Products  price  Stock
1     book     30     29
2   pencil      5    120
3    mouse    100     25

#### 17: Select a slice of rows and a slice of columns using .iloc

In [36]:
df1.iloc[-3:,0:2]

  Products  price
1     book     30
2   pencil      5
3    mouse    100

#### 18: Select the last row using .iloc

In [38]:
df1.iloc[-1]

Products    mouse
price         100
Stock          25
Name: 3, dtype: object

In [39]:
df1.iloc[[-1]]

  Products  price  Stock
3    mouse    100     25

#### 19: Select first three rows using .iloc

In [40]:
df1.iloc[:3]

  Products  price  Stock
0      pen     10     80
1     book     30     29
2   pencil      5    120

#### 20: Select rows using .iloc with step size

In [41]:
df1.iloc[::3]

  Products  price  Stock
0      pen     10     80
3    mouse    100     25

##  3. Mixed Selection & Direct Indexing

#### 21: Select a single column using dictionary-style indexing

In [42]:
df2 = pd.DataFrame({"Name":list("ABCDEF"), "Age":[22,33,44,55,53,44],"City":['Pune','Mumbai','Delhi','Benglore',"Hydrabad","Kolkata"]})
df2

  Name  Age      City
0    A   22      Pune
1    B   33    Mumbai
2    C   44     Delhi
3    D   55  Benglore
4    E   53  Hydrabad
5    F   44   Kolkata

In [44]:
df2["Name"]

0    A
1    B
2    C
3    D
4    E
5    F
Name: Name, dtype: object

In [45]:
df2[["Name"]]

  Name
0    A
1    B
2    C
3    D
4    E
5    F

#### 22: Select multiple columns using a list

In [46]:
# df2['Name','Age'] # KeyError: ('Name', 'Age')
df2[['Name','Age']]

  Name  Age
0    A   22
1    B   33
2    C   44
3    D   55
4    E   53
5    F   44

#### 23: Select the first row using .head(1)

In [48]:
df.head(1)

     Name  age city  Code
row1  Ram   22    A   101

#### 24. Select the last row

In [49]:
df2.tail(1)

  Name  Age     City
5    F   44  Kolkata

#### 25: Select a value by label using .at

In [50]:
df2.at[0,'Name']

'A'

#### 26: Select a value by position -- Queckly access single value

In [51]:
df2.iat[0,2]

'Pune'

#### 27: Select a subset of Series using .take()

In [52]:

s2 = pd.Series(["Akash",'Rahul','Ram',"Sheeta"])
s2

0     Akash
1     Rahul
2       Ram
3    Sheeta
dtype: object

In [53]:
# s2.take(1)#TypeError: len() of unsized object
s2.take([1,2])

1    Rahul
2      Ram
dtype: object

#### 28: Select a subset of DataFrame using .take()

In [54]:
# df2.take(2) #TypeError: len() of unsized object
df2.take([2])

  Name  Age   City
2    C   44  Delhi

In [55]:
df2.take([0,2])

  Name  Age   City
0    A   22   Pune
2    C   44  Delhi

In [56]:
df2.take([2],axis=1)

       City
0      Pune
1    Mumbai
2     Delhi
3  Benglore
4  Hydrabad
5   Kolkata

In [57]:
df2.take([2,0],axis=1)

       City Name
0      Pune    A
1    Mumbai    B
2     Delhi    C
3  Benglore    D
4  Hydrabad    E
5   Kolkata    F

##### 29: Select rows where index is in a list

In [58]:
df2.take([0,2,3])

  Name  Age      City
0    A   22      Pune
2    C   44     Delhi
3    D   55  Benglore

In [59]:
df2.iloc[[0,2,3]]

  Name  Age      City
0    A   22      Pune
2    C   44     Delhi
3    D   55  Benglore

In [60]:
# Correct way
result = df2[df2.index.isin(['a', 'c'])]
print(result)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [61]:
result = df2[df2.index.isin([0, 'c'])] # only 0 index preset and c index not in index list of DF
print(result)

  Name  Age  City
0    A   22  Pune

In [62]:
df2.index.isin([0, 'c'])

array([ True, False, False, False, False, False])

#### 30. Select rows where index matches a condition

In [63]:
df2.loc[df2.index>3]

  Name  Age      City
4    E   53  Hydrabad
5    F   44   Kolkata

#### 31.  Select every other row from a DataFrame

In [64]:
df2[::2]

  Name  Age      City
0    A   22      Pune
2    C   44     Delhi
4    E   53  Hydrabad

#### 32: Select a single row and multiple columns by mixed indexing

In [65]:
# df2[0,['Name',"Age"]] #InvalidIndexError: (0, ['Name', 'Age'])
df2.loc[[0],['Name','Age']]

  Name  Age
0    A   22

#### 33: Select multiple rows and single column by mixed indexing

In [66]:
df2.loc[[0,2,3],["City"]]

       City
0      Pune
2     Delhi
3  Benglore

#### 34: Select index values directly from a Series

In [67]:
s3 = pd.Series(['A',"B","C","D"])
print(s3.index)
s3.index=['x','y','w','z']
print(s3.index)

RangeIndex(start=0, stop=4, step=1)
Index(['x', 'y', 'w', 'z'], dtype='object')

#### 35: Select a subset of index values from DataFrame

In [68]:
df3 = pd.DataFrame({'A': [1, 2, 3]}, index=['x', 'y', 'z'])

In [71]:
print(df3.index)
print(df3.index[:2])

Index(['x', 'y', 'z'], dtype='object')
Index(['x', 'y'], dtype='object')

#### 36 Select rows by matching index string pattern

In [72]:
df4 = pd.DataFrame({'A': [1, 2, 3],'B':list("TUR")}, index=['item-1', 'item-2', 'item-3'])
mask = df4.index.str.contains('item')
print(df4[mask])

        A  B
item-1  1  T
item-2  2  U
item-3  3  R

#### 37: Select rows using .xs() by level in MultiIndex

#### 38: Select column using .xs() in DataFrame

In [35]:
 df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
 result = df.xs('A', axis=1)
 print(result)

0    1
1    2
Name: A, dtype: int64

#### 39: Select a row as a Series using .loc

In [36]:
df2

  Name  Age      City
0    A   22      Pune
1    B   33    Mumbai
2    C   44     Delhi
3    D   55  Benglore
4    E   53  Hydrabad
5    F   44   Kolkata

In [39]:
s5= df2.loc[0]
type(s5)

pandas.core.series.Series

In [42]:
print(s5)

Name       A
Age       22
City    Pune
Name: 0, dtype: object

#### 40: Select a column as a Series using attribute-style

In [44]:
s6 = df2.Name
print(type(s6))
print(s6)

<class 'pandas.core.series.Series'>
0    A
1    B
2    C
3    D
4    E
5    F
Name: Name, dtype: object