# Pandas Merging & Joining¶

In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame({
    'customer_id': [101,102,103,104],
    'name': ['Om','Raj','Neha','Amit'],
    'city': ['Delhi','Mumbai','Pune','Delhi']
})

In [3]:
customers

   customer_id  name    city
0          101    Om   Delhi
1          102   Raj  Mumbai
2          103  Neha    Pune
3          104  Amit   Delhi

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4 non-null      int64
 1   name         4 non-null      object
 2   city         4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

#

In [5]:
orders = pd.DataFrame({
    'order_id': [1,2,3,4],
    'customer_id': [101,102,105,101],
    'product': ['Laptop','Phone','Tablet','Mouse']
})

In [6]:
orders

   order_id  customer_id product
0         1          101  Laptop
1         2          102   Phone
2         3          105  Tablet
3         4          101   Mouse

In [7]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     4 non-null      int64
 1   customer_id  4 non-null      int64
 2   product      4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

#

In [8]:
payments = pd.DataFrame({
    'payment_id': [11,12,13],
    'order_id': [1,2,5],
    'method': ['UPI','Card','Cash']
})

In [9]:
payments

   payment_id  order_id method
0          11         1    UPI
1          12         2   Card
2          13         5   Cash

#

# -----------------------METHOD: .merge()-----------------------

#### 1. Merge customers and orders using common column customer_id.

In [10]:
pd.merge(customers, orders, on='customer_id')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

#### 2. Show only matching customer records who placed orders.

In [13]:
pd.merge(customers, orders, on='customer_id',how='inner')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

#### 3. Show all customers even if they never ordered.

In [14]:
pd.merge(customers, orders, on='customer_id',how='left')

   customer_id  name    city  order_id product
0          101    Om   Delhi       1.0  Laptop
1          101    Om   Delhi       4.0   Mouse
2          102   Raj  Mumbai       2.0   Phone
3          103  Neha    Pune       NaN     NaN
4          104  Amit   Delhi       NaN     NaN

#### 4. Show all orders even if customer details are missing.

In [15]:
pd.merge(customers,orders,on='customer_id',how='right')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          102  Raj  Mumbai         2   Phone
2          105  NaN     NaN         3  Tablet
3          101   Om   Delhi         4   Mouse

#### 5. Show all customers and all orders including unmatched data.

In [16]:
pd.merge(customers,orders,on='customer_id',how='outer')

   customer_id  name    city  order_id product
0          101    Om   Delhi       1.0  Laptop
1          101    Om   Delhi       4.0   Mouse
2          102   Raj  Mumbai       2.0   Phone
3          103  Neha    Pune       NaN     NaN
4          104  Amit   Delhi       NaN     NaN
5          105   NaN     NaN       3.0  Tablet

#

In [17]:
orders2 = pd.DataFrame({
    'order_id':[1,2,3],
    'cust_id':[101,102,101],
    'product':['Laptop','Phone','Mouse']
})

In [18]:
orders2

   order_id  cust_id product
0         1      101  Laptop
1         2      102   Phone
2         3      101   Mouse

In [19]:
customers

   customer_id  name    city
0          101    Om   Delhi
1          102   Raj  Mumbai
2          103  Neha    Pune
3          104  Amit   Delhi

#### 6. Merge customers and orders2 where column names are different.

In [20]:
pd.merge(customers,orders2,
    left_on='customer_id',
    right_on='cust_id' )

   customer_id name    city  order_id  cust_id product
0          101   Om   Delhi         1      101  Laptop
1          101   Om   Delhi         3      101   Mouse
2          102  Raj  Mumbai         2      102   Phone

#

In [21]:
extra = pd.DataFrame({
    'customer_id':[101,102],
    'city':['Bangalore','Chennai']
})

In [22]:
extra

   customer_id       city
0          101  Bangalore
1          102    Chennai

In [24]:
customers

   customer_id  name    city
0          101    Om   Delhi
1          102   Raj  Mumbai
2          103  Neha    Pune
3          104  Amit   Delhi

#### 7. Merge customers and extra where same column name city exists.

In [25]:
pd.merge(customers,extra,on='customer_id')

   customer_id name  city_x     city_y
0          101   Om   Delhi  Bangalore
1          102  Raj  Mumbai    Chennai

In [27]:
pd.merge(customers,extra,on='customer_id',
    suffixes=('_cust','_extra')
)

   customer_id name city_cust city_extra
0          101   Om     Delhi  Bangalore
1          102  Raj    Mumbai    Chennai

#### 8. Identify : matching rows, left-only rows,right-only rows after merging customers and orders.

In [28]:
pd.merge(customers,orders,on='customer_id',how='outer')

   customer_id  name    city  order_id product
0          101    Om   Delhi       1.0  Laptop
1          101    Om   Delhi       4.0   Mouse
2          102   Raj  Mumbai       2.0   Phone
3          103  Neha    Pune       NaN     NaN
4          104  Amit   Delhi       NaN     NaN
5          105   NaN     NaN       3.0  Tablet

In [30]:
pd.merge(customers,orders,on='customer_id',how='outer',indicator=True)

   customer_id  name    city  order_id product      _merge
0          101    Om   Delhi       1.0  Laptop        both
1          101    Om   Delhi       4.0   Mouse        both
2          102   Raj  Mumbai       2.0   Phone        both
3          103  Neha    Pune       NaN     NaN   left_only
4          104  Amit   Delhi       NaN     NaN   left_only
5          105   NaN     NaN       3.0  Tablet  right_only

#

#### 9. Validate that: one customer  can have many orders
validate='one_to_many'

In [31]:
pd.merge(customers,orders,on='customer_id')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

In [32]:
pd.merge(customers,orders,on='customer_id',validate='one_to_many')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

#

#### 10. Sort merged output by merge key automatically.

In [33]:
pd.merge(customers,orders,on='customer_id')

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

In [34]:
pd.merge(customers,orders,on='customer_id',sort=True)

   customer_id name    city  order_id product
0          101   Om   Delhi         1  Laptop
1          101   Om   Delhi         4   Mouse
2          102  Raj  Mumbai         2   Phone

#

#### 11. Create all possible customer-product combinations.

In [35]:
pd.merge(customers,orders,on='customer_id',how='cross')

MergeError: Can not pass on, right_on, left_on or set right_index=True or left_index=True

In [36]:
pd.merge(customers,orders,how='cross')

    customer_id_x  name    city  order_id  customer_id_y product
0             101    Om   Delhi         1            101  Laptop
1             101    Om   Delhi         2            102   Phone
2             101    Om   Delhi         3            105  Tablet
3             101    Om   Delhi         4            101   Mouse
4             102   Raj  Mumbai         1            101  Laptop
5             102   Raj  Mumbai         2            102   Phone
6             102   Raj  Mumbai         3            105  Tablet
7             102   Raj  Mumbai         4            101   Mouse
8             103  Neha    Pune         1            101  Laptop
9             103  Neha    Pune         2            102   Phone
10            103  Neha    Pune         3            105  Tablet
11            103  Neha    Pune         4            101   Mouse
12            104  Amit   Delhi         1            101  Laptop
13            104  Amit   Delhi         2            102   Phone
14            104  Amit   Delhi         3            105  Tablet
15            104  Amit   Delhi         4            101   Mouse

#### 12. Merge using: multiple columns : customer_id , city both together.

In [37]:
orders3 = pd.DataFrame({
    'customer_id':[101,101,102],
    'city':['Delhi','Mumbai','Mumbai'],
    'product':['Laptop','Mouse','Phone']
})

In [39]:
orders3

   customer_id    city product
0          101   Delhi  Laptop
1          101  Mumbai   Mouse
2          102  Mumbai   Phone

In [42]:
customers

   customer_id  name    city
0          101    Om   Delhi
1          102   Raj  Mumbai
2          103  Neha    Pune
3          104  Amit   Delhi

In [44]:
pd.merge(customers,orders3,on=['customer_id','city'])

   customer_id name    city product
0          101   Om   Delhi  Laptop
1          102  Raj  Mumbai   Phone

#

#### 13. Merge 3 Tables : Custmers, Orders, payments

In [45]:
customers

   customer_id  name    city
0          101    Om   Delhi
1          102   Raj  Mumbai
2          103  Neha    Pune
3          104  Amit   Delhi

In [47]:
orders

   order_id  customer_id product
0         1          101  Laptop
1         2          102   Phone
2         3          105  Tablet
3         4          101   Mouse

In [48]:
payments

   payment_id  order_id method
0          11         1    UPI
1          12         2   Card
2          13         5   Cash

In [49]:
merged1 = pd.merge(customers,orders,on='customer_id')

final = pd.merge( merged1,payments,on='order_id')

final

   customer_id name    city  order_id product  payment_id method
0          101   Om   Delhi         1  Laptop          11    UPI
1          102  Raj  Mumbai         2   Phone          12   Card

#

#### 14. Duplicate Keys

In [50]:
orders_dup = pd.DataFrame({
    'customer_id':[101,101,101],
    'product':['Laptop','Mouse','Keyboard']
})

In [51]:
orders_dup

   customer_id   product
0          101    Laptop
1          101     Mouse
2          101  Keyboard

In [52]:
pd.merge(customers,orders_dup,on='customer_id')

   customer_id name   city   product
0          101   Om  Delhi    Laptop
1          101   Om  Delhi     Mouse
2          101   Om  Delhi  Keyboard

# -----------------------METHOD: DataFrame.join()-----------------------

In [53]:
employees = pd.DataFrame({'emp_id':[1,2,3,4],'name':['Om','Raj','Neha','Amit']}).set_index('emp_id')

In [54]:
employees

        name
emp_id
1         Om
2        Raj
3       Neha
4       Amit

In [55]:
salaries = pd.DataFrame({'salary':[50000,60000,70000]}, index=[1,2,5])

In [57]:
salaries

   salary
1   50000
2   60000
5   70000

#

#### 1. Join employees and salaries.

In [58]:
employees.join(salaries)

        name   salary
emp_id
1         Om  50000.0
2        Raj  60000.0
3       Neha      NaN
4       Amit      NaN

#### 2. Show only matching indexes.

In [59]:
employees.join(salaries,how='inner')

  name  salary
1   Om   50000
2  Raj   60000

#### 3. Keep all employee records.

In [60]:
employees.join(salaries,how='left')

        name   salary
emp_id
1         Om  50000.0
2        Raj  60000.0
3       Neha      NaN
4       Amit      NaN

#### 4. Keep all salary records.

In [62]:
employees.join(salaries,how='right')

  name  salary
1   Om   50000
2  Raj   60000
5  NaN   70000

#### 5. Keep all indexes from both DataFrames.

In [63]:
employees.join(salaries,how='outer')

   name   salary
1    Om  50000.0
2   Raj  60000.0
3  Neha      NaN
4  Amit      NaN
5   NaN  70000.0

####

#### 6. Join using column instead of index.

In [66]:
departments = pd.DataFrame({
    'emp_id':[1,2,3],
    'dept':['HR','IT','Sales']
})

In [67]:
departments

   emp_id   dept
0       1     HR
1       2     IT
2       3  Sales

In [70]:
employees.join(departments.set_index('emp_id'),on='emp_id')

        name   dept
emp_id
1         Om     HR
2        Raj     IT
3       Neha  Sales
4       Amit    NaN

#

#### 7. Join employees + salaries + departments.

In [75]:
employees.join(salaries).join(departments.set_index('emp_id'))

        name   salary   dept
emp_id
1         Om  50000.0     HR
2        Raj  60000.0     IT
3       Neha      NaN  Sales
4       Amit      NaN    NaN

#### 8. Reset Index After Join

In [76]:
employees.join(salaries)

        name   salary
emp_id
1         Om  50000.0
2        Raj  60000.0
3       Neha      NaN
4       Amit      NaN

In [77]:
employees.join(salaries).reset_index()

   emp_id  name   salary
0       1    Om  50000.0
1       2   Raj  60000.0
2       3  Neha      NaN
3       4  Amit      NaN

## join() — Overlapping Columns

In [78]:
emp = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['Om','Raj','Neha','Amit'],
    'salary':[50000,60000,70000,80000]
}).set_index('emp_id')

In [79]:
emp

        name  salary
emp_id
1         Om   50000
2        Raj   60000
3       Neha   70000
4       Amit   80000

In [80]:
bonus1 = pd.DataFrame({
    'salary':[5000,7000,9000],
    'bonus':[1000,2000,3000]
}, index=[1,2,5])

In [81]:
bonus1

   salary  bonus
1    5000   1000
2    7000   2000
5    9000   3000

#### 1 . OVERLAPPING COLUMN ERROR
Join employees and bonus directly.

In [82]:
emp.join(bonus1)

ValueError: columns overlap but no suffix specified: Index(['salary'], dtype='object')

#### 2. HANDLE OVERLAP USING SUFFIXES

In [83]:
emp.join(bonus1,lsuffix='_emp',rsuffix='_bonus')

        name  salary_emp  salary_bonus   bonus
emp_id
1         Om       50000        5000.0  1000.0
2        Raj       60000        7000.0  2000.0
3       Neha       70000           NaN     NaN
4       Amit       80000           NaN     NaN

#### 3. INNER JOIN + OVERLAPPING COLUMNS
Show only matching indexes.

In [85]:
emp.join(bonus1,how='inner',lsuffix='_emp',rsuffix='_bonus')

  name  salary_emp  salary_bonus  bonus
1   Om       50000          5000   1000
2  Raj       60000          7000   2000

#### 4 . LEFT JOIN + OVERLAPPING
Keep all employee records.

In [86]:
emp.join(bonus1,how='left',lsuffix='_emp',rsuffix='_bonus')

        name  salary_emp  salary_bonus   bonus
emp_id
1         Om       50000        5000.0  1000.0
2        Raj       60000        7000.0  2000.0
3       Neha       70000           NaN     NaN
4       Amit       80000           NaN     NaN

#### 5 . RIGHT JOIN + OVERLAPPING
Keep all bonus records.

In [87]:
emp.join(bonus1,how='right',lsuffix='_emp',rsuffix='_bonus')

  name  salary_emp  salary_bonus  bonus
1   Om     50000.0          5000   1000
2  Raj     60000.0          7000   2000
5  NaN         NaN          9000   3000

#### 6. SELECT ONLY NEEDED COLUMNS
Join only bonus column.

In [89]:
emp.join(bonus1[['bonus']])

        name  salary   bonus
emp_id
1         Om   50000  1000.0
2        Raj   60000  2000.0
3       Neha   70000     NaN
4       Amit   80000     NaN

#### 7. RENAME COLUMN BEFORE JOIn
Rename salary column before join.

In [90]:
bonus3 = bonus1.rename(columns={'salary':'bonus_salary'})
emp.join(bonus3)

        name  salary  bonus_salary   bonus
emp_id
1         Om   50000        5000.0  1000.0
2        Raj   60000        7000.0  2000.0
3       Neha   70000           NaN     NaN
4       Amit   80000           NaN     NaN

# --------------------------METHOD: pd.concat()----------------------

In [92]:
df1 = pd.DataFrame({ 'id':[1,2], 'name':['Om','Raj']})

In [93]:
df1

   id name
0   1   Om
1   2  Raj

In [94]:
df2 = pd.DataFrame({'id':[3,4],'name':['Neha','Amit']})

In [95]:
df2

   id  name
0   3  Neha
1   4  Amit

In [96]:
df3 = pd.DataFrame({'age':[22,25]})

In [97]:
df3

   age
0   22
1   25

In [ ]:
df4 = pd.DataFrame({'city':['Delhi','Mumbai']})

In [98]:
df4

     city
0   Delhi
1  Mumbai

#### 1. Concatenate df1 and df2 together.

In [102]:
pd.concat(df1,df2)

TypeError: concat() takes 1 positional argument but 2 were given

In [103]:
pd.concat([df1,df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 2. Combine three DataFrames at once.

In [104]:
pd.concat([df1,df2,df3])

    id  name   age
0  1.0    Om   NaN
1  2.0   Raj   NaN
0  3.0  Neha   NaN
1  4.0  Amit   NaN
0  NaN   NaN  22.0
1  NaN   NaN  25.0

#### 3. Concatenate df1, df2, and df4.

In [105]:
pd.concat([df1,df2,df4])

    id  name    city
0  1.0    Om     NaN
1  2.0   Raj     NaN
0  3.0  Neha     NaN
1  4.0  Amit     NaN
0  NaN   NaN   Delhi
1  NaN   NaN  Mumbai

#### 4. Stack multiple DataFrames vertically.

In [106]:
pd.concat([df1, df2], axis=0)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 5. Create one DataFrame using all datasets.

In [107]:
pd.concat([df1,df2,df3,df4])

    id  name   age    city
0  1.0    Om   NaN     NaN
1  2.0   Raj   NaN     NaN
0  3.0  Neha   NaN     NaN
1  4.0  Amit   NaN     NaN
0  NaN   NaN  22.0     NaN
1  NaN   NaN  25.0     NaN
0  NaN   NaN   NaN   Delhi
1  NaN   NaN   NaN  Mumbai

#### 6. Combine all student records.

In [109]:
pd.concat([df1, df2,df3,df4], ignore_index=True)

    id  name   age    city
0  1.0    Om   NaN     NaN
1  2.0   Raj   NaN     NaN
2  3.0  Neha   NaN     NaN
3  4.0  Amit   NaN     NaN
4  NaN   NaN  22.0     NaN
5  NaN   NaN  25.0     NaN
6  NaN   NaN   NaN   Delhi
7  NaN   NaN   NaN  Mumbai

In [110]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 7. Concatenate DataFrames stored inside a list.

In [113]:
dfs = [df1, df2]
pd.concat(dfs)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 8. Append multiple tables together.

In [114]:
pd.concat([df1, df2, df3])

    id  name   age
0  1.0    Om   NaN
1  2.0   Raj   NaN
0  3.0  Neha   NaN
1  4.0  Amit   NaN
0  NaN   NaN  22.0
1  NaN   NaN  25.0

#### 9. Combine DataFrames using one concat statement.

In [115]:
pd.concat([df1, df2, df4])

    id  name    city
0  1.0    Om     NaN
1  2.0   Raj     NaN
0  3.0  Neha     NaN
1  4.0  Amit     NaN
0  NaN   NaN   Delhi
1  NaN   NaN  Mumbai

#### 10. Combine DataFrames using one concat statement.

In [118]:
pd.concat([df1, df2, df3, df4], ignore_index=True)

    id  name   age    city
0  1.0    Om   NaN     NaN
1  2.0   Raj   NaN     NaN
2  3.0  Neha   NaN     NaN
3  4.0  Amit   NaN     NaN
4  NaN   NaN  22.0     NaN
5  NaN   NaN  25.0     NaN
6  NaN   NaN   NaN   Delhi
7  NaN   NaN   NaN  Mumbai

#### 11. Stack df1 and df2 vertically.

In [120]:
pd.concat([df1, df2], axis=0)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 12. Add new student rows below old rows.

In [121]:
pd.concat([df1, df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 13. Append df2 under df1.

In [122]:
pd.concat([df1, df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

In [123]:
pd.concat([df1, df2], axis=0)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 14. Perform vertical concatenation.

In [124]:
pd.concat([df1, df2], axis=0)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 15. Combine rows from both DataFrames.

In [125]:
pd.concat([df1, df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 16. Create one long DataFrame using rows.

In [127]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 17. Merge records row-by-row.

In [128]:
pd.concat([df1, df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 18. Add second dataset below first dataset.

In [129]:
pd.concat([df1, df2], axis=0)

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 19. Create student history table vertically.

In [132]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 20 Perform row stacking using concat.

In [134]:
pd.concat([df1, df2])

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 21. Combine df1 and df3 side-by-side.

In [135]:
pd.concat([df1, df3], axis=1)

   id name  age
0   1   Om   22
1   2  Raj   25

#### 22. Add age column to df1 using concat.

In [136]:
df3

   age
0   22
1   25

In [139]:
pd.concat([df1,df3],axis=1)

   id name  age
0   1   Om   22
1   2  Raj   25

#### 23. Concatenate columns horizontally.

In [140]:
pd.concat([df1, df4], axis=1)

   id name    city
0   1   Om   Delhi
1   2  Raj  Mumbai

#### 24. Create wider DataFrame using columns.

In [141]:
pd.concat([df1, df3, df4], axis=1)

   id name  age    city
0   1   Om   22   Delhi
1   2  Raj   25  Mumbai

#### 25. Combine student names and ages.

In [142]:
pd.concat([df1[['name']], df3], axis=1)

  name  age
0   Om   22
1  Raj   25

#### 26. Join datasets column-wise.

In [143]:
pd.concat([df1, df4], axis=1)

   id name    city
0   1   Om   Delhi
1   2  Raj  Mumbai

#### 27. Add city column using concat.

In [145]:
pd.concat([df1, df4], axis=1)

   id name    city
0   1   Om   Delhi
1   2  Raj  Mumbai

#### 28. Build profile table using multiple columns.

In [146]:
pd.concat([df1, df3, df4], axis=1)

   id name  age    city
0   1   Om   22   Delhi
1   2  Raj   25  Mumbai

#### 29. Create horizontal data combination.

In [147]:
pd.concat([df1, df3], axis=1)

   id name  age
0   1   Om   22
1   2  Raj   25

#### 30. Combine DataFrames based on index alignment.

In [148]:
pd.concat([df1, df4], axis=1)

   id name    city
0   1   Om   Delhi
1   2  Raj  Mumbai

#### 31. Concatenate df1 and df2 with new indexes.

In [149]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 32. Reset indexes after concat.

In [153]:
pd.concat([df4, df2], ignore_index=True)

     city   id  name
0   Delhi  NaN   NaN
1  Mumbai  NaN   NaN
2     NaN  3.0  Neha
3     NaN  4.0  Amit

#### 33. Avoid duplicate indexes after stacking.

In [154]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 34. Create continuous indexing after concat.

In [155]:
pd.concat([df1, df3], ignore_index=True)

    id name   age
0  1.0   Om   NaN
1  2.0  Raj   NaN
2  NaN  NaN  22.0
3  NaN  NaN  25.0

#### 35. Remove original indexes during concat.

In [156]:
pd.concat([df1, df2], ignore_index=True)

   id  name
0   1    Om
1   2   Raj
2   3  Neha
3   4  Amit

#### 36. Concatenate df1 and df3 keeping all columns.

In [160]:
pd.concat([df1, df2], join='outer')

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 37. Combine DataFrames with different columns.

In [161]:
pd.concat([df1, df4], join='outer')

    id name    city
0  1.0   Om     NaN
1  2.0  Raj     NaN
0  NaN  NaN   Delhi
1  NaN  NaN  Mumbai

#### 38. Keep unmatched columns during concat.

In [164]:
pd.concat([df1, df3], axis=0, join='outer')

    id name   age
0  1.0   Om   NaN
1  2.0  Raj   NaN
0  NaN  NaN  22.0
1  NaN  NaN  25.0

#### 39. Perform outer concatenation.

In [166]:
pd.concat([df1, df3, df4], join='outer')

    id name   age    city
0  1.0   Om   NaN     NaN
1  2.0  Raj   NaN     NaN
0  NaN  NaN  22.0     NaN
1  NaN  NaN  25.0     NaN
0  NaN  NaN   NaN   Delhi
1  NaN  NaN   NaN  Mumbai

#### 40. Preserve all available columns.

In [168]:
pd.concat([df1, df2,df3,df4], join='outer')

    id  name   age    city
0  1.0    Om   NaN     NaN
1  2.0   Raj   NaN     NaN
0  3.0  Neha   NaN     NaN
1  4.0  Amit   NaN     NaN
0  NaN   NaN  22.0     NaN
1  NaN   NaN  25.0     NaN
0  NaN   NaN   NaN   Delhi
1  NaN   NaN   NaN  Mumbai

#### 41. Concatenate df1 and df2 keeping common columns only.

In [169]:
pd.concat([df1, df2], join='inner')

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 42. Remove unmatched columns during concat.

In [170]:
pd.concat([df1, df3], join='inner')

Empty DataFrame
Columns: []
Index: [0, 1, 0, 1]

#### 43. Perform inner concat operation.

In [172]:
pd.concat([df1, df2], join='inner')

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#### 44. Concatenate only matching structures.

In [173]:
pd.concat([df1, df2], join='inner')

   id  name
0   1    Om
1   2   Raj
0   3  Neha
1   4  Amit

#

#### 46. Concatenate df1 and df2 using source labels.

In [179]:
pd.concat([df1, df2], keys=['class1','class2'])

          id  name
class1 0   1    Om
       1   2   Raj
class2 0   3  Neha
       1   4  Amit

#### 47. Create hierarchical indexing using concat.

In [181]:
pd.concat([df1, df2], keys=['A','B'])

     id  name
A 0   1    Om
  1   2   Raj
B 0   3  Neha
  1   4  Amit

#### 48. Add dataset names during concatenation.

In [183]:
pd.concat([df1, df2], keys=['df1','df2'])

       id  name
df1 0   1    Om
    1   2   Raj
df2 0   3  Neha
    1   4  Amit

#### 49. Identify source DataFrame after concat.

In [185]:
pd.concat([df1, df2], keys=['first','second'])

          id  name
first  0   1    Om
       1   2   Raj
second 0   3  Neha
       1   4  Amit

#### 50. Create multi-level index using keys.

In [187]:
pd.concat([df1, df2], keys=['batch1','batch2'])

          id  name
batch1 0   1    Om
       1   2   Raj
batch2 0   3  Neha
       1   4  Amit

#### 51. Concatenate df1 and df3 with sorted columns.

In [188]:
pd.concat([df1, df3], sort=True)

    age   id name
0   NaN  1.0   Om
1   NaN  2.0  Raj
0  22.0  NaN  NaN
1  25.0  NaN  NaN

#### 52. Automatically sort column names after concat.

In [189]:
pd.concat([df1, df4], sort=True)

     city   id name
0     NaN  1.0   Om
1     NaN  2.0  Raj
0   Delhi  NaN  NaN
1  Mumbai  NaN  NaN

In [191]:
pd.concat([df1,df2, df3], sort=True)

    age   id  name
0   NaN  1.0    Om
1   NaN  2.0   Raj
0   NaN  3.0  Neha
1   NaN  4.0  Amit
0  22.0  NaN   NaN
1  25.0  NaN   NaN

#### 53. Arrange columns alphabetically during concat.

In [193]:
pd.concat([df1,df2 ,df3,df4], sort=True)

    age    city   id  name
0   NaN     NaN  1.0    Om
1   NaN     NaN  2.0   Raj
0   NaN     NaN  3.0  Neha
1   NaN     NaN  4.0  Amit
0  22.0     NaN  NaN   NaN
1  25.0     NaN  NaN   NaN
0   NaN   Delhi  NaN   NaN
1   NaN  Mumbai  NaN   NaN

In [194]:
pd.concat([df1, df3], sort=True)

    age   id name
0   NaN  1.0   Om
1   NaN  2.0  Raj
0  22.0  NaN  NaN
1  25.0  NaN  NaN

#### 54. Concatenate df1 with itself.

In [195]:
pd.concat([df1,df1])

   id name
0   1   Om
1   2  Raj
0   1   Om
1   2  Raj

In [196]:
pd.concat([df4,df4,df4,df4,df4,df4])

     city
0   Delhi
1  Mumbai
0   Delhi
1  Mumbai
0   Delhi
1  Mumbai
0   Delhi
1  Mumbai
0   Delhi
1  Mumbai
0   Delhi
1  Mumbai