# --- Duplicate Handling ---

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('duplicate_handling_practice.csv')

In [3]:
data

     employee_id   name department  salary       city  rating
0           1010   Neha      Sales   60000     Mumbai     4.1
1           1037   Ravi         HR   40000  Bangalore     5.0
2           1016   Sita      Sales   30000       Pune     5.0
3           1001   Amit    Finance   25000     Mumbai     4.1
4           1050   John    Finance   40000       Pune     4.5
..           ...    ...        ...     ...        ...     ...
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

[280 rows x 6 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  280 non-null    int64
 1   name         280 non-null    object
 2   department   280 non-null    object
 3   salary       280 non-null    int64
 4   city         280 non-null    object
 5   rating       280 non-null    float64
dtypes: float64(1), int64(2), object(3)
memory usage: 13.3+ KB

#

In [5]:
df1 = data.copy()

#### 1. Check duplicate rows

In [6]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
275     True
276     True
277     True
278     True
279     True
Length: 280, dtype: bool

#### 2. Show only duplicate rows.

In [7]:
df1[df1.duplicated()]

     employee_id   name department  salary       city  rating
250         1032   Amit         HR   50000  Bangalore     4.1
251         1026   Neha    Finance   25000       Pune     3.8
252         1044   Sita      Sales   50000  Bangalore     4.5
253         1018   Neha      Sales   25000      Delhi     5.0
254         1049   Amit         IT   30000       Pune     3.8
255         1014   Ravi         IT   40000     Mumbai     3.8
256         1013   Amit    Finance   60000     Mumbai     3.2
257         1005   Neha         HR   50000      Delhi     4.5
258         1030   Ravi    Finance   60000  Bangalore     3.2
259         1001   Ravi      Sales   40000       Pune     5.0
260         1007  Pooja         HR   50000  Bangalore     3.2
261         1049   Sita      Sales   50000      Delhi     3.2
262         1008   Neha      Sales   50000      Delhi     3.8
263         1007   Neha         IT   50000  Bangalore     4.5
264         1033   Amit         IT   25000     Mumbai     4.5
265         1006   Sita      Sales   50000      Delhi     4.1
266         1033  Karan    Finance   60000      Delhi     4.5
267         1041   Ravi      Sales   60000  Bangalore     3.2
268         1026   Neha    Finance   30000      Delhi     5.0
269         1009   Neha    Finance   60000  Bangalore     4.1
270         1046   Neha         HR   25000     Mumbai     4.1
271         1048   Neha         HR   30000  Bangalore     4.1
272         1016   Amit         IT   25000      Delhi     3.2
273         1025   Neha         HR   30000       Pune     4.1
274         1026  Karan         HR   25000     Mumbai     3.2
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

#### 3.  Count total duplicate rows.

In [8]:
df1.duplicated().sum()

np.int64(30)

#### 4. Check duplicates using employee_id.

In [9]:
df1.duplicated(subset='employee_id')

0      False
1      False
2      False
3      False
4      False
       ...
275     True
276     True
277     True
278     True
279     True
Length: 280, dtype: bool

In [10]:
df1.duplicated(subset='employee_id').any()

np.True_

In [12]:
df1.duplicated(subset='employee_id').sum()

np.int64(230)

#### 5.  Show duplicate employee IDs.

In [13]:
df1[df1.duplicated(subset='employee_id')]

     employee_id   name department  salary       city  rating
9           1030   Ravi    Finance   60000  Bangalore     3.2
10          1050   Amit         IT   30000       Pune     4.1
12          1010   John         IT   25000  Bangalore     5.0
13          1001   Neha         HR   25000       Pune     3.8
16          1037   Ravi         IT   40000  Bangalore     3.2
..           ...    ...        ...     ...        ...     ...
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

[230 rows x 6 columns]

#### 6. Check duplicates using name.

In [14]:
df1.duplicated(subset='name')

0      False
1      False
2      False
3      False
4      False
       ...
275     True
276     True
277     True
278     True
279     True
Length: 280, dtype: bool

In [16]:
df1.duplicated(subset='name').sum()

np.int64(273)

#### 7. Show duplicate names only.

In [17]:
df1[df1.duplicated(subset='name')]

     employee_id   name department  salary       city  rating
5           1029   Sita         HR   50000     Mumbai     5.0
6           1026   Neha    Finance   25000       Pune     3.8
8           1049   Sita    Finance   40000       Pune     3.2
9           1030   Ravi    Finance   60000  Bangalore     3.2
10          1050   Amit         IT   30000       Pune     4.1
..           ...    ...        ...     ...        ...     ...
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

[273 rows x 6 columns]

#### 8. Check duplicate combinations of: name + department

In [18]:
df1.duplicated(subset=['name', 'department'])

0      False
1      False
2      False
3      False
4      False
       ...
275     True
276     True
277     True
278     True
279     True
Length: 280, dtype: bool

In [19]:
print(df1.duplicated(subset=['name', 'department']).sum())

252

In [20]:
df1.duplicated(subset=['name', 'department']).mean()*100

np.float64(90.0)

#### 9. Mark all duplicates.

In [21]:
df1.duplicated(keep=False)

0      False
1      False
2      False
3      False
4      False
       ...
275     True
276     True
277     True
278     True
279     True
Length: 280, dtype: bool

In [23]:
df1.duplicated(keep=False).sum()

np.int64(60)

#### 10. Keep last occurrence while checking duplicates.

In [24]:
df1.duplicated(keep='last')

0      False
1      False
2      False
3      False
4      False
       ...
275    False
276    False
277    False
278    False
279    False
Length: 280, dtype: bool

In [25]:
df1.duplicated(keep='last').sum()

np.int64(30)

#### 11. Find unique employee IDs count.

In [26]:
df1['employee_id'].nunique()

50

#### 12. Find repeated employee IDs only.

In [28]:
df1['employee_id'].value_counts()[df1['employee_id'].value_counts() > 1]

employee_id
1014    12
1010    10
1025    10
1026    10
1031     9
1049     9
1033     9
1018     9
1012     8
1016     8
1044     8
1019     8
1023     7
1030     7
1041     7
1050     7
1029     7
1001     7
1046     7
1008     7
1045     6
1005     6
1007     6
1043     6
1038     6
1037     5
1013     5
1034     5
1017     5
1009     5
1032     5
1006     5
1028     4
1015     4
1022     4
1047     4
1048     3
1002     3
1040     3
1021     3
1024     3
1004     3
1042     3
1011     2
1035     2
1027     2
1039     2
1003     2
Name: count, dtype: int64

#### 13. Count frequency of names.

In [29]:
df1['name'].value_counts()

name
Neha     53
Ravi     47
Amit     44
Pooja    35
John     34
Karan    34
Sita     33
Name: count, dtype: int64

#### 14. Show most repeated name.

In [31]:
df1['name'].value_counts().max()

53

In [32]:
df1['name'].value_counts()[0]

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_27540\2316265365.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df1['name'].value_counts()[0]

np.int64(53)

In [33]:
df1['name'].value_counts().idxmax()

'Neha'

#### 15.  Show least repeated department.

In [35]:
df1['name'].value_counts().idxmin()

'Sita'

#

#

#### 16. Remove duplicate rows.

In [36]:
df1.drop_duplicates()

     employee_id   name department  salary       city  rating
0           1010   Neha      Sales   60000     Mumbai     4.1
1           1037   Ravi         HR   40000  Bangalore     5.0
2           1016   Sita      Sales   30000       Pune     5.0
3           1001   Amit    Finance   25000     Mumbai     4.1
4           1050   John    Finance   40000       Pune     4.5
..           ...    ...        ...     ...        ...     ...
245         1005   Neha         IT   25000     Mumbai     5.0
246         1015   Ravi      Sales   40000     Mumbai     3.8
247         1046   Neha         HR   25000     Mumbai     4.1
248         1005   John         HR   60000  Bangalore     5.0
249         1007  Pooja         HR   60000      Delhi     3.2

[250 rows x 6 columns]

In [39]:
df1.duplicated().any()

np.True_

In [40]:
df1 = df1.drop_duplicates()

In [41]:
df1.duplicated().any()

np.False_

#### 17. Remove duplicates using: employee_id

In [42]:
df2 = data.copy()

In [43]:
df2['employee_id'].duplicated().any()

np.True_

In [44]:
df2 = df2.drop_duplicates(subset='employee_id')

In [45]:
df2['employee_id'].duplicated().any()

np.False_

#### 18. Keep last employee record.

In [46]:
df3 = data.copy()

In [47]:
df3.duplicated().any()

np.True_

In [48]:
df3 = df3.drop_duplicates(subset='employee_id',keep='last')

In [49]:
df3.duplicated().any()

np.False_

#### 19. Remove all duplicate employee IDs completely.

In [51]:
df4= data.copy()

In [52]:
df4.duplicated().any()

np.True_

In [53]:
df4 =  df4.drop_duplicates(subset='employee_id',keep=False)

In [54]:
df4.duplicated().any()

np.False_

In [56]:
df4.size

12

In [57]:
df3.size

300

In [58]:
df2.size

300

#### 20. Reset index after removing duplicates.

In [71]:
df5 = data.copy()

In [75]:
df5 = df5.drop_duplicates(ignore_index=True)

#### 21. Add duplicate indicator column.

In [76]:
df6 = data.copy()

In [77]:
df6['is_duplicate'] = df6.duplicated()

In [78]:
df6

     employee_id   name department  salary       city  rating  is_duplicate
0           1010   Neha      Sales   60000     Mumbai     4.1         False
1           1037   Ravi         HR   40000  Bangalore     5.0         False
2           1016   Sita      Sales   30000       Pune     5.0         False
3           1001   Amit    Finance   25000     Mumbai     4.1         False
4           1050   John    Finance   40000       Pune     4.5         False
..           ...    ...        ...     ...        ...     ...           ...
275         1014   John         HR   40000     Mumbai     3.8          True
276         1019   Neha         HR   40000  Bangalore     4.5          True
277         1050   Amit         IT   30000       Pune     4.1          True
278         1014  Karan    Finance   40000  Bangalore     3.2          True
279         1018   John         HR   50000  Bangalore     3.2          True

[280 rows x 7 columns]

#### 22. Calculate duplicate percentage.

In [79]:
df7 = data.copy()

In [81]:
print(f"{df7.duplicated().mean()*100 :.2f} %")

10.71 %

#### 23. Sort by salary then remove duplicates.

In [82]:
df8 = data.copy()

In [85]:
df8.sort_values(by='salary').drop_duplicates(inplace=True)

In [86]:
df8.duplicated().any()

np.True_

In [87]:
df8 = df8.sort_values(by='salary').drop_duplicates()

In [88]:
df8.duplicated().any()

np.False_

#### 24. Keep highest salary per employee.

In [89]:
df9 = data.copy()

In [91]:
df9 = df9.sort_values(by='salary').drop_duplicates(keep='last')

In [92]:
df9.duplicated().any()

np.False_

#### 25. Keep highest rating per employee.

In [93]:
df10 = data.copy()

In [95]:
df10 = df10.sort_values(by='rating').drop_duplicates(keep='last')

In [96]:
df10.duplicated().any()

np.False_

#### 26. Find employees appearing more than 3 times.

In [97]:
df11 = data.copy()

In [98]:
df11.value_counts()[df11.value_counts()>3]

Series([], Name: count, dtype: int64)

In [99]:
df11['employee_id'].value_counts()[df11['employee_id'].value_counts() > 3]

employee_id
1014    12
1010    10
1025    10
1026    10
1031     9
1049     9
1033     9
1018     9
1012     8
1016     8
1044     8
1019     8
1023     7
1030     7
1041     7
1050     7
1029     7
1001     7
1046     7
1008     7
1045     6
1005     6
1007     6
1043     6
1038     6
1037     5
1013     5
1034     5
1017     5
1009     5
1032     5
1006     5
1028     4
1015     4
1022     4
1047     4
Name: count, dtype: int64

#### 27. Find duplicate cities.

In [101]:
df11[df11['city'].duplicated()]

     employee_id   name department  salary       city  rating
3           1001   Amit    Finance   25000     Mumbai     4.1
4           1050   John    Finance   40000       Pune     4.5
5           1029   Sita         HR   50000     Mumbai     5.0
6           1026   Neha    Finance   25000       Pune     3.8
7           1030  Pooja      Sales   50000     Mumbai     4.1
..           ...    ...        ...     ...        ...     ...
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

[276 rows x 6 columns]

#### 28.Find rows duplicated across all columns except rating.

In [107]:
cols = df11.columns
cols = cols.drop('rating')
cols

Index(['employee_id', 'name', 'department', 'salary', 'city'], dtype='object')

In [110]:
df11[df11.duplicated(subset=cols)]

     employee_id   name department  salary       city  rating
250         1032   Amit         HR   50000  Bangalore     4.1
251         1026   Neha    Finance   25000       Pune     3.8
252         1044   Sita      Sales   50000  Bangalore     4.5
253         1018   Neha      Sales   25000      Delhi     5.0
254         1049   Amit         IT   30000       Pune     3.8
255         1014   Ravi         IT   40000     Mumbai     3.8
256         1013   Amit    Finance   60000     Mumbai     3.2
257         1005   Neha         HR   50000      Delhi     4.5
258         1030   Ravi    Finance   60000  Bangalore     3.2
259         1001   Ravi      Sales   40000       Pune     5.0
260         1007  Pooja         HR   50000  Bangalore     3.2
261         1049   Sita      Sales   50000      Delhi     3.2
262         1008   Neha      Sales   50000      Delhi     3.8
263         1007   Neha         IT   50000  Bangalore     4.5
264         1033   Amit         IT   25000     Mumbai     4.5
265         1006   Sita      Sales   50000      Delhi     4.1
266         1033  Karan    Finance   60000      Delhi     4.5
267         1041   Ravi      Sales   60000  Bangalore     3.2
268         1026   Neha    Finance   30000      Delhi     5.0
269         1009   Neha    Finance   60000  Bangalore     4.1
270         1046   Neha         HR   25000     Mumbai     4.1
271         1048   Neha         HR   30000  Bangalore     4.1
272         1016   Amit         IT   25000      Delhi     3.2
273         1025   Neha         HR   30000       Pune     4.1
274         1026  Karan         HR   25000     Mumbai     3.2
275         1014   John         HR   40000     Mumbai     3.8
276         1019   Neha         HR   40000  Bangalore     4.5
277         1050   Amit         IT   30000       Pune     4.1
278         1014  Karan    Finance   40000  Bangalore     3.2
279         1018   John         HR   50000  Bangalore     3.2

#### 29. Remove duplicates using: name + city

In [111]:
df11.duplicated().any()

np.True_

In [112]:
df11 = df11.drop_duplicates(subset=['name','city'])

In [113]:
df11.duplicated().any()

np.False_

#### 30. Count unique combinations:department + city

In [114]:
df11.groupby(['department', 'city']).size()

department  city
Finance     Mumbai       1
            Pune         4
HR          Bangalore    4
            Mumbai       2
IT          Bangalore    1
            Delhi        2
            Mumbai       2
            Pune         2
Sales       Bangalore    2
            Delhi        5
            Mumbai       2
            Pune         1
dtype: int64

In [116]:
df12 = data.copy()

In [117]:
df12.groupby(['department', 'city']).size()

department  city
Finance     Bangalore    17
            Delhi        23
            Mumbai       10
            Pune         19
HR          Bangalore    28
            Delhi        17
            Mumbai       19
            Pune         10
IT          Bangalore    16
            Delhi        15
            Mumbai       17
            Pune         15
Sales       Bangalore    18
            Delhi        24
            Mumbai       13
            Pune         19
dtype: int64

#### 31. Create dataframe containing only unique rows

In [118]:
df12[~df12.duplicated()]

     employee_id   name department  salary       city  rating
0           1010   Neha      Sales   60000     Mumbai     4.1
1           1037   Ravi         HR   40000  Bangalore     5.0
2           1016   Sita      Sales   30000       Pune     5.0
3           1001   Amit    Finance   25000     Mumbai     4.1
4           1050   John    Finance   40000       Pune     4.5
..           ...    ...        ...     ...        ...     ...
245         1005   Neha         IT   25000     Mumbai     5.0
246         1015   Ravi      Sales   40000     Mumbai     3.8
247         1046   Neha         HR   25000     Mumbai     4.1
248         1005   John         HR   60000  Bangalore     5.0
249         1007  Pooja         HR   60000      Delhi     3.2

[250 rows x 6 columns]

#### 32. Find top 5 most duplicated employee IDs

In [119]:
df12['employee_id'].value_counts().head(5)

employee_id
1014    12
1010    10
1025    10
1026    10
1031     9
Name: count, dtype: int64