# Pandas pivot_table()

In [1]:
import pandas as pd

In [2]:
data = {
    'city': ['Delhi','Delhi','Mumbai','Mumbai','Pune','Pune','Delhi','Mumbai'],
    'product': ['Laptop','Mobile','Laptop','Mobile','Laptop','Mobile','Tablet','Tablet'],
    'sales': [50000,20000,45000,25000,40000,18000,15000,22000],
    'quantity': [5,10,4,12,3,8,6,5],  
    'payment_method': ['UPI','Card','Cash','UPI','Card','Cash','UPI','Card']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

     city product  sales  quantity payment_method
0   Delhi  Laptop  50000         5            UPI
1   Delhi  Mobile  20000        10           Card
2  Mumbai  Laptop  45000         4           Cash
3  Mumbai  Mobile  25000        12            UPI
4    Pune  Laptop  40000         3           Card
5    Pune  Mobile  18000         8           Cash
6   Delhi  Tablet  15000         6            UPI
7  Mumbai  Tablet  22000         5           Card

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   city            8 non-null      object
 1   product         8 non-null      object
 2   sales           8 non-null      int64
 3   quantity        8 non-null      int64
 4   payment_method  8 non-null      object
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes

### 1. Create pivot table using only sales column.

In [13]:
df.pivot_table(values='sales', index='city')

               sales
city
Delhi   28333.333333
Mumbai  30666.666667
Pune    29000.000000

### 2. Create pivot table using only quantity column.

In [16]:
df.pivot_table(values='quantity',index='product',aggfunc='sum')

         quantity
product
Laptop         12
Mobile         30
Tablet         11

In [17]:
df.pivot_table(values='quantity',index='city',aggfunc='sum')

        quantity
city
Delhi         21
Mumbai        21
Pune          11

### 3. Create pivot table using both sales and quantity.

In [19]:
df.pivot_table( values=['sales','quantity'], index='city')

        quantity         sales
city
Delhi        7.0  28333.333333
Mumbai       7.0  30666.666667
Pune         5.5  29000.000000

### 4.  Create pivot table with city as index.

In [20]:
df.head()

     city product  sales  quantity payment_method
0   Delhi  Laptop  50000         5            UPI
1   Delhi  Mobile  20000        10           Card
2  Mumbai  Laptop  45000         4           Cash
3  Mumbai  Mobile  25000        12            UPI
4    Pune  Laptop  40000         3           Card

In [23]:
df.pivot_table(index='city', values = 'quantity',aggfunc='count')

        quantity
city
Delhi          3
Mumbai         3
Pune           2

In [24]:
df.pivot_table(index='city', values = 'quantity',columns='product',aggfunc='count')

product  Laptop  Mobile  Tablet
city
Delhi       1.0     1.0     1.0
Mumbai      1.0     1.0     1.0
Pune        1.0     1.0     NaN

### 5. Create pivot table with product as index.

In [25]:
df.pivot_table(index='product', values = 'sales')

           sales
product
Laptop   45000.0
Mobile   21000.0
Tablet   18500.0

In [27]:
df.pivot_table(index='product', values = 'sales',columns='city')

city       Delhi   Mumbai     Pune
product
Laptop   50000.0  45000.0  40000.0
Mobile   20000.0  25000.0  18000.0
Tablet   15000.0  22000.0      NaN

### 6.  Create pivot table with : city , payment_method as multi-index.

In [28]:
df.pivot_table(values='sales',index=['city','payment_method'])

                         sales
city   payment_method
Delhi  Card            20000.0
       UPI             32500.0
Mumbai Card            22000.0
       Cash            45000.0
       UPI             25000.0
Pune   Card            40000.0
       Cash            18000.0

### 7.  Create pivot table with: city, product, payment_method as multi-index.

In [29]:
df.pivot_table( values='sales',   index=['city','product','payment_method'])

                                 sales
city   product payment_method
Delhi  Laptop  UPI             50000.0
       Mobile  Card            20000.0
       Tablet  UPI             15000.0
Mumbai Laptop  Cash            45000.0
       Mobile  UPI             25000.0
       Tablet  Card            22000.0
Pune   Laptop  Card            40000.0
       Mobile  Cash            18000.0

### 8. Create pivot table with:  product as columns.

In [31]:
df.pivot_table(values='sales', columns='product')

product   Laptop   Mobile   Tablet
sales    45000.0  21000.0  18500.0

### 9. Create pivot table with: payment_method  as columns.

In [32]:
df.pivot_table( values='sales',columns='payment_method')

payment_method          Card     Cash      UPI
sales           27333.333333  31500.0  30000.0

### 10. Create pivot table with: product, payment_method  as multi-columns.

In [34]:
df.pivot_table( values='sales', columns=['product','payment_method'])

product          Laptop                     Mobile                     Tablet  \
payment_method     Card     Cash      UPI     Card     Cash      UPI     Card
sales           40000.0  45000.0  50000.0  20000.0  18000.0  25000.0  22000.0

product
payment_method      UPI
sales           15000.0

### 11. Create pivot table using: aggfunc='sum'

In [37]:
df.pivot_table(values='sales',index='city',aggfunc='sum')

        sales
city
Delhi   85000
Mumbai  92000
Pune    58000

In [38]:
df.pivot_table(values='sales',index='product',aggfunc='sum')

          sales
product
Laptop   135000
Mobile    63000
Tablet    37000

### 12. Create pivot table using:aggfunc='mean'

In [40]:
df.pivot_table(values='sales',index='city',aggfunc='mean')

               sales
city
Delhi   28333.333333
Mumbai  30666.666667
Pune    29000.000000

In [41]:
df.pivot_table(values='sales',index='payment_method',aggfunc='mean')

                       sales
payment_method
Card            27333.333333
Cash            31500.000000
UPI             30000.000000

### 13. Create pivot table using: aggfunc='max'

In [42]:
df.pivot_table(values='sales',index='payment_method',aggfunc='max')

                sales
payment_method
Card            40000
Cash            45000
UPI             50000

### 14. Create pivot table using: aggfunc='min'

In [43]:
df.pivot_table(values='sales',index='payment_method',aggfunc='min')

                sales
payment_method
Card            20000
Cash            18000
UPI             15000

In [44]:
df.pivot_table(values='sales',index='city',aggfunc='min')

        sales
city
Delhi   15000
Mumbai  22000
Pune    18000

### 15. Create pivot table using:aggfunc='count'

In [46]:
df.pivot_table(values='sales',index='city',aggfunc='count')

        sales
city
Delhi       3
Mumbai      3
Pune        2

### 16. Create pivot table using: aggfunc=['sum','mean']

In [49]:
df.pivot_table(values='sales',index='city',aggfunc=['sum','mean'])

          sum          mean
        sales         sales
city
Delhi   85000  28333.333333
Mumbai  92000  30666.666667
Pune    58000  29000.000000

### 17. Create pivot table and replace all NaN with 0.

In [50]:
df.pivot_table(index='city', values = 'quantity',columns='product',aggfunc='count')

product  Laptop  Mobile  Tablet
city
Delhi       1.0     1.0     1.0
Mumbai      1.0     1.0     1.0
Pune        1.0     1.0     NaN

In [51]:
df.pivot_table(index='city', values = 'quantity',columns='product',aggfunc='count',fill_value=0)

product  Laptop  Mobile  Tablet
city
Delhi         1       1       1
Mumbai        1       1       1
Pune          1       1       0

In [52]:
df.pivot_table(values='sales',index='city',columns='product')

product   Laptop   Mobile   Tablet
city
Delhi    50000.0  20000.0  15000.0
Mumbai   45000.0  25000.0  22000.0
Pune     40000.0  18000.0      NaN

In [54]:
df.pivot_table(values='sales',index='city',columns='product',fill_value=0)

product   Laptop   Mobile   Tablet
city
Delhi    50000.0  20000.0  15000.0
Mumbai   45000.0  25000.0  22000.0
Pune     40000.0  18000.0      0.0

### 18. Create pivot table: 
#### city as index
#### product as columns
#### fill missing values with 100

In [55]:
df.pivot_table(values='sales',index='city',columns='product',fill_value=100)

product   Laptop   Mobile   Tablet
city
Delhi    50000.0  20000.0  15000.0
Mumbai   45000.0  25000.0  22000.0
Pune     40000.0  18000.0    100.0

### 19. Create pivot table with grand totals.

In [58]:
df.pivot_table(values='sales',index='city',margins=True)

               sales
city
Delhi   28333.333333
Mumbai  30666.666667
Pune    29000.000000
All     29375.000000

### 20. Create pivot table and rename total column to: 'Grand Total'

In [59]:
df.pivot_table(values='sales',index='city', columns='product', margins=True, margins_name='Grand Total')

product       Laptop   Mobile   Tablet   Grand Total
city
Delhi        50000.0  20000.0  15000.0  28333.333333
Mumbai       45000.0  25000.0  22000.0  30666.666667
Pune         40000.0  18000.0      NaN  29000.000000
Grand Total  45000.0  21000.0  18500.0  29375.000000

### 21. Create pivot table and rename totals to:'Final Report'

In [61]:
df.pivot_table(
     values='sales',
    index='city',
    columns='product',
    margins=True,
    margins_name='Final Report'
)

product        Laptop   Mobile   Tablet  Final Report
city
Delhi         50000.0  20000.0  15000.0  28333.333333
Mumbai        45000.0  25000.0  22000.0  30666.666667
Pune          40000.0  18000.0      NaN  29000.000000
Final Report  45000.0  21000.0  18500.0  29375.000000

### 22. Create pivot table using:
aggfunc=['sum','mean','max']

In [62]:
df.pivot_table( values='sales',
     index='city',
    aggfunc=['sum','mean','max']
)

          sum          mean    max
        sales         sales  sales
city
Delhi   85000  28333.333333  50000
Mumbai  92000  30666.666667  45000
Pune    58000  29000.000000  40000

### 23. Create pivot table with:
multi-index
multi-columns

In [63]:
df.pivot_table(
    values='sales',
    index=['city','product','payment_method'],
    columns=['product','payment_method'],
    aggfunc='sum'
)

product                       Laptop           Mobile            Tablet       \
payment_method                  Card Cash  UPI   Card Cash   UPI   Card  UPI
city   product payment_method
Delhi  Laptop  UPI               NaN  NaN  5.0    NaN  NaN   NaN    NaN  NaN
       Mobile  Card              NaN  NaN  NaN   10.0  NaN   NaN    NaN  NaN
       Tablet  UPI               NaN  NaN  NaN    NaN  NaN   NaN    NaN  6.0
Mumbai Laptop  Cash              NaN  4.0  NaN    NaN  NaN   NaN    NaN  NaN
       Mobile  UPI               NaN  NaN  NaN    NaN  NaN  12.0    NaN  NaN
       Tablet  Card              NaN  NaN  NaN    NaN  NaN   NaN    5.0  NaN
Pune   Laptop  Card              3.0  NaN  NaN    NaN  NaN   NaN    NaN  NaN
       Mobile  Cash              NaN  NaN  NaN    NaN  8.0   NaN    NaN  NaN

product                         Laptop                     Mobile           \
payment_method                    Card     Cash      UPI     Card     Cash
city   product payment_method
Delhi  Laptop  UPI                 NaN      NaN  50000.0      NaN      NaN
       Mobile  Card                NaN      NaN      NaN  20000.0      NaN
       Tablet  UPI                 NaN      NaN      NaN      NaN      NaN
Mumbai Laptop  Cash                NaN  45000.0      NaN      NaN      NaN
       Mobile  UPI                 NaN      NaN      NaN      NaN      NaN
       Tablet  Card                NaN      NaN      NaN      NaN      NaN
Pune   Laptop  Card            40000.0      NaN      NaN      NaN      NaN
       Mobile  Cash                NaN      NaN      NaN      NaN  18000.0

product                                  Tablet
payment_method                     UPI     Card      UPI
city   product payment_method
Delhi  Laptop  UPI                 NaN      NaN      NaN
       Mobile  Card                NaN      NaN      NaN
       Tablet  UPI                 NaN      NaN  15000.0
Mumbai Laptop  Cash                NaN      NaN      NaN
       Mobile  UPI             25000.0      NaN      NaN
       Tablet  Card                NaN  22000.0      NaN
Pune   Laptop  Card                NaN      NaN      NaN
       Mobile  Cash                NaN      NaN      NaN