# Data Cleaning Practice

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('messy_data3_ecommerce.csv')

In [4]:
df = data.copy(deep=True)

#

# Data Inspection

In [5]:
df.head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,Nitara Bumb,NaN,NaN,5.0,NaN,110.0,Delhi,UPI,2023-06-01,-1.0,shray@gmail
1,ORD10001,Kanav,Laptop,NaN,NaN,18817,NaN,Bangalore,UPI,2025-04-16,8.0,nehmat90@gmail.com
2,ORD10037,NaN,Tablet,NaN,0.0,NaN,110.0,Bangalore,NetBanking,NaN,NaN,NaN
3,NaN,NaN,Tablet,Electronics,3.0,unknown,110.0,Delhi,NaN,45-14-2024,NaN,NaN
4,ORD10073,Aayush Deep,Phone,Electronics,6.0,-5000,25.0,NaN,Cash,45-14-2024,NaN,wrong_email

In [6]:
 df.tail()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
995,ORD10047,NaN,Phone,NaN,0.0,NaN,NaN,Delhi,Card,2023-11-26,2.0,NaN
996,NaN,NaN,Monitor,Electronics,NaN,110487,4.0,Mumbai,NaN,NaN,2.0,wrong_email
997,ORD10997,NaN,Mouse,Electronics,NaN,NaN,-10.0,Bangalore,UPI,NaN,-1.0,wrong_email
998,ORD10998,Romil Venkatesh,Tablet,Electronics,-2.0,-5000,18.0,Pune,Card,NaN,-1.0,yakshit14@gmail.com
999,ORD10019,NaN,Keyboard,Electronics,10.0,104048,110.0,NaN,NaN,45-14-2024,8.0,NaN

In [7]:
df.dtypes

Order_ID             object
Customer_Name        object
Product              object
Category             object
Quantity            float64
Price                object
Discount_Percent    float64
City                 object
Payment_Method       object
Order_Date           object
Customer_Rating     float64
Email                object
dtype: object

In [8]:
df.isnull().sum()

Order_ID            331
Customer_Name       498
Product             161
Category            245
Quantity            242
Price               251
Discount_Percent    260
City                176
Payment_Method      349
Order_Date          323
Customer_Rating     239
Email               258
dtype: int64

In [9]:
df.isnull().mean().round(2)

Order_ID            0.33
Customer_Name       0.50
Product             0.16
Category            0.24
Quantity            0.24
Price               0.25
Discount_Percent    0.26
City                0.18
Payment_Method      0.35
Order_Date          0.32
Customer_Rating     0.24
Email               0.26
dtype: float64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Order_ID'].duplicated().sum()

np.int64(584)

In [12]:
df[['Order_ID','Product']].duplicated().sum()

np.int64(390)

In [13]:
df.shape

(1000, 12)

In [14]:
df.describe(include='object').T

               count unique          top freq
Order_ID         669    415     ORD10023    7
Customer_Name    502    414         Anay    5
Product          839      6       Laptop  144
Category         755      3  Electronics  262
Price            749    242      unknown  261
City             824      5        Delhi  193
Payment_Method   651      4   NetBanking  177
Order_Date       677    302   45-14-2024  339
Email            742    379  wrong_email  253

In [15]:
df.describe().T

                  count       mean        std   min   25%   50%    75%    max
Quantity          758.0   1.120053   3.507696  -2.0  -2.0   0.0    3.0   10.0
Discount_Percent  740.0  43.745946  51.460434 -10.0 -10.0  28.5  110.0  110.0
Customer_Rating   761.0   3.534823   3.760131  -1.0  -1.0   4.0    8.0    8.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          669 non-null    object
 1   Customer_Name     502 non-null    object
 2   Product           839 non-null    object
 3   Category          755 non-null    object
 4   Quantity          758 non-null    float64
 5   Price             749 non-null    object
 6   Discount_Percent  740 non-null    float64
 7   City              824 non-null    object
 8   Payment_Method    651 non-null    object
 9   Order_Date        677 non-null    object
 10  Customer_Rating   761 non-null    float64
 11  Email             742 non-null    object
dtypes: float64(3), object(9)
memory usage: 93.9+ KB

#

#

# Data Cleaning

In [17]:
df.dropna(subset='Order_ID').shape

(669, 12)

In [18]:
df['Order_ID'].fillna(method='ffill').dropna().shape

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14912\1625746472.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_ID'].fillna(method='ffill').dropna().shape

(1000,)

In [19]:
df = df.sort_values(by=['Order_Date', 'Customer_Name'])

##### Forward fill missing Order_ID

###### Because blank Order_ID rows belong to the previous order (line items).

In [20]:
df['Order_ID'] = df['Order_ID'].fillna(method='ffill')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14912\2779871130.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_ID'] = df['Order_ID'].fillna(method='ffill')

In [21]:
df.isna().sum()

Order_ID              1
Customer_Name       498
Product             161
Category            245
Quantity            242
Price               251
Discount_Percent    260
City                176
Payment_Method      349
Order_Date          323
Customer_Rating     239
Email               258
dtype: int64

In [22]:
df = df.dropna(subset='Order_ID')

In [23]:
df.isna().sum()

Order_ID              0
Customer_Name       497
Product             161
Category            245
Quantity            241
Price               251
Discount_Percent    259
City                176
Payment_Method      349
Order_Date          323
Customer_Rating     239
Email               258
dtype: int64

#

In [24]:
df['Customer_Name'] = df.groupby('Order_ID')['Customer_Name'].ffill()

In [25]:
df.isna().sum()

Order_ID              0
Customer_Name       319
Product             161
Category            245
Quantity            241
Price               251
Discount_Percent    259
City                176
Payment_Method      349
Order_Date          323
Customer_Rating     239
Email               258
dtype: int64

In [26]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.32
Product             0.16
Category            0.25
Quantity            0.24
Price               0.25
Discount_Percent    0.26
City                0.18
Payment_Method      0.35
Order_Date          0.32
Customer_Rating     0.24
Email               0.26
dtype: float64

In [27]:
df[df['Customer_Name'].isna()].sort_values('Order_ID')

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
276,ORD10000,NaN,Monitor,Electronics,0.0,NaN,0.0,Mumbai,Card,45-14-2024,8.0,NaN
463,ORD10000,NaN,Monitor,Office,5.0,-5000,110.0,Mumbai,NetBanking,45-14-2024,NaN,jkrish@khatri-bora.net
461,ORD10000,NaN,Tablet,NaN,0.0,unknown,NaN,Mumbai,Card,45-14-2024,8.0,rati@gmail
610,ORD10000,NaN,Monitor,Electronics,0.0,-5000,110.0,NaN,Cash,2026-04-13,8.0,kashvi@gmail
704,ORD10003,NaN,Laptop,Electronics,0.0,NaN,36.0,Delhi,Cash,2023-12-31,-1.0,ogarde@hotmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
957,ORD10957,NaN,Phone,Electronics,0.0,unknown,NaN,Bangalore,NetBanking,2023-09-08,3.0,NaN
964,ORD10964,NaN,Monitor,Office,0.0,119944,NaN,Hyderabad,NaN,NaN,8.0,iyerreyansh@hotmail.com
965,ORD10965,NaN,NaN,Electronics,NaN,-5000,110.0,Bangalore,NetBanking,2025-06-11,3.0,NaN
981,ORD10981,NaN,Phone,Office,1.0,unknown,13.0,NaN,UPI,2026-03-17,-1.0,madanbhamini@yahoo.com
997,ORD10997,NaN,Mouse,Electronics,NaN,NaN,-10.0,Bangalore,UPI,NaN,-1.0,wrong_email

In [28]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [29]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.25
Quantity            0.24
Price               0.25
Discount_Percent    0.26
City                0.18
Payment_Method      0.35
Order_Date          0.32
Customer_Rating     0.24
Email               0.26
dtype: float64

#

In [30]:
df['Product'].unique()

array([nan, 'Phone', 'Monitor', 'Laptop', 'Tablet', 'Mouse', 'Keyboard'],
      dtype=object)

In [31]:
df[df['Product'].isna()]

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,Nitara Bumb,NaN,NaN,5.0,NaN,110.0,Delhi,UPI,2023-06-01,-1.0,shray@gmail
641,ORD10104,Unknown,NaN,NaN,6.0,NaN,NaN,Delhi,NaN,2023-08-19,2.0,NaN
178,ORD10061,Unknown,NaN,Office,NaN,121317,-10.0,Pune,UPI,2023-08-25,8.0,rhea@gmail
181,ORD10181,Anvi,NaN,Accessories,-2.0,unknown,-10.0,Bangalore,NaN,2023-09-01,8.0,NaN
180,ORD10180,Zaina,NaN,Office,-2.0,unknown,110.0,Delhi,Card,2023-09-02,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
837,ORD10837,Unknown,NaN,Accessories,-2.0,124865,-10.0,Hyderabad,NetBanking,NaN,8.0,wrong_email
907,ORD10089,Kashvi,NaN,Office,-2.0,55624,NaN,Delhi,NaN,NaN,NaN,wrong_email
929,ORD10014,Emir Vaidya,NaN,Accessories,NaN,unknown,110.0,Hyderabad,UPI,NaN,-1.0,adira@gmail
941,ORD10014,Emir Vaidya,NaN,Office,0.0,NaN,40.0,Delhi,Cash,NaN,8.0,anikabora@sahni.info
943,ORD10014,Emir Vaidya,NaN,NaN,0.0,12762,NaN,Delhi,NetBanking,NaN,-1.0,indrajit@gmail

In [32]:
df.groupby('Order_ID')['Product'].unique()

Order_ID
ORD10000                   [Monitor, Tablet, nan]
ORD10001          [Keyboard, nan, Laptop, Tablet]
ORD10002                          [Keyboard, nan]
ORD10003    [Laptop, Keyboard, Mouse, Phone, nan]
ORD10004                          [Keyboard, nan]
                            ...
ORD10981                                  [Phone]
ORD10985            [nan, Phone, Mouse, Keyboard]
ORD10992                                 [Tablet]
ORD10997                                  [Mouse]
ORD10998                                 [Tablet]
Name: Product, Length: 415, dtype: object

In [33]:
df['Category'].unique()

array([nan, 'Office', 'Accessories', 'Electronics'], dtype=object)

In [34]:
product_category_map = (df.dropna(subset=['Product', 'Category']).drop_duplicates(subset=['Product']).set_index('Product')['Category'])

In [35]:
product_category_map

Product
Phone            Office
Tablet      Accessories
Monitor     Accessories
Keyboard    Electronics
Laptop      Accessories
Mouse            Office
Name: Category, dtype: object

In [36]:
product_category_map = {
    'Phone': 'Electronics',
    'Monitor': 'Electronics',
    'Laptop': 'Electronics',
    'Tablet': 'Electronics',
    'Mouse': 'Accessories',
    'Keyboard': 'Accessories'
}

In [37]:
product_category_map

{'Phone': 'Electronics',
 'Monitor': 'Electronics',
 'Laptop': 'Electronics',
 'Tablet': 'Electronics',
 'Mouse': 'Accessories',
 'Keyboard': 'Accessories'}

##### Office can remain for products like: Printer, Paper, Pen, Chair

### Fill Missing Categories

In [38]:
df['Category'] = df['Category'].fillna(
    df['Product'].map(product_category_map)
)

In [39]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.25
Discount_Percent    0.26
City                0.18
Payment_Method      0.35
Order_Date          0.32
Customer_Rating     0.24
Email               0.26
dtype: float64

In [40]:
df[df['Category'].isna()].head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,Nitara Bumb,NaN,NaN,5.0,NaN,110.0,Delhi,UPI,2023-06-01,-1.0,shray@gmail
641,ORD10104,Unknown,NaN,NaN,6.0,NaN,NaN,Delhi,NaN,2023-08-19,2.0,NaN
656,ORD10001,Aradhya,NaN,NaN,-2.0,unknown,NaN,Hyderabad,Card,2023-10-03,8.0,wrong_email
689,ORD10046,Unknown,NaN,NaN,NaN,-5000,-10.0,Hyderabad,Cash,2023-10-13,8.0,wrong_email
68,ORD10080,Unknown,NaN,NaN,-2.0,NaN,-10.0,Mumbai,Card,2024-01-01,8.0,kartik@gmail

#

In [41]:
df.dtypes

Order_ID             object
Customer_Name        object
Product              object
Category             object
Quantity            float64
Price                object
Discount_Percent    float64
City                 object
Payment_Method       object
Order_Date           object
Customer_Rating     float64
Email                object
dtype: object

In [42]:
df['Quantity'].unique()

array([ 5.,  0.,  8., -2.,  7., nan,  6., 10.,  1.,  3.,  9.,  4.,  2.])

In [43]:
df.loc[:,'Quantity'] = df['Quantity'].astype('Int64')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_14912\2219145642.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<IntegerArray>
[   5,    0,    8,    0,   -2,    7, <NA>,    6, <NA>,    0,
 ...
    4,    0,   -2,    0,    0, <NA>,    6,    0, <NA>, <NA>]
Length: 999, dtype: Int64' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:,'Quantity'] = df['Quantity'].astype('Int64')

In [44]:
df['Quantity'].dtypes

Int64Dtype()

In [45]:
df['Price'].head()

0          NaN
686    unknown
478      -5000
895      23774
784      32786
Name: Price, dtype: object

In [46]:
df['Price'].describe()

count         748
unique        242
top       unknown
freq          260
Name: Price, dtype: object

In [47]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [48]:
df['Price'].describe()

count       488.000000
mean      34044.696721
std       49336.455667
min       -5000.000000
25%       -5000.000000
50%       -5000.000000
75%       73407.250000
max      149117.000000
Name: Price, dtype: float64

In [49]:
df['Order_Date'].describe()

count            676
unique           301
top       45-14-2024
freq             339
Name: Order_Date, dtype: object

In [50]:
df['Order_Date'].str.contains(r'[a-zA-Z]').sum()

0

In [51]:
df['Order_Date'].str.contains(r'[-]').sum()

676

In [52]:
df['Order_Date'].str.contains(r'[/]').sum()

0

In [53]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

In [54]:
df['Order_Date'].describe()

count                              337
mean     2024-11-09 17:43:58.575667712
min                2023-06-01 00:00:00
25%                2024-02-22 00:00:00
50%                2024-11-01 00:00:00
75%                2025-08-18 00:00:00
max                2026-05-26 00:00:00
Name: Order_Date, dtype: object

In [55]:
df.shape

(999, 12)

In [56]:
df['Order_Date'] = (df.groupby(['Order_ID', 'City'])['Order_Date'].transform(lambda x: x.ffill().bfill()))

In [57]:
df['Order_Date'].describe()

count                              325
mean     2024-11-06 13:13:06.461538560
min                2023-06-01 00:00:00
25%                2024-02-10 00:00:00
50%                2024-10-22 00:00:00
75%                2025-08-10 00:00:00
max                2026-05-26 00:00:00
Name: Order_Date, dtype: object

In [58]:
df['Order_Date'].isna().sum()

np.int64(674)

In [59]:
df[df['Order_Date'].isna()][['Order_ID', 'City']].head(20)

     Order_ID City
686  ORD10686  NaN
478  ORD10478  NaN
312  ORD10024  NaN
249  ORD10024  NaN
154  ORD10093  NaN
357  ORD10357  NaN
778  ORD10778  NaN
233  ORD10233  NaN
458  ORD10119  NaN
231  ORD10059  NaN
55   ORD10055  NaN
316  ORD10019  NaN
822  ORD10303  NaN
831  ORD10011  NaN
240  ORD10240  NaN
808  ORD10808  NaN
538  ORD10100  NaN
886  ORD10008  NaN
931  ORD10931  NaN
383  ORD10003  NaN

In [60]:
filled_dates = (df.groupby('Order_ID')['Order_Date'].transform(lambda x: x.ffill().bfill()))

In [61]:
df['Order_Date'] = df['Order_Date'].fillna(filled_dates)

In [62]:
df['Order_Date'].isna().sum()

np.int64(488)

#

#

In [63]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.51
Discount_Percent    0.26
City                0.18
Payment_Method      0.35
Order_Date          0.49
Customer_Rating     0.24
Email               0.26
dtype: float64

In [64]:
df['Price'] = df.groupby(['Product','Quantity'])['Price'].transform(lambda p : p.fillna(p.median()))

In [65]:
df['Discount_Percent'] = df.groupby(['Product','Quantity'])['Discount_Percent'].transform(lambda p : p.fillna(p.median()))

In [66]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.38
Discount_Percent    0.36
City                0.18
Payment_Method      0.35
Order_Date          0.49
Customer_Rating     0.24
Email               0.26
dtype: float64

In [67]:
df['Discount_Percent'] = df.groupby(['Product'])['Discount_Percent'].transform(lambda p : p.fillna(p.median()))

In [68]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.38
Discount_Percent    0.16
City                0.18
Payment_Method      0.35
Order_Date          0.49
Customer_Rating     0.24
Email               0.26
dtype: float64

In [70]:
df['temp_price']= df['Price']

In [72]:
filled_prie = (df.groupby(['Product','Quantity'])['Price'].transform(lambda p : p.fillna(p.median())))

In [73]:
df['temp_price']= df['temp_price'].fillna(filled_prie)

In [74]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.38
Discount_Percent    0.16
City                0.18
Payment_Method      0.35
Order_Date          0.49
Customer_Rating     0.24
Email               0.26
temp_price          0.38
dtype: float64

In [75]:
filled_prie2 = (df.groupby(['Product'])['Price'].transform(lambda p : p.fillna(p.median())))

In [76]:
df['temp_price']= df['temp_price'].fillna(filled_prie2)

In [77]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.38
Discount_Percent    0.16
City                0.18
Payment_Method      0.35
Order_Date          0.49
Customer_Rating     0.24
Email               0.26
temp_price          0.16
dtype: float64

In [78]:
df[['Price','temp_price']].head(10)

       Price  temp_price
0        NaN         NaN
686   3240.0      3240.0
478  -5000.0     -5000.0
895  23774.0     23774.0
784  32786.0     32786.0
579  -5000.0     -5000.0
312      NaN     48162.5
249  87818.0     87818.0
701      NaN     -5000.0
264  -5000.0     -5000.0

In [79]:
df['Price'] = df['temp_price']

In [81]:
df.drop(columns='temp_price', inplace=True)

#

In [82]:
df['temp_Payment_Method'] = df['Payment_Method']

In [84]:
filled_pay_method = (df.groupby(['Order_ID'])['Payment_Method'].transform(lambda x : x.mode()[0] if not x.mode().empty else np.nan))

In [85]:
df[['Payment_Method','temp_Payment_Method']].isna().mean().round(2)

Payment_Method         0.35
temp_Payment_Method    0.35
dtype: float64

In [86]:
df['temp_Payment_Method'] = df['temp_Payment_Method'].fillna(filled_pay_method)

In [87]:
df[['Payment_Method','temp_Payment_Method']].isna().mean().round(2)

Payment_Method         0.35
temp_Payment_Method    0.11
dtype: float64

In [90]:
df[['Order_ID','Payment_Method','temp_Payment_Method']].head(20)

     Order_ID Payment_Method temp_Payment_Method
0    ORD10006            UPI                 UPI
686  ORD10686            NaN                 NaN
478  ORD10478            UPI                 UPI
895  ORD10895            NaN                 NaN
784  ORD10784            NaN                 NaN
579  ORD10024     NetBanking          NetBanking
312  ORD10024           Cash                Cash
249  ORD10024     NetBanking          NetBanking
701  ORD10093     NetBanking          NetBanking
264  ORD10093            UPI                 UPI
154  ORD10093            NaN                 UPI
873  ORD10873            NaN                 NaN
875  ORD10875            UPI                 UPI
731  ORD10875            UPI                 UPI
867  ORD10875            NaN                 UPI
397  ORD10875            NaN                 UPI
476  ORD10875     NetBanking          NetBanking
693  ORD10693            NaN                Card
552  ORD10693           Card                Card
314  ORD10314           Cash                Cash

In [91]:
df['Payment_Method'] = df['temp_Payment_Method']

In [92]:
df.drop(columns='temp_Payment_Method',inplace=True)

In [93]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

In [94]:
df['Customer_Rating'].unique()

array([-1.,  1.,  4.,  8.,  3.,  2.,  5.])

In [96]:
df.loc[(df['Customer_Rating']<0)| (df['Customer_Rating']> 5),'Customer_Rating'] = np.nan

In [97]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

In [98]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.16
Discount_Percent    0.16
City                0.18
Payment_Method      0.11
Order_Date          0.49
Customer_Rating     0.00
Email               0.26
dtype: float64

In [106]:
filled_order_date= (df.groupby(['Order_ID'])['Order_Date'].transform(lambda a : a.ffill().bfill()))

In [107]:
df['temp_Order_Date'] = df['Order_Date']

In [108]:
df['temp_Order_Date'] = df['temp_Order_Date'].fillna(filled_order_date)

In [109]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.16
Discount_Percent    0.16
City                0.18
Payment_Method      0.11
Order_Date          0.49
Customer_Rating     0.00
Email               0.26
temp_Order_Date     0.49
dtype: float64

In [111]:
df[df['Order_Date'].notna()].groupby('Order_ID').size()

Order_ID
ORD10001    6
ORD10003    6
ORD10005    2
ORD10006    4
ORD10007    4
           ..
ORD10944    1
ORD10957    1
ORD10959    1
ORD10963    1
ORD10965    1
Length: 153, dtype: int64

In [112]:
df.drop(columns='temp_Order_Date',inplace=True)

In [113]:
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

In [114]:
df['City'] = df['City'].fillna('Unknown')

In [115]:
mask = df['Email'].str.match(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',na=False)

In [116]:
df.loc[~mask, 'Email'] = np.nan

In [118]:
df['Email'] = df['Email'].fillna('Unknown')

In [119]:
df.isna().mean().round(2)

Order_ID            0.00
Customer_Name       0.00
Product             0.16
Category            0.04
Quantity            0.24
Price               0.16
Discount_Percent    0.16
City                0.00
Payment_Method      0.00
Order_Date          0.49
Customer_Rating     0.00
Email               0.00
dtype: float64

In [120]:
df['Discount_Percent'] = df['Discount_Percent'].fillna(0)

#

#

In [121]:
df.head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,Nitara Bumb,NaN,NaN,5,NaN,0.0,Delhi,UPI,2023-06-01,4.0,Unknown
686,ORD10686,Seher Soman,Phone,Office,0,3240.0,13.0,Unknown,Unknown,NaT,1.0,abahl@dutt-upadhyay.com
478,ORD10478,Unknown,Monitor,Electronics,8,-5000.0,7.0,Unknown,UPI,NaT,4.0,boaseanvi@thaman.info
895,ORD10895,Unknown,Laptop,Electronics,0,23774.0,110.0,Bangalore,Unknown,2023-06-15,4.0,Unknown
784,ORD10784,Unknown,Tablet,Accessories,-2,32786.0,24.0,Pune,Unknown,2023-06-16,4.0,Unknown

In [124]:
df.to_csv('data_cleaned4.csv')