# Advanced Indexing

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [50000, 60000, 45000, 47000, 55000, 52000]
})

In [3]:
df1

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   45000
3         HR        D   47000
4      Sales        E   55000
5      Sales        F   52000

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  6 non-null      object
 1   Employee    6 non-null      object
 2   Salary      6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

#

# 1. MultiIndex

### 1. Create a MultiIndex using Department and Employee columns.

In [5]:
df1.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
df1 = df1.set_index(['Department', 'Employee'])

In [7]:
df1

                     Salary
Department Employee
IT         A          50000
           B          60000
HR         C          45000
           D          47000
Sales      E          55000
           F          52000

### 2. Display all employees from the IT department.

In [9]:
df1.loc['IT']

          Salary
Employee
A          50000
B          60000

### 3. Display salary details of employee C from HR department.

In [10]:
df1.loc[('HR', 'C')]

Salary    45000
Name: (HR, C), dtype: int64

### 4. Find all records belonging to the Sales department.

In [11]:
df1.loc['Sales']

          Salary
Employee
E          55000
F          52000

### 5. Reset the MultiIndex back to normal columns.

In [12]:
df1.reset_index()

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   45000
3         HR        D   47000
4      Sales        E   55000
5      Sales        F   52000

### 6. Sort the MultiIndex DataFrame.

In [13]:
df1.sort_index()

                     Salary
Department Employee
HR         C          45000
           D          47000
IT         A          50000
           B          60000
Sales      E          55000
           F          52000

### 7. Add a new employee G to the IT department with salary 65000.

In [14]:
df1.loc[('IT', 'G')] = 65000

In [15]:
df1

                     Salary        G
Department Employee
IT         A          50000  65000.0
           B          60000  65000.0
HR         C          45000      NaN
           D          47000      NaN
Sales      E          55000      NaN
           F          52000      NaN

### 8. Display employees whose salary is greater than 50000.

In [17]:
df1['Salary']>50000

Department  Employee
IT          A           False
            B            True
HR          C           False
            D           False
Sales       E            True
            F            True
Name: Salary, dtype: bool

In [18]:
df1[df1['Salary']>50000]

                     Salary        G
Department Employee
IT         B          60000  65000.0
Sales      E          55000      NaN
           F          52000      NaN

### 9. Display only employee names from the HR department.

In [19]:
df1

                     Salary        G
Department Employee
IT         A          50000  65000.0
           B          60000  65000.0
HR         C          45000      NaN
           D          47000      NaN
Sales      E          55000      NaN
           F          52000      NaN

In [22]:
df1.columns

Index(['Salary', 'G'], dtype='object')

In [23]:
df1.index

MultiIndex([(   'IT', 'A'),
            (   'IT', 'B'),
            (   'HR', 'C'),
            (   'HR', 'D'),
            ('Sales', 'E'),
            ('Sales', 'F')],
           names=['Department', 'Employee'])

In [29]:
df1.reset_index()['Department']

0       IT
1       IT
2       HR
3       HR
4    Sales
5    Sales
Name: Department, dtype: object

In [33]:
df1.loc['HR']

          Salary   G
Employee
C          45000 NaN
D          47000 NaN

In [35]:
print(df1.loc['HR'].index)

Index(['C', 'D'], dtype='object', name='Employee')

In [36]:
df1.loc['HR'].index.to_list()

['C', 'D']

### 10. Count total employees in each department.

In [38]:
df1.groupby(level=0).size()

Department
HR       2
IT       2
Sales    2
dtype: int64

In [39]:
df1.groupby(level=1).size()

Employee
A    1
B    1
C    1
D    1
E    1
F    1
dtype: int64

# 2. Hierarchical Indexing

In [41]:
df2= pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South'],
    'Year': [2024, 2025, 2024, 2025],
    'Sales': [1000, 1200, 900, 1100]
})

In [42]:
df2

  Region  Year  Sales
0  North  2024   1000
1  North  2025   1200
2  South  2024    900
3  South  2025   1100

In [43]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Region  4 non-null      object
 1   Year    4 non-null      int64
 2   Sales   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

#

### 1. Create hierarchical indexing using Region and Year columns.

In [44]:
df2 = df2.set_index(['Region', 'Year'])

In [45]:
df2

             Sales
Region Year
North  2024   1000
       2025   1200
South  2024    900
       2025   1100

### 2. Display all sales records from North region.

In [46]:
df2.loc['North']

      Sales
Year
2024   1000
2025   1200

### 3. Display sales data for South region in 2025.

In [49]:
df2.loc['South']

      Sales
Year
2024    900
2025   1100

In [50]:
df2.loc['South',2025]

Sales    1100
Name: (South, 2025), dtype: int64

In [51]:
df2.loc[('South', 2025)]

Sales    1100
Name: (South, 2025), dtype: int64

### 4. Sort the hierarchical index DataFrame.

In [52]:
df2.sort_index()

             Sales
Region Year
North  2024   1000
       2025   1200
South  2024    900
       2025   1100

### 5. Convert hierarchical index into normal DataFrame.

In [53]:
df2.reset_index()

  Region  Year  Sales
0  North  2024   1000
1  North  2025   1200
2  South  2024    900
3  South  2025   1100

### 6. Swap Region and Year index levels.

In [56]:
df2.swaplevel()

             Sales
Year Region
2024 North    1000
2025 North    1200
2024 South     900
2025 South    1100

### 7. Calculate total sales by region.

In [60]:
df2

             Sales
Region Year
North  2024   1000
       2025   1200
South  2024    900
       2025   1100

In [61]:
df2.groupby(level=0).sum()

        Sales
Region
North    2200
South    2000

### 8. Calculate total sales by year.

In [62]:
df2.groupby(level=1).sum()

      Sales
Year
2024   1900
2025   2300

### 9. Find the maximum sales value from the dataset.

In [63]:
df2['Sales'].max()

1200

### 10. Slice and display only South region records.

In [64]:
df2.loc['South':'South']

             Sales
Region Year
South  2024    900
       2025   1100

# 3. Index Slicing

In [65]:
df3 = pd.DataFrame({
    'Sales': [100, 120, 140, 160, 180]
}, index=['A', 'B', 'C', 'D', 'E'])

In [66]:
df3

   Sales
A    100
B    120
C    140
D    160
E    180

In [67]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sales   5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes

### 1. Slice rows from index A to C.

In [69]:
df3.loc['A':'C']

   Sales
A    100
B    120
C    140

### 2. Slice rows using iloc from position 1 to 3.

In [70]:
df3.iloc[1:4]

   Sales
B    120
C    140
D    160

### 3. Display first three rows from the DataFrame.

In [71]:
df3[:3]

   Sales
A    100
B    120
C    140

### 4. Display last two rows from the DataFrame.

In [72]:
df3[-2:]

   Sales
D    160
E    180

### 5. Slice rows from A to D and display Sales column.

In [73]:
df3

   Sales
A    100
B    120
C    140
D    160
E    180

In [74]:
df3.loc['A':'D', ['Sales']]

   Sales
A    100
B    120
C    140
D    160

### 6. Reverse all rows using slicing.

In [75]:
df3.iloc[::-1]

   Sales
E    180
D    160
C    140
B    120
A    100

### 7. Display alternate rows from the DataFrame.

In [77]:
df3.iloc[::2]

   Sales
A    100
C    140
E    180

### 8. Display rows where Sales value is greater than 140.

In [79]:
df3[df3['Sales'] > 140]

   Sales
D    160
E    180

### 9. Display only row with index C.

In [80]:
df3.loc['C']

Sales    140
Name: C, dtype: int64

### 10. Slice first two rows using iloc.

In [81]:
df3.iloc[0:2]

   Sales
A    100
B    120

# 4. Index Alignment

In [82]:
s1 = pd.Series([100, 200, 300], index=['A', 'B', 'C'])

In [84]:
s1

A    100
B    200
C    300
dtype: int64

In [83]:
s2 = pd.Series([10, 20, 30], index=['B', 'C', 'D'])

In [85]:
s2

B    10
C    20
D    30
dtype: int64

### 1. Add two Series objects using index alignment.

In [86]:
s1 + s2

A      NaN
B    210.0
C    320.0
D      NaN
dtype: float64

### 2. Identify positions containing NaN after alignment.

In [88]:
(s1 + s2).isna()

A     True
B    False
C    False
D     True
dtype: bool

### 3. Add two Series and replace missing values with 0.

In [89]:
s1.add(s2, fill_value=0)

A    100.0
B    210.0
C    320.0
D     30.0
dtype: float64

In [90]:
(s1+s2).fillna(0)

A      0.0
B    210.0
C    320.0
D      0.0
dtype: float64

### 4. Subtract second Series from first Series.

In [91]:
s1 - s2

A      NaN
B    190.0
C    280.0
D      NaN
dtype: float64

### 5. Multiply two aligned Series.

In [92]:
s1 * s2

A       NaN
B    2000.0
C    6000.0
D       NaN
dtype: float64

### 6. Divide first Series by second Series.

In [93]:
(s1 / s2)

A     NaN
B    20.0
C    15.0
D     NaN
dtype: float64

### 7. Add two DataFrames with different indexes.

In [94]:
df1 = pd.DataFrame({'A': [1, 2]}, index=['X', 'Y'])

In [95]:
df2 = pd.DataFrame({'A': [3, 4]}, index=['Y', 'Z'])

In [96]:
df1+df2

     A
X  NaN
Y  5.0
Z  NaN

### 8. Add two DataFrames and fill missing aligned values with 0.

In [97]:
df1.add(df2, fill_value=0)

     A
X  1.0
Y  5.0
Z  4.0

In [99]:
(df1+df2).fillna(0)

     A
X  0.0
Y  5.0
Z  0.0

### 9. Check whether indexes of both Series are equal.

In [102]:
s1.index.equals(s2.index)

False

### 10. Reorder Series index using reindexing.

In [103]:
s1.reindex(['C', 'B', 'A'])

C    300
B    200
A    100
dtype: int64

# 5. Reindexing

In [104]:
df3 = pd.DataFrame({
    'Sales': [100, 200, 300]
}, index=['A', 'B', 'C'])

In [105]:
df3

   Sales
A    100
B    200
C    300

### 1. Reindex the DataFrame by adding a new row D.

In [106]:
df3.reindex(['A', 'B', 'C', 'D'])

   Sales
A  100.0
B  200.0
C  300.0
D    NaN

### 2. Reindex the DataFrame and fill missing values with 0.

In [107]:
df3.reindex(['A', 'B', 'C', 'D'], fill_value=0)

   Sales
A    100
B    200
C    300
D      0

### 3. Change the order of indexes to C, A, B.

In [108]:
df3.reindex(['C', 'A', 'B'])

   Sales
C    300
A    100
B    200

### 4. Reindex columns by adding a Profit column.

In [114]:
df3.reindex(columns=['Sales', 'Profit'])

   Sales  Profit
A    100     NaN
B    200     NaN
C    300     NaN

### 5. Apply forward fill while reindexing.

In [119]:
df3.reindex(['A', 'B', 'C', 'D'], method='ffill')

   Sales
A    100
B    200
C    300
D    300

### 6. Apply backward fill while reindexing.

In [120]:
df3.reindex(['A', 'B', 'C', 'D'], method='bfill')

   Sales
A  100.0
B  200.0
C  300.0
D    NaN

### 7. Add multiple new indexes D and E using reindex.

In [121]:
df3.reindex(['A', 'B', 'C', 'D', 'E'])

   Sales
A  100.0
B  200.0
C  300.0
D    NaN
E    NaN

### 8. Detect rows containing missing values after reindexing.

In [124]:
new_df = df3.reindex(['A', 'B', 'C', 'D'])

In [125]:
new_df[new_df['Sales'].isna()]

   Sales
D    NaN

### 9. Replace old index labels with new labels X, Y, Z.

In [128]:
df3.set_axis(['X', 'Y', 'Z'])

   Sales
X    100
Y    200
Z    300

### 10. Reindex DataFrame and replace missing values using fillna().

In [130]:
df3.reindex(['A', 'B', 'C', 'D']).fillna(999)

   Sales
A  100.0
B  200.0
C  300.0
D  999.0