# Handling Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:

 np.random.seed(42)
 data = {
 'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', np.nan, 'Frank', 'Grace'],
 'Age': [25, np.nan, 35, 28, np.nan, 45, 32, np.nan],
 'Salary': [50000, 60000, np.nan, 55000, np.nan, 70000, np.nan, 48000],
 'Department': ['HR', 'IT', 'Finance', np.nan, 'IT', 'HR', 'Finance', 'IT'],
 'Marks': [85, 90, np.nan, 78, 82, np.nan, 88, 92]
 }
 df = pd.DataFrame(data)
 df2 = df.copy(deep=True)

In [3]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

## A. Checking for Missing Data (1-15)

#### 1: Check if the DataFrame has any missing values

In [5]:
df.isna().any().any()

np.True_

#### 2: Check missing values in a single column Age

In [6]:
df['Age'].isna()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7     True
Name: Age, dtype: bool

In [8]:
df['Age'].isnull().any()

np.True_

In [9]:
df['Age'].isnull().sum()

np.int64(3)

#### 3: Get a boolean DataFrame showing which cells have NaN values

In [11]:
df[df.isnull()] # wrong

  Name  Age  Salary Department  Marks
0  NaN  NaN     NaN        NaN    NaN
1  NaN  NaN     NaN        NaN    NaN
2  NaN  NaN     NaN        NaN    NaN
3  NaN  NaN     NaN        NaN    NaN
4  NaN  NaN     NaN        NaN    NaN
5  NaN  NaN     NaN        NaN    NaN
6  NaN  NaN     NaN        NaN    NaN
7  NaN  NaN     NaN        NaN    NaN

In [12]:
df.isnull() # correct

    Name    Age  Salary  Department  Marks
0  False  False   False       False  False
1  False   True   False       False  False
2  False  False    True       False   True
3  False  False   False        True  False
4  False   True    True       False  False
5   True  False   False       False   True
6  False  False    True       False  False
7  False   True   False       False  False

#### 4: Count missing values for each column

In [13]:
df.isnull().sum()

Name          1
Age           3
Salary        3
Department    1
Marks         2
dtype: int64

#### 5. Count total missing values in the entire DataFrame

In [18]:
total_miss = df.isnull().sum().sum()
print("Total missing values in df : ",total_miss)

Total missing values in df :  10

#### 6: Check if any column contains NaN values

In [19]:
df.isna().any()

Name          True
Age           True
Salary        True
Department    True
Marks         True
dtype: bool

#### 7: Check if all values in a column are missing

In [20]:
print("Is all values in a columns are missing : ")
df.isnull().all()

Is all values in a columns are missing :

Name          False
Age           False
Salary        False
Department    False
Marks         False
dtype: bool

#### 8: Find columns that have missing values

In [21]:
df.isnull().any()  # not good

Name          True
Age           True
Salary        True
Department    True
Marks         True
dtype: bool

In [23]:
 columns_with_missing = df.columns[df.isnull().any()].tolist()  # best way
 print("Columns that have missing values:")
 print(columns_with_missing)

Columns that have missing values:
['Name', 'Age', 'Salary', 'Department', 'Marks']

#### 9: Find rows that contain at least one missing valu

In [24]:
missing_vlues = df.index[df.isna().any(axis=1)]
print("Rows that have missing values : \n",missing_vlues.tolist())

Rows that have missing values :
 [1, 2, 3, 4, 5, 6, 7]

In [25]:
 rows_with_missing = df[df.isnull().any(axis=1)]
 print("Rows containing at least one missing value:")
 print(rows_with_missing)

Rows containing at least one missing value:
      Name   Age   Salary Department  Marks
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 10: Get indexes of rows that contain missing values

In [26]:
 df.index[df.isna().any(axis=1)].tolist()

[1, 2, 3, 4, 5, 6, 7]

#### 11: Check if a specific cell (row 3, col 'Salary') is NaN

In [27]:
df.loc[2,'Salary'].isna()

AttributeError: 'numpy.float64' object has no attribute 'isna'

In [30]:
 # Check if specific cell is NaN
 is_nan = pd.isna(df.loc[3, 'Salary'])
 print(f"Is cell at row 3, column 'Salary' NaN? {is_nan}")
 print(f"Value at row 3, column 'Salary': {df.loc[3, 'Salary']}")

Is cell at row 3, column 'Salary' NaN? False
Value at row 3, column 'Salary': 55000.0

#### 12: Count missing values in a DataFrame and store them in a Series

In [31]:
miss_series = df.isna().sum()
print("Missing vlaues ")
print(miss_series)
print(type(miss_series))

Missing vlaues
Name          1
Age           3
Salary        3
Department    1
Marks         2
dtype: int64
<class 'pandas.core.series.Series'>

#### 13: Check percentage of missing values per column

In [32]:
df.isnull().mean()*100

Name          12.5
Age           37.5
Salary        37.5
Department    12.5
Marks         25.0
dtype: float64

#### 14: Check missing values only in numeric columns

In [33]:
num_col = df.select_dtypes(include=[np.number]).columns
result = df[num_col].isnull().sum()
print(result)

Age       3
Salary    3
Marks     2
dtype: int64

#### 15: Check missing values only in object/string columns

In [35]:
df.select_dtypes(include=['object']).isnull().sum()

Name          1
Department    1
dtype: int64

## B. Dropping Missing Data (16-35)

#### 16: Drop rows that contain any NaN values

In [36]:
print("DataFrame after dropping rows with any NaN:")
result=df.dropna()
print(result)

DataFrame after dropping rows with any NaN:
    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0

#### 17: Drop rows that contain all NaN values

In [38]:
print("DataFrame after dropping rows with all NaN:")
result = df.dropna(how='all')
print(result)

DataFrame after dropping rows with all NaN:
      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [40]:
clen=len(df.columns)
rlen = len(df.index)
print(rlen)
df.loc[rlen] =[np.nan]*clen
df

9

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0
8      NaN   NaN      NaN        NaN    NaN
9      NaN   NaN      NaN        NaN    NaN

In [41]:
print("DataFrame after dropping rows with all NaN:")
result = df.dropna(how='all')
print(result)

DataFrame after dropping rows with all NaN:
      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 18: Drop columns that contain any NaN values

In [43]:
 result = df.dropna(axis=1)
 print(result)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### 19: Drop columns that contain all NaN values

In [45]:
df['Na_col']= np.nan
df

      Name   Age   Salary Department  Marks  Na_col
0    Alice  25.0  50000.0         HR   85.0     NaN
1      Bob   NaN  60000.0         IT   90.0     NaN
2  Charlie  35.0      NaN    Finance    NaN     NaN
3    Diana  28.0  55000.0        NaN   78.0     NaN
4      Eve   NaN      NaN         IT   82.0     NaN
5      NaN  45.0  70000.0         HR    NaN     NaN
6    Frank  32.0      NaN    Finance   88.0     NaN
7    Grace   NaN  48000.0         IT   92.0     NaN
8      NaN   NaN      NaN        NaN    NaN     NaN
9      NaN   NaN      NaN        NaN    NaN     NaN

In [46]:
df.dropna(axis=1, how='all')

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0
8      NaN   NaN      NaN        NaN    NaN
9      NaN   NaN      NaN        NaN    NaN

#### 20: Drop rows with NaN in column Age

In [47]:
df.dropna(subset=['Age'])

      Name   Age   Salary Department  Marks  Na_col
0    Alice  25.0  50000.0         HR   85.0     NaN
2  Charlie  35.0      NaN    Finance    NaN     NaN
3    Diana  28.0  55000.0        NaN   78.0     NaN
5      NaN  45.0  70000.0         HR    NaN     NaN
6    Frank  32.0      NaN    Finance   88.0     NaN

In [48]:
df.dropna(axis=1, how='all', inplace=True)

In [50]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0
8      NaN   NaN      NaN        NaN    NaN
9      NaN   NaN      NaN        NaN    NaN

#### 21: Drop rows with NaN in multiple columns ['Age', 'Salary']

In [52]:
df.dropna(subset=['Age',"Salary"])

    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0
3  Diana  28.0  55000.0        NaN   78.0
5    NaN  45.0  70000.0         HR    NaN

#### 22: Drop rows with NaN only if all columns are NaN

In [53]:
df.dropna(subset=df.columns, how='all')

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [54]:
df.dropna(how='all')

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 23: Drop rows with NaN if a specific subset of columns has NaN

In [55]:
df.dropna(subset=['Name',"Age","Salary"])

    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0
3  Diana  28.0  55000.0        NaN   78.0

#### 24: Drop rows where more than 2 columns have NaN values

In [56]:
df.dropna(thresh=len(df.columns)-2)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [57]:
df.dropna(thresh=3)  # not beter if column have 10 then only 3 columns will check non null others

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 25: Drop rows where NaN percentage is more than 50%

In [61]:
df.dropna(thresh = len(df.columns)*0.5)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 26: Drop rows if NaN is in the first column

In [62]:
df.dropna(subset=df.columns[0])

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 27: Drop columns where more than 50% values are NaN

In [63]:

df.dropna(axis=1, thresh = (len(df)*0.5)+1)

      Name Department  Marks
0    Alice         HR   85.0
1      Bob         IT   90.0
2  Charlie    Finance    NaN
3    Diana        NaN   78.0
4      Eve         IT   82.0
5      NaN         HR    NaN
6    Frank    Finance   88.0
7    Grace         IT   92.0
8      NaN        NaN    NaN
9      NaN        NaN    NaN

In [64]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0
8      NaN   NaN      NaN        NaN    NaN
9      NaN   NaN      NaN        NaN    NaN

In [65]:
df.dropna(how='all',inplace=True)

In [66]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [67]:
df.dropna(axis=1, thresh = (len(df)*0.5))

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [79]:
 threshold = len(df) * 0.5  # 50% of rows
 cols_to_keep = df.columns[df.isnull().sum() <= threshold]
 df_cols_filtered = df[cols_to_keep]
 print(f"Columns kept (≤50% NaN): {cols_to_keep.tolist()}")
 print("DataFrame after dropping columns with >50% NaN:")
 print(df_cols_filtered)

Columns kept (≤50% NaN): ['Name', 'Age', 'Salary', 'Department', 'Marks']
DataFrame after dropping columns with >50% NaN:
      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 28: Drop rows where NaN occurs in numeric columns only

In [81]:
num_col = df.select_dtypes(include=[np.number])
num_col.dropna()

    Age   Salary  Marks
0  25.0  50000.0   85.0
3  28.0  55000.0   78.0

In [82]:
df.dropna(subset=num_col.columns)

    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0
3  Diana  28.0  55000.0        NaN   78.0

#### 29: Drop rows where NaN occurs in object columns only

In [85]:
df.select_dtypes(include=['object']).dropna()

      Name Department
0    Alice         HR
1      Bob         IT
2  Charlie    Finance
4      Eve         IT
6    Frank    Finance
7    Grace         IT

In [86]:
ob_col = df.select_dtypes(include=['object']).columns
df.dropna(subset=ob_col)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
4      Eve   NaN      NaN         IT   82.0
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 30: Drop rows with NaN and reset the index

In [87]:
df.dropna(ignore_index=True)

    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0

In [89]:
df.dropna(subset=['Age'],ignore_index=True)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1  Charlie  35.0      NaN    Finance    NaN
2    Diana  28.0  55000.0        NaN   78.0
3      NaN  45.0  70000.0         HR    NaN
4    Frank  32.0      NaN    Finance   88.0

#### 31: Drop rows with NaN but keep a copy of the original DataFrame

In [91]:
newdf = df.copy(deep=True)
newdf.dropna(inplace=True)
print("Oringinal : missing values count ")
print(df.isna().sum())
print("_"*20)
print("Copy after removeing Nans : mising values count")
print(newdf.isnull().sum())

Oringinal : missing values count
Name          1
Age           3
Salary        3
Department    1
Marks         2
dtype: int64
____________________
Copy after removeing Nans : mising values count
Name          0
Age           0
Salary        0
Department    0
Marks         0
dtype: int64

#### 32: Drop rows based on NaN in a condition (Age < 30 and NaN in Salary)

In [92]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

In [94]:
df[(df['Age']>=30) & ~(df['Salary'].isnull())]

  Name   Age   Salary Department  Marks
5  NaN  45.0  70000.0         HR    NaN

#### 33.  Drop rows where NaN is in any of the first 3 columns

In [96]:
df.dropna(subset= df.columns[:3])

    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0
3  Diana  28.0  55000.0        NaN   78.0

In [97]:
 first_three_cols = df.columns[:3]
 df_no_first_three_nan = df.dropna(subset=first_three_cols)
 print(f"First 3 columns: {first_three_cols.tolist()}")
 print("DataFrame after dropping rows with NaN in first 3 columns:")
 print(df_no_first_three_nan)

First 3 columns: ['Name', 'Age', 'Salary']
DataFrame after dropping rows with NaN in first 3 columns:
    Name   Age   Salary Department  Marks
0  Alice  25.0  50000.0         HR   85.0
3  Diana  28.0  55000.0        NaN   78.0

#### 34: Drop rows where all numeric columns are NaN

In [99]:
num_col = df.select_dtypes(include=[np.number]).columns
df.dropna(subset=num_col, how = 'all')

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 35: Drop columns where all numeric columns are NaN

In [100]:
num_col = df.select_dtypes(include=[np.number]).columns
drop_col =[]
for col in num_col:
    if df[col].isna().all() :
        drop_col.append(col)
df.drop(columns=drop_col)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

## C. Filling Missing Data (36-65)

#### 36: Fill all NaN values with 0

In [103]:
df.fillna(0)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   0.0  60000.0         IT   90.0
2  Charlie  35.0      0.0    Finance    0.0
3    Diana  28.0  55000.0          0   78.0
4      Eve   0.0      0.0         IT   82.0
5        0  45.0  70000.0         HR    0.0
6    Frank  32.0      0.0    Finance   88.0
7    Grace   0.0  48000.0         IT   92.0

#### 37: Fill all NaN values with 'Unknown'

In [104]:
df.fillna('Unknown')

      Name      Age   Salary Department    Marks
0    Alice     25.0  50000.0         HR     85.0
1      Bob  Unknown  60000.0         IT     90.0
2  Charlie     35.0  Unknown    Finance  Unknown
3    Diana     28.0  55000.0    Unknown     78.0
4      Eve  Unknown  Unknown         IT     82.0
5  Unknown     45.0  70000.0         HR  Unknown
6    Frank     32.0  Unknown    Finance     88.0
7    Grace  Unknown  48000.0         IT     92.0

#### 38: Fill NaN in Age with mean of the column

In [110]:
df2 = df.copy()
# df2["Age"].fillna(df2["Age"].mean(), inplace=True) # work but warning provided
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())

In [111]:
df2

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

#### 39: Fill NaN in Salary with median of the column

In [112]:
df2['Salary']=df['Salary'].fillna(df['Salary'].median())
df2

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0  55000.0         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0  55000.0    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

#### 40: Fill NaN in Marks with mode of the column

In [114]:
df2['Marks']=df['Marks'].fillna(df['Marks'].mode()[0])
df2

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance   78.0
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0  55000.0         IT   82.0
5      NaN  45.0  70000.0         HR   78.0
6    Frank  32.0  55000.0    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

In [115]:
df

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   NaN  60000.0         IT   90.0
2  Charlie  35.0      NaN    Finance    NaN
3    Diana  28.0  55000.0        NaN   78.0
4      Eve   NaN      NaN         IT   82.0
5      NaN  45.0  70000.0         HR    NaN
6    Frank  32.0      NaN    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 41: Fill NaN in a column with a fixed value 100

In [118]:
df.fillna(100)

      Name    Age   Salary Department  Marks
0    Alice   25.0  50000.0         HR   85.0
1      Bob  100.0  60000.0         IT   90.0
2  Charlie   35.0    100.0    Finance  100.0
3    Diana   28.0  55000.0        100   78.0
4      Eve  100.0    100.0         IT   82.0
5      100   45.0  70000.0         HR  100.0
6    Frank   32.0    100.0    Finance   88.0
7    Grace  100.0  48000.0         IT   92.0

#### 42: Fill NaN in multiple columns with different values using a dictionary

In [119]:
fill_values = {
  'Name' : 'Unkown',
 'Age': df['Age'].mean(),
 'Salary': df['Salary'].median(),
 'Department': 'Unknown',
 'Marks': df['Marks'].mean()
 }
df.fillna(fill_values)

      Name   Age   Salary Department      Marks
0    Alice  25.0  50000.0         HR  85.000000
1      Bob  33.0  60000.0         IT  90.000000
2  Charlie  35.0  55000.0    Finance  85.833333
3    Diana  28.0  55000.0    Unknown  78.000000
4      Eve  33.0  55000.0         IT  82.000000
5   Unkown  45.0  70000.0         HR  85.833333
6    Frank  32.0  55000.0    Finance  88.000000
7    Grace  33.0  48000.0         IT  92.000000

#### 43: Fill NaN in Age with average of min and max values

In [120]:
age = (df2['Age'].min() + df2['Age'].max()) /2
print(age)
df2['Age']=df2["Age"].fillna(age)
df2

35.0

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance   78.0
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0  55000.0         IT   82.0
5      NaN  45.0  70000.0         HR   78.0
6    Frank  32.0  55000.0    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

#### 44: Fill NaN in Salary with value from another columnm

In [123]:
df2["Salary"] = df2["Salary"].fillna(df2["Age"]*50)
df2

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance   78.0
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0  55000.0         IT   82.0
5      NaN  45.0  70000.0         HR   78.0
6    Frank  32.0  55000.0    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

#### 45#: Fill NaN in Date with current date

#### 46: Fill NaN with previous value

In [122]:
df.fillna(method='ffill')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_3552\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  25.0  60000.0         IT   90.0
2  Charlie  35.0  60000.0    Finance   90.0
3    Diana  28.0  55000.0    Finance   78.0
4      Eve  28.0  55000.0         IT   82.0
5      Eve  45.0  70000.0         HR   82.0
6    Frank  32.0  70000.0    Finance   88.0
7    Grace  32.0  48000.0         IT   92.0

In [124]:
df.ffill()

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  25.0  60000.0         IT   90.0
2  Charlie  35.0  60000.0    Finance   90.0
3    Diana  28.0  55000.0    Finance   78.0
4      Eve  28.0  55000.0         IT   82.0
5      Eve  45.0  70000.0         HR   82.0
6    Frank  32.0  70000.0    Finance   88.0
7    Grace  32.0  48000.0         IT   92.0

#### 47: Fill NaN with next value

In [125]:
df.bfill()

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  35.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance   78.0
3    Diana  28.0  55000.0         IT   78.0
4      Eve  45.0  70000.0         IT   82.0
5    Frank  45.0  70000.0         HR   88.0
6    Frank  32.0  48000.0    Finance   88.0
7    Grace   NaN  48000.0         IT   92.0

#### 48: Fill NaN only in first 5 rows with 0

In [126]:
df.fillna(0, limit=4) # wrong

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   0.0  60000.0         IT   90.0
2  Charlie  35.0      0.0    Finance    0.0
3    Diana  28.0  55000.0          0   78.0
4      Eve   0.0      0.0         IT   82.0
5        0  45.0  70000.0         HR    0.0
6    Frank  32.0      0.0    Finance   88.0
7    Grace   0.0  48000.0         IT   92.0

In [127]:
df.iloc[:5].fillna(0)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob   0.0  60000.0         IT   90.0
2  Charlie  35.0      0.0    Finance    0.0
3    Diana  28.0  55000.0          0   78.0
4      Eve   0.0      0.0         IT   82.0

#### 49 : Fill NaN in specific column using interpolation

In [128]:
df.interpolate()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_3552\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  30.0  60000.0         IT   90.0
2  Charlie  35.0  57500.0    Finance   84.0
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  36.5  62500.0         IT   82.0
5      NaN  45.0  70000.0         HR   85.0
6    Frank  32.0  59000.0    Finance   88.0
7    Grace  32.0  48000.0         IT   92.0

#### 50: Fill NaN using linear interpolation for numeric data

In [129]:
num_cols = df.select_dtypes(include=[np.number]).columns
df[num_cols].interpolate(method='linear')

    Age   Salary  Marks
0  25.0  50000.0   85.0
1  30.0  60000.0   90.0
2  35.0  57500.0   84.0
3  28.0  55000.0   78.0
4  36.5  62500.0   82.0
5  45.0  70000.0   85.0
6  32.0  59000.0   88.0
7  32.0  48000.0   92.0

#### 51: Fill NaN in time-series column using time interpolation

In [130]:
dates = pd.date_range('2024-08-23', periods=8,freq='D')
df2['date'] = dates
df2

      Name   Age   Salary Department  Marks       date
0    Alice  25.0  50000.0         HR   85.0 2024-08-23
1      Bob  33.0  60000.0         IT   90.0 2024-08-24
2  Charlie  35.0  55000.0    Finance   78.0 2024-08-25
3    Diana  28.0  55000.0        NaN   78.0 2024-08-26
4      Eve  33.0  55000.0         IT   82.0 2024-08-27
5      NaN  45.0  70000.0         HR   78.0 2024-08-28
6    Frank  32.0  55000.0    Finance   88.0 2024-08-29
7    Grace  33.0  48000.0         IT   92.0 2024-08-30

In [131]:
# df2['Age'].interpolate(method='time') #ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

In [132]:
df2.drop('date',axis=1)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  33.0  60000.0         IT   90.0
2  Charlie  35.0  55000.0    Finance   78.0
3    Diana  28.0  55000.0        NaN   78.0
4      Eve  33.0  55000.0         IT   82.0
5      NaN  45.0  70000.0         HR   78.0
6    Frank  32.0  55000.0    Finance   88.0
7    Grace  33.0  48000.0         IT   92.0

In [133]:
df2.index=dates
df2['Age'].interpolate(method='time')

2024-08-23    25.0
2024-08-24    33.0
2024-08-25    35.0
2024-08-26    28.0
2024-08-27    33.0
2024-08-28    45.0
2024-08-29    32.0
2024-08-30    33.0
Freq: D, Name: Age, dtype: float64

#### 52: Fill NaN in Temperature with rounded mean value

#### 53: Fill NaN with group-wise mean (e.g., per department)

#### 54: Fill NaN with group-wise median

#### 55: Fill NaN with group-wise forward fill

#### 56: Fill NaN in string column with "N/A"

In [137]:
str_col = df2.select_dtypes(include='object').columns
df2[str_col].fillna('N/A')

               Name Department
2024-08-23    Alice         HR
2024-08-24      Bob         IT
2024-08-25  Charlie    Finance
2024-08-26    Diana        N/A
2024-08-27      Eve         IT
2024-08-28      N/A         HR
2024-08-29    Frank    Finance
2024-08-30    Grace         IT

#### 57: Fill NaN with the most frequent value

In [138]:
df3 = df.copy()
for col in df3.columns:
    df3[col].fillna(df3[col].mode()[0], inplace=True)
df3

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_3552\2988531887.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].mode()[0], inplace=True)

      Name   Age   Salary Department  Marks
0    Alice  25.0  50000.0         HR   85.0
1      Bob  25.0  60000.0         IT   90.0
2  Charlie  35.0  48000.0    Finance   78.0
3    Diana  28.0  55000.0         IT   78.0
4      Eve  25.0  48000.0         IT   82.0
5    Alice  45.0  70000.0         HR   78.0
6    Frank  32.0  48000.0    Finance   88.0
7    Grace  25.0  48000.0         IT   92.0

#### 58: Fill NaN in Score with random integers between 50 and 100m4

In [ ]:
df3["Score"] = [np.nan, np.nan, None, 1,23,None,0,-1]

In [142]:
df3

      Name   Age   Salary Department  Marks  Score
0    Alice  25.0  50000.0         HR   85.0    NaN
1      Bob  25.0  60000.0         IT   90.0    NaN
2  Charlie  35.0  48000.0    Finance   78.0    NaN
3    Diana  28.0  55000.0         IT   78.0    1.0
4      Eve  25.0  48000.0         IT   82.0   23.0
5    Alice  45.0  70000.0         HR   78.0    NaN
6    Frank  32.0  48000.0    Finance   88.0    0.0
7    Grace  25.0  48000.0         IT   92.0   -1.0

In [143]:
none_values = df3['Score'].isna()
df3['Score'].fillna([np.random.randint(50,100,len(none_values))])

TypeError: "value" parameter must be a scalar or dict, but you passed a "list"

In [148]:
df3.loc[none_values,'Score']=np.random.randint(50,100,none_values.sum())

In [149]:
df3

      Name   Age   Salary Department  Marks  Score
0    Alice  25.0  50000.0         HR   85.0   79.0
1      Bob  25.0  60000.0         IT   90.0   87.0
2  Charlie  35.0  48000.0    Finance   78.0   51.0
3    Diana  28.0  55000.0         IT   78.0    1.0
4      Eve  25.0  48000.0         IT   82.0   23.0
5    Alice  45.0  70000.0         HR   78.0   70.0
6    Frank  32.0  48000.0    Finance   88.0    0.0
7    Grace  25.0  48000.0         IT   92.0   -1.0

In [150]:
df3.dtypes

Name           object
Age           float64
Salary        float64
Department     object
Marks         float64
Score         float64
dtype: object

In [151]:
col= df3.select_dtypes(include=[np.number]).columns
df3[col]= df3[col].clip(lower=0)

##### df3[col]= df3[col].clip(lower=0,inplace=True) 
If you do thse then none will  store all numberic column 
beacuse inplace = true Doest return anything

In [154]:
df3

      Name   Age   Salary Department  Marks  Score
0    Alice  25.0  50000.0         HR   85.0   79.0
1      Bob  25.0  60000.0         IT   90.0   87.0
2  Charlie  35.0  48000.0    Finance   78.0   51.0
3    Diana  28.0  55000.0         IT   78.0    1.0
4      Eve  25.0  48000.0         IT   82.0   23.0
5    Alice  45.0  70000.0         HR   78.0   70.0
6    Frank  32.0  48000.0    Finance   88.0    0.0
7    Grace  25.0  48000.0         IT   92.0    0.0

#### 59: Fill NaN in percentage column with 0%

In [156]:
df3['perce'] = np.nan*8

In [157]:
df3

      Name   Age   Salary Department  Marks  Score  perce
0    Alice  25.0  50000.0         HR   85.0   79.0    NaN
1      Bob  25.0  60000.0         IT   90.0   87.0    NaN
2  Charlie  35.0  48000.0    Finance   78.0   51.0    NaN
3    Diana  28.0  55000.0         IT   78.0    1.0    NaN
4      Eve  25.0  48000.0         IT   82.0   23.0    NaN
5    Alice  45.0  70000.0         HR   78.0   70.0    NaN
6    Frank  32.0  48000.0    Finance   88.0    0.0    NaN
7    Grace  25.0  48000.0         IT   92.0    0.0    NaN

In [158]:
df3['perce'].fillna("0%")

0    0%
1    0%
2    0%
3    0%
4    0%
5    0%
6    0%
7    0%
Name: perce, dtype: object

#### Fill NaN in currency column with ₹0.00

In [159]:
df3['Bonus'] = ['₹5000', np.nan, '₹3000', '₹4500', np.nan, '₹6000', '₹3500', np.nan]
df3

      Name   Age   Salary Department  Marks  Score  perce  Bonus
0    Alice  25.0  50000.0         HR   85.0   79.0    NaN  ₹5000
1      Bob  25.0  60000.0         IT   90.0   87.0    NaN    NaN
2  Charlie  35.0  48000.0    Finance   78.0   51.0    NaN  ₹3000
3    Diana  28.0  55000.0         IT   78.0    1.0    NaN  ₹4500
4      Eve  25.0  48000.0         IT   82.0   23.0    NaN    NaN
5    Alice  45.0  70000.0         HR   78.0   70.0    NaN  ₹6000
6    Frank  32.0  48000.0    Finance   88.0    0.0    NaN  ₹3500
7    Grace  25.0  48000.0         IT   92.0    0.0    NaN    NaN

In [160]:
df3.info()
df3['Bonus'] = df3['Bonus'].fillna("₹0")
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         8 non-null      float64
 2   Salary      8 non-null      float64
 3   Department  8 non-null      object
 4   Marks       8 non-null      float64
 5   Score       8 non-null      float64
 6   perce       0 non-null      float64
 7   Bonus       5 non-null      object
dtypes: float64(5), object(3)
memory usage: 576.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         8 non-null      float64
 2   Salary      8 non-null      float64
 3   Department  8 non-null      object
 4   Marks       8 non-null      float64
 5   Score       8 non-null      float64
 6   perce       0 non-null      float64
 7   Bonus       8 non-null      object
dtypes: float64(5), object(3)
memory usage: 576.0+ bytes

#### 61: Fill NaN in product column with 'No Product'

In [161]:
df3['Product'] = ['pen', 'book','pencil','pendrive',None,np.nan, None,'Notebook']
df3

      Name   Age   Salary Department  Marks  Score  perce  Bonus   Product
0    Alice  25.0  50000.0         HR   85.0   79.0    NaN  ₹5000       pen
1      Bob  25.0  60000.0         IT   90.0   87.0    NaN     ₹0      book
2  Charlie  35.0  48000.0    Finance   78.0   51.0    NaN  ₹3000    pencil
3    Diana  28.0  55000.0         IT   78.0    1.0    NaN  ₹4500  pendrive
4      Eve  25.0  48000.0         IT   82.0   23.0    NaN     ₹0      None
5    Alice  45.0  70000.0         HR   78.0   70.0    NaN  ₹6000       NaN
6    Frank  32.0  48000.0    Finance   88.0    0.0    NaN  ₹3500      None
7    Grace  25.0  48000.0         IT   92.0    0.0    NaN     ₹0  Notebook

In [162]:
df3['Product'] = df3['Product'].fillna("NO-Product")

In [163]:
df3

      Name   Age   Salary Department  Marks  Score  perce  Bonus     Product
0    Alice  25.0  50000.0         HR   85.0   79.0    NaN  ₹5000         pen
1      Bob  25.0  60000.0         IT   90.0   87.0    NaN     ₹0        book
2  Charlie  35.0  48000.0    Finance   78.0   51.0    NaN  ₹3000      pencil
3    Diana  28.0  55000.0         IT   78.0    1.0    NaN  ₹4500    pendrive
4      Eve  25.0  48000.0         IT   82.0   23.0    NaN     ₹0  NO-Product
5    Alice  45.0  70000.0         HR   78.0   70.0    NaN  ₹6000  NO-Product
6    Frank  32.0  48000.0    Finance   88.0    0.0    NaN  ₹3500  NO-Product
7    Grace  25.0  48000.0         IT   92.0    0.0    NaN     ₹0    Notebook

#### 62: Fill NaN with upper-case version of previous value

In [173]:
df2

               Name   Age   Salary Department  Marks       date
2024-08-23    Alice  25.0  50000.0         HR   85.0 2024-08-23
2024-08-24      Bob  33.0  60000.0         IT   90.0 2024-08-24
2024-08-25  Charlie  35.0  55000.0    Finance   78.0 2024-08-25
2024-08-26    Diana  28.0  55000.0        NaN   78.0 2024-08-26
2024-08-27      Eve  33.0  55000.0         IT   82.0 2024-08-27
2024-08-28      NaN  45.0  70000.0         HR   78.0 2024-08-28
2024-08-29    Frank  32.0  55000.0    Finance   88.0 2024-08-29
2024-08-30    Grace  33.0  48000.0         IT   92.0 2024-08-30

In [176]:
df2.fillna(method='ffill'.upper())

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_3552\511898368.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill'.upper())

               Name   Age   Salary Department  Marks       date
2024-08-23    Alice  25.0  50000.0         HR   85.0 2024-08-23
2024-08-24      Bob  33.0  60000.0         IT   90.0 2024-08-24
2024-08-25  Charlie  35.0  55000.0    Finance   78.0 2024-08-25
2024-08-26    Diana  28.0  55000.0    Finance   78.0 2024-08-26
2024-08-27      Eve  33.0  55000.0         IT   82.0 2024-08-27
2024-08-28      Eve  45.0  70000.0         HR   78.0 2024-08-28
2024-08-29    Frank  32.0  55000.0    Finance   88.0 2024-08-29
2024-08-30    Grace  33.0  48000.0         IT   92.0 2024-08-30

In [177]:
df2.ffill().upper()

AttributeError: 'DataFrame' object has no attribute 'upper'

#### 63: Fill NaN with a constant per data type (0 for numeric, 'Unknown' for
 strings)

In [178]:
df2

               Name   Age   Salary Department  Marks       date
2024-08-23    Alice  25.0  50000.0         HR   85.0 2024-08-23
2024-08-24      Bob  33.0  60000.0         IT   90.0 2024-08-24
2024-08-25  Charlie  35.0  55000.0    Finance   78.0 2024-08-25
2024-08-26    Diana  28.0  55000.0        NaN   78.0 2024-08-26
2024-08-27      Eve  33.0  55000.0         IT   82.0 2024-08-27
2024-08-28      NaN  45.0  70000.0         HR   78.0 2024-08-28
2024-08-29    Frank  32.0  55000.0    Finance   88.0 2024-08-29
2024-08-30    Grace  33.0  48000.0         IT   92.0 2024-08-30

In [179]:
obj_col = df2.select_dtypes(include=['object']).columns
num_col = df2.select_dtypes(include=[np.number]).columns
df2[obj_col].fillna('Unkown')

               Name Department
2024-08-23    Alice         HR
2024-08-24      Bob         IT
2024-08-25  Charlie    Finance
2024-08-26    Diana     Unkown
2024-08-27      Eve         IT
2024-08-28   Unkown         HR
2024-08-29    Frank    Finance
2024-08-30    Grace         IT

In [180]:
df2[num_col].fillna(0)

             Age   Salary  Marks
2024-08-23  25.0  50000.0   85.0
2024-08-24  33.0  60000.0   90.0
2024-08-25  35.0  55000.0   78.0
2024-08-26  28.0  55000.0   78.0
2024-08-27  33.0  55000.0   82.0
2024-08-28  45.0  70000.0   78.0
2024-08-29  32.0  55000.0   88.0
2024-08-30  33.0  48000.0   92.0

#### 64: Fill NaN in column with average of two other columns

In [181]:
 df_avg_fill = pd.DataFrame({"Name":list("ABCDEFTY")})
 df_avg_fill['Test1'] = [85, 90, 88, 78, 82, 87, 91, 92]
 df_avg_fill['Test2'] = [82, 88, 85, 80, 85, 90, 89, 88]
 df_avg_fill['Final_Score'] = [np.nan, 89, np.nan, 79, np.nan, 88.5, 90, np.nan]
 df_avg_fill

  Name  Test1  Test2  Final_Score
0    A     85     82          NaN
1    B     90     88         89.0
2    C     88     85          NaN
3    D     78     80         79.0
4    E     82     85          NaN
5    F     87     90         88.5
6    T     91     89         90.0
7    Y     92     88          NaN

In [182]:
avg_fill = (df_avg_fill["Test1"] + df_avg_fill['Test2']) /2
print(avg_fill)
df_avg_fill['Final_Score'].fillna(avg_fill)

0    83.5
1    89.0
2    86.5
3    79.0
4    83.5
5    88.5
6    90.0
7    90.0
dtype: float64

0    83.5
1    89.0
2    86.5
3    79.0
4    83.5
5    88.5
6    90.0
7    90.0
Name: Final_Score, dtype: float64