# Handling Missing Values:
- Interpolate()
- replace()

## A. Interpolation Practice on Sensor Data

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("sensor_data.csv")

In [4]:
data.head()

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00         22.5      45.0    1012.0
1  2024-01-01 01:00         23.0       NaN    1013.0
2  2024-01-01 02:00          NaN      47.0    1012.0
3  2024-01-01 03:00         24.0      48.0       NaN
4  2024-01-01 04:00          NaN      49.0    1011.0

In [5]:
data.isna().any()

timestamp      False
temperature     True
humidity        True
pressure        True
dtype: bool

In [6]:
data.isna().sum()

timestamp       0
temperature    17
humidity       16
pressure        8
dtype: int64

In [7]:
data.isna().mean()*100

timestamp       0.0
temperature    34.0
humidity       32.0
pressure       16.0
dtype: float64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    50 non-null     object
 1   temperature  33 non-null     float64
 2   humidity     34 non-null     float64
 3   pressure     42 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.7+ KB

#

In [9]:
df = data.copy()

In [10]:
df.head()

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00         22.5      45.0    1012.0
1  2024-01-01 01:00         23.0       NaN    1013.0
2  2024-01-01 02:00          NaN      47.0    1012.0
3  2024-01-01 03:00         24.0      48.0       NaN
4  2024-01-01 04:00          NaN      49.0    1011.0

#

#### 1. Fill missing values only in the temperature column using interpolation.

In [11]:
df['temperature'] = df['temperature'].interpolate()

In [12]:
df.head(10)

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00        22.50      45.0    1012.0
1  2024-01-01 01:00        23.00       NaN    1013.0
2  2024-01-01 02:00        23.50      47.0    1012.0
3  2024-01-01 03:00        24.00      48.0       NaN
4  2024-01-01 04:00        24.75      49.0    1011.0
5  2024-01-01 05:00        25.50       NaN    1010.0
6  2024-01-01 06:00        26.00      52.0    1009.0
7  2024-01-01 07:00        26.50      53.0    1008.0
8  2024-01-01 08:00        27.00       NaN    1007.0
9  2024-01-01 09:00        27.50      55.0       NaN

#### 2. Apply interpolation and store the result in a new DataFrame without modifying the original.

In [13]:
df2 = df.interpolate()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_26728\3442953142.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df2 = df.interpolate()

In [14]:
df.dtypes

timestamp       object
temperature    float64
humidity       float64
pressure       float64
dtype: object

In [15]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [16]:
df.dtypes

timestamp      datetime64[ns]
temperature           float64
humidity              float64
pressure              float64
dtype: object

In [17]:
df3 = df.interpolate()

In [18]:
df3

             timestamp  temperature  humidity  pressure
0  2024-01-01 00:00:00        22.50      45.0    1012.0
1  2024-01-01 01:00:00        23.00      46.0    1013.0
2  2024-01-01 02:00:00        23.50      47.0    1012.0
3  2024-01-01 03:00:00        24.00      48.0    1011.5
4  2024-01-01 04:00:00        24.75      49.0    1011.0
5  2024-01-01 05:00:00        25.50      50.5    1010.0
6  2024-01-01 06:00:00        26.00      52.0    1009.0
7  2024-01-01 07:00:00        26.50      53.0    1008.0
8  2024-01-01 08:00:00        27.00      54.0    1007.0
9  2024-01-01 09:00:00        27.50      55.0    1006.5
10 2024-01-01 10:00:00        28.00      56.0    1006.0
11 2024-01-01 11:00:00        28.50      57.0    1005.0
12 2024-01-01 12:00:00        29.00      58.0    1004.0
13 2024-01-01 13:00:00        29.50      59.0    1003.0
14 2024-01-01 14:00:00        30.00      60.0    1002.5
15 2024-01-01 15:00:00        30.50      61.0    1002.0
16 2024-01-01 16:00:00        31.00      62.0    1001.0
17 2024-01-01 17:00:00        31.50      63.0    1000.0
18 2024-01-01 18:00:00        32.00      64.0     999.0
19 2024-01-01 19:00:00        31.50      65.0     998.0
20 2024-01-01 20:00:00        31.00      66.0     997.5
21 2024-01-01 21:00:00        30.50      67.0     997.0
22 2024-01-01 22:00:00        30.00      68.0     996.0
23 2024-01-01 23:00:00        29.50      69.0     995.0
24 2024-01-02 00:00:00        29.00      68.0     994.0
25 2024-01-02 01:00:00        28.50      67.0     993.0
26 2024-01-02 02:00:00        28.00      66.0     992.5
27 2024-01-02 03:00:00        27.50      65.0     992.0
28 2024-01-02 04:00:00        27.00      64.0     991.0
29 2024-01-02 05:00:00        26.50      63.0     990.0
30 2024-01-02 06:00:00        26.00      62.0     989.0
31 2024-01-02 07:00:00        26.50      61.0     988.0
32 2024-01-02 08:00:00        27.00      60.0     987.5
33 2024-01-02 09:00:00        27.50      59.0     987.0
34 2024-01-02 10:00:00        28.00      58.0     986.0
35 2024-01-02 11:00:00        28.50      57.0     985.0
36 2024-01-02 12:00:00        29.00      56.0     984.0
37 2024-01-02 13:00:00        29.50      55.0     983.0
38 2024-01-02 14:00:00        30.00      54.0     982.5
39 2024-01-02 15:00:00        30.50      53.0     982.0
40 2024-01-02 16:00:00        31.00      52.0     981.0
41 2024-01-02 17:00:00        31.50      51.0     980.0
42 2024-01-02 18:00:00        32.00      50.0     979.0
43 2024-01-02 19:00:00        31.50      49.0     978.0
44 2024-01-02 20:00:00        31.00      48.0     977.5
45 2024-01-02 21:00:00        30.50      47.0     977.0
46 2024-01-02 22:00:00        30.00      46.0     976.0
47 2024-01-02 23:00:00        29.50      45.0     975.0
48 2024-01-03 00:00:00        29.00      46.0     974.0
49 2024-01-03 01:00:00        29.00      47.0     973.0

#### 3. Interpolate missing values row-wise instead of column-wise.

In [19]:
df_row = df.interpolate(axis=1)

TypeError: Cannot interpolate with all object-dtype columns in the DataFrame. Try setting at least one column to a numeric dtype.

In [20]:
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].interpolate(axis=1)

In [21]:
df.head(10)

            timestamp  temperature  humidity  pressure
0 2024-01-01 00:00:00        22.50     45.00    1012.0
1 2024-01-01 01:00:00        23.00    518.00    1013.0
2 2024-01-01 02:00:00        23.50     47.00    1012.0
3 2024-01-01 03:00:00        24.00     48.00      48.0
4 2024-01-01 04:00:00        24.75     49.00    1011.0
5 2024-01-01 05:00:00        25.50    517.75    1010.0
6 2024-01-01 06:00:00        26.00     52.00    1009.0
7 2024-01-01 07:00:00        26.50     53.00    1008.0
8 2024-01-01 08:00:00        27.00    517.00    1007.0
9 2024-01-01 09:00:00        27.50     55.00      55.0

In [22]:
data.head()

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00         22.5      45.0    1012.0
1  2024-01-01 01:00         23.0       NaN    1013.0
2  2024-01-01 02:00          NaN      47.0    1012.0
3  2024-01-01 03:00         24.0      48.0       NaN
4  2024-01-01 04:00          NaN      49.0    1011.0

In [23]:
num_cols = data.select_dtypes(include='number').columns
df_row = data.copy()
df_row[num_cols] = df_row[num_cols].interpolate(axis =1)

In [24]:
df_row.head(10)

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00         22.5     45.00    1012.0
1  2024-01-01 01:00         23.0    518.00    1013.0
2  2024-01-01 02:00          NaN     47.00    1012.0
3  2024-01-01 03:00         24.0     48.00      48.0
4  2024-01-01 04:00          NaN     49.00    1011.0
5  2024-01-01 05:00         25.5    517.75    1010.0
6  2024-01-01 06:00         26.0     52.00    1009.0
7  2024-01-01 07:00          NaN     53.00    1008.0
8  2024-01-01 08:00         27.0    517.00    1007.0
9  2024-01-01 09:00         27.5     55.00      55.0

#### 4. Fill only the first missing value in each column using limit=1.

In [25]:
df5 = data.copy()
df5.head()

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00         22.5      45.0    1012.0
1  2024-01-01 01:00         23.0       NaN    1013.0
2  2024-01-01 02:00          NaN      47.0    1012.0
3  2024-01-01 03:00         24.0      48.0       NaN
4  2024-01-01 04:00          NaN      49.0    1011.0

In [26]:
df5.interpolate(limit=1)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_26728\1056774441.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df5.interpolate(limit=1)

           timestamp  temperature  humidity  pressure
0   2024-01-01 00:00        22.50      45.0    1012.0
1   2024-01-01 01:00        23.00      46.0    1013.0
2   2024-01-01 02:00        23.50      47.0    1012.0
3   2024-01-01 03:00        24.00      48.0    1011.5
4   2024-01-01 04:00        24.75      49.0    1011.0
5   2024-01-01 05:00        25.50      50.5    1010.0
6   2024-01-01 06:00        26.00      52.0    1009.0
7   2024-01-01 07:00        26.50      53.0    1008.0
8   2024-01-01 08:00        27.00      54.0    1007.0
9   2024-01-01 09:00        27.50      55.0    1006.5
10  2024-01-01 10:00        28.00      56.0    1006.0
11  2024-01-01 11:00        28.50      57.0    1005.0
12  2024-01-01 12:00        29.00      58.0    1004.0
13  2024-01-01 13:00        29.50      59.0    1003.0
14  2024-01-01 14:00        30.00      60.0    1002.5
15  2024-01-01 15:00        30.50      61.0    1002.0
16  2024-01-01 16:00        31.00      62.0    1001.0
17  2024-01-01 17:00        31.50      63.0    1000.0
18  2024-01-01 18:00        32.00      64.0     999.0
19  2024-01-01 19:00        31.50      65.0     998.0
20  2024-01-01 20:00        31.00      66.0     997.5
21  2024-01-01 21:00        30.50      67.0     997.0
22  2024-01-01 22:00        30.00      68.0     996.0
23  2024-01-01 23:00        29.50      69.0     995.0
24  2024-01-02 00:00        29.00      68.0     994.0
25  2024-01-02 01:00        28.50      67.0     993.0
26  2024-01-02 02:00        28.00      66.0     992.5
27  2024-01-02 03:00        27.50      65.0     992.0
28  2024-01-02 04:00        27.00      64.0     991.0
29  2024-01-02 05:00        26.50      63.0     990.0
30  2024-01-02 06:00        26.00      62.0     989.0
31  2024-01-02 07:00        26.50      61.0     988.0
32  2024-01-02 08:00        27.00      60.0     987.5
33  2024-01-02 09:00        27.50      59.0     987.0
34  2024-01-02 10:00        28.00      58.0     986.0
35  2024-01-02 11:00        28.50      57.0     985.0
36  2024-01-02 12:00        29.00      56.0     984.0
37  2024-01-02 13:00        29.50      55.0     983.0
38  2024-01-02 14:00        30.00      54.0     982.5
39  2024-01-02 15:00        30.50      53.0     982.0
40  2024-01-02 16:00        31.00      52.0     981.0
41  2024-01-02 17:00        31.50      51.0     980.0
42  2024-01-02 18:00        32.00      50.0     979.0
43  2024-01-02 19:00        31.50      49.0     978.0
44  2024-01-02 20:00        31.00      48.0     977.5
45  2024-01-02 21:00        30.50      47.0     977.0
46  2024-01-02 22:00        30.00      46.0     976.0
47  2024-01-02 23:00        29.50      45.0     975.0
48  2024-01-03 00:00        29.00      46.0     974.0
49  2024-01-03 01:00        29.00      47.0     973.0

In [27]:
num_cols = df5.select_dtypes(include=['number']).columns
df5[num_cols].interpolate(limit=1)

    temperature  humidity  pressure
0         22.50      45.0    1012.0
1         23.00      46.0    1013.0
2         23.50      47.0    1012.0
3         24.00      48.0    1011.5
4         24.75      49.0    1011.0
5         25.50      50.5    1010.0
6         26.00      52.0    1009.0
7         26.50      53.0    1008.0
8         27.00      54.0    1007.0
9         27.50      55.0    1006.5
10        28.00      56.0    1006.0
11        28.50      57.0    1005.0
12        29.00      58.0    1004.0
13        29.50      59.0    1003.0
14        30.00      60.0    1002.5
15        30.50      61.0    1002.0
16        31.00      62.0    1001.0
17        31.50      63.0    1000.0
18        32.00      64.0     999.0
19        31.50      65.0     998.0
20        31.00      66.0     997.5
21        30.50      67.0     997.0
22        30.00      68.0     996.0
23        29.50      69.0     995.0
24        29.00      68.0     994.0
25        28.50      67.0     993.0
26        28.00      66.0     992.5
27        27.50      65.0     992.0
28        27.00      64.0     991.0
29        26.50      63.0     990.0
30        26.00      62.0     989.0
31        26.50      61.0     988.0
32        27.00      60.0     987.5
33        27.50      59.0     987.0
34        28.00      58.0     986.0
35        28.50      57.0     985.0
36        29.00      56.0     984.0
37        29.50      55.0     983.0
38        30.00      54.0     982.5
39        30.50      53.0     982.0
40        31.00      52.0     981.0
41        31.50      51.0     980.0
42        32.00      50.0     979.0
43        31.50      49.0     978.0
44        31.00      48.0     977.5
45        30.50      47.0     977.0
46        30.00      46.0     976.0
47        29.50      45.0     975.0
48        29.00      46.0     974.0
49        29.00      47.0     973.0

#### Interpolate values but only in the forward direction.

In [28]:
df5[num_cols].interpolate(method='ffill').head()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_26728\287689441.py:1: FutureWarning: DataFrame.interpolate with method=ffill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df5[num_cols].interpolate(method='ffill').head()

   temperature  humidity  pressure
0         22.5      45.0    1012.0
1         23.0      45.0    1013.0
2         23.0      47.0    1012.0
3         24.0      48.0    1012.0
4         24.0      49.0    1011.0

In [29]:
df5[num_cols].interpolate(limit_direction='forward').head(10)

   temperature  humidity  pressure
0        22.50      45.0    1012.0
1        23.00      46.0    1013.0
2        23.50      47.0    1012.0
3        24.00      48.0    1011.5
4        24.75      49.0    1011.0
5        25.50      50.5    1010.0
6        26.00      52.0    1009.0
7        26.50      53.0    1008.0
8        27.00      54.0    1007.0
9        27.50      55.0    1006.5

#### Interpolate values and ensure both start and end NaN values are filled.

In [30]:
df5[num_cols].interpolate(limit_direction='both').head(10)

   temperature  humidity  pressure
0        22.50      45.0    1012.0
1        23.00      46.0    1013.0
2        23.50      47.0    1012.0
3        24.00      48.0    1011.5
4        24.75      49.0    1011.0
5        25.50      50.5    1010.0
6        26.00      52.0    1009.0
7        26.50      53.0    1008.0
8        27.00      54.0    1007.0
9        27.50      55.0    1006.5

#### Apply interpolation on only selected columns (temperature, humidity).

In [31]:
df5[['temperature','humidity']].interpolate().head()

   temperature  humidity
0        22.50      45.0
1        23.00      46.0
2        23.50      47.0
3        24.00      48.0
4        24.75      49.0

#### Convert timestamp to datetime and perform time-based interpolation.

In [41]:
df6 = data.copy()
df6['timestamp'] = pd.to_datetime( df6['timestamp'], errors='coerce')
df6 = df6.dropna(subset=['timestamp'])
df6.set_index(df6['timestamp'],inplace=True)
df6 = df6.sort_index()
df6[num_cols].interpolate(method='time')

                     temperature  humidity  pressure
timestamp
2024-01-01 00:00:00        22.50      45.0    1012.0
2024-01-01 01:00:00        23.00      46.0    1013.0
2024-01-01 02:00:00        23.50      47.0    1012.0
2024-01-01 03:00:00        24.00      48.0    1011.5
2024-01-01 04:00:00        24.75      49.0    1011.0
2024-01-01 05:00:00        25.50      50.5    1010.0
2024-01-01 06:00:00        26.00      52.0    1009.0
2024-01-01 07:00:00        26.50      53.0    1008.0
2024-01-01 08:00:00        27.00      54.0    1007.0
2024-01-01 09:00:00        27.50      55.0    1006.5
2024-01-01 10:00:00        28.00      56.0    1006.0
2024-01-01 11:00:00        28.50      57.0    1005.0
2024-01-01 12:00:00        29.00      58.0    1004.0
2024-01-01 13:00:00        29.50      59.0    1003.0
2024-01-01 14:00:00        30.00      60.0    1002.5
2024-01-01 15:00:00        30.50      61.0    1002.0
2024-01-01 16:00:00        31.00      62.0    1001.0
2024-01-01 17:00:00        31.50      63.0    1000.0
2024-01-01 18:00:00        32.00      64.0     999.0
2024-01-01 19:00:00        31.50      65.0     998.0
2024-01-01 20:00:00        31.00      66.0     997.5
2024-01-01 21:00:00        30.50      67.0     997.0
2024-01-01 22:00:00        30.00      68.0     996.0
2024-01-01 23:00:00        29.50      69.0     995.0
2024-01-02 00:00:00        29.00      68.0     994.0
2024-01-02 01:00:00        28.50      67.0     993.0
2024-01-02 02:00:00        28.00      66.0     992.5
2024-01-02 03:00:00        27.50      65.0     992.0
2024-01-02 04:00:00        27.00      64.0     991.0
2024-01-02 05:00:00        26.50      63.0     990.0
2024-01-02 06:00:00        26.00      62.0     989.0
2024-01-02 07:00:00        26.50      61.0     988.0
2024-01-02 08:00:00        27.00      60.0     987.5
2024-01-02 09:00:00        27.50      59.0     987.0
2024-01-02 10:00:00        28.00      58.0     986.0
2024-01-02 11:00:00        28.50      57.0     985.0
2024-01-02 12:00:00        29.00      56.0     984.0
2024-01-02 13:00:00        29.50      55.0     983.0
2024-01-02 14:00:00        30.00      54.0     982.5
2024-01-02 15:00:00        30.50      53.0     982.0
2024-01-02 16:00:00        31.00      52.0     981.0
2024-01-02 17:00:00        31.50      51.0     980.0
2024-01-02 18:00:00        32.00      50.0     979.0
2024-01-02 19:00:00        31.50      49.0     978.0
2024-01-02 20:00:00        31.00      48.0     977.5
2024-01-02 21:00:00        30.50      47.0     977.0
2024-01-02 22:00:00        30.00      46.0     976.0
2024-01-02 23:00:00        29.50      45.0     975.0
2024-01-03 00:00:00        29.00      46.0     974.0
2024-01-03 01:00:00        29.00      47.0     973.0

#### Compare linear interpolation vs time interpolation on the same dataset.

In [42]:
df_linear = data.copy()

num_cols = df_linear.select_dtypes(include='number').columns
df_linear[num_cols] = df_linear[num_cols].interpolate(method='linear')

In [44]:
df_time = data.copy()
df_time['timestamp'] = pd.to_datetime(df_time['timestamp'])
df_time.set_index('timestamp', inplace=True)
df_time[num_cols] = df_time[num_cols].interpolate(method='time')

In [45]:
df_linear.head(10)

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00        22.50      45.0    1012.0
1  2024-01-01 01:00        23.00      46.0    1013.0
2  2024-01-01 02:00        23.50      47.0    1012.0
3  2024-01-01 03:00        24.00      48.0    1011.5
4  2024-01-01 04:00        24.75      49.0    1011.0
5  2024-01-01 05:00        25.50      50.5    1010.0
6  2024-01-01 06:00        26.00      52.0    1009.0
7  2024-01-01 07:00        26.50      53.0    1008.0
8  2024-01-01 08:00        27.00      54.0    1007.0
9  2024-01-01 09:00        27.50      55.0    1006.5

In [46]:
df_time.head(10)

                     temperature  humidity  pressure
timestamp
2024-01-01 00:00:00        22.50      45.0    1012.0
2024-01-01 01:00:00        23.00      46.0    1013.0
2024-01-01 02:00:00        23.50      47.0    1012.0
2024-01-01 03:00:00        24.00      48.0    1011.5
2024-01-01 04:00:00        24.75      49.0    1011.0
2024-01-01 05:00:00        25.50      50.5    1010.0
2024-01-01 06:00:00        26.00      52.0    1009.0
2024-01-01 07:00:00        26.50      53.0    1008.0
2024-01-01 08:00:00        27.00      54.0    1007.0
2024-01-01 09:00:00        27.50      55.0    1006.5

#### Apply interpolation and then check if any NaN values still remain.

In [47]:
df6 = data.copy()
df6.isna().any().any()

np.True_

In [48]:
df6 = df6.interpolate()
df6.isna().any().any()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_26728\1173677076.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df6 = df6.interpolate()

np.False_

#### Fill consecutive missing values using interpolation but restrict to 2 values max.

In [58]:
df7 = data.copy()
num_cols = df7.select_dtypes(include='number').columns

df7[num_cols] = df7[num_cols].interpolate(limit=2)

In [59]:
df7.head(10)

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00        22.50      45.0    1012.0
1  2024-01-01 01:00        23.00      46.0    1013.0
2  2024-01-01 02:00        23.50      47.0    1012.0
3  2024-01-01 03:00        24.00      48.0    1011.5
4  2024-01-01 04:00        24.75      49.0    1011.0
5  2024-01-01 05:00        25.50      50.5    1010.0
6  2024-01-01 06:00        26.00      52.0    1009.0
7  2024-01-01 07:00        26.50      53.0    1008.0
8  2024-01-01 08:00        27.00      54.0    1007.0
9  2024-01-01 09:00        27.50      55.0    1006.5

In [60]:
import numpy as np
df7["Null_col"] = np.nan

In [61]:
df7.head()

          timestamp  temperature  humidity  pressure  Null_col
0  2024-01-01 00:00        22.50      45.0    1012.0       NaN
1  2024-01-01 01:00        23.00      46.0    1013.0       NaN
2  2024-01-01 02:00        23.50      47.0    1012.0       NaN
3  2024-01-01 03:00        24.00      48.0    1011.5       NaN
4  2024-01-01 04:00        24.75      49.0    1011.0       NaN

In [62]:
df7.dtypes

timestamp       object
temperature    float64
humidity       float64
pressure       float64
Null_col       float64
dtype: object

In [63]:
df7.loc[:1, 'Null_col'] = np.random.randint(10, 100, size=2)

In [64]:
df7.head()

          timestamp  temperature  humidity  pressure  Null_col
0  2024-01-01 00:00        22.50      45.0    1012.0      40.0
1  2024-01-01 01:00        23.00      46.0    1013.0      34.0
2  2024-01-01 02:00        23.50      47.0    1012.0       NaN
3  2024-01-01 03:00        24.00      48.0    1011.5       NaN
4  2024-01-01 04:00        24.75      49.0    1011.0       NaN

In [65]:
num_cols = df7.select_dtypes(include='float64').columns
df7[num_cols] = df7[num_cols].interpolate(limit=2)

In [66]:
df7.head(10)

          timestamp  temperature  humidity  pressure  Null_col
0  2024-01-01 00:00        22.50      45.0    1012.0      40.0
1  2024-01-01 01:00        23.00      46.0    1013.0      34.0
2  2024-01-01 02:00        23.50      47.0    1012.0      34.0
3  2024-01-01 03:00        24.00      48.0    1011.5      34.0
4  2024-01-01 04:00        24.75      49.0    1011.0       NaN
5  2024-01-01 05:00        25.50      50.5    1010.0       NaN
6  2024-01-01 06:00        26.00      52.0    1009.0       NaN
7  2024-01-01 07:00        26.50      53.0    1008.0       NaN
8  2024-01-01 08:00        27.00      54.0    1007.0       NaN
9  2024-01-01 09:00        27.50      55.0    1006.5       NaN

#### Interpolate missing values and then round results to 2 decimal places.

In [68]:
df8 = data.copy()
num_cols = df8.select_dtypes(include='number').columns
df8[num_cols] = (df8[num_cols].interpolate(method='linear').round(2))

In [69]:
df8.head()

          timestamp  temperature  humidity  pressure
0  2024-01-01 00:00        22.50      45.0    1012.0
1  2024-01-01 01:00        23.00      46.0    1013.0
2  2024-01-01 02:00        23.50      47.0    1012.0
3  2024-01-01 03:00        24.00      48.0    1011.5
4  2024-01-01 04:00        24.75      49.0    1011.0

#### Replace missing values using interpolation and then fill remaining using ffill.

In [71]:
df9 = data.copy()
df9['timestamp'] = pd.to_datetime(df9['timestamp'], errors='coerce')
df9 = df9.dropna(subset=['timestamp'])
df9 = df9.set_index('timestamp').sort_index()

df9[num_cols] = (df9[num_cols].interpolate(method='time').ffill())

In [72]:
df9.head(10)

                     temperature  humidity  pressure
timestamp
2024-01-01 00:00:00        22.50      45.0    1012.0
2024-01-01 01:00:00        23.00      46.0    1013.0
2024-01-01 02:00:00        23.50      47.0    1012.0
2024-01-01 03:00:00        24.00      48.0    1011.5
2024-01-01 04:00:00        24.75      49.0    1011.0
2024-01-01 05:00:00        25.50      50.5    1010.0
2024-01-01 06:00:00        26.00      52.0    1009.0
2024-01-01 07:00:00        26.50      53.0    1008.0
2024-01-01 08:00:00        27.00      54.0    1007.0
2024-01-01 09:00:00        27.50      55.0    1006.5

In [73]:
df9.isna().any().any()

np.False_

#### Interpolate data and then drop rows where NaN still exists.

In [74]:
df10 = data.copy()
df10[num_cols] = df10[num_cols].interpolate(method='linear')
df10 = df10.dropna(subset=num_cols)

In [75]:
df10.isna().any().any()

np.False_

#### Apply interpolation separately for each column using a loop.

In [76]:
df11 = data.copy()
num_cols = df11.select_dtypes(include=['number']).columns
for col in num_cols:
    df11[col] = df11[col].interpolate(method='linear')

In [77]:
df11.isna().any().any()

np.False_

#

#

## B. filling missing values (especially with replace()--

In [2]:
dataB = {
    'timestamp': [
        '2024-01-01 10:00', '2024-01-01 11:00', '2024-01-01 12:00',
        '2024-01-01 13:00', '2024-01-01 14:00'
    ],
    'temperature': [22.5, np.nan, 24.0, 'NA', 25.5],
    'humidity': [45, 50, np.nan, '', 55],
    'salary': [30000, 35000, np.nan, 40000, 'null'],
    'marks': [80, np.nan, 85, 90, '?'],
    'price': [100, 200, '-', np.nan, 300],
    'category': ['A', 'A', 'B', 'B', 'A'],
    'age': [25, np.nan, 22, '', 30],
    'status': ['student', 'employee', 'student', 'employee', 'student']
}

dfB = pd.DataFrame(dataB)

In [3]:
dfB

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NA,,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 1. Replace 'NA' in temperature with np.nan.

In [5]:
d1= dfB.copy()
d1['temperature'] = d1['temperature'].replace('NA', np.nan)
d1

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_12584\560660660.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  d1['temperature'] = d1['temperature'].replace('NA', np.nan)

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NaN,,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 2. Replace '' in humidity with np.nan.

In [6]:
d1['humidity'] = d1['humidity'].replace('', np.nan)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_12584\3689084255.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  d1['humidity'] = d1['humidity'].replace('', np.nan)

In [7]:
pd.set_option('future.no_silent_downcasting', True)

#### 3. Replace 'null' in salary with np.nan.

In [8]:
d1['salary'] = d1['salary'].replace('null', np.nan)
d1

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50.0,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55.0,NaN,?,300,A,30,student

#### 4. Replace '?' in marks with np.nan.

In [9]:
d1['marks'] = d1['marks'].replace('?', np.nan)
d1

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50.0,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55.0,NaN,NaN,300,A,30,student

#### 5. Replace '-' in price with np.nan.

In [10]:
d1['price'] = d1['price'].replace('-', np.nan)
d1

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50.0,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,NaN,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55.0,NaN,NaN,300,A,30,student

#### 6. Replace ['NA', 'null'] only in numeric columns.

In [13]:
num_cols = d1.select_dtypes(include=['number']).columns
d1[num_cols] = d1[num_cols].replace(['NA','null'], np.nan)
d1

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50.0,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,NaN,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55.0,NaN,NaN,300,A,30,student

#### 7. Replace missing indicators only in temperature and humidity.

In [15]:
d2 = dfB.copy()
d2[['temperature','humidity']] = d2[['temperature','humidity']].replace(['NA',''], np.nan)
d2

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 8. Replace all NaN values in temperature with 0.

In [16]:
d2['temperature'] = d2['temperature'].replace(np.nan, 0)

In [17]:
d2

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,0,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,0,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 9. Replace NaN in each column with its median using loop.

In [18]:
num_cols = d2.select_dtypes(include=['number']).columns
for col in num_cols:
    d2[col] = d2[col].replace(np.nan, d2[col].median())

In [19]:
d2

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,0,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,0,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 10. Replace all 'NA', 'null', and empty strings in a sales dataset with proper NaN and then fill them with 0.

In [20]:
d3 = dfB.copy()

In [21]:
d3 = d1.replace('NA',np.nan)

In [22]:
d3

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50.0,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,NaN,B,22,student
3,2024-01-01 13:00,NaN,NaN,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55.0,NaN,NaN,300,A,30,student

In [23]:
d3 = d3.replace(['NA', 'null', '', '?', '-'], np.nan)

In [25]:
d3 = d3.replace(np.nan,0)

In [26]:
d3

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45.0,30000,80,100,A,25,student
1,2024-01-01 11:00,0.0,50.0,35000,0,200,A,0,employee
2,2024-01-01 12:00,24.0,0.0,0,85,0,B,22,student
3,2024-01-01 13:00,0.0,0.0,40000,90,0,B,0,employee
4,2024-01-01 14:00,25.5,55.0,0,0,300,A,30,student

#### 11. Replace missing temperature values with the column’s average temperature.

In [28]:
d4 = dfB.copy()

In [29]:
d4['temperature'] = d4['temperature'].replace(['Na','None','Null','_',''], np.nan)
d4['temperature'] = pd.to_numeric(d4['temperature'], errors='coerce')
mean_d = np.mean(d4['temperature'])
d4['temperature'] = d4['temperature'].replace(np.nan,mean_d)
d4

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,24.0,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,24.0,,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 12. Replace missing age with 18 if status = student.

In [34]:
d5 = dfB.copy()
d5['age'] = d5.apply(lambda r: 18 if pd.isna(r['age']) and r['status']=='student' else r['age'], axis=1)

In [35]:
d5

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NA,,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 13. Replace ['?', ''] only in marks and age.

In [39]:
d5[['marks','age']] = d5[['marks','age']].replace(['?',''], np.nan)

In [40]:
d5

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NA,,40000,90,NaN,B,NaN,employee
4,2024-01-01 14:00,25.5,55,null,NaN,300,A,30,student

#### 14. Replace missing temperature with 25 only when humidity > 50.

In [42]:
d6 = dfB.copy()
d6['temperature'] = d6.apply(lambda r: 25 if pd.isna(r['temperature']) and r['humidity']>50 else r['temperature'], axis=1)

In [43]:
d6

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,NaN,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,NaN,NaN,85,-,B,22,student
3,2024-01-01 13:00,NA,,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student

#### 15. Replace multiple columns using one dictionary mapping.

In [48]:
d6 = d6.replace({'temperature': [np.nan,'NA'], 'humidity': [np.nan,'']}, {'temperature': 25, 'humidity': 50})

In [49]:
d6

,timestamp,temperature,humidity,salary,marks,price,category,age,status
0,2024-01-01 10:00,22.5,45,30000,80,100,A,25,student
1,2024-01-01 11:00,25,50,35000,NaN,200,A,NaN,employee
2,2024-01-01 12:00,24.0,50,NaN,85,-,B,22,student
3,2024-01-01 13:00,25,50,40000,90,NaN,B,,employee
4,2024-01-01 14:00,25.5,55,null,?,300,A,30,student