# groupby() Practice Questions

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('sales_datasetGB.csv')

In [3]:
data.head()

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122

In [4]:
data.dtypes

order_id            int64
customer_id         int64
city               object
product            object
category           object
quantity            int64
price               int64
payment_method     object
order_status       object
rating            float64
total_amount        int64
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        500 non-null    int64
 1   customer_id     500 non-null    int64
 2   city            500 non-null    object
 3   product         500 non-null    object
 4   category        500 non-null    object
 5   quantity        500 non-null    int64
 6   price           500 non-null    int64
 7   payment_method  500 non-null    object
 8   order_status    500 non-null    object
 9   rating          500 non-null    float64
 10  total_amount    500 non-null    int64
dtypes: float64(1), int64(5), object(5)
memory usage: 43.1+ KB

In [6]:
data.duplicated().any()

np.False_

#

In [7]:
data1 = data.copy(deep=True)

#

#### 1. Find city-wise total sales

In [8]:
data1.groupby('city')['total_amount'].sum()

city
Bangalore    8403266
Delhi        7292948
Hyderabad    6161815
Mumbai       7416563
Pune         8159528
Name: total_amount, dtype: int64

#

#### 2. Find city-wise average sales

In [10]:
data1.groupby('city')['total_amount'].mean()

city
Bangalore    77808.018519
Delhi        71499.490196
Hyderabad    65551.223404
Mumbai       80614.815217
Pune         78457.000000
Name: total_amount, dtype: float64

In [11]:
round(data1.groupby('city')['total_amount'].mean(),2)

city
Bangalore    77808.02
Delhi        71499.49
Hyderabad    65551.22
Mumbai       80614.82
Pune         78457.00
Name: total_amount, dtype: float64

#

#### 3. Find city-wise maximum order amount

In [12]:
data1.groupby('city')['total_amount'].max()

city
Bangalore    246770
Delhi        243265
Hyderabad    224545
Mumbai       246350
Pune         249985
Name: total_amount, dtype: int64

#

#### 4. Find city-wise minimum order amount

In [13]:
data1.groupby('city')['total_amount'].min()

city
Bangalore    1322
Delhi        1234
Hyderabad    1620
Mumbai       2024
Pune          577
Name: total_amount, dtype: int64

#

#### 5. Find city-wise total quantity sold

In [15]:
data1.groupby('city')['quantity'].sum()

city
Bangalore    325
Delhi        318
Hyderabad    281
Mumbai       285
Pune         298
Name: quantity, dtype: int64

#

#### 6. Find product-wise total revenue

In [16]:
data1.groupby('product')['total_amount'].sum()

product
Keyboard    6351361
Laptop      6160475
Mobile      8006431
Monitor     9437831
Mouse       7478022
Name: total_amount, dtype: int64

#

#### 7. Find product-wise average revenue

In [17]:
round(data1.groupby('product')['total_amount'].mean(),1)

product
Keyboard    77455.6
Laptop      68449.7
Mobile      82540.5
Monitor     77359.3
Mouse       68605.7
Name: total_amount, dtype: float64

#

#### 8. Find product-wise highest price

In [18]:
data1.groupby('product')['total_amount'].max()

product
Keyboard    246350
Laptop      217145
Mobile      249985
Monitor     246770
Mouse       246280
Name: total_amount, dtype: int64

#

#### 9. Find product-wise lowest price

In [19]:
data1.groupby('product')['total_amount'].min()

product
Keyboard    2036
Laptop      2743
Mobile       577
Monitor     1620
Mouse       1322
Name: total_amount, dtype: int64

#

#### 10. Find product-wise total quantity sold

In [20]:
data1.groupby('product')['quantity'].sum()

product
Keyboard    247
Laptop      254
Mobile      286
Monitor     381
Mouse       339
Name: quantity, dtype: int64

#

#### 11. Find category-wise total sales

In [21]:
data1.groupby('category')['total_amount'].sum()

category
Accessories    17959869
Electronics    19474251
Name: total_amount, dtype: int64

#### 12. Find category-wise average rating

In [22]:
data1.groupby('category')['rating'].mean()

category
Accessories    3.036364
Electronics    2.997674
Name: rating, dtype: float64

#### 13. Find category-wise maximum sales

In [23]:
data1.groupby('category')['total_amount'].max()

category
Accessories    246770
Electronics    249985
Name: total_amount, dtype: int64

#### 14. Find category-wise minimum sales

In [24]:
data1.groupby('category')['total_amount'].min()

category
Accessories    1620
Electronics     577
Name: total_amount, dtype: int64

#### 15. Find category-wise total orders

In [27]:
data1.groupby('category')['order_id'].count()

category
Accessories    242
Electronics    258
Name: order_id, dtype: int64

#

#### 16. Find payment-method-wise transaction count

In [28]:
data1.columns

Index(['order_id', 'customer_id', 'city', 'product', 'category', 'quantity',
       'price', 'payment_method', 'order_status', 'rating', 'total_amount'],
      dtype='object')

In [29]:
data1.groupby('payment_method')['order_id'].count()

payment_method
Card    168
Cash    169
UPI     163
Name: order_id, dtype: int64

#### 17. Find payment-method-wise total revenue

In [30]:
data1.groupby('payment_method')['total_amount'].sum()

payment_method
Card    12186299
Cash    12931539
UPI     12316282
Name: total_amount, dtype: int64

#### 18. Find payment-method-wise average spending

In [31]:
data1.groupby('payment_method')['total_amount'].mean()

payment_method
Card    72537.494048
Cash    76517.982249
UPI     75560.012270
Name: total_amount, dtype: float64

#### 19. Find payment-method-wise highest transaction

In [32]:
data1.groupby('payment_method')['total_amount'].max()

payment_method
Card    249985
Cash    246350
UPI     246770
Name: total_amount, dtype: int64

#### 20. Find payment-method-wise quantity sold

In [33]:
data1.groupby('payment_method')['quantity'].sum()

payment_method
Card    498
Cash    523
UPI     486
Name: quantity, dtype: int64

In [35]:
data1.groupby('payment_method',as_index=False)['quantity'].sum()

  payment_method  quantity
0           Card       498
1           Cash       523
2            UPI       486

#

#### 21. Find order-status-wise total sales

In [36]:
data1.columns

Index(['order_id', 'customer_id', 'city', 'product', 'category', 'quantity',
       'price', 'payment_method', 'order_status', 'rating', 'total_amount'],
      dtype='object')

In [37]:
data1.groupby('order_status')['total_amount'].sum()

order_status
Cancelled    11436180
Delivered    11619368
Pending      14378572
Name: total_amount, dtype: int64

#### 22. Find order-status-wise average rating

In [38]:
data1.groupby('order_status',as_index=False)['rating'].mean()

  order_status    rating
0    Cancelled  2.920382
1    Delivered  3.052096
2      Pending  3.068182

#### 23. Find order-status-wise total orders

In [39]:
data1.groupby('order_status',as_index=False)['order_id'].count()

  order_status  order_id
0    Cancelled       157
1    Delivered       167
2      Pending       176

#### 24. Find order-status-wise quantity sold

In [40]:
data1.groupby('order_status',as_index=False)['quantity'].sum()

  order_status  quantity
0    Cancelled       460
1    Delivered       499
2      Pending       548

#### 25. Find order-status-wise highest order amount

In [41]:
data1.groupby('order_status')['total_amount'].max()

order_status
Cancelled    242120
Delivered    239310
Pending      249985
Name: total_amount, dtype: int64

#

#### 26. Find city-wise product count

In [42]:
data1.columns

Index(['order_id', 'customer_id', 'city', 'product', 'category', 'quantity',
       'price', 'payment_method', 'order_status', 'rating', 'total_amount'],
      dtype='object')

In [43]:
data1.groupby('city')['product'].count()

city
Bangalore    108
Delhi        102
Hyderabad     94
Mumbai        92
Pune         104
Name: product, dtype: int64

#### 27. Find city-wise average rating

In [45]:
round(data1.groupby('city')['rating'].mean())

city
Bangalore    3.0
Delhi        3.0
Hyderabad    3.0
Mumbai       3.0
Pune         3.0
Name: rating, dtype: float64

#### 28. Find city-wise delivered orders

In [46]:
data1.head()

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122

In [48]:
(data1.groupby('city')['order_status']=='Deliverd').count()

AttributeError: 'bool' object has no attribute 'count'

In [50]:
data1[data1['order_status']=='Delivered'].groupby('city')['order_id'].count()

city
Bangalore    37
Delhi        49
Hyderabad    23
Mumbai       28
Pune         30
Name: order_id, dtype: int64

#### 29. Find city-wise cancelled orders

In [52]:
data1[data1['order_status']=='Cancelled'].groupby('city')['order_id'].count()

city
Bangalore    32
Delhi        21
Hyderabad    40
Mumbai       25
Pune         39
Name: order_id, dtype: int64

#### 30. Find city-wise Electronics sales

In [53]:
data1[data1['category']=='Electronics'].groupby('city')['total_amount'].sum()

city
Bangalore    3908832
Delhi        3975134
Hyderabad    3081979
Mumbai       4093185
Pune         4415121
Name: total_amount, dtype: int64

#

#### 31. Find top 5 cities by revenue

In [56]:
data1.groupby('city')['total_amount'].sum().sort_values(ascending=False).head(5)

city
Bangalore    8403266
Pune         8159528
Mumbai       7416563
Delhi        7292948
Hyderabad    6161815
Name: total_amount, dtype: int64

#### 32. Find top-selling products

In [57]:
data1.groupby('product')['quantity'].sum().sort_values(ascending=False)

product
Monitor     381
Mouse       339
Mobile      286
Laptop      254
Keyboard    247
Name: quantity, dtype: int64

In [61]:
data1.groupby('product')['quantity'].sum().sort_values(ascending=False).head(1)

product
Monitor    381
Name: quantity, dtype: int64

#### 33. Find least-selling products

In [62]:
data1.groupby('product')['quantity'].sum().sort_values()

product
Keyboard    247
Laptop      254
Mobile      286
Mouse       339
Monitor     381
Name: quantity, dtype: int64

#### 34. Find highest revenue payment method

In [68]:
data1.groupby('payment_method')['total_amount'].sum().sort_values(ascending=False).head(1)

payment_method
Cash    12931539
Name: total_amount, dtype: int64

#### 35. Find category with highest average sales

In [70]:
data1.groupby('payment_method')['total_amount'].mean().sort_values(ascending=False).head(1)

payment_method
Cash    76517.982249
Name: total_amount, dtype: float64

#

#### 36. Find city and product-wise sales

In [71]:
data1.groupby(['city','product'])['total_amount'].sum()

city       product
Bangalore  Keyboard     866487
           Laptop      1442046
           Mobile      1333569
           Monitor     2965266
           Mouse       1795898
Delhi      Keyboard    1307572
           Laptop      1304534
           Mobile      1978351
           Monitor     1131936
           Mouse       1570555
Hyderabad  Keyboard    1434898
           Laptop      1109368
           Mobile       961252
           Monitor     1631345
           Mouse       1024952
Mumbai     Keyboard    1508633
           Laptop      1135095
           Mobile      1755993
           Monitor     1438476
           Mouse       1578366
Pune       Keyboard    1233771
           Laptop      1169432
           Mobile      1977266
           Monitor     2270808
           Mouse       1508251
Name: total_amount, dtype: int64

#### 37. Find city and category-wise revenue

In [72]:
data1.groupby(['city','category'])['total_amount'].sum()

city       category
Bangalore  Accessories    4494434
           Electronics    3908832
Delhi      Accessories    3317814
           Electronics    3975134
Hyderabad  Accessories    3079836
           Electronics    3081979
Mumbai     Accessories    3323378
           Electronics    4093185
Pune       Accessories    3744407
           Electronics    4415121
Name: total_amount, dtype: int64

#### 38. Find city and payment-method-wise sales

In [73]:
data1.groupby(['city','payment_method'])['total_amount'].sum()

city       payment_method
Bangalore  Card              2566439
           Cash              2016442
           UPI               3820385
Delhi      Card              2105423
           Cash              2793521
           UPI               2394004
Hyderabad  Card              2455447
           Cash              2446770
           UPI               1259598
Mumbai     Card              1807276
           Cash              3265078
           UPI               2344209
Pune       Card              3251714
           Cash              2409728
           UPI               2498086
Name: total_amount, dtype: int64

#### 39. Find category and order-status-wise quantity sold

In [74]:
data1.groupby(['category','order_status'])['quantity'].sum()

category     order_status
Accessories  Cancelled       234
             Delivered       247
             Pending         249
Electronics  Cancelled       226
             Delivered       252
             Pending         299
Name: quantity, dtype: int64

#### 40. Find product and payment-method-wise revenue

In [75]:
data1.groupby(['product','payment_method'])['total_amount'].sum()

product   payment_method
Keyboard  Card              1454108
          Cash              2587852
          UPI               2309401
Laptop    Card              2444830
          Cash              1970161
          UPI               1745484
Mobile    Card              2268690
          Cash              2925611
          UPI               2812130
Monitor   Card              3088641
          Cash              3227395
          UPI               3121795
Mouse     Card              2930030
          Cash              2220520
          UPI               2327472
Name: total_amount, dtype: int64

#

#### 41. Find city-wise:
    mean sales
    max sales
    min sales
    total quantity

In [76]:
data1.groupby('city')['total_amount'].agg(['mean','max','min','sum'])

                   mean     max   min      sum
city
Bangalore  77808.018519  246770  1322  8403266
Delhi      71499.490196  243265  1234  7292948
Hyderabad  65551.223404  224545  1620  6161815
Mumbai     80614.815217  246350  2024  7416563
Pune       78457.000000  249985   577  8159528

In [84]:
data1.groupby('city').agg({'total_amount':['mean','max','min'],'quantity':'sum'})

           total_amount               quantity
                   mean     max   min      sum
city
Bangalore  77808.018519  246770  1322      325
Delhi      71499.490196  243265  1234      318
Hyderabad  65551.223404  224545  1620      281
Mumbai     80614.815217  246350  2024      285
Pune       78457.000000  249985   577      298

#

#### 42. Find product-wise:
    total revenue
    average revenue
    highest rating
    lowest rating

In [78]:
data1.groupby('product').agg(Total_revenue = ['total_amount','sum'],
                             Avg_revenue = ['total_amount','mean'],
                             Highest_rating = ['rating','max'],
                             Lowest_rating = ['rating','min'])

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

In [79]:
data1.groupby('product').agg(Total_revenue = ('total_amount','sum'),
                             Avg_revenue = ('total_amount','mean'),
                             Highest_rating = ('rating','max'),
                             Lowest_rating = ('rating','min'))

          Total_revenue   Avg_revenue  Highest_rating  Lowest_rating
product
Keyboard        6351361  77455.621951             5.0            1.0
Laptop          6160475  68449.722222             5.0            1.0
Mobile          8006431  82540.525773             5.0            1.2
Monitor         9437831  77359.270492             5.0            1.0
Mouse           7478022  68605.706422             5.0            1.0

In [81]:
data1.groupby('product').agg(Total_revenue = ('total_amount','sum'),
                             Avg_revenue = ('total_amount','mean'),
                             Highest_rating = ('rating','max'),
                             Lowest_rating = ('rating','min')).round(2)

          Total_revenue  Avg_revenue  Highest_rating  Lowest_rating
product
Keyboard        6351361     77455.62             5.0            1.0
Laptop          6160475     68449.72             5.0            1.0
Mobile          8006431     82540.53             5.0            1.2
Monitor         9437831     77359.27             5.0            1.0
Mouse           7478022     68605.71             5.0            1.0

#

#### 43. Find category-wise:
    total quantity
    average quantity
    total revenue

In [83]:
data1.groupby('category').agg(Total_quantity = ('quantity','sum'),
                             Avg_quantity = ('quantity','mean'),
                             Total_revenue = ('total_amount','sum')).round(2)

             Total_quantity  Avg_quantity  Total_revenue
category
Accessories             730          3.02       17959869
Electronics             777          3.01       19474251

#

#### 44. Find products with average rating > 4

In [86]:
data1.groupby('product').filter(lambda x: x['rating'].mean() > 4)

Empty DataFrame
Columns: [order_id, customer_id, city, product, category, quantity, price, payment_method, order_status, rating, total_amount]
Index: []

#

#### 45. Find cities with sales > 1000000

In [88]:
data1.groupby('city').filter(lambda a : a['total_amount'].sum()>1000000)

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122
...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2114,Mumbai,Mobile,Electronics,1,2024,UPI,Cancelled,4.5,2024
496,1497,2288,Hyderabad,Mouse,Accessories,2,35388,Cash,Pending,2.5,70776
497,1498,2431,Mumbai,Laptop,Accessories,4,15548,UPI,Delivered,2.2,62192
498,1499,2342,Pune,Laptop,Accessories,1,35611,Cash,Pending,3.6,35611
499,1500,2151,Mumbai,Mouse,Accessories,1,38404,UPI,Pending,2.3,38404

#

#### 46. Find payment methods with more than 100 transactions

In [94]:
data1.groupby('payment_method').filter(lambda p : p['order_id'].count() > 100)

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122
...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2114,Mumbai,Mobile,Electronics,1,2024,UPI,Cancelled,4.5,2024
496,1497,2288,Hyderabad,Mouse,Accessories,2,35388,Cash,Pending,2.5,70776
497,1498,2431,Mumbai,Laptop,Accessories,4,15548,UPI,Delivered,2.2,62192
498,1499,2342,Pune,Laptop,Accessories,1,35611,Cash,Pending,3.6,35611
499,1500,2151,Mumbai,Mouse,Accessories,1,38404,UPI,Pending,2.3,38404

In [95]:
data1.groupby('payment_method').filter(lambda p : p['order_id'].count() > 100).payment_method.unique()

array(['UPI', 'Cash', 'Card'], dtype=object)

#

#### 47. Find categories with average sales > 50000

In [96]:
data1.groupby('category').filter(lambda c: c['total_amount'].mean() > 50000)

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122
...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2114,Mumbai,Mobile,Electronics,1,2024,UPI,Cancelled,4.5,2024
496,1497,2288,Hyderabad,Mouse,Accessories,2,35388,Cash,Pending,2.5,70776
497,1498,2431,Mumbai,Laptop,Accessories,4,15548,UPI,Delivered,2.2,62192
498,1499,2342,Pune,Laptop,Accessories,1,35611,Cash,Pending,3.6,35611
499,1500,2151,Mumbai,Mouse,Accessories,1,38404,UPI,Pending,2.3,38404

#### 48. Find cities where average quantity > 3

In [98]:
data1.groupby('city').filter(lambda x: x['quantity'].mean() > 3)

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
6,1007,2189,Bangalore,Keyboard,Accessories,1,17116,Card,Delivered,1.0,17116
...,...,...,...,...,...,...,...,...,...,...,...
487,1488,2490,Delhi,Mobile,Accessories,2,12612,UPI,Delivered,1.4,25224
490,1491,2058,Mumbai,Keyboard,Accessories,1,39390,UPI,Delivered,4.7,39390
495,1496,2114,Mumbai,Mobile,Electronics,1,2024,UPI,Cancelled,4.5,2024
497,1498,2431,Mumbai,Laptop,Accessories,4,15548,UPI,Delivered,2.2,62192
499,1500,2151,Mumbai,Mouse,Accessories,1,38404,UPI,Pending,2.3,38404

#### 49. Find percentage contribution of each product to revenue

In [103]:
data1.groupby('product')['total_amount'].sum()

product
Keyboard    6351361
Laptop      6160475
Mobile      8006431
Monitor     9437831
Mouse       7478022
Name: total_amount, dtype: int64

In [104]:
data1['total_amount'].sum()

np.int64(37434120)

In [107]:
(data1.groupby('product')['total_amount'].sum()/data1['total_amount'].sum()*100).round(2)

product
Keyboard    16.97
Laptop      16.46
Mobile      21.39
Monitor     25.21
Mouse       19.98
Name: total_amount, dtype: float64

#### 50. Find percentage contribution of each city to total sales

In [108]:
((data1.groupby('city')['total_amount'].sum() / data1['total_amount'].sum()) * 100).round(2)

city
Bangalore    22.45
Delhi        19.48
Hyderabad    16.46
Mumbai       19.81
Pune         21.80
Name: total_amount, dtype: float64

#### 51. Find percentage contribution of each category

In [109]:
data1.columns

Index(['order_id', 'customer_id', 'city', 'product', 'category', 'quantity',
       'price', 'payment_method', 'order_status', 'rating', 'total_amount'],
      dtype='object')

In [111]:
((data1.groupby('category')['total_amount'].sum() / data1['total_amount'].sum()) * 100).round(2)

category
Accessories    47.98
Electronics    52.02
Name: total_amount, dtype: float64

#### 52. Find city-wise sales ranking

In [116]:
data1.groupby('city')['total_amount'].sum().rank(ascending=False)

city
Bangalore    1.0
Delhi        4.0
Hyderabad    5.0
Mumbai       3.0
Pune         2.0
Name: total_amount, dtype: float64

#### 53. Find top product in each city

In [124]:
data1.groupby(['city','product'])['total_amount'].sum().reset_index().sort_values('total_amount')

         city   product  total_amount
0   Bangalore  Keyboard        866487
12  Hyderabad    Mobile        961252
14  Hyderabad     Mouse       1024952
11  Hyderabad    Laptop       1109368
8       Delhi   Monitor       1131936
16     Mumbai    Laptop       1135095
21       Pune    Laptop       1169432
20       Pune  Keyboard       1233771
6       Delhi    Laptop       1304534
5       Delhi  Keyboard       1307572
2   Bangalore    Mobile       1333569
10  Hyderabad  Keyboard       1434898
18     Mumbai   Monitor       1438476
1   Bangalore    Laptop       1442046
24       Pune     Mouse       1508251
15     Mumbai  Keyboard       1508633
9       Delhi     Mouse       1570555
19     Mumbai     Mouse       1578366
13  Hyderabad   Monitor       1631345
17     Mumbai    Mobile       1755993
4   Bangalore     Mouse       1795898
22       Pune    Mobile       1977266
7       Delhi    Mobile       1978351
23       Pune   Monitor       2270808
3   Bangalore   Monitor       2965266

In [127]:
grouped = data1.groupby(['city', 'product'])['total_amount'].sum().reset_index()
grouped.loc[grouped.groupby('city')['total_amount'].idxmax()]

         city  product  total_amount
3   Bangalore  Monitor       2965266
7       Delhi   Mobile       1978351
13  Hyderabad  Monitor       1631345
17     Mumbai   Mobile       1755993
23       Pune  Monitor       2270808

#### 54. Find most used payment method in each city

In [132]:
gp = data1.groupby(['city','payment_method']).size().reset_index(name ='count')
gp.loc[gp.groupby('city')['count'].idxmax()]

         city payment_method  count
2   Bangalore            UPI     40
4       Delhi           Cash     39
6   Hyderabad           Card     36
10     Mumbai           Cash     33
12       Pune           Card     37

#### 55. Find highest revenue category in each city

In [133]:
grouped = data1.groupby(['city','category'])['total_amount'].sum().reset_index()
grouped.loc[grouped.groupby('city')['total_amount'].idxmax()]

        city     category  total_amount
0  Bangalore  Accessories       4494434
3      Delhi  Electronics       3975134
5  Hyderabad  Electronics       3081979
7     Mumbai  Electronics       4093185
9       Pune  Electronics       4415121

#### 56. Find most sold product in each category

In [134]:
grouped = data1.groupby(['city','category'])['quantity'].sum().reset_index()
grouped.loc[grouped.groupby('city')['quantity'].idxmax()]

        city     category  quantity
0  Bangalore  Accessories       182
3      Delhi  Electronics       171
4  Hyderabad  Accessories       145
7     Mumbai  Electronics       164
9       Pune  Electronics       163

#### 57. Find city with highest average rating

In [135]:
gp = data1.groupby('city')['rating'].mean().reset_index()
gp.loc[gp.groupby('city')['rating'].idxmax()]

        city    rating
0  Bangalore  2.959259
1      Delhi  2.945098
2  Hyderabad  3.067021
3     Mumbai  2.927174
4       Pune  3.178846

#### 58. Find product with highest total quantity sold

In [138]:
data1.groupby('product')['quantity'].sum()

product
Keyboard    247
Laptop      254
Mobile      286
Monitor     381
Mouse       339
Name: quantity, dtype: int64

In [139]:
data1.groupby('product')['quantity'].sum().sort_values(ascending=False)

product
Monitor     381
Mouse       339
Mobile      286
Laptop      254
Keyboard    247
Name: quantity, dtype: int64

#### 59. Find total cancelled sales city-wise

In [141]:
data1.head(2)

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229

In [142]:
data1[data1['order_status']=='Cancelled'].groupby('city').size()

city
Bangalore    32
Delhi        21
Hyderabad    40
Mumbai       25
Pune         39
dtype: int64

#### 60. Find delivered sales category-wise

In [144]:
data1[data1['order_status']=='Delivered'].groupby('category').size()

category
Accessories    87
Electronics    80
dtype: int64

#### 61. Find pending orders product-wise

In [9]:
data1[data1['order_status']=='Pending'].groupby('product').size()

product
Keyboard    31
Laptop      27
Mobile      43
Monitor     35
Mouse       40
dtype: int64

In [10]:
data1[data1['order_status']=='Pending'].groupby('product')['order_id'].count()

product
Keyboard    31
Laptop      27
Mobile      43
Monitor     35
Mouse       40
Name: order_id, dtype: int64

#### 62. Find cancelled percentage city-wise

In [24]:
data1[data1['order_status']=='Cancelled'].groupby('city')['order_id'].mean()*100 # wrong

city
Bangalore    127559.375000
Delhi        125271.428571
Hyderabad    126377.500000
Mumbai       127672.000000
Pune         124266.666667
Name: order_id, dtype: float64

In [26]:
data1[data1['order_status']=='Cancelled'].groupby('city')['order_id'].mean() #  wrong

city
Bangalore    1275.593750
Delhi        1252.714286
Hyderabad    1263.775000
Mumbai       1276.720000
Pune         1242.666667
Name: order_id, dtype: float64

In [28]:
(data1[data1['order_status']=='Cancelled'].groupby('city')['order_id'].count() /data1.groupby('city')['order_id'].count()) * 100 # correct

city
Bangalore    29.629630
Delhi        20.588235
Hyderabad    42.553191
Mumbai       27.173913
Pune         37.500000
Name: order_id, dtype: float64

#### 63. Find delivered percentage category-wise

In [32]:
(data1[data1['order_status']=='Delivered'].groupby('category')['order_id'].count() /data1.groupby('category')['order_id'].count()) * 100 # correct

category
Accessories    35.950413
Electronics    31.007752
Name: order_id, dtype: float64

#### 64. Find average order value city-wise

In [37]:
data1.groupby('city')['total_amount'].mean().round(2)

city
Bangalore    77808.02
Delhi        71499.49
Hyderabad    65551.22
Mumbai       80614.82
Pune         78457.00
Name: total_amount, dtype: float64

#### 65. Find average order value product-wise

In [39]:
data1.groupby('product')['total_amount'].mean().round(2)

product
Keyboard    77455.62
Laptop      68449.72
Mobile      82540.53
Monitor     77359.27
Mouse       68605.71
Name: total_amount, dtype: float64

#### 66. Find average order value payment-method-wise

In [40]:
data1.groupby('payment_method')['total_amount'].mean().round(2)

payment_method
Card    72537.49
Cash    76517.98
UPI     75560.01
Name: total_amount, dtype: float64

#### 67. Find average order value category-wise

In [41]:
data1.groupby('category')['total_amount'].mean().round(2)

category
Accessories    74214.33
Electronics    75481.59
Name: total_amount, dtype: float64

#### 68. Find average order value order-status-wise

In [42]:
data1.groupby('order_status')['total_amount'].mean().round(2)

order_status
Cancelled    72841.91
Delivered    69577.05
Pending      81696.43
Name: total_amount, dtype: float64

#### 69. Find total ratings city-wise

In [43]:
data1.groupby('city')['rating'].count()

city
Bangalore    108
Delhi        102
Hyderabad     94
Mumbai        92
Pune         104
Name: rating, dtype: int64

In [44]:
data1.groupby('city',as_index= False)['rating'].count()

        city  rating
0  Bangalore     108
1      Delhi     102
2  Hyderabad      94
3     Mumbai      92
4       Pune     104

In [46]:
data1.groupby('city',as_index= False).agg(Total_rating = ('rating','count'))

        city  Total_rating
0  Bangalore           108
1      Delhi           102
2  Hyderabad            94
3     Mumbai            92
4       Pune           104

#### 70. Find average ratings product-wise

In [49]:
data1.groupby('product')['rating'].mean().round(2)

product
Keyboard    2.91
Laptop      3.00
Mobile      3.18
Monitor     3.10
Mouse       2.87
Name: rating, dtype: float64

#### 71. Find highest-rated category

In [50]:
data1.groupby('category')['rating'].max()

category
Accessories    5.0
Electronics    5.0
Name: rating, dtype: float64

In [51]:
data1.groupby('category')['rating'].mean().sort_values(ascending=False)

category
Accessories    3.036364
Electronics    2.997674
Name: rating, dtype: float64

#### 72. Find lowest-rated product

In [53]:
data.groupby('product')['rating'].mean().sort_values()

product
Mouse       2.868807
Keyboard    2.912195
Laptop      3.002222
Monitor     3.097541
Mobile      3.181443
Name: rating, dtype: float64

In [54]:
data.groupby('product')['rating'].mean().sort_values().head(1)

product
Mouse    2.868807
Name: rating, dtype: float64


#### 73. Find city-wise rating count

In [55]:
data1.groupby('city')['rating'].count()

city
Bangalore    108
Delhi        102
Hyderabad     94
Mumbai        92
Pune         104
Name: rating, dtype: int64

In [57]:
data1.groupby('city').agg(Total_rating_count = ('rating','count'))

           Total_rating_count
city
Bangalore                 108
Delhi                     102
Hyderabad                  94
Mumbai                     92
Pune                      104

#### 74. Find product-wise revenue share

In [58]:
(data1.groupby('product')['total_amount'].sum() / data1['total_amount'].sum()) * 100

product
Keyboard    16.966770
Laptop      16.456845
Mobile      21.388057
Monitor     25.211841
Mouse       19.976487
Name: total_amount, dtype: float64

#

#### 75. Find city-wise quantity share

In [61]:
((data1.groupby('city')['quantity'].sum() / data1['quantity'].sum()) * 100).round(2)

city
Bangalore    21.57
Delhi        21.10
Hyderabad    18.65
Mumbai       18.91
Pune         19.77
Name: quantity, dtype: float64

#### 76. Find category-wise sales share

In [65]:
((data1.groupby('category')['total_amount'].sum() / data1['total_amount'].sum()) * 100).round(2)

category
Accessories    47.98
Electronics    52.02
Name: total_amount, dtype: float64

#

#### 77. Find payment-method-wise revenue share

In [66]:
((data1.groupby('payment_method')['total_amount'].sum() / data1['total_amount'].sum()) * 100).round(2)

payment_method
Card    32.55
Cash    34.54
UPI     32.90
Name: total_amount, dtype: float64

#

#### 78. Find status-wise sales share

In [67]:
data1.columns

Index(['order_id', 'customer_id', 'city', 'product', 'category', 'quantity',
       'price', 'payment_method', 'order_status', 'rating', 'total_amount'],
      dtype='object')

In [68]:
((data1.groupby('order_status')['total_amount'].sum() / data1['total_amount'].sum()) * 100).round(2)

order_status
Cancelled    30.55
Delivered    31.04
Pending      38.41
Name: total_amount, dtype: float64

#### 79. Find highest order amount in each city

In [69]:
data1.head()

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122

In [70]:
data1.groupby('city')['total_amount'].max()

city
Bangalore    246770
Delhi        243265
Hyderabad    224545
Mumbai       246350
Pune         249985
Name: total_amount, dtype: int64

#### 80. Find lowest order amount in each city

In [71]:
data1.groupby('city')['total_amount'].min()

city
Bangalore    1322
Delhi        1234
Hyderabad    1620
Mumbai       2024
Pune          577
Name: total_amount, dtype: int64

#### 81. Find highest quantity sold in each category

In [72]:
data1.groupby('category')['quantity'].max()

category
Accessories    5
Electronics    5
Name: quantity, dtype: int64

#### 82. Find highest-rated product in each category

In [73]:
data1.groupby('category')['rating'].max()

category
Accessories    5.0
Electronics    5.0
Name: rating, dtype: float64

#### 83. Find city-wise unique products count

In [74]:
data1.groupby('city')['product'].nunique()

city
Bangalore    5
Delhi        5
Hyderabad    5
Mumbai       5
Pune         5
Name: product, dtype: int64

#### 84. Find unique payment methods used city-wise

In [75]:
data1.groupby('city')['payment_method'].nunique()

city
Bangalore    3
Delhi        3
Hyderabad    3
Mumbai       3
Pune         3
Name: payment_method, dtype: int64

#### 85. Find unique products sold category-wise

In [76]:
data1.groupby('category')['product'].nunique()

category
Accessories    5
Electronics    5
Name: product, dtype: int64

#### 86. Find total unique customers city-wise

In [77]:
data1.groupby('city')['customer_id'].nunique()

city
Bangalore    94
Delhi        93
Hyderabad    82
Mumbai       84
Pune         94
Name: customer_id, dtype: int64

#### 87. Find total unique products payment-method-wise

In [79]:
data1.groupby('payment_method',as_index=False)['product'].nunique()

  payment_method  product
0           Card        5
1           Cash        5
2            UPI        5

#### 88. Find total unique categories city-wise

In [80]:
data1.groupby('city')['category'].nunique()

city
Bangalore    2
Delhi        2
Hyderabad    2
Mumbai       2
Pune         2
Name: category, dtype: int64

#### 89. Find category-wise sales using agg()

In [82]:
data1.groupby('category').agg(Total_sales = ('total_amount','sum'))

             Total_sales
category
Accessories     17959869
Electronics     19474251

#### 90. Find city-wise multiple aggregations

In [85]:
data1.groupby('city')['total_amount'].agg(['sum','mean','max','min'])

               sum          mean     max   min
city
Bangalore  8403266  77808.018519  246770  1322
Delhi      7292948  71499.490196  243265  1234
Hyderabad  6161815  65551.223404  224545  1620
Mumbai     7416563  80614.815217  246350  2024
Pune       8159528  78457.000000  249985   577

#### 91. Find payment-method-wise multiple aggregations

In [88]:
data1.groupby('payment_method')['total_amount'].agg(['sum','mean','max','min'])

                     sum          mean     max   min
payment_method
Card            12186299  72537.494048  249985  3073
Cash            12931539  76517.982249  246350   577
UPI             12316282  75560.012270  246770  1620

#### 92. Find product-wise multiple aggregations

In [89]:
data1.groupby('product')['total_amount'].agg(['sum','mean','max','min'])

              sum          mean     max   min
product
Keyboard  6351361  77455.621951  246350  2036
Laptop    6160475  68449.722222  217145  2743
Mobile    8006431  82540.525773  249985   577
Monitor   9437831  77359.270492  246770  1620
Mouse     7478022  68605.706422  246280  1322

#### 93. Find order-status-wise multiple aggregations

In [90]:
data1.groupby('order_status')['total_amount'].agg(['sum','mean','max','min'])

                   sum          mean     max   min
order_status
Cancelled     11436180  72841.910828  242120  1620
Delivered     11619368  69577.053892  239310  1234
Pending       14378572  81696.431818  249985   577

#### 94. Find city-wise average price

In [91]:
data1.head()

,order_id,customer_id,city,product,category,quantity,price,payment_method,order_status,rating,total_amount
0,1001,2103,Delhi,Mouse,Electronics,2,4096,UPI,Cancelled,2.7,8192
1,1002,2436,Mumbai,Mouse,Accessories,3,44743,Cash,Pending,3.8,134229
2,1003,2349,Delhi,Laptop,Electronics,2,6668,UPI,Delivered,3.4,13336
3,1004,2271,Bangalore,Monitor,Electronics,2,43063,Cash,Pending,2.8,86126
4,1005,2107,Pune,Laptop,Electronics,2,8061,Card,Cancelled,1.3,16122

In [93]:
data1.groupby('city')['price'].mean().round()

city
Bangalore    25778.0
Delhi        22841.0
Hyderabad    21895.0
Mumbai       25937.0
Pune         26206.0
Name: price, dtype: float64

#### 95. Find product-wise average quantity

In [95]:
data1.groupby('product')['quantity'].mean().round(2)

product
Keyboard    3.01
Laptop      2.82
Mobile      2.95
Monitor     3.12
Mouse       3.11
Name: quantity, dtype: float64

#### 96. Find category-wise average price

In [96]:
data1.groupby('category')['total_amount'].mean()

category
Accessories    74214.334711
Electronics    75481.593023
Name: total_amount, dtype: float64

#### 97. Find payment-method-wise average rating

In [97]:
data1.groupby('payment_method')['rating'].mean()

payment_method
Card    3.011310
Cash    3.039053
UPI     2.998160
Name: rating, dtype: float64

#### 98. Find order-status-wise average quantity

In [99]:
data1.groupby('order_status')['quantity'].mean()

order_status
Cancelled    2.929936
Delivered    2.988024
Pending      3.113636
Name: quantity, dtype: float64

#### 99. Find city and product-wise average sales

In [101]:
data1.groupby(['city','product'])['total_amount'].mean()

city       product
Bangalore  Keyboard     61891.928571
           Laptop       80113.666667
           Mobile       78445.235294
           Monitor      92664.562500
           Mouse        66514.740741
Delhi      Keyboard     68819.578947
           Laptop       72474.111111
           Mobile       94207.190476
           Monitor      49214.608696
           Mouse        74788.333333
Hyderabad  Keyboard     75520.947368
           Laptop       58387.789474
           Mobile       60078.250000
           Monitor      74152.045455
           Mouse        56941.777778
Mumbai     Keyboard    125719.416667
           Laptop       59741.842105
           Mobile       92420.684211
           Monitor      68498.857143
           Mouse        75160.285714
Pune       Keyboard     68542.833333
           Laptop       73089.500000
           Mobile       82386.083333
           Monitor      94617.000000
           Mouse        68556.863636
Name: total_amount, dtype: float64

#### 100. Find city and category-wise average quantity

In [104]:
data1.groupby(['city','category'])['quantity'].mean()

city       category
Bangalore  Accessories    3.084746
           Electronics    2.918367
Delhi      Accessories    3.062500
           Electronics    3.166667
Hyderabad  Accessories    2.959184
           Electronics    3.022222
Mumbai     Accessories    2.951220
           Electronics    3.215686
Pune       Accessories    3.000000
           Electronics    2.762712
Name: quantity, dtype: float64