## Pandas Stack

In [1]:
import pandas as pd

## Dataset 1

In [2]:
data = {
    'Student': ['Amit','Neha','Rahul'],
    'Math': [78,85,90],
    'Science': [82,88,91],
    'English': [75,80,89]
}

df1 = pd.DataFrame(data)
print(df1)

  Student  Math  Science  English
0    Amit    78       82       75
1    Neha    85       88       80
2   Rahul    90       91       89

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  3 non-null      object
 1   Math     3 non-null      int64
 2   Science  3 non-null      int64
 3   English  3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

#

### 1. Convert all subject columns into row index using stack().

In [4]:
df1.set_index('Student').stack()

Student
Amit     Math       78
         Science    82
         English    75
Neha     Math       85
         Science    88
         English    80
Rahul    Math       90
         Science    91
         English    89
dtype: int64

### 2. Store stacked output into a variable called stacked_df.

In [5]:
stacked_df = df1.set_index('Student').stack()
stacked_df

Student
Amit     Math       78
         Science    82
         English    75
Neha     Math       85
         Science    88
         English    80
Rahul    Math       90
         Science    91
         English    89
dtype: int64

### 3. Check the type of stacked output.

In [6]:
stacked_df.dtype.type

numpy.int64

In [7]:
type(stacked_df)

pandas.core.series.Series

### 4. Convert stacked Series into DataFrame.

In [8]:
sdf = stacked_df.to_frame()
sdf

                  0
Student
Amit    Math     78
        Science  82
        English  75
Neha    Math     85
        Science  88
        English  80
Rahul   Math     90
        Science  91
        English  89

In [9]:
type(sdf)

pandas.core.frame.DataFrame

### 5. Reset index after stacking.

In [10]:
df1.stack().reset_index()

    level_0  level_1      0
0         0  Student   Amit
1         0     Math     78
2         0  Science     82
3         0  English     75
4         1  Student   Neha
5         1     Math     85
6         1  Science     88
7         1  English     80
8         2  Student  Rahul
9         2     Math     90
10        2  Science     91
11        2  English     89

In [11]:
df1.stack()

0  Student     Amit
   Math          78
   Science       82
   English       75
1  Student     Neha
   Math          85
   Science       88
   English       80
2  Student    Rahul
   Math          90
   Science       91
   English       89
dtype: object

### 6. Rename stacked value column to Marks.

In [12]:
df1.stack().reset_index(name='Marks')

    level_0  level_1  Marks
0         0  Student   Amit
1         0     Math     78
2         0  Science     82
3         0  English     75
4         1  Student   Neha
5         1     Math     85
6         1  Science     88
7         1  English     80
8         2  Student  Rahul
9         2     Math     90
10        2  Science     91
11        2  English     89

In [13]:
stacked_df.reset_index(name='Marks')

  Student  level_1  Marks
0    Amit     Math     78
1    Amit  Science     82
2    Amit  English     75
3    Neha     Math     85
4    Neha  Science     88
5    Neha  English     80
6   Rahul     Math     90
7   Rahul  Science     91
8   Rahul  English     89

### 7. Access only Math marks after stacking.

In [14]:
stacked_df.loc[:,'Math']

Student
Amit     78
Neha     85
Rahul    90
dtype: int64

In [15]:
stacked_df.xs('Math', level=1)

Student
Amit     78
Neha     85
Rahul    90
dtype: int64

### 8. Access Amit's Science marks after stacking.

In [16]:
stacked_df

Student
Amit     Math       78
         Science    82
         English    75
Neha     Math       85
         Science    88
         English    80
Rahul    Math       90
         Science    91
         English    89
dtype: int64

In [17]:
stacked_df.index

MultiIndex([( 'Amit',    'Math'),
            ( 'Amit', 'Science'),
            ( 'Amit', 'English'),
            ( 'Neha',    'Math'),
            ( 'Neha', 'Science'),
            ( 'Neha', 'English'),
            ('Rahul',    'Math'),
            ('Rahul', 'Science'),
            ('Rahul', 'English')],
           names=['Student', None])

In [18]:
stacked_df.loc['Amit','Science']

np.int64(82)

In [19]:
stacked_df['Amit', 'Science']

np.int64(82)

### 9. Sort stacked data by values.

In [20]:
stacked_df.sort_values()

Student
Amit     English    75
         Math       78
Neha     English    80
Amit     Science    82
Neha     Math       85
         Science    88
Rahul    English    89
         Math       90
         Science    91
dtype: int64

### 10. Convert stacked data back using unstack().

In [21]:
stacked_df.unstack()

         Math  Science  English
Student
Amit       78       82       75
Neha       85       88       80
Rahul      90       91       89

#

#

## Dataset 2

In [22]:
data2 = {
    'Product': ['Laptop','Mouse','Keyboard'],
    'Jan': [50000,12000,15000],
    'Feb': [52000,14000,16000],
    'Mar': [51000,13000,17000]
}

sales_df = pd.DataFrame(data2)
sales_df

    Product    Jan    Feb    Mar
0    Laptop  50000  52000  51000
1     Mouse  12000  14000  13000
2  Keyboard  15000  16000  17000

### 1. Set Product as index and apply stack().

In [23]:
sales_df.reset_index('Product').stack()

KeyError: 'Requested level (Product) does not match index name (None)'

In [24]:
sales_df.set_index('Product').stack()

Product
Laptop    Jan    50000
          Feb    52000
          Mar    51000
Mouse     Jan    12000
          Feb    14000
          Mar    13000
Keyboard  Jan    15000
          Feb    16000
          Mar    17000
dtype: int64

### 2. Convert month columns into rows.

In [25]:
sales_df.set_index('Product').stack().reset_index()

    Product level_1      0
0    Laptop     Jan  50000
1    Laptop     Feb  52000
2    Laptop     Mar  51000
3     Mouse     Jan  12000
4     Mouse     Feb  14000
5     Mouse     Mar  13000
6  Keyboard     Jan  15000
7  Keyboard     Feb  16000
8  Keyboard     Mar  17000

### 3. Store stacked output in sales_stack.

In [26]:
sales_stack = sales_df.set_index('Product').stack()
sales_stack

Product
Laptop    Jan    50000
          Feb    52000
          Mar    51000
Mouse     Jan    12000
          Feb    14000
          Mar    13000
Keyboard  Jan    15000
          Feb    16000
          Mar    17000
dtype: int64

### 4. Reset index after stacking.

In [27]:
sales_stack.reset_index()

    Product level_1      0
0    Laptop     Jan  50000
1    Laptop     Feb  52000
2    Laptop     Mar  51000
3     Mouse     Jan  12000
4     Mouse     Feb  14000
5     Mouse     Mar  13000
6  Keyboard     Jan  15000
7  Keyboard     Feb  16000
8  Keyboard     Mar  17000

### 5. Rename columns:
level_1 → Month
0 → Revenue

In [28]:
sales_stack.reset_index().rename(columns={'level_1': 'Month',0: 'Revenue'})

    Product Month  Revenue
0    Laptop   Jan    50000
1    Laptop   Feb    52000
2    Laptop   Mar    51000
3     Mouse   Jan    12000
4     Mouse   Feb    14000
5     Mouse   Mar    13000
6  Keyboard   Jan    15000
7  Keyboard   Feb    16000
8  Keyboard   Mar    17000

### 6. Find Laptop sales after stacking.

In [29]:
sales_stack['Laptop']

Jan    50000
Feb    52000
Mar    51000
dtype: int64

### 7. Access February revenue only.

In [30]:
sales_stack[:,'Feb']

Product
Laptop      52000
Mouse       14000
Keyboard    16000
dtype: int64

In [31]:
sales_stack.xs('Feb', level=1)

Product
Laptop      52000
Mouse       14000
Keyboard    16000
dtype: int64

### 8. Sort stacked revenue values.

In [32]:
sales_stack.sort_values()

Product
Mouse     Jan    12000
          Mar    13000
          Feb    14000
Keyboard  Jan    15000
          Feb    16000
          Mar    17000
Laptop    Jan    50000
          Mar    51000
          Feb    52000
dtype: int64

### 9. Convert stacked output back using unstack().

In [33]:
sales_stack.unstack()

            Jan    Feb    Mar
Product
Laptop    50000  52000  51000
Mouse     12000  14000  13000
Keyboard  15000  16000  17000

### 10. Compare original and unstacked output.

In [34]:
sales_df.set_index('Product').equals(sales_stack.unstack())

True

#

#

## Dataset 3

In [35]:
data3 = {
    'Website': ['Amazon','Flipkart','Myntra'],
    'Monday': [1200,900,700],
    'Tuesday': [1300,850,750],
    'Wednesday': [1250,920,780]
}

traffic_df = pd.DataFrame(data3)
traffic_df

    Website  Monday  Tuesday  Wednesday
0    Amazon    1200     1300       1250
1  Flipkart     900      850        920
2    Myntra     700      750        780

### 1. Set Website as index and stack weekdays.

In [36]:
traffic_df.set_index('Website').stack()

Website
Amazon    Monday       1200
          Tuesday      1300
          Wednesday    1250
Flipkart  Monday        900
          Tuesday       850
          Wednesday     920
Myntra    Monday        700
          Tuesday       750
          Wednesday     780
dtype: int64

### 2. Convert traffic data into long format using stack().

In [37]:
traffic_df.set_index('Website').stack().reset_index()

    Website    level_1     0
0    Amazon     Monday  1200
1    Amazon    Tuesday  1300
2    Amazon  Wednesday  1250
3  Flipkart     Monday   900
4  Flipkart    Tuesday   850
5  Flipkart  Wednesday   920
6    Myntra     Monday   700
7    Myntra    Tuesday   750
8    Myntra  Wednesday   780

### 3. Reset index after stacking.

In [39]:
traffic_df.set_index('Website').stack().reset_index()

    Website    level_1     0
0    Amazon     Monday  1200
1    Amazon    Tuesday  1300
2    Amazon  Wednesday  1250
3  Flipkart     Monday   900
4  Flipkart    Tuesday   850
5  Flipkart  Wednesday   920
6    Myntra     Monday   700
7    Myntra    Tuesday   750
8    Myntra  Wednesday   780

### 4. Rename columns:

level_1 → Day
0 → Visitors

In [42]:
traffic_df.set_index('Website').stack().reset_index().rename(
    columns={'level_1': 'Day',0: 'Visitors'})

    Website        Day  Visitors
0    Amazon     Monday      1200
1    Amazon    Tuesday      1300
2    Amazon  Wednesday      1250
3  Flipkart     Monday       900
4  Flipkart    Tuesday       850
5  Flipkart  Wednesday       920
6    Myntra     Monday       700
7    Myntra    Tuesday       750
8    Myntra  Wednesday       780

### 5.  Find Amazon Tuesday visitors.

In [44]:
traffic_df.set_index('Website').stack()['Amazon', 'Tuesday']

np.int64(1300)

### 6.   Sort visitors in descending order.

In [47]:
traffic_df.set_index('Website').stack().sort_values(ascending=False)

Website
Amazon    Tuesday      1300
          Wednesday    1250
          Monday       1200
Flipkart  Wednesday     920
          Monday        900
          Tuesday       850
Myntra    Wednesday     780
          Tuesday       750
          Monday        700
dtype: int64

### 7. Convert stacked data back using unstack().

In [49]:
stack_data = traffic_df.set_index('Website').stack()
stack_data

Website
Amazon    Monday       1200
          Tuesday      1300
          Wednesday    1250
Flipkart  Monday        900
          Tuesday       850
          Wednesday     920
Myntra    Monday        700
          Tuesday       750
          Wednesday     780
dtype: int64

In [50]:
stack_data.unstack()

          Monday  Tuesday  Wednesday
Website
Amazon      1200     1300       1250
Flipkart     900      850        920
Myntra       700      750        780

### 9. Access only Wednesday data after stacking.

In [51]:
traffic_df.set_index('Website').stack().xs('Wednesday', level=1)

Website
Amazon      1250
Flipkart     920
Myntra       780
dtype: int64

### 10. Convert stacked Series into DataFrame.

In [54]:
traffic_df.set_index('Website').stack().xs('Wednesday', level=1)

Website
Amazon      1250
Flipkart     920
Myntra       780
dtype: int64

#

#

## Dataset 4

In [58]:
data = {
    'Player': ['Virat','Rohit','Raina'],
    'Match1': [78,56,88],
    'Match2': [90,67,70],
    'Match3': [66,80,95]
}

cricket_df = pd.DataFrame(data)

In [59]:
print(cricket_df)

  Player  Match1  Match2  Match3
0  Virat      78      90      66
1  Rohit      56      67      80
2  Raina      88      70      95

### 1. Set Player as index and apply stack().

In [60]:
cricket_df.set_index('Player').stack()

Player
Virat   Match1    78
        Match2    90
        Match3    66
Rohit   Match1    56
        Match2    67
        Match3    80
Raina   Match1    88
        Match2    70
        Match3    95
dtype: int64

### 2. Convert match columns into rows.

In [62]:
cricket_df.set_index('Player').stack().reset_index()

  Player level_1   0
0  Virat  Match1  78
1  Virat  Match2  90
2  Virat  Match3  66
3  Rohit  Match1  56
4  Rohit  Match2  67
5  Rohit  Match3  80
6  Raina  Match1  88
7  Raina  Match2  70
8  Raina  Match3  95

### 3.Reset index after stacking.

In [64]:
cricket_df.set_index('Player').stack().reset_index()

  Player level_1   0
0  Virat  Match1  78
1  Virat  Match2  90
2  Virat  Match3  66
3  Rohit  Match1  56
4  Rohit  Match2  67
5  Rohit  Match3  80
6  Raina  Match1  88
7  Raina  Match2  70
8  Raina  Match3  95

### 4. Rename columns:

level_1 → Match
0 → Runs

In [67]:
cricket_df.set_index('Player').stack().reset_index().rename(
    columns={'level_1': 'Match',0: 'Runs' }
)

  Player   Match  Runs
0  Virat  Match1    78
1  Virat  Match2    90
2  Virat  Match3    66
3  Rohit  Match1    56
4  Rohit  Match2    67
5  Rohit  Match3    80
6  Raina  Match1    88
7  Raina  Match2    70
8  Raina  Match3    95

### 5. Find Virat Match2 runs.

In [68]:
cricket_df.set_index('Player').stack()['Virat', 'Match2']

np.int64(90)

### 6. Sort runs descending.

In [70]:
cricket_df.set_index('Player').stack().sort_values(ascending=False)

Player
Raina   Match3    95
Virat   Match2    90
Raina   Match1    88
Rohit   Match3    80
Virat   Match1    78
Raina   Match2    70
Rohit   Match2    67
Virat   Match3    66
Rohit   Match1    56
dtype: int64

### 7. Find highest run after stacking.

In [72]:
cricket_df.set_index('Player').stack().sort_values(ascending=False)

Player
Raina   Match3    95
Virat   Match2    90
Raina   Match1    88
Rohit   Match3    80
Virat   Match1    78
Raina   Match2    70
Rohit   Match2    67
Virat   Match3    66
Rohit   Match1    56
dtype: int64

### 8. Convert stacked data back using unstack().

In [74]:
cricket_df.set_index('Player').stack().unstack()

        Match1  Match2  Match3
Player
Virat       78      90      66
Rohit       56      67      80
Raina       88      70      95

### 9. Access only Match1 runs after stacking.

In [76]:
cricket_df.set_index('Player').stack().xs('Match1', level=1)

Player
Virat    78
Rohit    56
Raina    88
dtype: int64

#

#

## Unstack Practice Dataset

In [79]:
data = {
    'Student': ['Amit','Amit','Neha','Neha'],
    'Subject': ['Math','Science','Math','Science'],
    'Marks': [78,82,85,88]
}

In [80]:
long_df = pd.DataFrame(data)

In [81]:
long_df = long_df.set_index(['Student','Subject'])

In [82]:
print(long_df)

                 Marks
Student Subject
Amit    Math        78
        Science     82
Neha    Math        85
        Science     88

### 1. Apply unstack() on Subject level.

In [85]:
long_df.unstack(level='Subject')

        Marks
Subject  Math Science
Student
Amit       78      82
Neha       85      88

### 2. Convert Subject rows into columns.

In [88]:
long_df.unstack(level=1)

        Marks
Subject  Math Science
Student
Amit       78      82
Neha       85      88

In [89]:
long_df.unstack(level='Subject')

        Marks
Subject  Math Science
Student
Amit       78      82
Neha       85      88

### 3. Store unstacked output into wide_df.

In [90]:
wide_df = long_df.unstack()
print(wide_df)

        Marks
Subject  Math Science
Student
Amit       78      82
Neha       85      88

### 4. Reset index after unstacking.

In [91]:
wide_df.reset_index()

        Student Marks
Subject          Math Science
0          Amit    78      82
1          Neha    85      88

### 5. Access Amit's Math marks after unstacking.

In [92]:
wide_df.loc['Amit', ('Marks', 'Math')]

np.int64(78)

### 6. Fill missing values using fill_value.

In [93]:
long_df.unstack(fill_value=0)

        Marks
Subject  Math Science
Student
Amit       78      82
Neha       85      88

### 7. Apply stack() again on unstacked data.

In [95]:
wide_df.stack()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_45900\2698997343.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  wide_df.stack()

                 Marks
Student Subject
Amit    Math        78
        Science     82
Neha    Math        85
        Science     88

### 8. Compare original and reconstructed data.

In [96]:
long_df.equals(wide_df.stack())

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_45900\33744630.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  long_df.equals(wide_df.stack())

True

### 9. Use unstack(level=0).

In [97]:
long_df.unstack(level=0)

        Marks
Student  Amit Neha
Subject
Math       78   85
Science    82   88

## Dataset 2

In [98]:
data = {
    'Product': ['Laptop','Laptop','Mouse','Mouse'],
    'Month': ['Jan','Feb','Jan','Feb'],
    'Sales': [50000,52000,12000,14000]
}

In [99]:
sales_df1 = pd.DataFrame(data)

In [112]:
print(sales_df1)

               Sales
Product Month
Laptop  Jan    50000
        Feb    52000
Mouse   Jan    12000
        Feb    14000

### 1.Convert Month index into columns using unstack().

In [113]:
sales_df1.unstack()

         Sales
Month      Feb    Jan
Product
Laptop   52000  50000
Mouse    14000  12000

### 2. Store unstacked output into wide_sales.

In [114]:
wide_sales = sales_df1.unstack()
wide_sales

         Sales
Month      Feb    Jan
Product
Laptop   52000  50000
Mouse    14000  12000

### 3. Reset index after unstacking.

In [115]:
wide_sales.reset_index()

      Product  Sales
Month            Feb    Jan
0      Laptop  52000  50000
1       Mouse  14000  12000

### 4. Access Laptop February sales.

In [118]:
wide_sales.loc['Laptop', ('Sales', 'Feb')]

np.int64(52000)

### 5. Apply unstack(level=1).

In [120]:
sales_df1.unstack(level=1)

         Sales
Month      Feb    Jan
Product
Laptop   52000  50000
Mouse    14000  12000

### 6. Apply unstack(level=0).

In [123]:
sales_df1.unstack(level=0)

         Sales
Product Laptop  Mouse
Month
Feb      52000  14000
Jan      50000  12000

### 7. Convert unstacked data back using stack().

In [125]:
wide_sales.stack()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_45900\1625581163.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  wide_sales.stack()

               Sales
Product Month
Laptop  Feb    52000
        Jan    50000
Mouse   Feb    14000
        Jan    12000

### 8. Compare original and reconstructed output.

In [126]:
sales_df1.equals(wide_sales.stack())

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_45900\4125280253.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  sales_df1.equals(wide_sales.stack())

False

### 9. Fill missing values using fill_value=0.

In [127]:
sales_df1.unstack(fill_value=0)

         Sales
Month      Feb    Jan
Product
Laptop   52000  50000
Mouse    14000  12000

### 10. Sort index before unstacking.

In [128]:
sales_df1.sort_index().unstack()

         Sales
Month      Feb    Jan
Product
Laptop   52000  50000
Mouse    14000  12000