# Column & Row Operations

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('col_row-dataset.csv')

In [4]:
data.head()

   id   name   age       city   salary department  experience
0   1   Neha  19.0  Hyderabad      NaN         HR         7.0
1   2  Kiran  21.0        NaN  60000.0         IT         7.0
2   3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3   4   John  25.0     Mumbai  40000.0  Marketing         NaN
4   5   John  21.0  Bangalore  20000.0         IT         5.0

In [5]:
data.tail()

      id   name   age    city   salary department  experience
495  496   Neha  24.0     NaN  40000.0    Finance         7.0
496  497   Ravi  24.0     NaN      NaN  Marketing         6.0
497  498  Kiran  20.0  Mumbai  20000.0         IT         4.0
498  499   Ravi  21.0     NaN  60000.0  Marketing         4.0
499  500   John  23.0  Mumbai  40000.0    Finance         NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          500 non-null    int64
 1   name        500 non-null    object
 2   age         457 non-null    float64
 3   city        448 non-null    object
 4   salary      421 non-null    float64
 5   department  500 non-null    object
 6   experience  449 non-null    float64
dtypes: float64(3), int64(1), object(3)
memory usage: 27.5+ KB

## 🔸 Column Operations

#### 1. Select only name column

In [8]:
data['name'].head()

0     Neha
1    Kiran
2     Amit
3     John
4     John
Name: name, dtype: object

#### 2. Select name and city columns together

In [10]:
data[['name','city']]

      name       city
0     Neha  Hyderabad
1    Kiran        NaN
2     Amit  Bangalore
3     John     Mumbai
4     John  Bangalore
..     ...        ...
495   Neha        NaN
496   Ravi        NaN
497  Kiran     Mumbai
498   Ravi        NaN
499   John     Mumbai

[500 rows x 2 columns]

#### 3. Create a new column age_plus_5 (age + 5)

In [12]:
data['age_plus'] = data['age']+5

In [13]:
data.head()

   id   name   age       city   salary department  experience  age_plus
0   1   Neha  19.0  Hyderabad      NaN         HR         7.0      24.0
1   2  Kiran  21.0        NaN  60000.0         IT         7.0      26.0
2   3   Amit  23.0  Bangalore      NaN  Marketing         2.0      28.0
3   4   John  25.0     Mumbai  40000.0  Marketing         NaN      30.0
4   5   John  21.0  Bangalore  20000.0         IT         5.0      26.0

#### 4. Rename column name → full_name

In [14]:
data.rename(columns={"name":"full_name"},inplace= True)

In [16]:
data.head()

   id full_name   age       city   salary department  experience  age_plus
0   1      Neha  19.0  Hyderabad      NaN         HR         7.0      24.0
1   2     Kiran  21.0        NaN  60000.0         IT         7.0      26.0
2   3      Amit  23.0  Bangalore      NaN  Marketing         2.0      28.0
3   4      John  25.0     Mumbai  40000.0  Marketing         NaN      30.0
4   5      John  21.0  Bangalore  20000.0         IT         5.0      26.0

#### 5. Delete column salary

In [18]:
data1 = data.copy()
data1.head()

   id full_name   age       city   salary department  experience  age_plus
0   1      Neha  19.0  Hyderabad      NaN         HR         7.0      24.0
1   2     Kiran  21.0        NaN  60000.0         IT         7.0      26.0
2   3      Amit  23.0  Bangalore      NaN  Marketing         2.0      28.0
3   4      John  25.0     Mumbai  40000.0  Marketing         NaN      30.0
4   5      John  21.0  Bangalore  20000.0         IT         5.0      26.0

In [20]:
data1.drop(columns={"salary"},inplace=True)
data1.head()

   id full_name   age       city department  experience  age_plus
0   1      Neha  19.0  Hyderabad         HR         7.0      24.0
1   2     Kiran  21.0        NaN         IT         7.0      26.0
2   3      Amit  23.0  Bangalore  Marketing         2.0      28.0
3   4      John  25.0     Mumbai  Marketing         NaN      30.0
4   5      John  21.0  Bangalore         IT         5.0      26.0

#### 6. Create a new column salary_in_k (salary / 1000)

In [21]:
data1["salary_in_k"] = data["salary"]/1000

In [22]:
data1.head()

   id full_name   age       city department  experience  age_plus  salary_in_k
0   1      Neha  19.0  Hyderabad         HR         7.0      24.0          NaN
1   2     Kiran  21.0        NaN         IT         7.0      26.0         60.0
2   3      Amit  23.0  Bangalore  Marketing         2.0      28.0          NaN
3   4      John  25.0     Mumbai  Marketing         NaN      30.0         40.0
4   5      John  21.0  Bangalore         IT         5.0      26.0         20.0

#### 7. Convert all column names to lowercase

In [24]:
data1.columns = data1.columns.str.lower()

In [25]:
data1.columns

Index(['id', 'full_name', 'age', 'city', 'department', 'experience',
       'age_plus', 'salary_in_k'],
      dtype='object')

#### 8. Rearrange columns: id, name, city, age, salary

In [27]:
data1 = data1[['city','department','experience','age','salary_in_k','full_name','id','age_plus']]

In [28]:
data1.head()

        city department  experience   age  salary_in_k full_name  id  age_plus
0  Hyderabad         HR         7.0  19.0          NaN      Neha   1      24.0
1        NaN         IT         7.0  21.0         60.0     Kiran   2      26.0
2  Bangalore  Marketing         2.0  23.0          NaN      Amit   3      28.0
3     Mumbai  Marketing         NaN  25.0         40.0      John   4      30.0
4  Bangalore         IT         5.0  21.0         20.0      John   5      26.0

#### 9. Replace column city with uppercase values

In [29]:
data1['city'] = data1['city'].str.upper()

In [30]:
data1.head()

        city department  experience   age  salary_in_k full_name  id  age_plus
0  HYDERABAD         HR         7.0  19.0          NaN      Neha   1      24.0
1        NaN         IT         7.0  21.0         60.0     Kiran   2      26.0
2  BANGALORE  Marketing         2.0  23.0          NaN      Amit   3      28.0
3     MUMBAI  Marketing         NaN  25.0         40.0      John   4      30.0
4  BANGALORE         IT         5.0  21.0         20.0      John   5      26.0

#### 10. Create a column is_adult (age >= 18 → True/False)

In [31]:
data1["Is_adult"] = data1["age"]>=18

In [33]:
data1.head(10)

,city,department,experience,age,salary_in_k,full_name,id,age_plus,Is_adult
0,HYDERABAD,HR,7.0,19.0,NaN,Neha,1,24.0,True
1,NaN,IT,7.0,21.0,60.0,Kiran,2,26.0,True
2,BANGALORE,Marketing,2.0,23.0,NaN,Amit,3,28.0,True
3,MUMBAI,Marketing,NaN,25.0,40.0,John,4,30.0,True
4,BANGALORE,IT,5.0,21.0,20.0,John,5,26.0,True
5,DELHI,Sales,3.0,24.0,50.0,John,6,29.0,True
6,CHENNAI,HR,1.0,24.0,30.0,Ravi,7,29.0,True
7,BANGALORE,Finance,3.0,25.0,60.0,John,8,30.0,True
8,BANGALORE,Finance,NaN,19.0,60.0,Kiran,9,24.0,True
9,MUMBAI,HR,4.0,24.0,30.0,Sita,10,29.0,True

In [35]:
data1.sample(5)

,city,department,experience,age,salary_in_k,full_name,id,age_plus,Is_adult
123,NaN,Sales,3.0,22.0,20.0,Amit,124,27.0,True
443,DELHI,Sales,NaN,19.0,40.0,Neha,444,24.0,True
368,DELHI,Sales,3.0,NaN,50.0,Ravi,369,NaN,False
264,DELHI,Finance,1.0,21.0,NaN,Kiran,265,26.0,True
211,HYDERABAD,HR,2.0,25.0,20.0,Ravi,212,30.0,True

#### 11. Create column salary_category:
<30000 → Low
30000–40000 → Medium

40000 → High

In [41]:
def category(a):
    if a < 30000:
        return 'low'
    elif a < 40000 :
        return 'Medium'
    else:
        return "High"
data1["Salary_category"] = data["salary"].apply(category)

In [42]:
data1.sample(10)

,city,department,experience,age,salary_in_k,full_name,id,age_plus,Is_adult,Salary_category
420,HYDERABAD,Marketing,2.0,22.0,40.0,Amit,421,27.0,True,High
318,PUNE,IT,1.0,22.0,40.0,John,319,27.0,True,High
187,HYDERABAD,Marketing,5.0,25.0,50.0,Sita,188,30.0,True,High
453,HYDERABAD,Marketing,4.0,22.0,50.0,John,454,27.0,True,High
400,NaN,Sales,5.0,25.0,40.0,Neha,401,30.0,True,High
440,MUMBAI,IT,5.0,20.0,20.0,Kiran,441,25.0,True,low
89,DELHI,HR,6.0,22.0,20.0,Anu,90,27.0,True,low
451,BANGALORE,Marketing,6.0,20.0,60.0,Amit,452,25.0,True,High
327,MUMBAI,IT,3.0,18.0,20.0,Neha,328,23.0,True,low
243,MUMBAI,Marketing,5.0,18.0,30.0,Kiran,244,23.0,True,Medium

#### 12. Drop multiple columns at once (age, salary)

In [44]:
data1.drop(columns={"age","salary_in_k"},inplace=True)

In [45]:
data1.head()

,city,department,experience,full_name,id,age_plus,Is_adult,Salary_category
0,HYDERABAD,HR,7.0,Neha,1,24.0,True,High
1,NaN,IT,7.0,Kiran,2,26.0,True,High
2,BANGALORE,Marketing,2.0,Amit,3,28.0,True,High
3,MUMBAI,Marketing,NaN,John,4,30.0,True,High
4,BANGALORE,IT,5.0,John,5,26.0,True,low

#### 13. Rename all columns using list assignment

In [47]:
data1.columns = ['city','dept','experi','name','id','age_p','is_adlt','slr_category']

In [48]:
data1.head()

        city       dept  experi   name  id  age_p  is_adlt slr_category
0  HYDERABAD         HR     7.0   Neha   1   24.0     True         High
1        NaN         IT     7.0  Kiran   2   26.0     True         High
2  BANGALORE  Marketing     2.0   Amit   3   28.0     True         High
3     MUMBAI  Marketing     NaN   John   4   30.0     True         High
4  BANGALORE         IT     5.0   John   5   26.0     True          low

#### 14. Add a constant column country = India

In [49]:
data1["country"] ="India"

In [50]:
data1

,city,dept,experi,name,id,age_p,is_adlt,slr_category,country
0,HYDERABAD,HR,7.0,Neha,1,24.0,True,High,India
1,NaN,IT,7.0,Kiran,2,26.0,True,High,India
2,BANGALORE,Marketing,2.0,Amit,3,28.0,True,High,India
3,MUMBAI,Marketing,NaN,John,4,30.0,True,High,India
4,BANGALORE,IT,5.0,John,5,26.0,True,low,India
...,...,...,...,...,...,...,...,...,...
495,NaN,Finance,7.0,Neha,496,29.0,True,High,India
496,NaN,Marketing,6.0,Ravi,497,29.0,True,High,India
497,MUMBAI,IT,4.0,Kiran,498,25.0,True,low,India
498,NaN,Marketing,4.0,Ravi,499,26.0,True,High,India
499,MUMBAI,Finance,NaN,John,500,28.0,True,High,India

#### 15.Swap two columns positions

In [51]:
cols = list(data1.columns)
cols[0],cols[2] = cols[2],cols[0]
data1 = data1[cols]

In [52]:
data1.head()

,experi,dept,city,name,id,age_p,is_adlt,slr_category,country
0,7.0,HR,HYDERABAD,Neha,1,24.0,True,High,India
1,7.0,IT,NaN,Kiran,2,26.0,True,High,India
2,2.0,Marketing,BANGALORE,Amit,3,28.0,True,High,India
3,NaN,Marketing,MUMBAI,John,4,30.0,True,High,India
4,5.0,IT,BANGALORE,John,5,26.0,True,low,India

#

## 🔸 Row Operations

#### 16. Select first 5 rows

In [4]:
data.head()

   id   name   age       city   salary department  experience
0   1   Neha  19.0  Hyderabad      NaN         HR         7.0
1   2  Kiran  21.0        NaN  60000.0         IT         7.0
2   3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3   4   John  25.0     Mumbai  40000.0  Marketing         NaN
4   5   John  21.0  Bangalore  20000.0         IT         5.0

#### 17. Select last 10 rows

In [5]:
data.tail(10)

      id   name   age       city   salary department  experience
490  491   Neha   NaN       Pune  30000.0         IT         8.0
491  492   Ravi   NaN  Bangalore  50000.0    Finance         7.0
492  493    Anu  22.0     Mumbai  50000.0         IT         1.0
493  494    Anu  23.0  Hyderabad  50000.0      Sales         6.0
494  495   Ravi  21.0      Delhi  30000.0    Finance         6.0
495  496   Neha  24.0        NaN  40000.0    Finance         7.0
496  497   Ravi  24.0        NaN      NaN  Marketing         6.0
497  498  Kiran  20.0     Mumbai  20000.0         IT         4.0
498  499   Ravi  21.0        NaN  60000.0  Marketing         4.0
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

In [6]:
data.head(-10)

      id   name   age       city   salary department  experience
0      1   Neha  19.0  Hyderabad      NaN         HR         7.0
1      2  Kiran  21.0        NaN  60000.0         IT         7.0
2      3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3      4   John  25.0     Mumbai  40000.0  Marketing         NaN
4      5   John  21.0  Bangalore  20000.0         IT         5.0
..   ...    ...   ...        ...      ...        ...         ...
485  486   Sita  21.0       Pune  30000.0         IT         2.0
486  487  Kiran  25.0  Hyderabad      NaN         HR         1.0
487  488   Amit  19.0  Bangalore  30000.0      Sales         NaN
488  489   Neha  21.0       Pune      NaN         IT         2.0
489  490   Neha  25.0  Hyderabad  60000.0  Marketing         8.0

[490 rows x 7 columns]

#### 18. Select row with index 3

In [7]:
data.loc[3]

id                    4
name               John
age                25.0
city             Mumbai
salary          40000.0
department    Marketing
experience          NaN
Name: 3, dtype: object

#### 19. Select rows from index 10 to 20

In [8]:
data.loc[10:20]

    id  name   age       city   salary department  experience
10   6  John  24.0      Delhi  50000.0      Sales         3.0
11  12   Anu  21.0  Hyderabad      NaN      Sales         3.0
12  13  Amit   NaN    Chennai      NaN         IT         2.0
13  14  Amit  22.0      Delhi  30000.0    Finance         5.0
14  15  Neha  19.0  Hyderabad      NaN         IT         5.0
15  16  Sita  22.0      Delhi  60000.0    Finance         5.0
16  17  Ravi  23.0     Mumbai  40000.0    Finance         3.0
17  18   Anu  18.0      Delhi      NaN  Marketing         5.0
18  19   Anu  21.0       Pune  60000.0    Finance         NaN
19  20  Amit  19.0  Bangalore  60000.0  Marketing         8.0
20  21  Ravi  22.0    Chennai  60000.0         HR         NaN

In [10]:
data[10:20]

    id  name   age       city   salary department  experience
10   6  John  24.0      Delhi  50000.0      Sales         3.0
11  12   Anu  21.0  Hyderabad      NaN      Sales         3.0
12  13  Amit   NaN    Chennai      NaN         IT         2.0
13  14  Amit  22.0      Delhi  30000.0    Finance         5.0
14  15  Neha  19.0  Hyderabad      NaN         IT         5.0
15  16  Sita  22.0      Delhi  60000.0    Finance         5.0
16  17  Ravi  23.0     Mumbai  40000.0    Finance         3.0
17  18   Anu  18.0      Delhi      NaN  Marketing         5.0
18  19   Anu  21.0       Pune  60000.0    Finance         NaN
19  20  Amit  19.0  Bangalore  60000.0  Marketing         8.0

#### 20. Select specific rows [2, 5, 8]

In [11]:
data.loc[[2,5,8]]

   id   name   age       city   salary department  experience
2   3   Amit  23.0  Bangalore      NaN  Marketing         2.0
5   6   John  24.0      Delhi  50000.0      Sales         3.0
8   9  Kiran  19.0  Bangalore  60000.0    Finance         NaN

#### 21. Add a new row manually

In [12]:
new_row = ['1111','Jack',26,"BGM",55000,'IT',5]
data.loc[len(data)] = new_row

In [15]:
data.tail(2)

       id  name   age    city   salary department  experience
499   500  John  23.0  Mumbai  40000.0    Finance         NaN
500  1111  Jack  26.0     BGM  55000.0         IT         5.0

#### 22. Delete row with index 7

In [24]:
data.iloc[7]

id                    9
name              Kiran
age                19.0
city          Bangalore
salary          60000.0
department      Finance
experience          NaN
Name: 8, dtype: object

In [25]:
data.drop(index=7,inplace=True)

In [26]:
data.iloc[7]

id                 10
name             Sita
age              24.0
city           Mumbai
salary        30000.0
department         HR
experience        4.0
Name: 9, dtype: object

#### 23. Reset index after deleting rows

In [27]:
data.reset_index(drop=True, inplace=True)

In [28]:
data.head(10)

   id   name   age       city   salary department  experience
0   1   Neha  19.0  Hyderabad      NaN         HR         7.0
1   2  Kiran  21.0        NaN  60000.0         IT         7.0
2   3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3   4   John  25.0     Mumbai  40000.0  Marketing         NaN
4   5   John  21.0  Bangalore  20000.0         IT         5.0
5   7   Ravi  24.0    Chennai  30000.0         HR         1.0
6   9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
7  10   Sita  24.0     Mumbai  30000.0         HR         4.0
8   6   John  24.0      Delhi  50000.0      Sales         3.0
9  12    Anu  21.0  Hyderabad      NaN      Sales         3.0

#### 24. Select rows where age > 22

In [29]:
data[data["age"]>22]

       id  name   age       city   salary department  experience
2       3  Amit  23.0  Bangalore      NaN  Marketing         2.0
3       4  John  25.0     Mumbai  40000.0  Marketing         NaN
5       7  Ravi  24.0    Chennai  30000.0         HR         1.0
7      10  Sita  24.0     Mumbai  30000.0         HR         4.0
8       6  John  24.0      Delhi  50000.0      Sales         3.0
..    ...   ...   ...        ...      ...        ...         ...
491   494   Anu  23.0  Hyderabad  50000.0      Sales         6.0
493   496  Neha  24.0        NaN  40000.0    Finance         7.0
494   497  Ravi  24.0        NaN      NaN  Marketing         6.0
497   500  John  23.0     Mumbai  40000.0    Finance         NaN
498  1111  Jack  26.0        BGM  55000.0         IT         5.0

[175 rows x 7 columns]

##### 25. Select rows where city = "Mumbai"

In [31]:
data[data["city"]=='Mumbai']

      id   name   age    city   salary department  experience
3      4   John  25.0  Mumbai  40000.0  Marketing         NaN
7     10   Sita  24.0  Mumbai  30000.0         HR         4.0
14    17   Ravi  23.0  Mumbai  40000.0    Finance         3.0
21    24  Kiran  18.0  Mumbai      NaN    Finance         NaN
30    33   Amit  20.0  Mumbai  20000.0         HR         6.0
..   ...    ...   ...     ...      ...        ...         ...
477  480   Neha  22.0  Mumbai  50000.0    Finance         2.0
479  482   Sita  24.0  Mumbai  50000.0    Finance         6.0
490  493    Anu  22.0  Mumbai  50000.0         IT         1.0
495  498  Kiran  20.0  Mumbai  20000.0         IT         4.0
497  500   John  23.0  Mumbai  40000.0    Finance         NaN

[69 rows x 7 columns]

#### 26. Select rows where:
age > 22 AND salary > 30000

In [33]:
data[(data['age']>22)&(data['salary']>30000)]

       id  name   age       city   salary department  experience
3       4  John  25.0     Mumbai  40000.0  Marketing         NaN
8       6  John  24.0      Delhi  50000.0      Sales         3.0
14     17  Ravi  23.0     Mumbai  40000.0    Finance         3.0
25     28  John  24.0  Hyderabad  50000.0         HR         1.0
37     40  John  25.0       Pune  40000.0      Sales         5.0
..    ...   ...   ...        ...      ...        ...         ...
487   490  Neha  25.0  Hyderabad  60000.0  Marketing         8.0
491   494   Anu  23.0  Hyderabad  50000.0      Sales         6.0
493   496  Neha  24.0        NaN  40000.0    Finance         7.0
497   500  John  23.0     Mumbai  40000.0    Finance         NaN
498  1111  Jack  26.0        BGM  55000.0         IT         5.0

[92 rows x 7 columns]

#### 27. Select rows where city is either "Delhi" or "Pune"

In [36]:
data[(data['city']=='Delhi')|(data['city']=='Pune')]

      id  name   age   city   salary department  experience
8      6  John  24.0  Delhi  50000.0      Sales         3.0
11    14  Amit  22.0  Delhi  30000.0    Finance         5.0
13    16  Sita  22.0  Delhi  60000.0    Finance         5.0
15    18   Anu  18.0  Delhi      NaN  Marketing         5.0
16    19   Anu  21.0   Pune  60000.0    Finance         NaN
..   ...   ...   ...    ...      ...        ...         ...
482  485  Amit  24.0  Delhi  50000.0  Marketing         8.0
483  486  Sita  21.0   Pune  30000.0         IT         2.0
486  489  Neha  21.0   Pune      NaN         IT         2.0
488  491  Neha   NaN   Pune  30000.0         IT         8.0
492  495  Ravi  21.0  Delhi  30000.0    Finance         6.0

[151 rows x 7 columns]

In [37]:
data[data['city'].isin(["Delhi","Pune"])]

      id  name   age   city   salary department  experience
8      6  John  24.0  Delhi  50000.0      Sales         3.0
11    14  Amit  22.0  Delhi  30000.0    Finance         5.0
13    16  Sita  22.0  Delhi  60000.0    Finance         5.0
15    18   Anu  18.0  Delhi      NaN  Marketing         5.0
16    19   Anu  21.0   Pune  60000.0    Finance         NaN
..   ...   ...   ...    ...      ...        ...         ...
482  485  Amit  24.0  Delhi  50000.0  Marketing         8.0
483  486  Sita  21.0   Pune  30000.0         IT         2.0
486  489  Neha  21.0   Pune      NaN         IT         2.0
488  491  Neha   NaN   Pune  30000.0         IT         8.0
492  495  Ravi  21.0  Delhi  30000.0    Finance         6.0

[151 rows x 7 columns]

#### 28. Get top 5 rows with highest salary

In [38]:
data.nlargest(5, 'salary')

    id   name   age       city   salary department  experience
1    2  Kiran  21.0        NaN  60000.0         IT         7.0
6    9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
13  16   Sita  22.0      Delhi  60000.0    Finance         5.0
16  19    Anu  21.0       Pune  60000.0    Finance         NaN
17  20   Amit  19.0  Bangalore  60000.0  Marketing         8.0

#### 29. Sort dataset by age (ascending)

In [40]:
data.sort_values(by='age').head(10)

      id   name   age       city   salary department  experience
22    25   Amit  18.0  Bangalore  40000.0  Marketing         NaN
21    24  Kiran  18.0     Mumbai      NaN    Finance         NaN
36    39  Kiran  18.0  Hyderabad  20000.0      Sales         4.0
463  466    Anu  18.0       Pune  40000.0    Finance         4.0
470  473    Anu  18.0       Pune      NaN      Sales         2.0
82    85   Ravi  18.0    Chennai      NaN      Sales         4.0
66    69   Amit  18.0      Delhi  20000.0         IT         3.0
73    76   John  18.0     Mumbai      NaN         HR         7.0
80    83  Kiran  18.0     Mumbai  40000.0         HR         4.0
405  408   Neha  18.0    Chennai      NaN      Sales         5.0

#### 30. Sort dataset by salary (descending)

In [41]:
data.sort_values(by='salary', ascending=False)

      id   name   age       city   salary department  experience
1      2  Kiran  21.0        NaN  60000.0         IT         7.0
471  474   Amit  25.0  Bangalore  60000.0         IT         7.0
42    45   Ravi  24.0      Delhi  60000.0         IT         3.0
464  467    Anu  19.0       Pune  60000.0      Sales         6.0
35    38   John  19.0       Pune  60000.0         IT         8.0
..   ...    ...   ...        ...      ...        ...         ...
466  469  Kiran  24.0  Hyderabad      NaN         IT         6.0
470  473    Anu  18.0       Pune      NaN      Sales         2.0
484  487  Kiran  25.0  Hyderabad      NaN         HR         1.0
486  489   Neha  21.0       Pune      NaN         IT         2.0
494  497   Ravi  24.0        NaN      NaN  Marketing         6.0

[499 rows x 7 columns]