# Data Cleaning 10

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('messy_data10.csv')

In [4]:
df= data.copy()

#

In [5]:
df.shape

(500, 7)

In [6]:
df.head(10)

  Customer_ID   Name   Age       City   Salary Department     Join_Date
0       C1000    NaN  40.0  Bangalore  35000.0         IT    2021-01-15
1       C1001  Sneha  35.0    Chennai      NaN         IT  invalid_date
2       C1002  Karan  22.0       Pune      NaN      Sales           NaN
3       C1003    NaN   NaN    Chennai  -1000.0        NaN    2022-05-20
4       C1004  Rahul  35.0        NaN      NaN    Finance    2023-08-10
5       C1005  Karan  35.0      Delhi      NaN    Finance           NaN
6       C1006  Karan   NaN        NaN  90000.0        NaN           NaN
7       C1007    NaN  31.0       Pune  -1000.0        NaN           NaN
8       C1008  Priya  40.0  Bangalore  25000.0        NaN           NaN
9       C1009  Rahul  31.0       Pune  35000.0         IT           NaN

In [7]:
df.tail(10)

    Customer_ID   Name    Age       City   Salary Department     Join_Date
490       C1490    NaN   40.0    Chennai  90000.0        NaN    2022-05-20
491       C1491  Karan   40.0    Chennai  50000.0      Sales    2023-08-10
492       C1492    NaN   22.0  Bangalore  70000.0         HR  invalid_date
493       C1493  Priya    NaN  Bangalore  -1000.0        NaN           NaN
494       C1494  Priya   40.0       Pune  35000.0         HR           NaN
495       C1495    NaN   28.0     Mumbai      NaN    Finance    2023-08-10
496       C1496   Amit   -5.0  Bangalore      NaN    Finance           NaN
497       C1497  Sneha   25.0        NaN  70000.0    Finance           NaN
498       C1498  Priya    NaN  Bangalore      NaN        NaN    2021-01-15
499       C1499    NaN  150.0        NaN  50000.0        NaN    2023-08-10

In [8]:
df.sample(10)

    Customer_ID   Name   Age       City   Salary Department     Join_Date
492       C1492    NaN  22.0  Bangalore  70000.0         HR  invalid_date
259       C1259  Priya  22.0  Bangalore  -1000.0         IT    2022-05-20
23        C1023  Sneha  35.0       Pune  25000.0         IT  invalid_date
16        C1016    NaN  28.0      Delhi  50000.0         IT    2021-01-15
48        C1048   Amit  -5.0        NaN  35000.0        NaN    2023-08-10
128       C1128  Rahul   NaN    Chennai  70000.0      Sales  invalid_date
2         C1002  Karan  22.0       Pune      NaN      Sales           NaN
301       C1301  Priya   NaN     Mumbai  90000.0         HR           NaN
67        C1067  Sneha  31.0        NaN  50000.0        NaN    2023-08-10
95        C1095    NaN  25.0        NaN  35000.0         HR    2023-08-10

In [9]:
df.dtypes

Customer_ID     object
Name            object
Age            float64
City            object
Salary         float64
Department      object
Join_Date       object
dtype: object

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Customer_ID'].duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Customer_ID      0
Name           145
Age             87
City           147
Salary         115
Department     169
Join_Date      175
dtype: int64

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,413.0,43.985472,45.828350,-5.0,25.0,31.0,40.0,150.0
Salary,385.0,45301.298701,29505.872003,-1000.0,25000.0,35000.0,70000.0,90000.0

In [16]:
df.describe(include='object').T

            count unique           top freq
Customer_ID   500    500         C1499    1
Name          355      5         Sneha   82
City          353      5     Bangalore   74
Department    331      4       Finance   93
Join_Date     325      4  invalid_date   90

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  500 non-null    object
 1   Name         355 non-null    object
 2   Age          413 non-null    float64
 3   City         353 non-null    object
 4   Salary       385 non-null    float64
 5   Department   331 non-null    object
 6   Join_Date    325 non-null    object
dtypes: float64(2), object(5)
memory usage: 27.5+ KB

In [19]:
for col in df.columns:
    print(df[col].unique()[:10])
    print()

['C1000' 'C1001' 'C1002' 'C1003' 'C1004' 'C1005' 'C1006' 'C1007' 'C1008'
 'C1009']

[nan 'Sneha' 'Karan' 'Rahul' 'Priya' 'Amit']

[ 40.  35.  22.  nan  31.  28.  25. 150.  -5.]

['Bangalore' 'Chennai' 'Pune' nan 'Delhi' 'Mumbai']

[35000.    nan -1000. 90000. 25000. 70000. 50000.]

['IT' 'Sales' nan 'Finance' 'HR']

['2021-01-15' 'invalid_date' nan '2022-05-20' '2023-08-10']

#

In [21]:
df['Name'] = df['Name'].fillna('Unknown')

In [23]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [24]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [25]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [26]:
df['Department'] = df['Department'].fillna('Unknown')

In [27]:
df.isnull().sum()

Customer_ID      0
Name             0
Age              0
City             0
Salary           0
Department       0
Join_Date      175
dtype: int64

In [28]:
df['Join_Date'].head(10)

0      2021-01-15
1    invalid_date
2             NaN
3      2022-05-20
4      2023-08-10
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
Name: Join_Date, dtype: object

In [29]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],format='mixed', errors='coerce')

In [30]:
df['Join_Date'].isnull().sum()

np.int64(265)

In [31]:
df['Join_Date'].fillna(df['Join_Date'].mode()[0], inplace=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_17932\2287839858.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Join_Date'].fillna(df['Join_Date'].mode()[0], inplace=True)

In [32]:
df['Join_Date'].isnull().sum()

np.int64(0)

In [33]:
df.loc[(df['Age']<0)|(df['Age']>110),'Age']= np.nan

In [34]:
df['Age'] = df['Age'].astype('Int64')

In [35]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [36]:
df.loc[df['Salary']< 0,'Salary'] = np.nan

In [37]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [38]:
df['City'].nunique()

5

In [39]:
df['City'].unique()

array(['Bangalore', 'Chennai', 'Pune', 'Delhi', 'Mumbai'], dtype=object)

In [40]:
df['Department'].nunique()

5

In [41]:
df['Department'].unique()

array(['IT', 'Sales', 'Unknown', 'Finance', 'HR'], dtype=object)

In [42]:
df.isnull().sum()

Customer_ID    0
Name           0
Age            0
City           0
Salary         0
Department     0
Join_Date      0
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  500 non-null    object
 1   Name         500 non-null    object
 2   Age          500 non-null    Int64
 3   City         500 non-null    object
 4   Salary       500 non-null    float64
 5   Department   500 non-null    object
 6   Join_Date    500 non-null    datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(1), object(4)
memory usage: 28.0+ KB