#### Windows Function

# Pandas Expanding Function

In [1]:
import pandas as pd

## 1 — Expanding Mean

In [3]:
sales_df = pd.DataFrame({'Sales': [100, 200, 300, 400, 500]})

In [4]:
sales_df

   Sales
0    100
1    200
2    300
3    400
4    500

### 1. Create expanding mean.

In [5]:
sales_df.expanding().mean()

   Sales
0  100.0
1  150.0
2  200.0
3  250.0
4  300.0

### 2. Store result in column Expanding_Mean.

In [6]:
sales_df['Expanding_Mean'] = sales_df['Sales'].expanding().mean()

In [7]:
sales_df

   Sales  Expanding_Mean
0    100           100.0
1    200           150.0
2    300           200.0
3    400           250.0
4    500           300.0

### 3. Find average till each row.

In [8]:
sales_df['Sales'].expanding().mean()

0    100.0
1    150.0
2    200.0
3    250.0
4    300.0
Name: Sales, dtype: float64

### 4. Compare expanding mean with normal mean.

In [14]:
normal_mean = sales_df['Sales'].mean()

In [15]:
normal_mean

np.float64(300.0)

In [16]:
sales_df['Expanding_Mean']

0    100.0
1    150.0
2    200.0
3    250.0
4    300.0
Name: Expanding_Mean, dtype: float64

### 5. Find final cumulative average.

In [17]:
final_avg = sales_df['Expanding_Mean'].iloc[-1]
final_avg

np.float64(300.0)

### 6. Which rows become NaN?

In [29]:
sales_df['Expanding_Mean_2'] = (sales_df['Sales'].expanding(min_periods=2).mean())

In [30]:
sales_df

   Sales  Expanding_Mean  Expanding_Mean_2  Rolling_mean
0    100           100.0               NaN           NaN
1    200           150.0             150.0         150.0
2    300           200.0             200.0         250.0
3    400           250.0             250.0         350.0
4    500           300.0             300.0         450.0

### 7. Create expanding mean using min_periods=3.

In [35]:
sales_df['Sales'].expanding(min_periods=3).mean()

0      NaN
1      NaN
2    200.0
3    250.0
4    300.0
Name: Sales, dtype: float64

### 8. Compare expanding mean vs rolling mean.

In [36]:
sales_df

   Sales  Expanding_Mean  Expanding_Mean_2  Rolling_mean
0    100           100.0               NaN           NaN
1    200           150.0             150.0         150.0
2    300           200.0             200.0         250.0
3    400           250.0             250.0         350.0
4    500           300.0             300.0         450.0

In [37]:
sales_df['Rolling_mean'] = sales_df['Sales'].rolling(2).mean()

In [38]:
sales_df

   Sales  Expanding_Mean  Expanding_Mean_2  Rolling_mean
0    100           100.0               NaN           NaN
1    200           150.0             150.0         150.0
2    300           200.0             200.0         250.0
3    400           250.0             250.0         350.0
4    500           300.0             300.0         450.0

#

#

## 2 — Expanding Sum

In [39]:
orders_df = pd.DataFrame({'Orders': [10, 20, 30, 40, 50]})

In [40]:
orders_df

   Orders
0      10
1      20
2      30
3      40
4      50

### 1.  Create expanding sum.

In [41]:
orders_df.expanding().sum()

   Orders
0    10.0
1    30.0
2    60.0
3   100.0
4   150.0

### 2. Store result in column Running_Total.

In [42]:
orders_df['Running_Total'] = orders_df['Orders'].expanding().sum()

In [44]:
orders_df

   Orders  Running_Total
0      10           10.0
1      20           30.0
2      30           60.0
3      40          100.0
4      50          150.0

### 3. Find cumulative orders till each row.

In [45]:
orders_df['Orders'].expanding().sum()

0     10.0
1     30.0
2     60.0
3    100.0
4    150.0
Name: Orders, dtype: float64

### 4. Find final total orders.

In [48]:
print(orders_df['Running_Total'].iloc[-1])

150.0

### 5. Create expanding sum with min_periods=3.

In [49]:
orders_df['Orders'].expanding(min_periods=3).sum()

0      NaN
1      NaN
2     60.0
3    100.0
4    150.0
Name: Orders, dtype: float64

### 6. Find growth in total orders.

In [50]:
orders_df['Running_Total']

0     10.0
1     30.0
2     60.0
3    100.0
4    150.0
Name: Running_Total, dtype: float64

#

#

## 3 — Expanding Maximum

In [51]:
temp_df = pd.DataFrame({'Temperature': [28, 30, 27, 35, 32, 40]})

In [52]:
temp_df

   Temperature
0           28
1           30
2           27
3           35
4           32
5           40

### 1. Create expanding max.

In [53]:
temp_df.expanding().max

In [54]:
temp_df.expanding().max()

   Temperature
0         28.0
1         30.0
2         30.0
3         35.0
4         35.0
5         40.0

### 2. Track highest temperature till each row.

In [56]:
temp_df.expanding().max()

   Temperature
0         28.0
1         30.0
2         30.0
3         35.0
4         35.0
5         40.0

### 3. Store result in column Highest_Temp.

In [57]:
temp_df['Highest_temp'] = temp_df['Temperature'].expanding().max()

In [58]:
temp_df

   Temperature  Highest_temp
0           28          28.0
1           30          30.0
2           27          30.0
3           35          35.0
4           32          35.0
5           40          40.0

### 4. Find hottest point till current row.

In [61]:
temp_df['Temperature'].expanding().max()

0    28.0
1    30.0
2    30.0
3    35.0
4    35.0
5    40.0
Name: Temperature, dtype: float64

### 5.Compare expanding max vs actual max.

In [62]:
temp_df['Temperature'].max()

40

In [63]:
temp_df['Highest_temp']

0    28.0
1    30.0
2    30.0
3    35.0
4    35.0
5    40.0
Name: Highest_temp, dtype: float64

### 6. Create expanding max with min_periods=2.

In [64]:
temp_df['Temperature'].expanding(min_periods=2).max()

0     NaN
1    30.0
2    30.0
3    35.0
4    35.0
5    40.0
Name: Temperature, dtype: float64

#

#

## 4 — Expanding Minimum

In [65]:
rain_df = pd.DataFrame({'Rainfall': [15, 12, 18, 10, 8, 20]})

In [66]:
rain_df

   Rainfall
0        15
1        12
2        18
3        10
4         8
5        20

### 1. Create expanding min.

In [67]:
rain_df.expanding().min()

   Rainfall
0      15.0
1      12.0
2      12.0
3      10.0
4       8.0
5       8.0

In [72]:
rain_df.expanding(min_periods=2).min()

   Rainfall
0       NaN
1      12.0
2      12.0
3      10.0
4       8.0
5       8.0

In [76]:
rain_df.expanding(min_periods=4).min()

   Rainfall
0       NaN
1       NaN
2       NaN
3      10.0
4       8.0
5       8.0

### 2. Track lowest rainfall till each row.

In [77]:
rain_df.expanding().min()

   Rainfall
0      15.0
1      12.0
2      12.0
3      10.0
4       8.0
5       8.0

### 3. Store result in Lowest_Rainfall.

In [78]:
rain_df['Lowest_rainfall'] = rain_df['Rainfall'].expanding().min()

In [79]:
rain_df

   Rainfall  Lowest_rainfall
0        15             15.0
1        12             12.0
2        18             12.0
3        10             10.0
4         8              8.0
5        20              8.0

### 4. Which rows become NaN?

In [80]:
rain_df.expanding(min_periods=2).min()

   Rainfall  Lowest_rainfall
0       NaN              NaN
1      12.0             12.0
2      12.0             12.0
3      10.0             10.0
4       8.0              8.0
5       8.0              8.0

### 5. Compare expanding min vs actual min.

In [81]:
rain_df['Rainfall'].min()

8

In [82]:
rain_df['Lowest_rainfall']

0    15.0
1    12.0
2    12.0
3    10.0
4     8.0
5     8.0
Name: Lowest_rainfall, dtype: float64

#

#

## 5 — Expanding Standard Deviation

In [83]:
stock_df = pd.DataFrame({'Price': [100, 105, 102, 110, 108, 115]})

In [84]:
stock_df

   Price
0    100
1    105
2    102
3    110
4    108
5    115

### 1. Create expanding std.

In [85]:
stock_df.expanding().std()

      Price
0       NaN
1  3.535534
2  2.516611
3  4.349329
4  4.123106
5  5.501515

In [86]:
stock_df.expanding(min_periods=0).std()

      Price
0       NaN
1  3.535534
2  2.516611
3  4.349329
4  4.123106
5  5.501515

In [87]:
stock_df.expanding(min_periods=1).std()

      Price
0       NaN
1  3.535534
2  2.516611
3  4.349329
4  4.123106
5  5.501515

In [89]:
stock_df.expanding(min_periods=3).std()

      Price
0       NaN
1       NaN
2  2.516611
3  4.349329
4  4.123106
5  5.501515

### 2.Store result in Volatility.

In [97]:
stock_df['Volatility'] = stock_df['Price'].expanding().std()

In [98]:
stock_df

   Price  Volatility
0    100         NaN
1    105    3.535534
2    102    2.516611
3    110    4.349329
4    108    4.123106
5    115    5.501515

### 3.Find periods of high volatility.

In [99]:
high_volatility = stock_df[stock_df['Volatility'] > 4]
high_volatility

   Price  Volatility
3    110    4.349329
4    108    4.123106
5    115    5.501515

### 4.Find periods of low volatility.

In [102]:
low_volatility = stock_df[stock_df['Volatility'] < 4]

In [104]:
low_volatility

   Price  Volatility
1    105    3.535534
2    102    2.516611

### 5. Compare expanding std vs rolling std.

In [105]:
stock_df['Rolling_STD'] = stock_df['Price'].rolling(3).std()
stock_df[['Price', 'Volatility', 'Rolling_STD']]

   Price  Volatility  Rolling_STD
0    100         NaN          NaN
1    105    3.535534          NaN
2    102    2.516611     2.516611
3    110    4.349329     4.041452
4    108    4.123106     4.163332
5    115    5.501515     3.605551

#

#

## 6 — min_periods

In [106]:
marks_df = pd.DataFrame({'Marks': [45, 50, 60, 55, 70]})

In [107]:
marks_df

   Marks
0     45
1     50
2     60
3     55
4     70

### 1. Create expanding mean normally.

In [111]:
marks_df['Expanding_Mean_Normal'] = marks_df['Marks'].expanding().mean()

In [112]:
marks_df

   Marks  Expanding_Mean_Normal
0     45              45.000000
1     50              47.500000
2     60              51.666667
3     55              52.500000
4     70              56.000000

### 2. Use min_periods=1.

In [114]:
marks_df['Mean_Min1'] = marks_df['Marks'].expanding(min_periods=1).mean()

In [115]:
marks_df

   Marks  Expanding_Mean_Normal  Mean_Min1
0     45              45.000000  45.000000
1     50              47.500000  47.500000
2     60              51.666667  51.666667
3     55              52.500000  52.500000
4     70              56.000000  56.000000

### 3. Use min_periods=3.

In [116]:
marks_df['Mean_min2'] = marks_df['Marks'].expanding(min_periods=2).mean()

In [117]:
marks_df

   Marks  Expanding_Mean_Normal  Mean_Min1  Mean_min2
0     45              45.000000  45.000000        NaN
1     50              47.500000  47.500000  47.500000
2     60              51.666667  51.666667  51.666667
3     55              52.500000  52.500000  52.500000
4     70              56.000000  56.000000  56.000000

### 4. Find where calculations begin.

In [128]:
marks_df['Marks'].expanding().mean().first_valid_index()

0

In [129]:
marks_df['Marks'].expanding(min_periods=1).mean().first_valid_index()

0

In [130]:
marks_df['Marks'].expanding(min_periods=2).mean().first_valid_index()

1

In [132]:
marks_df['Marks'].expanding(min_periods=3).mean().first_valid_index()

2

In [133]:
marks_df['Marks'].expanding(min_periods=5).mean().first_valid_index()

4

#

#

## 7 — GroupBy + Expanding

In [134]:
store_df = pd.DataFrame({
    'Store': ['A', 'A', 'A', 'B', 'B', 'B'],
    'Sales': [100, 200, 300, 400, 500, 600]
    })

In [135]:
store_df

  Store  Sales
0     A    100
1     A    200
2     A    300
3     B    400
4     B    500
5     B    600

### 1. Create expanding sum separately for each store.

In [138]:
store_df.groupby('Store')['Sales'].expanding().sum()

Store
A      0     100.0
       1     300.0
       2     600.0
B      3     400.0
       4     900.0
       5    1500.0
Name: Sales, dtype: float64

In [141]:
store_df.groupby('Store')['Sales'].expanding().sum().reset_index()

  Store  level_1   Sales
0     A        0   100.0
1     A        1   300.0
2     A        2   600.0
3     B        3   400.0
4     B        4   900.0
5     B        5  1500.0

### 2. Create expanding mean separately for each store.

In [142]:
store_df.groupby('Store')['Sales'].expanding().mean()

Store
A      0    100.0
       1    150.0
       2    200.0
B      3    400.0
       4    450.0
       5    500.0
Name: Sales, dtype: float64

### 3. Create expanding max separately for each store.

In [143]:
store_df.groupby('Store')['Sales'].expanding().max().reset_index()

  Store  level_1  Sales
0     A        0  100.0
1     A        1  200.0
2     A        2  300.0
3     B        3  400.0
4     B        4  500.0
5     B        5  600.0

### 4. Create expanding min separately for each store.

In [144]:
store_df.groupby('Store')['Sales'].expanding().min()

Store
A      0    100.0
       1    100.0
       2    100.0
B      3    400.0
       4    400.0
       5    400.0
Name: Sales, dtype: float64

In [147]:
store_df.groupby('Store')['Sales'].expanding().min().reset_index()

  Store  level_1  Sales
0     A        0  100.0
1     A        1  100.0
2     A        2  100.0
3     B        3  400.0
4     B        4  400.0
5     B        5  400.0

### 5. Create expanding std separately for each store.

In [148]:
store_df.groupby('Store')['Sales'].expanding().std()

Store
A      0           NaN
       1     70.710678
       2    100.000000
B      3           NaN
       4     70.710678
       5    100.000000
Name: Sales, dtype: float64

### 6. Find best-performing store.

In [157]:
total_sales = store_df.groupby('Store')['Sales'].sum()

best_store = total_sales.idxmax()

print("\nBest Performing Store")
print("Store:", best_store)
print("Total Sales:", total_sales.max())

Best Performing Store
Store: B
Total Sales: 1500

### 7. Use reset_index(level=0, drop=True).

In [158]:
store_df.groupby('Store')['Sales'].expanding().min().reset_index(level=0,drop=True)

0    100.0
1    100.0
2    100.0
3    400.0
4    400.0
5    400.0
Name: Sales, dtype: float64

### 8. Find most stable store.

In [166]:
store_stability = store_df.groupby('Store')['Sales'].std()
stable_store = store_stability.idxmin()
print()
print("Most Stable Store")
print("Store:", stable_store)
print("STD:", store_stability.min())

Most Stable Store
Store: A
STD: 100.0

#

#