# Pandas apply(), map()

In [2]:
import pandas as pd

## 1. map()

In [3]:
df1 = pd.DataFrame({
    "Name": ["Omkar", "Rahul", "Sneha", "Amit", "Pooja"],
    "Gender": ["M", "M", "F", "M", "F"],
    "Marks": [78, 56, 91, 45, 88],
    "City": ["Belgaum", "Delhi", "Mumbai", "Pune", "Bangalore"]
})

print(df1)

    Name Gender  Marks       City
0  Omkar      M     78    Belgaum
1  Rahul      M     56      Delhi
2  Sneha      F     91     Mumbai
3   Amit      M     45       Pune
4  Pooja      F     88  Bangalore

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Gender  5 non-null      object
 2   Marks   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

### 1.Convert Gender: M → Male,  F → Female

In [6]:
 df1.map({'M':'Male', 'F':'Female'})

TypeError: the first argument must be callable

In [7]:
 df1['Gender'].map({'M':'Male', 'F':'Female'})

0      Male
1      Male
2    Female
3      Male
4    Female
Name: Gender, dtype: object

In [10]:
dfc1 = df1.copy()
dfc1['Gender'] =  dfc1['Gender'].map({'M':'Male', 'F':'Female'})

In [11]:
dfc1

    Name  Gender  Marks       City
0  Omkar    Male     78    Belgaum
1  Rahul    Male     56      Delhi
2  Sneha  Female     91     Mumbai
3   Amit    Male     45       Pune
4  Pooja  Female     88  Bangalore

### 2. Convert Marks into grades:
##### 90+ → A
##### 70-89 → B
##### 50-69 → C
##### Below 50 → Fail

In [12]:
df1.columns

Index(['Name', 'Gender', 'Marks', 'City'], dtype='object')

In [14]:
dfc2 = df1.copy()

In [15]:
def grade(x):
    if x >= 90:
        return "A"
    elif x >= 70:
        return "B"
    elif x >= 50:
        return "C"
    else:
        return "Fail"

dfc2["Grade"] = dfc2["Marks"].map(grade)

In [16]:
dfc2

    Name Gender  Marks       City Grade
0  Omkar      M     78    Belgaum     B
1  Rahul      M     56      Delhi     C
2  Sneha      F     91     Mumbai     A
3   Amit      M     45       Pune  Fail
4  Pooja      F     88  Bangalore     B

### 3. Map city names to state names.

In [17]:
city_state = {
    "Belgaum": "Karnataka",
    "Delhi": "Delhi",
    "Mumbai": "Maharashtra",
    "Pune": "Maharashtra",
    "Bangalore": "Karnataka"
}

In [18]:
city_state

{'Belgaum': 'Karnataka',
 'Delhi': 'Delhi',
 'Mumbai': 'Maharashtra',
 'Pune': 'Maharashtra',
 'Bangalore': 'Karnataka'}

In [22]:
dfc3 = dfc2.copy()

In [23]:
dfc3['State'] = dfc3['City'].map(city_state)

In [24]:
dfc3

    Name Gender  Marks       City Grade        State
0  Omkar      M     78    Belgaum     B    Karnataka
1  Rahul      M     56      Delhi     C        Delhi
2  Sneha      F     91     Mumbai     A  Maharashtra
3   Amit      M     45       Pune  Fail  Maharashtra
4  Pooja      F     88  Bangalore     B    Karnataka

### 4. Convert student names into uppercase.

In [25]:
dfc3['Name'] = dfc3['Name'].map(lambda x : x.upper())

In [26]:
dfc3

    Name Gender  Marks       City Grade        State
0  OMKAR      M     78    Belgaum     B    Karnataka
1  RAHUL      M     56      Delhi     C        Delhi
2  SNEHA      F     91     Mumbai     A  Maharashtra
3   AMIT      M     45       Pune  Fail  Maharashtra
4  POOJA      F     88  Bangalore     B    Karnataka

### 5. Convert student names into lowercase.

In [29]:
dfc3['Name'] = dfc3['Name'].map(lambda x : x.lower())

In [30]:
dfc3

    Name Gender  Marks       City Grade        State
0  omkar      M     78    Belgaum     B    Karnataka
1  rahul      M     56      Delhi     C        Delhi
2  sneha      F     91     Mumbai     A  Maharashtra
3   amit      M     45       Pune  Fail  Maharashtra
4  pooja      F     88  Bangalore     B    Karnataka

### 6. Find length of each student name using map().

In [33]:
dfc3['Name_length'] = dfc3['Name'].map(lambda x : len(x))

In [34]:
dfc3

    Name Gender  Marks       City Grade        State  Name_length
0  omkar      M     78    Belgaum     B    Karnataka            5
1  rahul      M     56      Delhi     C        Delhi            5
2  sneha      F     91     Mumbai     A  Maharashtra            5
3   amit      M     45       Pune  Fail  Maharashtra            4
4  pooja      F     88  Bangalore     B    Karnataka            5

In [35]:
dfc3["Name"].map(len)

0    5
1    5
2    5
3    4
4    5
Name: Name, dtype: int64

### 7. Add "Mr./Ms." before each name.

In [36]:
dfc3["Title"] = dfc3["Name"].map(lambda x: "Mr./Ms. " + x)

In [37]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja

### 8. Convert marks into pass/fail: 40+ → Pass, Below 40 → Fail

In [39]:
dfc3['Result'] = dfc3['Marks'].map(lambda x : "Pass" if x >= 40 else  "Fail")

In [40]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title,Result
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar,Pass
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul,Pass
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha,Pass
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit,Pass
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja,Pass

### 9. Add 5 bonus marks to every student using map().

In [41]:
dfc3['Bonus_marks'] = dfc3['Marks'].map(lambda x : x+5)

In [42]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title,Result,Bonus_marks
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar,Pass,83
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul,Pass,61
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha,Pass,96
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit,Pass,50
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja,Pass,93

### 10. Convert city names into short codes:
##### Bangalore → BLR
##### Mumbai → MUM
##### Delhi → DEL

In [43]:
codes = {
    "Bangalore": "BLR",
    "Mumbai": "MUM",
    "Delhi": "DEL",
    "Belgaum": "BGM",
    "Pune": "PUN"
}

In [44]:
dfc3['City_code'] = dfc3['City'].map(codes)

In [45]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title,Result,Bonus_marks,City_code
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar,Pass,83,BGM
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul,Pass,61,DEL
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha,Pass,96,MUM
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit,Pass,50,PUN
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja,Pass,93,BLR

### 11. Replace missing city values with "Unknown" using map().

In [46]:
dfc3["City"] = dfc3["City"].map(lambda x: "Unknown" if pd.isna(x) else x)

In [48]:
dfc3.isna().any().any()

np.False_

### 12. Convert all marks into strings.

In [50]:
dfc3["Marks_String"] = dfc3["Marks"].map(lambda  x : str(x))

In [51]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title,Result,Bonus_marks,City_code,Marks_String
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar,Pass,83,BGM,78
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul,Pass,61,DEL,56
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha,Pass,96,MUM,91
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit,Pass,50,PUN,45
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja,Pass,93,BLR,88

In [53]:
dfc3["Marks"].map(str)

0    78
1    56
2    91
3    45
4    88
Name: Marks, dtype: object

In [54]:
dfc3.dtypes

Name            object
Gender          object
Marks            int64
City            object
Grade           object
State           object
Name_length      int64
Title           object
Result          object
Bonus_marks      int64
City_code       object
Marks_String    object
dtype: object

### 13. Map even/odd labels to marks.

In [55]:
dfc3["Even_Odd"] = dfc3["Marks"].map(lambda x: "Even" if x % 2 == 0 else "Odd")

In [56]:
dfc3

,Name,Gender,Marks,City,Grade,State,Name_length,Title,Result,Bonus_marks,City_code,Marks_String,Even_Odd
0,omkar,M,78,Belgaum,B,Karnataka,5,Mr./Ms. omkar,Pass,83,BGM,78,Even
1,rahul,M,56,Delhi,C,Delhi,5,Mr./Ms. rahul,Pass,61,DEL,56,Even
2,sneha,F,91,Mumbai,A,Maharashtra,5,Mr./Ms. sneha,Pass,96,MUM,91,Odd
3,amit,M,45,Pune,Fail,Maharashtra,4,Mr./Ms. amit,Pass,50,PUN,45,Odd
4,pooja,F,88,Bangalore,B,Karnataka,5,Mr./Ms. pooja,Pass,93,BLR,88,Even

### 14. Create a new column:

High if marks > 75
Low otherwise

In [59]:
dfc3["Performance"] = dfc3["Marks"].map(lambda x: "High" if x > 75 else "Low")
print(dfc3)

    Name Gender  Marks       City Grade        State  Name_length  \
0  omkar      M     78    Belgaum     B    Karnataka            5
1  rahul      M     56      Delhi     C        Delhi            5
2  sneha      F     91     Mumbai     A  Maharashtra            5
3   amit      M     45       Pune  Fail  Maharashtra            4
4  pooja      F     88  Bangalore     B    Karnataka            5

           Title Result  Bonus_marks City_code Marks_String Even_Odd  \
0  Mr./Ms. omkar   Pass           83       BGM           78     Even
1  Mr./Ms. rahul   Pass           61       DEL           56     Even
2  Mr./Ms. sneha   Pass           96       MUM           91      Odd
3   Mr./Ms. amit   Pass           50       PUN           45      Odd
4  Mr./Ms. pooja   Pass           93       BLR           88     Even

  Performance
0        High
1         Low
2        High
3         Low
4        High

In [60]:
dfc4 = df1.copy()

In [61]:
dfc4["Performance"] = dfc4["Marks"].map(lambda x: "High" if x > 75 else "Low")
dfc4

    Name Gender  Marks       City Performance
0  Omkar      M     78    Belgaum        High
1  Rahul      M     56      Delhi         Low
2  Sneha      F     91     Mumbai        High
3   Amit      M     45       Pune         Low
4  Pooja      F     88  Bangalore        High

### 15. Map first letter of each name.

In [62]:
dfc4["First_Letter"] = dfc4["Name"].map(lambda x: x[0])
dfc4

    Name Gender  Marks       City Performance First_Letter
0  Omkar      M     78    Belgaum        High            O
1  Rahul      M     56      Delhi         Low            R
2  Sneha      F     91     Mumbai        High            S
3   Amit      M     45       Pune         Low            A
4  Pooja      F     88  Bangalore        High            P

### 16. Convert marks into percentages:

Example: 78 → "78%"

In [63]:
dfc4["Percentage"] = dfc4["Marks"].map(lambda x: str(x) + "%")

In [64]:
dfc4

    Name Gender  Marks       City Performance First_Letter Percentage
0  Omkar      M     78    Belgaum        High            O        78%
1  Rahul      M     56      Delhi         Low            R        56%
2  Sneha      F     91     Mumbai        High            S        91%
3   Amit      M     45       Pune         Low            A        45%
4  Pooja      F     88  Bangalore        High            P        88%

### 17. Map vowels count in each student name.

In [65]:
def vowels_count(name):
    vowels = "aeiouAEIOU"
    return sum(1 for ch in name if ch in vowels)

In [66]:
dfc4["Vowel_Count"] = dfc4["Name"].map(vowels_count)

In [67]:
dfc4

,Name,Gender,Marks,City,Performance,First_Letter,Percentage,Vowel_Count
0,Omkar,M,78,Belgaum,High,O,78%,2
1,Rahul,M,56,Delhi,Low,R,56%,2
2,Sneha,F,91,Mumbai,High,S,91%,2
3,Amit,M,45,Pune,Low,A,45%,2
4,Pooja,F,88,Bangalore,High,P,88%,3

### 18. Convert city names into title case.

In [68]:
dfc4["City_Title"] = dfc4["City"].map(str.title)

In [69]:
dfc4

,Name,Gender,Marks,City,Performance,First_Letter,Percentage,Vowel_Count,City_Title
0,Omkar,M,78,Belgaum,High,O,78%,2,Belgaum
1,Rahul,M,56,Delhi,Low,R,56%,2,Delhi
2,Sneha,F,91,Mumbai,High,S,91%,2,Mumbai
3,Amit,M,45,Pune,Low,A,45%,2,Pune
4,Pooja,F,88,Bangalore,High,P,88%,3,Bangalore

### 19. Map whether student is eligible for scholarship:

Marks ≥ 85 → Yes
Else → No

In [71]:
dfc4["Scholarship"] = dfc4["Marks"].map(lambda x: "Yes" if x >= 85 else "No")

In [72]:
dfc4

,Name,Gender,Marks,City,Performance,First_Letter,Percentage,Vowel_Count,City_Title,Scholarship
0,Omkar,M,78,Belgaum,High,O,78%,2,Belgaum,No
1,Rahul,M,56,Delhi,Low,R,56%,2,Delhi,No
2,Sneha,F,91,Mumbai,High,S,91%,2,Mumbai,Yes
3,Amit,M,45,Pune,Low,A,45%,2,Pune,No
4,Pooja,F,88,Bangalore,High,P,88%,3,Bangalore,Yes

### 20. Replace specific marks:

45 → 50
56 → 60

In [73]:
dfc4["Updated_Marks"] = dfc4["Marks"].map({78: 78, 56: 60, 91: 91, 45: 50, 88: 88})

In [74]:
dfc4

,Name,Gender,Marks,City,Performance,First_Letter,Percentage,Vowel_Count,City_Title,Scholarship,Updated_Marks
0,Omkar,M,78,Belgaum,High,O,78%,2,Belgaum,No,78
1,Rahul,M,56,Delhi,Low,R,56%,2,Delhi,No,60
2,Sneha,F,91,Mumbai,High,S,91%,2,Mumbai,Yes,91
3,Amit,M,45,Pune,Low,A,45%,2,Pune,No,50
4,Pooja,F,88,Bangalore,High,P,88%,3,Bangalore,Yes,88

#

#

## 2. apply()

In [75]:
df2 = pd.DataFrame({
    "Math": [78, 56, 90, 45, 88],
    "Science": [67, 72, 95, 40, 91],
    "English": [80, 60, 89, 50, 85]
})
df2

   Math  Science  English
0    78       67       80
1    56       72       60
2    90       95       89
3    45       40       50
4    88       91       85

In [77]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     5 non-null      int64
 1   Science  5 non-null      int64
 2   English  5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [78]:
marks_df = df2.copy()

### 1. Find total marks row-wise using apply().

In [80]:
marks_df["Total"] = marks_df.apply(sum, axis=1)

In [81]:
marks_df

   Math  Science  English  Total
0    78       67       80    225
1    56       72       60    188
2    90       95       89    274
3    45       40       50    135
4    88       91       85    264

### 2. Find average marks row-wise.

In [83]:
marks_df["Avg"] = marks_df.apply(mean, axis=1)

NameError: name 'mean' is not defined

In [84]:
marks_df["Avg"] = marks_df[["Math", "Science", "English"]].apply(lambda row: row.mean(), axis=1)

In [85]:
marks_df

   Math  Science  English  Total        Avg
0    78       67       80    225  75.000000
1    56       72       60    188  62.666667
2    90       95       89    274  91.333333
3    45       40       50    135  45.000000
4    88       91       85    264  88.000000

### 3. Find maximum marks from each row.

In [87]:
marks_df["Maximum"] = marks_df.apply(max, axis=1)

In [88]:
marks_df

   Math  Science  English  Total        Avg  Maximum
0    78       67       80    225  75.000000    225.0
1    56       72       60    188  62.666667    188.0
2    90       95       89    274  91.333333    274.0
3    45       40       50    135  45.000000    135.0
4    88       91       85    264  88.000000    264.0

In [89]:
marks_df["Maximum"] = marks_df[["Math", "Science", "English"]].apply(max, axis=1)

In [90]:
marks_df

   Math  Science  English  Total        Avg  Maximum
0    78       67       80    225  75.000000       80
1    56       72       60    188  62.666667       72
2    90       95       89    274  91.333333       95
3    45       40       50    135  45.000000       50
4    88       91       85    264  88.000000       91

### 4. Find minimum marks from each row.

In [92]:
marks_df["Minimum"] = marks_df[["Math", "Science", "English"]].apply(min, axis=1)

In [93]:
marks_df

   Math  Science  English  Total        Avg  Maximum  Minimum
0    78       67       80    225  75.000000       80       67
1    56       72       60    188  62.666667       72       56
2    90       95       89    274  91.333333       95       89
3    45       40       50    135  45.000000       50       40
4    88       91       85    264  88.000000       91       85

### 5. Find total marks subject-wise.

In [94]:
marks_df.apply(sum, axis=0)

Math        357.0
Science     365.0
English     364.0
Total      1086.0
Avg         362.0
Maximum     388.0
Minimum     337.0
dtype: float64

In [95]:
marks_df[["Math", "Science", "English"]].apply(sum, axis=0)

Math       357
Science    365
English    364
dtype: int64

### 6. Find average marks subject-wise.

In [97]:
marks_df.apply(lambda col: col.mean(), axis=0)

Math        71.4
Science     73.0
English     72.8
Total      217.2
Avg         72.4
Maximum     77.6
Minimum     67.4
dtype: float64

### 7. Add 10 grace marks to all subjects using apply().

In [98]:
updated = marks_df[["Math", "Science", "English"]].apply(lambda x: x + 10)

In [99]:
updated

   Math  Science  English
0    88       77       90
1    66       82       70
2   100      105       99
3    55       50       60
4    98      101       95

### 8. Convert all marks into grades using custom function.

In [100]:
def convert_grade(x):
    if x >= 90:
        return "A"
    elif x >= 70:
        return "B"
    elif x >= 50:
        return "C"
    else:
        return "Fail"

In [102]:
marks_df['Grades']  = marks_df[["Math", "Science", "English"]].apply(lambda col: col.map(convert_grade))

ValueError: Cannot set a DataFrame with multiple columns to the single column Grades

In [104]:
grades = marks_df[["Math", "Science", "English"]].apply(lambda col: col.map(convert_grade))
grades

   Math Science English
0     B       C       B
1     C       B       C
2     A       A       B
3  Fail    Fail       C
4     B       A       B

### 9. Check whether each student passed:

All subjects ≥ 35

In [119]:
marks_df.dtypes

Math             int64
Science          int64
English          int64
Total            int64
Avg            float64
Maximum          int64
Minimum          int64
Pass_Status     object
Result          object
dtype: object

In [121]:
marks_df[['Math','Science','English']].apply(lambda row: "Pass" if all(row >= 35) else "Fail",axis=1)

0    Pass
1    Pass
2    Pass
3    Pass
4    Pass
dtype: object

### 10. Create result column:

Distinction → average > 75
Pass → otherwise

In [122]:
marks_df["Result"] = marks_df.apply(lambda row: "Distinction" if row[["Math", "Science", "English"]].mean() > 75 else "Pass",axis=1)

In [123]:
marks_df

,Math,Science,English,Total,Avg,Maximum,Minimum,Pass_Status,Result
0,78,67,80,225,75.000000,80,67,Pass,Pass
1,56,72,60,188,62.666667,72,56,Pass,Pass
2,90,95,89,274,91.333333,95,89,Pass,Distinction
3,45,40,50,135,45.000000,50,40,Pass,Pass
4,88,91,85,264,88.000000,91,85,Pass,Distinction

### 11. Find range:

max - min for each row

In [126]:
marks_df["Range"] = marks_df[["Math", "Science", "English"]].apply(lambda row: row.max() - row.min(),axis=1)

In [127]:
marks_df

,Math,Science,English,Total,Avg,Maximum,Minimum,Pass_Status,Result,Range
0,78,67,80,225,75.000000,80,67,Pass,Pass,13
1,56,72,60,188,62.666667,72,56,Pass,Pass,16
2,90,95,89,274,91.333333,95,89,Pass,Distinction,6
3,45,40,50,135,45.000000,50,40,Pass,Pass,10
4,88,91,85,264,88.000000,91,85,Pass,Distinction,6

### 12. Convert marks into percentages.

In [128]:
 marks_df[["Math", "Science", "English"]].apply(lambda col: col.map(lambda x: str(x) + "%"))

  Math Science English
0  78%     67%     80%
1  56%     72%     60%
2  90%     95%     89%
3  45%     40%     50%
4  88%     91%     85%

### 13. Round all marks to nearest multiple of 10.

In [129]:
marks_df[["Math", "Science", "English"]].apply(lambda col: round(col / 10) * 10)

   Math  Science  English
0  80.0     70.0     80.0
1  60.0     70.0     60.0
2  90.0    100.0     90.0
3  40.0     40.0     50.0
4  90.0     90.0     80.0

### 14. Multiply all marks by 2 using apply().

In [131]:
marks_df[["Math", "Science", "English"]].apply(lambda col: col * 2)

   Math  Science  English
0   156      134      160
1   112      144      120
2   180      190      178
3    90       80      100
4   176      182      170

### 15. Count subjects where marks > 70 for each student.

In [145]:
marks_df["Any_Fail"] = marks_df[["Math", "Science", "English"]].apply( lambda row: any(row < 35),axis=1)

In [135]:
marks_df

,Math,Science,English,Total,Avg,Maximum,Minimum,Pass_Status,Result,Range,Any_Fail
0,78,67,80,225,75.000000,80,67,Pass,Pass,13,False
1,56,72,60,188,62.666667,72,56,Pass,Pass,16,False
2,90,95,89,274,91.333333,95,89,Pass,Distinction,6,False
3,45,40,50,135,45.000000,50,40,Pass,Pass,10,False
4,88,91,85,264,88.000000,91,85,Pass,Distinction,6,False

### 16. Find whether row contains any failing marks.

In [148]:
marks_df[["Math", "Science", "English"]].apply(lambda row: any(row < 35), axis=1)

0    False
1    False
2    False
3    False
4    False
dtype: bool

### 17. Convert numeric marks into strings:

Example: "78 Marks"

In [150]:
marks_df[["Math", "Science", "English"]].apply(lambda mark : str(mark) + " Marks")

Math       0    78\n1    56\n2    90\n3    45\n4    88\nN...
Science    0    67\n1    72\n2    95\n3    40\n4    91\nN...
English    0    80\n1    60\n2    89\n3    50\n4    85\nN...
dtype: object

In [151]:
marks_df[['Math', 'Science', 'English']].apply(lambda col: col.map(lambda mark: str(mark) + " Marks"))

       Math   Science   English
0  78 Marks  67 Marks  80 Marks
1  56 Marks  72 Marks  60 Marks
2  90 Marks  95 Marks  89 Marks
3  45 Marks  40 Marks  50 Marks
4  88 Marks  91 Marks  85 Marks

### 18. Create custom performance labels:

Excellent
Good
Average
Poor

In [152]:
def performance(avg):
    if avg >= 85:
        return "Excellent"
    elif avg >= 70:
        return "Good"
    elif avg >= 50:
        return "Average"
    else:
        return "Poor"

marks_df["Performance"] = marks_df[["Math", "Science", "English"]].apply(lambda row: performance(row.mean()),axis=1)

print(marks_df)

   Math  Science  English  Total        Avg  Maximum  Minimum Pass_Status  \
0    78       67       80    225  75.000000       80       67        Pass
1    56       72       60    188  62.666667       72       56        Pass
2    90       95       89    274  91.333333       95       89        Pass
3    45       40       50    135  45.000000       50       40        Pass
4    88       91       85    264  88.000000       91       85        Pass

        Result  Range  Any_Fail Performance Top_Subject  Math_English_Diff
0         Pass     13     False        Good     English                 -2
1         Pass     16     False     Average     Science                 -4
2  Distinction      6     False   Excellent     Science                  1
3         Pass     10     False        Poor     English                 -5
4  Distinction      6     False   Excellent     Science                  3

### 19. Find topper subject for each student.

In [155]:
marks_df["Top_Subject"] = marks_df[["Math", "Science", "English"]].apply(lambda row: row.idxmax(), axis=1)

print(marks_df)

   Math  Science  English  Total        Avg  Maximum  Minimum Pass_Status  \
0    78       67       80    225  75.000000       80       67        Pass
1    56       72       60    188  62.666667       72       56        Pass
2    90       95       89    274  91.333333       95       89        Pass
3    45       40       50    135  45.000000       50       40        Pass
4    88       91       85    264  88.000000       91       85        Pass

        Result  Range  Any_Fail Performance Top_Subject  Math_English_Diff
0         Pass     13     False        Good     English                 -2
1         Pass     16     False     Average     Science                 -4
2  Distinction      6     False   Excellent     Science                  1
3         Pass     10     False        Poor     English                 -5
4  Distinction      6     False   Excellent     Science                  3

### 20. Find difference between Math and English marks.

In [156]:
marks_df["Math_English_Diff"] = marks_df.apply(lambda row: row["Math"] - row["English"],axis=1)
print(marks_df)

   Math  Science  English  Total        Avg  Maximum  Minimum Pass_Status  \
0    78       67       80    225  75.000000       80       67        Pass
1    56       72       60    188  62.666667       72       56        Pass
2    90       95       89    274  91.333333       95       89        Pass
3    45       40       50    135  45.000000       50       40        Pass
4    88       91       85    264  88.000000       91       85        Pass

        Result  Range  Any_Fail Performance Top_Subject  Math_English_Diff
0         Pass     13     False        Good     English                 -2
1         Pass     16     False     Average     Science                 -4
2  Distinction      6     False   Excellent     Science                  1
3         Pass     10     False        Poor     English                 -5
4  Distinction      6     False   Excellent     Science                  3