# Pandas Merging & Joining

In [2]:
import pandas as pd

#  #Pandas merge()

In [2]:
customers = pd.DataFrame({
    'customer_id': [101,102,103,104,105,106,107,108,109,110],
    'customer_name': ['Omkar','Rahul','Sneha','Amit','Pooja','Kiran','Neha','Vijay','Anjali','Rohit'],
    'city': ['Delhi','Mumbai','Pune','Delhi','Bangalore', 'Pune','Mumbai','Delhi','Hyderabad','Chennai'],
    'age': [22,25,24,30,27,29,23,31,26,28]
})

In [3]:
customers.head()

   customer_id customer_name       city  age
0          101         Omkar      Delhi   22
1          102         Rahul     Mumbai   25
2          103         Sneha       Pune   24
3          104          Amit      Delhi   30
4          105         Pooja  Bangalore   27

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    10 non-null     int64
 1   customer_name  10 non-null     object
 2   city           10 non-null     object
 3   age            10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

#

In [5]:
orders = pd.DataFrame({
    'order_id': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011 ],
    'customer_id': [101,102,102,104,105,108,101,111,109,105,120],
    'product': ['Laptop','Phone','Keyboard','Mouse','Tablet','Monitor','Printer','Camera','Phone','Laptop','TV'],
    'amount': [55000,20000,3000,1500,25000,12000,8000,45000,22000,60000,70000]
})

In [6]:
orders.head()

   order_id  customer_id   product  amount
0      1001          101    Laptop   55000
1      1002          102     Phone   20000
2      1003          102  Keyboard    3000
3      1004          104     Mouse    1500
4      1005          105    Tablet   25000

In [7]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     11 non-null     int64
 1   customer_id  11 non-null     int64
 2   product      11 non-null     object
 3   amount       11 non-null     int64
dtypes: int64(3), object(1)
memory usage: 484.0+ bytes

#

### 1. Merge customers and orders using customer_id.
(Create customer order report.)

In [9]:
pd.merge(customers,orders,on = 'customer_id')

   customer_id customer_name       city  age  order_id   product  amount
0          101         Omkar      Delhi   22      1001    Laptop   55000
1          101         Omkar      Delhi   22      1007   Printer    8000
2          102         Rahul     Mumbai   25      1002     Phone   20000
3          102         Rahul     Mumbai   25      1003  Keyboard    3000
4          104          Amit      Delhi   30      1004     Mouse    1500
5          105         Pooja  Bangalore   27      1005    Tablet   25000
6          105         Pooja  Bangalore   27      1010    Laptop   60000
7          108         Vijay      Delhi   31      1006   Monitor   12000
8          109        Anjali  Hyderabad   26      1009     Phone   22000

### 2.Perform INNER JOIN between customers and orders.
Question: Which customers actually placed orders?

In [10]:
pd.merge(customers, orders, on='customer_id', how='inner')

   customer_id customer_name       city  age  order_id   product  amount
0          101         Omkar      Delhi   22      1001    Laptop   55000
1          101         Omkar      Delhi   22      1007   Printer    8000
2          102         Rahul     Mumbai   25      1002     Phone   20000
3          102         Rahul     Mumbai   25      1003  Keyboard    3000
4          104          Amit      Delhi   30      1004     Mouse    1500
5          105         Pooja  Bangalore   27      1005    Tablet   25000
6          105         Pooja  Bangalore   27      1010    Laptop   60000
7          108         Vijay      Delhi   31      1006   Monitor   12000
8          109        Anjali  Hyderabad   26      1009     Phone   22000

### 3.Perform LEFT JOIN.
Question: Show all customers even if they never ordered.

In [11]:
pd.merge(customers, orders, on='customer_id', how='left')

    customer_id customer_name       city  age  order_id   product   amount
0           101         Omkar      Delhi   22    1001.0    Laptop  55000.0
1           101         Omkar      Delhi   22    1007.0   Printer   8000.0
2           102         Rahul     Mumbai   25    1002.0     Phone  20000.0
3           102         Rahul     Mumbai   25    1003.0  Keyboard   3000.0
4           103         Sneha       Pune   24       NaN       NaN      NaN
5           104          Amit      Delhi   30    1004.0     Mouse   1500.0
6           105         Pooja  Bangalore   27    1005.0    Tablet  25000.0
7           105         Pooja  Bangalore   27    1010.0    Laptop  60000.0
8           106         Kiran       Pune   29       NaN       NaN      NaN
9           107          Neha     Mumbai   23       NaN       NaN      NaN
10          108         Vijay      Delhi   31    1006.0   Monitor  12000.0
11          109        Anjali  Hyderabad   26    1009.0     Phone  22000.0
12          110         Rohit    Chennai   28       NaN       NaN      NaN

### 4 . Perform RIGHT JOIN.
Question:  Show all orders even if customer information is missing.

In [12]:
pd.merge(customers, orders, on='customer_id', how='right')

    customer_id customer_name       city   age  order_id   product  amount
0           101         Omkar      Delhi  22.0      1001    Laptop   55000
1           102         Rahul     Mumbai  25.0      1002     Phone   20000
2           102         Rahul     Mumbai  25.0      1003  Keyboard    3000
3           104          Amit      Delhi  30.0      1004     Mouse    1500
4           105         Pooja  Bangalore  27.0      1005    Tablet   25000
5           108         Vijay      Delhi  31.0      1006   Monitor   12000
6           101         Omkar      Delhi  22.0      1007   Printer    8000
7           111           NaN        NaN   NaN      1008    Camera   45000
8           109        Anjali  Hyderabad  26.0      1009     Phone   22000
9           105         Pooja  Bangalore  27.0      1010    Laptop   60000
10          120           NaN        NaN   NaN      1011        TV   70000

### 5 . Perform FULL OUTER JOIN.
Question: Show every customer and every order.

In [13]:
pd.merge(customers,orders,how = 'outer', on='customer_id')

    customer_id customer_name       city   age  order_id   product   amount
0           101         Omkar      Delhi  22.0    1001.0    Laptop  55000.0
1           101         Omkar      Delhi  22.0    1007.0   Printer   8000.0
2           102         Rahul     Mumbai  25.0    1002.0     Phone  20000.0
3           102         Rahul     Mumbai  25.0    1003.0  Keyboard   3000.0
4           103         Sneha       Pune  24.0       NaN       NaN      NaN
5           104          Amit      Delhi  30.0    1004.0     Mouse   1500.0
6           105         Pooja  Bangalore  27.0    1005.0    Tablet  25000.0
7           105         Pooja  Bangalore  27.0    1010.0    Laptop  60000.0
8           106         Kiran       Pune  29.0       NaN       NaN      NaN
9           107          Neha     Mumbai  23.0       NaN       NaN      NaN
10          108         Vijay      Delhi  31.0    1006.0   Monitor  12000.0
11          109        Anjali  Hyderabad  26.0    1009.0     Phone  22000.0
12          110         Rohit    Chennai  28.0       NaN       NaN      NaN
13          111           NaN        NaN   NaN    1008.0    Camera  45000.0
14          120           NaN        NaN   NaN    1011.0        TV  70000.0

#

### 6.Find customers who never placed orders.

In [14]:
merge_data = pd.merge(customers,orders,on='customer_id',how='left')
merge_data[merge_data['order_id'].isna()]

    customer_id customer_name     city  age  order_id product  amount
4           103         Sneha     Pune   24       NaN     NaN     NaN
8           106         Kiran     Pune   29       NaN     NaN     NaN
9           107          Neha   Mumbai   23       NaN     NaN     NaN
12          110         Rohit  Chennai   28       NaN     NaN     NaN

#

### 7.Find orders having invalid customer IDs.

In [15]:
merge_data = pd.merge(customers, orders, on='customer_id', how='right')
merge_data[merge_data['customer_name'].isna()]

    customer_id customer_name city  age  order_id product  amount
7           111           NaN  NaN  NaN      1008  Camera   45000
10          120           NaN  NaN  NaN      1011      TV   70000

#

### 8. Find customers from Delhi who placed orders.

In [16]:
merged = pd.merge(customers, orders, on='customer_id')
merged[merged['city'] == 'Delhi']

   customer_id customer_name   city  age  order_id  product  amount
0          101         Omkar  Delhi   22      1001   Laptop   55000
1          101         Omkar  Delhi   22      1007  Printer    8000
4          104          Amit  Delhi   30      1004    Mouse    1500
7          108         Vijay  Delhi   31      1006  Monitor   12000

#

### 9. Find customers who ordered Laptop.

In [17]:
merged = pd.merge(customers, orders, on='customer_id')
merged[merged['product'] == 'Laptop']

   customer_id customer_name       city  age  order_id product  amount
0          101         Omkar      Delhi   22      1001  Laptop   55000
6          105         Pooja  Bangalore   27      1010  Laptop   60000

#

### 10 . Find total orders placed by each customer.(merge + groupby)

In [20]:
group_data = pd.merge(customers,orders,on='customer_id')
group_data.groupby('customer_id')['order_id'].count()

customer_id
101    2
102    2
104    1
105    2
108    1
109    1
Name: order_id, dtype: int64

In [21]:
group_data= pd.merge(customers, orders,on='customer_id')
group_data.groupby('customer_name')['order_id'].count()

customer_name
Amit      1
Anjali    1
Omkar     2
Pooja     2
Rahul     2
Vijay     1
Name: order_id, dtype: int64

#

### 11. Find top spending customers.

In [22]:
group_data.groupby('customer_id')['amount'].sum()

customer_id
101    63000
102    23000
104     1500
105    85000
108    12000
109    22000
Name: amount, dtype: int64

In [23]:
group_data.groupby('customer_name')['amount'].sum().sort_values(ascending=False)

customer_name
Pooja     85000
Omkar     63000
Rahul     23000
Anjali    22000
Vijay     12000
Amit       1500
Name: amount, dtype: int64

#

### 12. Find customers whose order amount > 30000.

In [24]:
merged = pd.merge(customers, orders, on='customer_id')
merged[merged['amount'] > 30000]

   customer_id customer_name       city  age  order_id product  amount
0          101         Omkar      Delhi   22      1001  Laptop   55000
6          105         Pooja  Bangalore   27      1010  Laptop   60000

#

### 13. Find customers with multiple orders.

In [25]:
merged.groupby('customer_name')['order_id'].count().loc[lambda x: x > 1]

customer_name
Omkar    2
Pooja    2
Rahul    2
Name: order_id, dtype: int64

#

### 14. Find average order amount city-wise.

In [26]:
group_data

   customer_id customer_name       city  age  order_id   product  amount
0          101         Omkar      Delhi   22      1001    Laptop   55000
1          101         Omkar      Delhi   22      1007   Printer    8000
2          102         Rahul     Mumbai   25      1002     Phone   20000
3          102         Rahul     Mumbai   25      1003  Keyboard    3000
4          104          Amit      Delhi   30      1004     Mouse    1500
5          105         Pooja  Bangalore   27      1005    Tablet   25000
6          105         Pooja  Bangalore   27      1010    Laptop   60000
7          108         Vijay      Delhi   31      1006   Monitor   12000
8          109        Anjali  Hyderabad   26      1009     Phone   22000

In [27]:
group_data.groupby('city')['amount'].mean()

city
Bangalore    42500.0
Delhi        19125.0
Hyderabad    22000.0
Mumbai       11500.0
Name: amount, dtype: float64

#

### 15 . Find which city generated highest revenue.

In [28]:
group_data.groupby('city')['amount'].sum().sort_values(ascending=False).head(2)

city
Bangalore    85000
Delhi        76500
Name: amount, dtype: int64

#

### 16. Merge orders and payments using order_id.

In [29]:
payments = pd.DataFrame({
    'payment_id': [1,2,3,4,5,6,7,8],
    'order_id': [1001,1002,1003,1005,1006,1007,1012,1010],
    'payment_method': ['UPI','Card','Cash','UPI','NetBanking','Card','Cash','UPI' ],
    'payment_status': ['Success','Success','Failed','Success','Success','Pending','Success','Success' ]
})

In [30]:
payments

   payment_id  order_id payment_method payment_status
0           1      1001            UPI        Success
1           2      1002           Card        Success
2           3      1003           Cash         Failed
3           4      1005            UPI        Success
4           5      1006     NetBanking        Success
5           6      1007           Card        Pending
6           7      1012           Cash        Success
7           8      1010            UPI        Success

In [31]:
merge_PO = pd.merge(orders,payments,on='order_id')

In [32]:
merge_PO

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
0,1001,101,Laptop,55000,1,UPI,Success
1,1002,102,Phone,20000,2,Card,Success
2,1003,102,Keyboard,3000,3,Cash,Failed
3,1005,105,Tablet,25000,4,UPI,Success
4,1006,108,Monitor,12000,5,NetBanking,Success
5,1007,101,Printer,8000,6,Card,Pending
6,1010,105,Laptop,60000,8,UPI,Success

#### Q. Find orders without payment details.

In [33]:
merged = pd.merge(orders, payments, on='order_id', how='left')

merged[merged['payment_id'].isna()]

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
3,1004,104,Mouse,1500,NaN,NaN,NaN
7,1008,111,Camera,45000,NaN,NaN,NaN
8,1009,109,Phone,22000,NaN,NaN,NaN
10,1011,120,TV,70000,NaN,NaN,NaN

#### Q. Find successful payments only.

In [34]:
merge_PO[merge_PO['payment_status'] == 'Success']

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
0,1001,101,Laptop,55000,1,UPI,Success
1,1002,102,Phone,20000,2,Card,Success
3,1005,105,Tablet,25000,4,UPI,Success
4,1006,108,Monitor,12000,5,NetBanking,Success
6,1010,105,Laptop,60000,8,UPI,Success

#### Q. Find failed payments.

In [38]:
merge_PO[merge_PO['payment_status'] == 'Failed']

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
2,1003,102,Keyboard,3000,3,Cash,Failed

#### Q. Find orders paid using UPI.

In [41]:
merge_PO[merge_PO['payment_method']=='UPI']

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
0,1001,101,Laptop,55000,1,UPI,Success
3,1005,105,Tablet,25000,4,UPI,Success
6,1010,105,Laptop,60000,8,UPI,Success

#### Q. Find total successful payment amount.

In [42]:
merge_PO[merge_PO['payment_status'] == 'Success']['amount'].sum()

np.int64(172000)

#### Q. Find payment method used most frequently.

In [43]:
merge_PO['payment_method'].value_counts()

payment_method
UPI           3
Card          2
Cash          1
NetBanking    1
Name: count, dtype: int64

#

#

### 17.  Merge orders and returns.

In [44]:
returns = pd.DataFrame({
    'return_id': [201,202,203],
    'order_id': [1003,1005,1015],
    'return_reason': ['Damaged','Wrong Item','Late Delivery']})

In [45]:
returns

   return_id  order_id  return_reason
0        201      1003        Damaged
1        202      1005     Wrong Item
2        203      1015  Late Delivery

In [47]:
orders.head(2)

   order_id  customer_id product  amount
0      1001          101  Laptop   55000
1      1002          102   Phone   20000

In [61]:
merge_Ord_ret = pd.merge(orders,returns,on='order_id',how='right')

In [62]:
merge_Ord_ret

   order_id  customer_id   product   amount  return_id  return_reason
0      1003        102.0  Keyboard   3000.0        201        Damaged
1      1005        105.0    Tablet  25000.0        202     Wrong Item
2      1015          NaN       NaN      NaN        203  Late Delivery

#### Q. Find returned products.

In [63]:
merge_Ord_ret[['product', 'return_reason']]

    product  return_reason
0  Keyboard        Damaged
1    Tablet     Wrong Item
2       NaN  Late Delivery

#### Q. Find total loss due to returned orders.

In [64]:
merge_Ord_ret['amount'].sum()

np.float64(28000.0)

#### Q.Find products returned because of "Damaged".

In [66]:
merge_Ord_ret[merge_Ord_ret[ 'return_reason']=='Damaged']

   order_id  customer_id   product  amount  return_id return_reason
0      1003        102.0  Keyboard  3000.0        201       Damaged

#### Q. Find customers who returned products.

In [71]:
merge_Cs_Or = pd.merge(customers, orders, on='customer_id')
final = pd.merge(merge_Cs_Or, returns, on='order_id')

In [72]:
final

,customer_id,customer_name,city,age,order_id,product,amount,return_id,return_reason
0,102,Rahul,Mumbai,25,1003,Keyboard,3000,201,Damaged
1,105,Pooja,Bangalore,27,1005,Tablet,25000,202,Wrong Item

In [73]:
final[['customer_name', 'product', 'return_reason']]

  customer_name   product return_reason
0         Rahul  Keyboard       Damaged
1         Pooja    Tablet    Wrong Item

#

#

### 18 . Merge customers + orders + payments together.

Create final ecommerce transaction dataset.

In [74]:
payments.columns

Index(['payment_id', 'order_id', 'payment_method', 'payment_status'], dtype='object')

In [75]:
merge_Cs_Or.columns

Index(['customer_id', 'customer_name', 'city', 'age', 'order_id', 'product',
       'amount'],
      dtype='object')

In [80]:
merged1 = pd.merge(customers, orders, on='customer_id', how='left')

final_C_Ord_pay= pd.merge(merged1, payments, on='order_id', how='left')

final_C_Ord_pay

,customer_id,customer_name,city,age,order_id,product,amount,payment_id,payment_method,payment_status
0,101,Omkar,Delhi,22,1001.0,Laptop,55000.0,1.0,UPI,Success
1,101,Omkar,Delhi,22,1007.0,Printer,8000.0,6.0,Card,Pending
2,102,Rahul,Mumbai,25,1002.0,Phone,20000.0,2.0,Card,Success
3,102,Rahul,Mumbai,25,1003.0,Keyboard,3000.0,3.0,Cash,Failed
4,103,Sneha,Pune,24,NaN,NaN,NaN,NaN,NaN,NaN
5,104,Amit,Delhi,30,1004.0,Mouse,1500.0,NaN,NaN,NaN
6,105,Pooja,Bangalore,27,1005.0,Tablet,25000.0,4.0,UPI,Success
7,105,Pooja,Bangalore,27,1010.0,Laptop,60000.0,8.0,UPI,Success
8,106,Kiran,Pune,29,NaN,NaN,NaN,NaN,NaN,NaN
9,107,Neha,Mumbai,23,NaN,NaN,NaN,NaN,NaN,NaN
10,108,Vijay,Delhi,31,1006.0,Monitor,12000.0,5.0,NetBanking,Success
11,109,Anjali,Hyderabad,26,1009.0,Phone,22000.0,NaN,NaN,NaN
12,110,Rohit,Chennai,28,NaN,NaN,NaN,NaN,NaN,NaN

#### Find customers whose payment failed.

In [81]:
final_C_Ord_pay[final_C_Ord_pay['payment_status']=='Failed']

,customer_id,customer_name,city,age,order_id,product,amount,payment_id,payment_method,payment_status
3,102,Rahul,Mumbai,25,1003.0,Keyboard,3000.0,3.0,Cash,Failed

#### Find customers who ordered but payment is missing.

In [82]:
final_C_Ord_pay[final_C_Ord_pay['payment_status']=='Pending']

,customer_id,customer_name,city,age,order_id,product,amount,payment_id,payment_method,payment_status
1,101,Omkar,Delhi,22,1007.0,Printer,8000.0,6.0,Card,Pending

#### Find orders existing in payments but not in orders.

In [86]:
merged = pd.merge(orders, payments, on='order_id', how='right')
merged[merged['customer_id'].isna()]

,order_id,customer_id,product,amount,payment_id,payment_method,payment_status
6,1012,NaN,NaN,NaN,7,Cash,Success

#

#

# #Pandas join()

### Q1. Join customers and orders.

In [3]:
customers = pd.DataFrame({
    'customer_id':[101,102,103,104,105],
    'name':['Om','Raj','Neha','Amit','Sara'],
    'city':['Delhi','Mumbai','Pune','Delhi','Chennai']
}).set_index('customer_id')

In [4]:
customers

             name     city
customer_id
101            Om    Delhi
102           Raj   Mumbai
103          Neha     Pune
104          Amit    Delhi
105          Sara  Chennai

In [5]:
orders = pd.DataFrame({
    'product':['Laptop','Phone','Mouse','Tablet'],
    'amount':[70000,30000,1500,25000]
}, index=[101,102,106,101])

In [7]:
orders

    product  amount
101  Laptop   70000
102   Phone   30000
106   Mouse    1500
101  Tablet   25000

In [9]:
join_data = customers.join(orders)

In [10]:
join_data

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

### Q2. Show customer names with purchased products.

In [11]:
customers.join(orders)[['name','product']]

             name product
customer_id
101            Om  Laptop
101            Om  Tablet
102           Raj   Phone
103          Neha     NaN
104          Amit     NaN
105          Sara     NaN

### Q3. Join amount details with customer table.

In [14]:
customers.join(orders)[['name','amount']]

             name   amount
customer_id
101            Om  70000.0
101            Om  25000.0
102           Raj  30000.0
103          Neha      NaN
104          Amit      NaN
105          Sara      NaN

### Q4. Create customer-order dataset.

In [16]:
customer_orders = customers.join(orders)
customer_orders

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

### Q5. Combine customer and order information.

In [18]:
customers.join(orders)

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

#

### Q6. Show only customers who placed orders.

In [22]:
customers.join(orders,how='inner')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
101           Om   Delhi  Tablet   25000
102          Raj  Mumbai   Phone   30000

### Q7. Find customers having matching order records.

In [24]:
customers.join(orders,how='inner')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
101           Om   Delhi  Tablet   25000
102          Raj  Mumbai   Phone   30000

### Q8. Show customers who actually purchased products.

In [25]:
customers.join( orders,how='inner')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
101           Om   Delhi  Tablet   25000
102          Raj  Mumbai   Phone   30000

### Q9. Keep only matching customer IDs.

In [26]:
customers.join(orders,how='inner')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
101           Om   Delhi  Tablet   25000
102          Raj  Mumbai   Phone   30000

### Q10 Create dataset containing valid customer transactions only.

In [34]:
valid_cust = customers.join(orders,how='inner')
valid_cust

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
101           Om   Delhi  Tablet   25000
102          Raj  Mumbai   Phone   30000

#

#

### Q11. Show all customers even if they never ordered.

In [35]:
customers.join(orders,how='left')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

### Q12. Find customers without orders.

In [39]:
cust_ord = customers.join(orders)
cust_ord[cust_ord['product'].isna()]

             name     city product  amount
customer_id
103          Neha     Pune     NaN     NaN
104          Amit    Delhi     NaN     NaN
105          Sara  Chennai     NaN     NaN

### Q13. Keep all customer records while joining orders.

In [41]:
customers.join(orders,how='left')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

### Q14. Create customer master table with order info.

In [42]:
cust_master = customers.join(orders,how='left')
cust_master

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

### Q15. Show all customers with possible purchase details.

In [43]:
customers.join(orders,how='left')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN

#

###  Q16. Show all orders even if customer details are missing.

In [44]:
customers.join(orders,how='right')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
102          Raj  Mumbai   Phone   30000
106          NaN     NaN   Mouse    1500
101           Om   Delhi  Tablet   25000

In [45]:
orders.join(customers,how='left')

    product  amount name    city
101  Laptop   70000   Om   Delhi
102   Phone   30000  Raj  Mumbai
106   Mouse    1500  NaN     NaN
101  Tablet   25000   Om   Delhi

### Q17. Find orders having invalid customer IDs.

In [49]:
cust_Ord = customers.join(orders, how='right')
cust_Ord[cust_Ord['name'].isna()]

            name city product  amount
customer_id
106          NaN  NaN   Mouse    1500

### Q18 Keep all order records during join.

In [51]:
customers.join(orders,how='right')

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
102          Raj  Mumbai   Phone   30000
106          NaN     NaN   Mouse    1500
101           Om   Delhi  Tablet   25000

### Q19. Create dataset preserving every order.

In [52]:
all_orders = customers.join(orders,how='right')
all_orders

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
102          Raj  Mumbai   Phone   30000
106          NaN     NaN   Mouse    1500
101           Om   Delhi  Tablet   25000

### Q20. Show unmatched order entries.

In [56]:
cust_Ord

            name    city product  amount
customer_id
101           Om   Delhi  Laptop   70000
102          Raj  Mumbai   Phone   30000
106          NaN     NaN   Mouse    1500
101           Om   Delhi  Tablet   25000

In [57]:
cust_Ord[cust_Ord['name'].isna()]

            name city product  amount
customer_id
106          NaN  NaN   Mouse    1500

#

### Q21. Show all customers and all orders.

In [59]:
customers.join(orders,how='outer')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN
106           NaN      NaN   Mouse   1500.0

### Q22. Keep every index from both tables.

In [61]:
customers.join(orders,how='outer')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN
106           NaN      NaN   Mouse   1500.0

### Q23. Find unmatched customers and unmatched orders.

In [66]:
all_cust_ord = customers.join(orders,how='outer')
all_cust_ord

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN
106           NaN      NaN   Mouse   1500.0

In [68]:
all_cust_ord[all_cust_ord['name'].isna() |all_cust_ord['product'].isna()]

             name     city product  amount
customer_id
103          Neha     Pune     NaN     NaN
104          Amit    Delhi     NaN     NaN
105          Sara  Chennai     NaN     NaN
106           NaN      NaN   Mouse  1500.0

### Q24. Create full customer-order mapping table.

In [70]:
cust_ord_map = customers.join(orders,how='outer')
cust_ord_map

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN
106           NaN      NaN   Mouse   1500.0

### Q25. Combine all records including missing matches.

In [72]:
customers.join(orders,how='outer')

             name     city product   amount
customer_id
101            Om    Delhi  Laptop  70000.0
101            Om    Delhi  Tablet  25000.0
102           Raj   Mumbai   Phone  30000.0
103          Neha     Pune     NaN      NaN
104          Amit    Delhi     NaN      NaN
105          Sara  Chennai     NaN      NaN
106           NaN      NaN   Mouse   1500.0