# Probability Distribution (General)

#

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

## Discrete Probability Distribution
- A discrete probability distribution is a type of probability distribution that is used only for countable (discrete) values.

### Example 1: Dice Roll 🎲

- Possible outcomes: 1, 2, 3, 4, 5, 6
- These are countable values, so this is a discrete probability distribution.

In [8]:
#Possible values
x = [1, 2, 3, 4, 5, 6]
n= len(x)
# Probability of each value
probability = [1/n] * n
distribution = pd.DataFrame({"Random Variable (X)": x,"Probability": probability})
print(distribution)

   Random Variable (X)  Probability
0                    1     0.166667
1                    2     0.166667
2                    3     0.166667
3                    4     0.166667
4                    5     0.166667
5                    6     0.166667

#

#### Example 2: Student Result

In [9]:
students = pd.DataFrame({"Result": ["Pass", "Pass", "Fail", "Pass", "Fail"]})

In [10]:
students

  Result
0   Pass
1   Pass
2   Fail
3   Pass
4   Fail

In [11]:
pass_count = len(students[students["Result"] == "Pass"] )
fail_count =  len(students[students["Result"] == "Fail"])
total = len( students)

In [12]:
pass_count

3

In [13]:
fail_count

2

In [14]:
total

5

In [15]:
pass_probability = pass_count / total

In [16]:
pass_probability

0.6

In [17]:
fail_probability = fail_count/total

In [18]:
fail_probability

0.4

In [19]:
distribution = pd.DataFrame({
    "Random Variable (X)": [1, 0],
    "Outcome": ["Pass", "Fail"],
    "Probability": [pass_probability, fail_probability]
})

In [20]:
distribution

   Random Variable (X) Outcome  Probability
0                    1    Pass          0.6
1                    0    Fail          0.4

#

## Continuous Probability Distribution
- shows the probabilities of values that can take any value within a range.

#### Example 1: Students  Heights

In [21]:
heights = np.random.normal(loc=170, scale=5, size=10)
df = pd.DataFrame({"Height (cm)": heights})

In [22]:
df

   Height (cm)
0   168.680676
1   169.433053
2   169.500839
3   171.335726
4   176.929079
5   168.764388
6   159.620093
7   182.042110
8   178.542418
9   162.752491

#### Example 2: Delivery Time

In [25]:
delivery_time = np.random.normal(loc=30, scale=4, size=10)
df2 = pd.DataFrame({"Delivery Time (Minutes)": delivery_time})

In [24]:
df2

   Delivery Time (Minutes)
0                35.165642
1                35.599872
2                36.082096
3                29.741362
4                31.422960
5                28.818584
6                27.322948
7                29.232032
8                26.404474
9                36.778631

#

#### Problem: When the number of possible outcomes is large, a probability distribution table becomes difficult to use.
#### So, we use mathematical functions : 
- Probability Mass Function → for discrete (countable) values
- Probability Density Function → for continuous (measurable) values

#

### Probability Mass Function (PMF)

#### Example 1: Coin Toss
- A fair coin is tossed 10 times. What is the probability of getting exactly 6 Heads?

In [28]:
n = 10      # coin is tossed 10 times

In [34]:
p = 1/2     # Probability of Head

In [35]:
x = 6  #  getting exactly 6 Heads

In [36]:
print('Number of time coin tossed : ',n)
print('Probability of Head : ',p)
print('Randome Variable(Head) :',x)

Number of time coin tossed :  10
Probability of Head :  0.5
Randome Variable(Head) : 6

In [39]:
probability = stats.binom.pmf(x, n, p)

In [41]:
print(probability)

0.2050781249999999

#### Binomial PMF
Use when:
- Fixed number of trials
- Only two outcomes: Success or Failure

#

#### Example 2: Customers Arriving
- A coffee shop receives 8 customers per hour on average.
- What is the probability that exactly 10 customers arrive in the next hour?

In [42]:
avg_customers = 8
x = 10

In [48]:
probability2 = stats.poisson.pmf(x, avg_customers)

In [49]:
print(probability2)

0.09926153383153544

#

#### Example 3 : Calls Received
- A call center receives 15 calls per hour on average.
- What is the probability of receiving exactly 12 calls in the next hour?

In [54]:
avg_calls = 15
x = 12
probability3 = stats.poisson.pmf(x, avg_calls)

In [55]:
print(probability3)

0.08285923436864541

#### Poisson PMF
Use when:
- Counting the number of events
- Events occur in a fixed interval (time, distance, area, etc.)

#

### Probability Density Function (PDF)

##### Example 1: Student Heights (Normal PDF)
- A school records the heights of 100 students. Find the probability density for a student whose height is 170 cm.

In [56]:
heights = pd.DataFrame({
    "Height": [165,168,170,172,169,
               171,173,167,170,169]
})

In [57]:
heights

   Height
0     165
1     168
2     170
3     172
4     169
5     171
6     173
7     167
8     170
9     169

In [58]:
mean_height = heights["Height"].mean()

In [59]:
mean_height

np.float64(169.4)

In [60]:
std_height = heights["Height"].std()

In [61]:
std_height

2.3664319132398464

In [64]:
stu_H_density = stats.norm.pdf(x=170,loc=mean_height,scale=std_height)

In [67]:
print(stu_H_density)

0.16325127688242055

#

##### Example 2: Delivery Time (Normal PDF)
- A company records the delivery time (minutes) of its orders. Find the probability density for a delivery time of 30 minutes.

In [70]:
delivery = pd.DataFrame({
    "Time":[28,32,30,29,31,
            27,33,30,29,31]
})

In [71]:
delivery

   Time
0    28
1    32
2    30
3    29
4    31
5    27
6    33
7    30
8    29
9    31

In [72]:
mean_time = delivery["Time"].mean()

In [73]:
std_time = delivery["Time"].std()

In [77]:
D_Time_density = stats.norm.pdf(x=30,loc=mean_time,scale=std_time)

In [78]:
print(D_Time_density)

0.2185096861184158

#

##### 3: Employee Salary (Normal PDF)
- A company records the salary of its employees. Find the probability density for an employee earning ₹52,000.

In [81]:
salary = pd.DataFrame({
    "Salary":[45000,48000,50000,52000,51000,
              49000,53000,55000,47000,50000]
})

In [83]:
mean_salary = salary["Salary"].mean()
std_salary = salary["Salary"].std()

In [87]:
salary_dens = stats.norm.pdf(x=52000,loc=mean_salary,scale=std_salary)

In [89]:
print(salary_dens)

0.00010758759901884184

#

##### 4: Product Weight (Normal PDF)
- A factory records the weight (grams) of its products. Find the probability density for a product weighing 505 grams.

In [96]:
weights = pd.DataFrame({
    "Weight":[498,500,503,506,501,
              504,507,499,502,505]})

In [99]:
mean_weight = weights["Weight"].mean()
std_weight = weights["Weight"].std()

In [104]:
P_weight_dens = stats.norm.pdf(x=505, loc=mean_weight,scale=std_weight)

In [105]:
print(P_weight_dens)

0.09370211835810706

#

### Cumulative Distribution Function (CDF )
- gives the probability that a random variable is less than or equal to a given value.

##### Example 1: Delivery Time (Continuous)
- Find the probability that a delivery takes 30 minutes or less.

In [107]:
delivery = pd.DataFrame({
    "Time": [28, 32, 30, 29, 31, 27, 33, 30, 29, 31]})

In [108]:
delivery

   Time
0    28
1    32
2    30
3    29
4    31
5    27
6    33
7    30
8    29
9    31

In [111]:
mean_time =  delivery["Time"].mean()
std_time =  delivery["Time"].std()

In [113]:
prob = stats.norm.cdf(x=30,loc=mean_time,scale=std_time)

In [117]:
print("Mean:", mean_time)
print("Standard Deviation:", std_time)
print("Probability:", prob)

Mean: 30.0
Standard Deviation: 1.8257418583505538
Probability: 0.5

#

##### Example 2: Student Height
- Find the probability that a student's height is 170 cm or less.

In [118]:
heights = pd.DataFrame({
    "Height": [165,168,170,172,169,
               171,173,167,170,169]})

In [119]:
heights

   Height
0     165
1     168
2     170
3     172
4     169
5     171
6     173
7     167
8     170
9     169

In [120]:
mean_height = heights["Height"].mean()
std_height = heights["Height"].std()

In [126]:
prob_st = stats.norm.cdf(x=170,loc=mean_height,scale=std_height)

In [129]:
print("Mean:", mean_height)
print("Standard Deviation:", std_height)
print("Probability:", prob_st)

Mean: 169.4
Standard Deviation: 2.3664319132398464
Probability: 0.6000769471687625