# Filtering Data

In [1]:
import pandas as pd

In [2]:
import numpy as np

## Series Filtering

In [3]:
s = pd.Series([10, 25, 30, 45, 50, 15, 5, 60, 35, 20])

In [4]:
s

0    10
1    25
2    30
3    45
4    50
5    15
6     5
7    60
8    35
9    20
dtype: int64

#### 1. Get values greater than 30

In [5]:
s[s>30]

3    45
4    50
7    60
8    35
dtype: int64

#### 2. Get values less than 20

In [6]:
s[s<20]

0    10
5    15
6     5
dtype: int64

#### 3. Get values equal to 25

In [7]:
s[s==25]

1    25
dtype: int64

#### 4. Get values not equal to 10

In [8]:
s[s!=10]

1    25
2    30
3    45
4    50
5    15
6     5
7    60
8    35
9    20
dtype: int64

#### 5. Get values greater than or equal to 50.

In [9]:
s[s>=50]

4    50
7    60
dtype: int64

#### 6. Get values between 20 and 40

In [10]:
s[(s>20) &(s<40)]

1    25
2    30
8    35
dtype: int64

#### 7. Get even numbers only

In [11]:
s[s%2==0]

0    10
2    30
4    50
7    60
9    20
dtype: int64

#### 8. Get even numbers only

In [12]:
s[s%2!=0]

1    25
3    45
5    15
6     5
8    35
dtype: int64

#### 9. Get values divisible by 5

In [13]:
s[s%5==0]

0    10
1    25
2    30
3    45
4    50
5    15
6     5
7    60
8    35
9    20
dtype: int64

#### 10. Get top 3 highest values

In [14]:
s.nlargest(3)

7    60
4    50
3    45
dtype: int64

#### 11. Get values greater than mean

In [15]:
mean = np.mean(s)
s[s>mean]

2    30
3    45
4    50
7    60
8    35
dtype: int64

In [16]:
s[s > s.mean()]

2    30
3    45
4    50
7    60
8    35
dtype: int64

#### 12. Get values less than median

In [17]:
mdm = np.median(s)
s[s<mdm]

0    10
1    25
5    15
6     5
9    20
dtype: int64

In [18]:
s[s < s.median()]

0    10
1    25
5    15
6     5
9    20
dtype: int64

#### 13. Get values in list [10, 20, 30]

In [19]:
s[s in [10,20,30]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [21]:
s[s.isin([10, 20, 30])]

0    10
2    30
9    20
dtype: int64

#### 14. Remove values less than 15

In [22]:
s[s >= 15]

1    25
2    30
3    45
4    50
5    15
7    60
8    35
9    20
dtype: int64

#### 15. Replace values > 40 with 100 (filter + modify)

In [24]:
s.where(s <= 40, 100)

0     10
1     25
2     30
3    100
4    100
5     15
6      5
7    100
8     35
9     20
dtype: int64

#

## DataFrame Filtering

In [25]:
data = pd.read_csv('col_row-dataset.csv')

In [26]:
data.sample(10)

      id   name   age       city   salary department  experience
299  300   Amit  20.0       Pune  20000.0    Finance         8.0
58    59  Kiran  24.0      Delhi  20000.0  Marketing         3.0
420  421   Amit  22.0  Hyderabad  40000.0  Marketing         2.0
52    53   Sita  21.0       Pune  30000.0  Marketing         3.0
290  291   Sita  20.0       Pune      NaN         IT         3.0
23    24  Kiran  18.0     Mumbai      NaN    Finance         NaN
147  148    Anu  21.0  Hyderabad  20000.0         IT         7.0
359  360   Ravi  19.0        NaN  20000.0  Marketing         7.0
454  455   Amit  19.0      Delhi  40000.0  Marketing         NaN
129  130   John  20.0        NaN  20000.0    Finance         2.0

#### 1. Get rows where age > 22

In [27]:
data[data['age']>22]

      id  name   age       city   salary department  experience
2      3  Amit  23.0  Bangalore      NaN  Marketing         2.0
3      4  John  25.0     Mumbai  40000.0  Marketing         NaN
5      6  John  24.0      Delhi  50000.0      Sales         3.0
6      7  Ravi  24.0    Chennai  30000.0         HR         1.0
7      8  John  25.0  Bangalore  60000.0    Finance         3.0
..   ...   ...   ...        ...      ...        ...         ...
489  490  Neha  25.0  Hyderabad  60000.0  Marketing         8.0
493  494   Anu  23.0  Hyderabad  50000.0      Sales         6.0
495  496  Neha  24.0        NaN  40000.0    Finance         7.0
496  497  Ravi  24.0        NaN      NaN  Marketing         6.0
499  500  John  23.0     Mumbai  40000.0    Finance         NaN

[176 rows x 7 columns]

#### 2. Get rows where salary < 30000

In [28]:
data[data["salary"]<30000].head()

    id   name   age       city   salary department  experience
4    5   John  21.0  Bangalore  20000.0         IT         5.0
29  30   John  21.0       Pune  20000.0         IT         4.0
30  31  Kiran  20.0  Hyderabad  20000.0  Marketing         3.0
32  33   Amit  20.0     Mumbai  20000.0         HR         6.0
34  35   John  21.0  Bangalore  20000.0  Marketing         2.0

#### 3. Get rows where city = "Delhi"

In [29]:
data[data["city"]=='Delhi'].head()

    id  name   age   city   salary department  experience
5    6  John  24.0  Delhi  50000.0      Sales         3.0
10   6  John  24.0  Delhi  50000.0      Sales         3.0
13  14  Amit  22.0  Delhi  30000.0    Finance         5.0
15  16  Sita  22.0  Delhi  60000.0    Finance         5.0
17  18   Anu  18.0  Delhi      NaN  Marketing         5.0

#### 4. Get rows where department = "IT"

In [30]:
data[data["department"]=='IT'].head()

    id   name   age       city   salary department  experience
1    2  Kiran  21.0        NaN  60000.0         IT         7.0
4    5   John  21.0  Bangalore  20000.0         IT         5.0
12  13   Amit   NaN    Chennai      NaN         IT         2.0
14  15   Neha  19.0  Hyderabad      NaN         IT         5.0
28  29   Amit  21.0    Chennai  50000.0         IT         3.0

#### 5. Get rows where experience >= 5

In [31]:
data[data['experience']>=5].head(10)

    id   name   age       city   salary department  experience
0    1   Neha  19.0  Hyderabad      NaN         HR         7.0
1    2  Kiran  21.0        NaN  60000.0         IT         7.0
4    5   John  21.0  Bangalore  20000.0         IT         5.0
13  14   Amit  22.0      Delhi  30000.0    Finance         5.0
14  15   Neha  19.0  Hyderabad      NaN         IT         5.0
15  16   Sita  22.0      Delhi  60000.0    Finance         5.0
17  18    Anu  18.0      Delhi      NaN  Marketing         5.0
19  20   Amit  19.0  Bangalore  60000.0  Marketing         8.0
21  22  Kiran  22.0  Hyderabad  40000.0    Finance         6.0
25  26   Ravi   NaN       Pune  50000.0    Finance         7.0

#### 6. Get rows where age > 25 AND salary > 40000

In [32]:
data[data[(data['age']>25)&(data['salary']>40000)]]

     id name  age city  salary department  experience
0   NaN  NaN  NaN  NaN     NaN        NaN         NaN
1   NaN  NaN  NaN  NaN     NaN        NaN         NaN
2   NaN  NaN  NaN  NaN     NaN        NaN         NaN
3   NaN  NaN  NaN  NaN     NaN        NaN         NaN
4   NaN  NaN  NaN  NaN     NaN        NaN         NaN
..   ..  ...  ...  ...     ...        ...         ...
495 NaN  NaN  NaN  NaN     NaN        NaN         NaN
496 NaN  NaN  NaN  NaN     NaN        NaN         NaN
497 NaN  NaN  NaN  NaN     NaN        NaN         NaN
498 NaN  NaN  NaN  NaN     NaN        NaN         NaN
499 NaN  NaN  NaN  NaN     NaN        NaN         NaN

[500 rows x 7 columns]

#### 7. Get rows where city = "Mumbai" OR "Pune"

In [33]:
data[data['city'].isin(['Mumbai','Pune'])]

      id   name   age    city   salary department  experience
3      4   John  25.0  Mumbai  40000.0  Marketing         NaN
9     10   Sita  24.0  Mumbai  30000.0         HR         4.0
16    17   Ravi  23.0  Mumbai  40000.0    Finance         3.0
18    19    Anu  21.0    Pune  60000.0    Finance         NaN
23    24  Kiran  18.0  Mumbai      NaN    Finance         NaN
..   ...    ...   ...     ...      ...        ...         ...
488  489   Neha  21.0    Pune      NaN         IT         2.0
490  491   Neha   NaN    Pune  30000.0         IT         8.0
492  493    Anu  22.0  Mumbai  50000.0         IT         1.0
497  498  Kiran  20.0  Mumbai  20000.0         IT         4.0
499  500   John  23.0  Mumbai  40000.0    Finance         NaN

[142 rows x 7 columns]

#### 8. Get rows where salary is between 30000 and 50000

In [37]:
data[(data['salary']>=30000) &(data['salary']<=50000)]

      id  name   age       city   salary department  experience
3      4  John  25.0     Mumbai  40000.0  Marketing         NaN
5      6  John  24.0      Delhi  50000.0      Sales         3.0
6      7  Ravi  24.0    Chennai  30000.0         HR         1.0
9     10  Sita  24.0     Mumbai  30000.0         HR         4.0
10     6  John  24.0      Delhi  50000.0      Sales         3.0
..   ...   ...   ...        ...      ...        ...         ...
492  493   Anu  22.0     Mumbai  50000.0         IT         1.0
493  494   Anu  23.0  Hyderabad  50000.0      Sales         6.0
494  495  Ravi  21.0      Delhi  30000.0    Finance         6.0
495  496  Neha  24.0        NaN  40000.0    Finance         7.0
499  500  John  23.0     Mumbai  40000.0    Finance         NaN

[263 rows x 7 columns]

In [38]:
data[data['salary'].between(30000, 50000)]

      id  name   age       city   salary department  experience
3      4  John  25.0     Mumbai  40000.0  Marketing         NaN
5      6  John  24.0      Delhi  50000.0      Sales         3.0
6      7  Ravi  24.0    Chennai  30000.0         HR         1.0
9     10  Sita  24.0     Mumbai  30000.0         HR         4.0
10     6  John  24.0      Delhi  50000.0      Sales         3.0
..   ...   ...   ...        ...      ...        ...         ...
492  493   Anu  22.0     Mumbai  50000.0         IT         1.0
493  494   Anu  23.0  Hyderabad  50000.0      Sales         6.0
494  495  Ravi  21.0      Delhi  30000.0    Finance         6.0
495  496  Neha  24.0        NaN  40000.0    Finance         7.0
499  500  John  23.0     Mumbai  40000.0    Finance         NaN

[263 rows x 7 columns]

#### 9 . Get rows where age is null

In [35]:
data[data['age']==None]

Empty DataFrame
Columns: [id, name, age, city, salary, department, experience]
Index: []

In [39]:
data[data['age'].isnull()]

      id   name  age       city   salary department  experience
12    13   Amit  NaN    Chennai      NaN         IT         2.0
25    26   Ravi  NaN       Pune  50000.0    Finance         7.0
40    41   John  NaN     Mumbai      NaN      Sales         7.0
47    48   Sita  NaN    Chennai  40000.0         IT         8.0
51    52   John  NaN  Hyderabad  20000.0  Marketing         NaN
57    58   Neha  NaN        NaN  30000.0  Marketing         7.0
74    75    Anu  NaN      Delhi  20000.0  Marketing         7.0
76    77    Anu  NaN       Pune  20000.0  Marketing         2.0
109  110   Amit  NaN    Chennai  30000.0         HR         7.0
130  131   Sita  NaN        NaN  30000.0  Marketing         2.0
133  134   Ravi  NaN  Hyderabad      NaN  Marketing         2.0
134  135   Sita  NaN      Delhi  60000.0         HR         8.0
138  139   John  NaN     Mumbai  50000.0      Sales         NaN
143  144   Neha  NaN       Pune  40000.0    Finance         5.0
159  160   Amit  NaN     Mumbai  50000.0    Finance         7.0
170  171   Amit  NaN       Pune  30000.0  Marketing         4.0
181  182   Amit  NaN    Chennai  40000.0      Sales         8.0
184  185   John  NaN     Mumbai  50000.0    Finance         1.0
188  189   Amit  NaN  Bangalore  40000.0  Marketing         6.0
239  240   Ravi  NaN     Mumbai      NaN  Marketing         4.0
247  248   John  NaN        NaN      NaN         HR         8.0
250  251    Anu  NaN    Chennai      NaN         IT         1.0
252  253    Anu  NaN        NaN  40000.0    Finance         1.0
254  255  Kiran  NaN        NaN  20000.0         IT         6.0
292  293  Kiran  NaN  Hyderabad  60000.0         IT         4.0
298  299   Sita  NaN    Chennai  60000.0    Finance         NaN
304  305   Amit  NaN     Mumbai  60000.0  Marketing         7.0
337  338   Neha  NaN  Bangalore  60000.0    Finance         7.0
338  339  Kiran  NaN      Delhi  30000.0         HR         2.0
368  369   Ravi  NaN      Delhi  50000.0      Sales         3.0
377  378   Sita  NaN        NaN  20000.0    Finance         7.0
378  379   Neha  NaN    Chennai      NaN         IT         7.0
386  387   John  NaN        NaN  30000.0  Marketing         6.0
389  390    Anu  NaN    Chennai  40000.0      Sales         5.0
392  393   Amit  NaN       Pune  30000.0    Finance         2.0
398  399   Amit  NaN  Hyderabad  50000.0    Finance         4.0
403  404   Amit  NaN     Mumbai  50000.0         IT         5.0
425  426  Kiran  NaN     Mumbai  60000.0      Sales         2.0
437  438   Sita  NaN      Delhi  30000.0         IT         4.0
444  445   Neha  NaN  Bangalore  30000.0         HR         6.0
469  470   Amit  NaN  Hyderabad  40000.0         IT         4.0
490  491   Neha  NaN       Pune  30000.0         IT         8.0
491  492   Ravi  NaN  Bangalore  50000.0    Finance         7.0

#### 10. Get rows where city is not null

In [40]:
data[data['city'].notnull()]

      id   name   age       city   salary department  experience
0      1   Neha  19.0  Hyderabad      NaN         HR         7.0
2      3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3      4   John  25.0     Mumbai  40000.0  Marketing         NaN
4      5   John  21.0  Bangalore  20000.0         IT         5.0
5      6   John  24.0      Delhi  50000.0      Sales         3.0
..   ...    ...   ...        ...      ...        ...         ...
492  493    Anu  22.0     Mumbai  50000.0         IT         1.0
493  494    Anu  23.0  Hyderabad  50000.0      Sales         6.0
494  495   Ravi  21.0      Delhi  30000.0    Finance         6.0
497  498  Kiran  20.0     Mumbai  20000.0         IT         4.0
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

[448 rows x 7 columns]

#### 11. Get rows where salary > average salary

In [41]:
data[data['salary'] > data['salary'].mean()]

      id   name   age       city   salary department  experience
1      2  Kiran  21.0        NaN  60000.0         IT         7.0
3      4   John  25.0     Mumbai  40000.0  Marketing         NaN
5      6   John  24.0      Delhi  50000.0      Sales         3.0
7      8   John  25.0  Bangalore  60000.0    Finance         3.0
8      9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
..   ...    ...   ...        ...      ...        ...         ...
492  493    Anu  22.0     Mumbai  50000.0         IT         1.0
493  494    Anu  23.0  Hyderabad  50000.0      Sales         6.0
495  496   Neha  24.0        NaN  40000.0    Finance         7.0
498  499   Ravi  21.0        NaN  60000.0  Marketing         4.0
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

[253 rows x 7 columns]

#### 12. Get rows where experience < median experience

In [43]:
data[data['experience'] < data['experience'].median()]

      id   name   age       city   salary department  experience
2      3   Amit  23.0  Bangalore      NaN  Marketing         2.0
5      6   John  24.0      Delhi  50000.0      Sales         3.0
6      7   Ravi  24.0    Chennai  30000.0         HR         1.0
7      8   John  25.0  Bangalore  60000.0    Finance         3.0
10     6   John  24.0      Delhi  50000.0      Sales         3.0
..   ...    ...   ...        ...      ...        ...         ...
482  483   Neha  25.0      Delhi  20000.0         HR         1.0
485  486   Sita  21.0       Pune  30000.0         IT         2.0
486  487  Kiran  25.0  Hyderabad      NaN         HR         1.0
488  489   Neha  21.0       Pune      NaN         IT         2.0
492  493    Anu  22.0     Mumbai  50000.0         IT         1.0

[168 rows x 7 columns]

#### 13. Get top 10 highest salary rows

In [46]:
data.nlargest(10, 'salary')

    id   name   age       city   salary department  experience
1    2  Kiran  21.0        NaN  60000.0         IT         7.0
7    8   John  25.0  Bangalore  60000.0    Finance         3.0
8    9  Kiran  19.0  Bangalore  60000.0    Finance         NaN
15  16   Sita  22.0      Delhi  60000.0    Finance         5.0
18  19    Anu  21.0       Pune  60000.0    Finance         NaN
19  20   Amit  19.0  Bangalore  60000.0  Marketing         8.0
20  21   Ravi  22.0    Chennai  60000.0         HR         NaN
37  38   John  19.0       Pune  60000.0         IT         8.0
44  45   Ravi  24.0      Delhi  60000.0         IT         3.0
48  49   Neha  19.0        NaN  60000.0         IT         7.0

#### 14. Get rows where name starts with "A"

In [47]:
data[data['name'].str.startswith('A')]

      id  name   age       city   salary department  experience
2      3  Amit  23.0  Bangalore      NaN  Marketing         2.0
11    12   Anu  21.0  Hyderabad      NaN      Sales         3.0
12    13  Amit   NaN    Chennai      NaN         IT         2.0
13    14  Amit  22.0      Delhi  30000.0    Finance         5.0
17    18   Anu  18.0      Delhi      NaN  Marketing         5.0
..   ...   ...   ...        ...      ...        ...         ...
483  484  Amit  21.0      Delhi  50000.0    Finance         4.0
484  485  Amit  24.0      Delhi  50000.0  Marketing         8.0
487  488  Amit  19.0  Bangalore  30000.0      Sales         NaN
492  493   Anu  22.0     Mumbai  50000.0         IT         1.0
493  494   Anu  23.0  Hyderabad  50000.0      Sales         6.0

[143 rows x 7 columns]

#### 15. Get rows where department is NOT "HR"

In [48]:
data[data['department'] != "HR"]

      id   name   age       city   salary department  experience
1      2  Kiran  21.0        NaN  60000.0         IT         7.0
2      3   Amit  23.0  Bangalore      NaN  Marketing         2.0
3      4   John  25.0     Mumbai  40000.0  Marketing         NaN
4      5   John  21.0  Bangalore  20000.0         IT         5.0
5      6   John  24.0      Delhi  50000.0      Sales         3.0
..   ...    ...   ...        ...      ...        ...         ...
495  496   Neha  24.0        NaN  40000.0    Finance         7.0
496  497   Ravi  24.0        NaN      NaN  Marketing         6.0
497  498  Kiran  20.0     Mumbai  20000.0         IT         4.0
498  499   Ravi  21.0        NaN  60000.0  Marketing         4.0
499  500   John  23.0     Mumbai  40000.0    Finance         NaN

[408 rows x 7 columns]