# Data Cleaning Practice 7

In [1]:
import pandas as pd

In [2]:
import numpy as np

## Data Inspection

In [3]:
data = pd.read_csv('messy_data6_employees.csv')

In [4]:
df = data.copy(deep=True)

#

In [6]:
df.shape

(500, 6)

In [7]:
df.head()

  Employee_ID Employee_Name Department   Salary   Join_Date  Performance_Score
0         NaN          Anil        NaN  -5000.0  15/01/2025                7.0
1       EMP-1           NaN         IT  75000.0         NaN                7.0
2         NaN           NaN    Finance      NaN         NaN                1.0
3          E3         SNEHA         hr  35000.0  01-15-2025                1.0
4        1004         SNEHA         IT  50000.0  2025-01-15                NaN

In [8]:
df.tail()

,Employee_ID,Employee_Name,Department,Salary,Join_Date,Performance_Score
495,E495,NaN,HR,50000.0,2025/01/15,5.0
496,EMP-496,NaN,Finance,25000.0,NaN,NaN
497,E497,sneha,Human Resource,-5000.0,2025/01/15,2.0
498,EMP-498,Priya,I.T.,NaN,NaN,1.0
499,1499,Anil,IT,NaN,NaN,1.0

In [11]:
df.head(10)

  Employee_ID Employee_Name Department   Salary   Join_Date  Performance_Score
0         NaN          Anil        NaN  -5000.0  15/01/2025                7.0
1       EMP-1           NaN         IT  75000.0         NaN                7.0
2         NaN           NaN    Finance      NaN         NaN                1.0
3          E3         SNEHA         hr  35000.0  01-15-2025                1.0
4        1004         SNEHA         IT  50000.0  2025-01-15                NaN
5        1005         SNEHA         IT  -5000.0         NaN                1.0
6       EMP-6         SNEHA        NaN  75000.0         NaN                2.0
7        1007         Priya         HR  35000.0  15/01/2025                3.0
8       EMP-8        sneha        I.T.  25000.0         NaN                2.0
9        1009          Anil        NaN  75000.0         NaN                1.0

In [12]:
df.dtypes

Employee_ID           object
Employee_Name         object
Department            object
Salary               float64
Join_Date             object
Performance_Score    float64
dtype: object

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Employee_ID'].duplicated().sum()

np.int64(93)

In [17]:
df.isnull().sum()

Employee_ID           94
Employee_Name        149
Department           132
Salary               134
Join_Date            162
Performance_Score    130
dtype: int64

In [19]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Salary', 'Join_Date',
       'Performance_Score'],
      dtype='object')

In [20]:
df['Department'].unique()

array([nan, 'IT', 'Finance', 'hr', 'HR', 'I.T.', 'Human Resource'],
      dtype=object)

In [22]:
for col in df.columns:
    print(df[col].unique()[:10])

[nan 'EMP-1' 'E3' '1004' '1005' 'EMP-6' '1007' 'EMP-8' '1009' '1011']
['Anil' nan 'SNEHA' 'Priya' ' sneha ' 'Ravi']
[nan 'IT' 'Finance' 'hr' 'HR' 'I.T.' 'Human Resource']
[-5000. 75000.    nan 35000. 50000. 25000.]
['15/01/2025' nan '01-15-2025' '2025-01-15' '2025/01/15']
[ 7.  1. nan  2.  3.  5.  4. -1.]

In [23]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Salary,366.0,36721.311475,26075.001085,-5000.0,25000.0,35000.0,50000.0,75000.0
Performance_Score,370.0,2.945946,2.381568,-1.0,1.0,3.0,5.0,7.0

In [24]:
df.describe(include='object').T

              count unique         top freq
Employee_ID     406    406        1499    1
Employee_Name   351      5       Priya   77
Department      368      6        I.T.   67
Join_Date       338      4  01-15-2025  111

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        406 non-null    object
 1   Employee_Name      351 non-null    object
 2   Department         368 non-null    object
 3   Salary             366 non-null    float64
 4   Join_Date          338 non-null    object
 5   Performance_Score  370 non-null    float64
dtypes: float64(2), object(4)
memory usage: 23.6+ KB

#

#

## Data Cleaning

In [26]:
df['Employee_ID'].isnull().sum()

np.int64(94)

In [27]:
df.dropna(subset='Employee_ID',inplace=True)

In [28]:
df['Employee_ID'].isnull().sum()

np.int64(0)

In [29]:
df['Employee_ID'].unique()[:20]

array(['EMP-1', 'E3', '1004', '1005', 'EMP-6', '1007', 'EMP-8', '1009',
       '1011', 'EMP-12', 'E14', '1016', 'EMP-17', '1018', '1020', '1021',
       'EMP-22', '1023', 'E25', '1026'], dtype=object)

In [32]:
import re

def standardize_id(emp_id):
    numbers = re.findall(r'\d+', str(emp_id))
    if numbers:
        return f"EMP-{int(numbers[0]):04d}"
        
df['Employee_ID'] = df['Employee_ID'].apply(standardize_id)

In [33]:
df['Employee_ID'].unique()[:20]

array(['EMP-0001', 'EMP-0003', 'EMP-1004', 'EMP-1005', 'EMP-0006',
       'EMP-1007', 'EMP-0008', 'EMP-1009', 'EMP-1011', 'EMP-0012',
       'EMP-0014', 'EMP-1016', 'EMP-0017', 'EMP-1018', 'EMP-1020',
       'EMP-1021', 'EMP-0022', 'EMP-1023', 'EMP-0025', 'EMP-1026'],
      dtype=object)

#

In [34]:
df['Employee_Name'].isnull().sum()

np.int64(119)

In [35]:
df['Employee_Name'] = df['Employee_Name'].str.strip().str.title()

In [36]:
df['Employee_Name'] = df['Employee_Name'].fillna('Unknown')

#

In [37]:
df['Department'].unique()

array(['IT', 'hr', nan, 'HR', 'I.T.', 'Finance', 'Human Resource'],
      dtype=object)

In [75]:
dept_map = {
'I.T.' : 'It',
    'Human Resource' : 'HR'
}

In [39]:
df['Department'] = df['Department'].str.replace(dept_map).str.title()

TypeError: StringMethods.replace() missing 1 required positional argument: 'repl'

In [40]:
df['Department'] = df['Department'].replace(dept_map).str.title()

In [41]:
df['Department'].unique()

array(['It', 'Hr', nan, 'Finance'], dtype=object)

#

In [42]:
df['Salary'].dtypes

dtype('float64')

In [43]:
df['Salary'].describe()

count      296.000000
mean     37162.162162
std      25859.215727
min      -5000.000000
25%      25000.000000
50%      35000.000000
75%      50000.000000
max      75000.000000
Name: Salary, dtype: float64

In [45]:
df.loc[df['Salary']<0,'Salary'].count()

np.int64(49)

In [46]:
df['Salary'].isnull().sum()

np.int64(110)

In [47]:
df.loc[df['Salary']<0,'Salary'] = np.nan

In [48]:
df['Salary'].isnull().sum()

np.int64(159)

#

In [51]:
df['Join_Date'].dtypes

dtype('O')

In [52]:
df['Join_Date'].unique()[:10]

array([nan, '01-15-2025', '2025-01-15', '15/01/2025', '2025/01/15'],
      dtype=object)

In [53]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],format='mixed',errors = 'coerce')

In [54]:
df['Join_Date'].unique()[:10]

<DatetimeArray>
['NaT', '2025-01-15 00:00:00']
Length: 2, dtype: datetime64[ns]

In [55]:
df['Join_Date'].head()

1          NaT
3   2025-01-15
4   2025-01-15
5          NaT
6          NaT
Name: Join_Date, dtype: datetime64[ns]

In [56]:
df['Join_Date'].isnull().sum()

np.int64(133)

In [61]:
df['Join_Date'] = df.groupby('Department')['Join_Date'].transform(lambda a : a.mode()[0] if not a.mode().empty else np.nan)

In [64]:
## Problem:  This destroys valid dates.
## Employees in the same department can join on different date

In [65]:
df['Join_Date'].isnull().sum()

np.int64(133)

In [66]:
df['Join_Date'] = pd.to_datetime(data['Join_Date'],format='mixed',errors = 'coerce')

In [71]:
# Best Way 
df['Join_Date'] = df['Join_Date'].fillna(df.groupby('Department')['Join_Date'].transform(lambda a : a.mode()[0] if not a.mode().empty else np.nan))

In [72]:
df['Join_Date'].isnull().sum()

np.int64(0)

In [73]:
df['Join_Date'] = df['Join_Date'].fillna(df['Join_Date'].mode()[0])

In [74]:
df['Join_Date'].isnull().sum()

np.int64(0)

#

In [76]:
df["Performance_Score"].unique()

array([ 7.,  1., nan,  2.,  3.,  5.,  4., -1.])

In [77]:
df["Performance_Score"].isnull().sum()

np.int64(106)

In [79]:
df.loc[(df["Performance_Score"] < 0) & (df["Performance_Score"] > 5 ),'Performance_Score']  = np.nan

In [80]:
df['Performance_Score'] = df['Performance_Score'].fillna(
    df.groupby('Department')['Performance_Score']
      .transform(lambda p : p.median())
)

In [81]:
df["Performance_Score"].isnull().sum()

np.int64(37)

In [82]:
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].median())

In [83]:
df["Performance_Score"].isnull().sum()

np.int64(0)

In [88]:
df['Department'] = df['Department'].fillna(
    df.groupby('Join_Date')['Department']
    .transform(lambda a : a.mode()[0] if not  a.mode().empty else np.nan))

In [97]:
df.isnull().sum()

Employee_ID            0
Employee_Name          0
Department             0
Salary               159
Join_Date              0
Performance_Score      0
dtype: int64

In [98]:
df['Salary'].isnull().sum()

np.int64(159)

In [99]:
df.loc[df['Salary']<0,'Salary'] = np.nan

In [100]:
df['Salary'].isnull().sum()

np.int64(159)

In [101]:
df['Salary'] = df['Salary'].fillna(df.groupby('Department')['Salary'].transform(lambda a : a.fillna(a.median())))

In [102]:
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           0
Salary               0
Join_Date            0
Performance_Score    0
dtype: int64

#

#

In [105]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Salary,406.0,42253.694581,25000.0,35000.0,35000.0,50000.0,75000.0,16029.515173
Join_Date,406,2025-01-15 00:00:00,2025-01-15 00:00:00,2025-01-15 00:00:00,2025-01-15 00:00:00,2025-01-15 00:00:00,2025-01-15 00:00:00,NaN
Performance_Score,406.0,3.504926,1.0,3.0,3.0,4.375,7.0,1.627685

In [106]:
df.describe(include='object').T

              count unique       top freq
Employee_ID     406    406  EMP-1499    1
Employee_Name   406      5   Unknown  119
Department      406      3        Hr  257

In [107]:
df.dtypes

Employee_ID                  object
Employee_Name                object
Department                   object
Salary                      float64
Join_Date            datetime64[ns]
Performance_Score           float64
dtype: object

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406 entries, 1 to 499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        406 non-null    object
 1   Employee_Name      406 non-null    object
 2   Department         406 non-null    object
 3   Salary             406 non-null    float64
 4   Join_Date          406 non-null    datetime64[ns]
 5   Performance_Score  406 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 22.2+ KB

In [110]:
df.sample(10)

,Employee_ID,Employee_Name,Department,Salary,Join_Date,Performance_Score
478,EMP-0478,Sneha,It,75000.0,2025-01-15,4.0
392,EMP-0392,Priya,Hr,35000.0,2025-01-15,3.0
36,EMP-0036,Anil,Hr,35000.0,2025-01-15,3.0
439,EMP-1439,Unknown,Hr,35000.0,2025-01-15,4.0
330,EMP-1330,Sneha,It,35000.0,2025-01-15,4.0
386,EMP-1386,Ravi,Hr,35000.0,2025-01-15,2.0
426,EMP-1426,Sneha,Hr,35000.0,2025-01-15,1.0
130,EMP-1130,Ravi,Hr,35000.0,2025-01-15,4.0
82,EMP-1082,Unknown,Hr,25000.0,2025-01-15,3.0
429,EMP-1429,Sneha,Finance,50000.0,2025-01-15,4.5

In [111]:
df.head()

  Employee_ID Employee_Name Department   Salary  Join_Date  Performance_Score
1    EMP-0001       Unknown         It  75000.0 2025-01-15                7.0
3    EMP-0003         Sneha         Hr  35000.0 2025-01-15                1.0
4    EMP-1004         Sneha         It  50000.0 2025-01-15                4.0
5    EMP-1005         Sneha         It  35000.0 2025-01-15                1.0
6    EMP-0006         Sneha         Hr  75000.0 2025-01-15                2.0

In [114]:
df['Department'] = df['Department'].str.upper()

In [115]:
df.head()

  Employee_ID Employee_Name Department   Salary  Join_Date  Performance_Score
1    EMP-0001       Unknown         IT  75000.0 2025-01-15                7.0
3    EMP-0003         Sneha         HR  35000.0 2025-01-15                1.0
4    EMP-1004         Sneha         IT  50000.0 2025-01-15                4.0
5    EMP-1005         Sneha         IT  35000.0 2025-01-15                1.0
6    EMP-0006         Sneha         HR  75000.0 2025-01-15                2.0

In [116]:
df.tail()

,Employee_ID,Employee_Name,Department,Salary,Join_Date,Performance_Score
495,EMP-0495,Unknown,HR,50000.0,2025-01-15,5.0
496,EMP-0496,Unknown,FINANCE,25000.0,2025-01-15,4.5
497,EMP-0497,Sneha,HR,35000.0,2025-01-15,2.0
498,EMP-0498,Priya,IT,35000.0,2025-01-15,1.0
499,EMP-1499,Anil,IT,35000.0,2025-01-15,1.0

In [117]:
df.duplicated().sum()

np.int64(0)

In [119]:
df.to_csv("cleaned_data6.csv", index=False)