##### Windows Fuction

# Pandas Rolling Function

In [1]:
import pandas as pd

## 1 — Rolling Mean

In [2]:
sales_df = pd.DataFrame({'Sales': [100, 200, 300, 400, 500, 600]})

In [5]:
sales_df

   Sales
0    100
1    200
2    300
3    400
4    500
5    600

### 1. Create a 2-row rolling mean.

In [6]:
sales_df.rolling(window=2).mean()

   Sales
0    NaN
1  150.0
2  250.0
3  350.0
4  450.0
5  550.0

In [7]:
sales_df['Sales'].rolling(window=2).mean()

0      NaN
1    150.0
2    250.0
3    350.0
4    450.0
5    550.0
Name: Sales, dtype: float64

In [8]:
sales_df['Sales'].rolling(2).mean()

0      NaN
1    150.0
2    250.0
3    350.0
4    450.0
5    550.0
Name: Sales, dtype: float64

#

### 2. Create a 3-row rolling mean.

In [9]:
sales_df['Sales'].rolling(window=3).mean()

0      NaN
1      NaN
2    200.0
3    300.0
4    400.0
5    500.0
Name: Sales, dtype: float64

In [10]:
sales_df.rolling(3).mean()

   Sales
0    NaN
1    NaN
2  200.0
3  300.0
4  400.0
5  500.0

### 3. Create a 4-row rolling mean.

In [11]:
sales_df.rolling(4).mean()

   Sales
0    NaN
1    NaN
2    NaN
3  250.0
4  350.0
5  450.0

### 4. Store result in a new column named Rolling_Avg.

In [14]:
sales_df['Rolling_Avg'] = sales_df['Sales'].rolling(2).mean()

In [15]:
sales_df

   Sales  Rolling_Avg
0    100          NaN
1    200        150.0
2    300        250.0
3    400        350.0
4    500        450.0
5    600        550.0

### 5. Find which row gets the first non-NaN value.

In [20]:
print(sales_df['Rolling_Avg'].first_valid_index())

1

### 6. Explain why first rows become NaN.

In [22]:
# rolling(3)
# Pandas needs 3 values to calculate the mean.
# Row 0 has only [10] → not enough → NaN
# Row 1 has only [10,20] → not enough → NaN
# Row 2 has [10,20,30] → enough → mean = 20

In [23]:
#WE can  avoid initial NaN: by using parameter  ----- min_periods. 
# min_periods=1 means calculation can start even with 1 value.

### 7. Create rolling mean using min_periods=1.

In [25]:
sales_df.rolling(window= 3,min_periods=1).mean()

   Sales  Rolling_Avg
0  100.0          NaN
1  150.0        150.0
2  200.0        200.0
3  300.0        250.0
4  400.0        350.0
5  500.0        450.0

In [26]:
sales_df['Sales'].rolling(window= 3,min_periods=1).mean()

0    100.0
1    150.0
2    200.0
3    300.0
4    400.0
5    500.0
Name: Sales, dtype: float64

### 8. Compare normal rolling mean vs min_periods=1.

In [27]:
sales_df['Min_Periods'] = sales_df['Sales'].rolling(2, min_periods=1).mean()

In [30]:
print(sales_df[['Rolling_Avg', 'Min_Periods']])

   Rolling_Avg  Min_Periods
0          NaN        100.0
1        150.0        150.0
2        250.0        250.0
3        350.0        350.0
4        450.0        450.0
5        550.0        550.0

### 9. Find overall difference between original sales and rolling average.

In [31]:
sales_df['Difference'] = sales_df['Sales'] - sales_df['Rolling_Avg']

In [32]:
sales_df

   Sales  Rolling_Avg  Min_Periods  Difference
0    100          NaN        100.0         NaN
1    200        150.0        150.0        50.0
2    300        250.0        250.0        50.0
3    400        350.0        350.0        50.0
4    500        450.0        450.0        50.0
5    600        550.0        550.0        50.0

### 10. Create centered rolling mean using center=True.

In [33]:
sales_df['Sales'].rolling(window= 3,min_periods=1, center=True).mean()

0    150.0
1    200.0
2    300.0
3    400.0
4    500.0
5    550.0
Name: Sales, dtype: float64

In [34]:
sales_df['Sales'].rolling(window= 3,min_periods=1).mean()

0    100.0
1    150.0
2    200.0
3    300.0
4    400.0
5    500.0
Name: Sales, dtype: float64

#

#

## 2 — Rolling Sum

In [35]:
orders_df = pd.DataFrame({'Orders': [5, 10, 15, 20, 25, 30, 35]})

In [36]:
orders_df

   Orders
0       5
1      10
2      15
3      20
4      25
5      30
6      35

### 1. Create rolling sum of last 2 rows.

In [37]:
orders_df.rolling(window=2)

Rolling [window=2,center=False,axis=0,method=single]

In [38]:
orders_df.rolling(window=2).sum()

   Orders
0     NaN
1    15.0
2    25.0
3    35.0
4    45.0
5    55.0
6    65.0

### 2. Create rolling sum of last 3 rows.

In [41]:
orders_df.rolling(window=3).sum()

   Orders
0     NaN
1     NaN
2    30.0
3    45.0
4    60.0
5    75.0
6    90.0

### 3. Create rolling sum of last 5 rows.

In [40]:
orders_df.rolling(window=5).sum()

   Orders
0     NaN
1     NaN
2     NaN
3     NaN
4    75.0
5   100.0
6   125.0

### 4. Create rolling sum using min_periods=1.

In [42]:
orders_df.rolling(window=2,min_periods=1).sum()

   Orders
0     5.0
1    15.0
2    25.0
3    35.0
4    45.0
5    55.0
6    65.0

In [45]:
orders_df['Rolling_sum'] = orders_df['Orders'].rolling(window=2, min_periods=1).sum()

In [46]:
orders_df

   Orders  Rolling_sum
0       5          5.0
1      10         15.0
2      15         25.0
3      20         35.0
4      25         45.0
5      30         55.0
6      35         65.0

### 5. Find total orders inside each rolling window.

In [47]:
orders_df.sum()

Orders         140.0
Rolling_sum    245.0
dtype: float64

### 6. Find highest rolling sum.

In [49]:
orders_df['Rolling_sum'].max()

65.0

### 7. Find lowest rolling sum.

In [50]:
orders_df['Rolling_sum'].min()

5.0

### 8. Create centered rolling sum.

In [51]:
orders_df['Centered'] = orders_df['Orders'].rolling(3, center=True).sum()

In [52]:
orders_df

   Orders  Rolling_sum  Centered
0       5          5.0       NaN
1      10         15.0      30.0
2      15         25.0      45.0
3      20         35.0      60.0
4      25         45.0      75.0
5      30         55.0      90.0
6      35         65.0       NaN

### 9. Compare rolling sum with cumulative sum.

In [56]:
orders_df['Cumulative'] = orders_df['Orders'].expanding().sum()

In [57]:
orders_df

   Orders  Rolling_sum  Centered  Cumulative
0       5          5.0       NaN         5.0
1      10         15.0      30.0        15.0
2      15         25.0      45.0        30.0
3      20         35.0      60.0        50.0
4      25         45.0      75.0        75.0
5      30         55.0      90.0       105.0
6      35         65.0       NaN       140.0

## 3 — Rolling Maximum

In [58]:
temp_df = pd.DataFrame({'Temperature': [28, 30, 27, 35, 32, 31, 36]})

In [59]:
temp_df

   Temperature
0           28
1           30
2           27
3           35
4           32
5           31
6           36

### 1. Find rolling maximum temperature using window size 2.

In [60]:
temp_df['Max_2'] = temp_df['Temperature'].rolling(2).max()

In [61]:
temp_df

   Temperature  Max_2
0           28    NaN
1           30   30.0
2           27   30.0
3           35   35.0
4           32   35.0
5           31   32.0
6           36   36.0

### 2. Find rolling maximum temperature using window size 3.

In [63]:
temp_df['Max_3'] = temp_df['Temperature'].rolling(3).max()

In [64]:
temp_df

   Temperature  Max_2  Max_3
0           28    NaN    NaN
1           30   30.0    NaN
2           27   30.0   30.0
3           35   35.0   35.0
4           32   35.0   35.0
5           31   32.0   35.0
6           36   36.0   36.0

### 3. Find hottest value inside each rolling window.

In [68]:
temp_df['Rolling_Max'] = temp_df['Temperature'].rolling(3).max()

In [69]:
temp_df

   Temperature  Max_2  Max_3  Rolling_Max
0           28    NaN    NaN          NaN
1           30   30.0    NaN          NaN
2           27   30.0   30.0         30.0
3           35   35.0   35.0         35.0
4           32   35.0   35.0         35.0
5           31   32.0   35.0         35.0
6           36   36.0   36.0         36.0

### 4. Create a new column named Rolling_Max.

In [72]:
temp_df['Centered'] = temp_df['Temperature'].rolling(3, center=True).max()
temp_df

   Temperature  Max_2  Max_3  Rolling_Max  Centered
0           28    NaN    NaN          NaN       NaN
1           30   30.0    NaN          NaN      30.0
2           27   30.0   30.0         30.0      35.0
3           35   35.0   35.0         35.0      35.0
4           32   35.0   35.0         35.0      35.0
5           31   32.0   35.0         35.0      36.0
6           36   36.0   36.0         36.0       NaN

### 5. Find maximum temperature trend.

In [74]:
temp_df['Min_Periods'] = temp_df['Temperature'].rolling(3, min_periods=1).max()

In [75]:
temp_df

   Temperature  Max_2  Max_3  Rolling_Max  Centered  Min_Periods
0           28    NaN    NaN          NaN       NaN         28.0
1           30   30.0    NaN          NaN      30.0         30.0
2           27   30.0   30.0         30.0      35.0         30.0
3           35   35.0   35.0         35.0      35.0         35.0
4           32   35.0   35.0         35.0      35.0         35.0
5           31   32.0   35.0         35.0      36.0         35.0
6           36   36.0   36.0         36.0       NaN         36.0

#

#

## 4 — Rolling Minimum

In [76]:
rain_df = pd.DataFrame({'Rainfall': [12, 8, 15, 5, 10, 7, 4]})

In [77]:
rain_df

   Rainfall
0        12
1         8
2        15
3         5
4        10
5         7
6         4

### 1. Find rolling minimum rainfall using window size 2.

In [83]:
rain_df['Min_2'] = rain_df['Rainfall'].rolling(2).min()

In [84]:
rain_df

   Rainfall  Min_2  Min_3
0        12    NaN    NaN
1         8    8.0    NaN
2        15    8.0    8.0
3         5    5.0    5.0
4        10    5.0    5.0
5         7    7.0    5.0
6         4    4.0    4.0

In [ ]:

print(rain_df)

### 2. Find rolling minimum rainfall using window size 3.

In [86]:
rain_df['Min_3'] = rain_df['Rainfall'].rolling(3).min()

In [87]:
rain_df

   Rainfall  Min_2  Min_3
0        12    NaN    NaN
1         8    8.0    NaN
2        15    8.0    8.0
3         5    5.0    5.0
4        10    5.0    5.0
5         7    7.0    5.0
6         4    4.0    4.0

### 3.  Store result in column Rolling_Min.

In [88]:
rain_df['Rolling_Min'] = rain_df['Rainfall'].rolling(3).min()

In [89]:
rain_df

   Rainfall  Min_2  Min_3  Rolling_Min
0        12    NaN    NaN          NaN
1         8    8.0    NaN          NaN
2        15    8.0    8.0          8.0
3         5    5.0    5.0          5.0
4        10    5.0    5.0          5.0
5         7    7.0    5.0          5.0
6         4    4.0    4.0          4.0

### 4. Find lowest rainfall trend.

In [92]:
rain_df['Min_Periods'] = rain_df['Rainfall'].rolling(3, min_periods=1).min()

In [93]:
rain_df

   Rainfall  Min_2  Min_3  Rolling_Min  Min_Periods
0        12    NaN    NaN          NaN         12.0
1         8    8.0    NaN          NaN          8.0
2        15    8.0    8.0          8.0          8.0
3         5    5.0    5.0          5.0          5.0
4        10    5.0    5.0          5.0          5.0
5         7    7.0    5.0          5.0          5.0
6         4    4.0    4.0          4.0          4.0

### 5. Compare rolling minimum with actual minimum.

In [94]:
rain_df[['Rainfall','Min_Periods']]

   Rainfall  Min_Periods
0        12         12.0
1         8          8.0
2        15          8.0
3         5          5.0
4        10          5.0
5         7          5.0
6         4          4.0

## 5 — Rolling Standard Deviation

In [95]:
stock_df = pd.DataFrame({'Price': [100, 105, 102, 110, 108, 115, 120]})

In [96]:
stock_df

   Price
0    100
1    105
2    102
3    110
4    108
5    115
6    120

### 1. Calculate rolling standard deviation using window size 2.

In [99]:
stock_df['STD_2']= stock_df['Price'].rolling(2).std()

In [101]:
stock_df

   Price     STD_2
0    100       NaN
1    105  3.535534
2    102  2.121320
3    110  5.656854
4    108  1.414214
5    115  4.949747
6    120  3.535534

### 2. Calculate rolling standard deviation using window size 3.

In [102]:
stock_df['STD_3'] = stock_df['Price'].rolling(3).std()

In [103]:
stock_df

   Price     STD_2     STD_3
0    100       NaN       NaN
1    105  3.535534       NaN
2    102  2.121320  2.516611
3    110  5.656854  4.041452
4    108  1.414214  4.163332
5    115  4.949747  3.605551
6    120  3.535534  6.027714

### 3. Create a column named Volatility.

In [109]:
stock_df['Volatility'] = stock_df['Price'].rolling(3).std()

In [110]:
stock_df

   Price     STD_2     STD_3  Volatility
0    100       NaN       NaN         NaN
1    105  3.535534       NaN         NaN
2    102  2.121320  2.516611    2.516611
3    110  5.656854  4.041452    4.041452
4    108  1.414214  4.163332    4.163332
5    115  4.949747  3.605551    3.605551
6    120  3.535534  6.027714    6.027714

### 4.  Find periods of high volatility.

In [127]:
high_volatility = stock_df['Volatility'] > 4

print(high_volatility)

0    False
1    False
2    False
3     True
4     True
5    False
6     True
Name: Volatility, dtype: bool

In [128]:
high_volatility = stock_df[stock_df['Volatility'] > 4]
high_volatility

   Price     STD_2     STD_3  Volatility
3    110  5.656854  4.041452    4.041452
4    108  1.414214  4.163332    4.163332
6    120  3.535534  6.027714    6.027714

### 5. Find periods of low volatility.

In [130]:
low_volatility = stock_df[stock_df['Volatility'] < 3]
low_volatility

   Price    STD_2     STD_3  Volatility
2    102  2.12132  2.516611    2.516611

#

#

## 6 — min_periods

In [131]:
marks_df = pd.DataFrame({'Marks': [45, 50, 60, 55, 70]})

In [132]:
marks_df

   Marks
0     45
1     50
2     60
3     55
4     70

### 1. Create rolling mean with window size 3.

In [134]:
marks_df['Normal'] = marks_df['Marks'].rolling(3).mean()

In [135]:
marks_df

   Marks     Normal
0     45        NaN
1     50        NaN
2     60  51.666667
3     55  55.000000
4     70  61.666667

### 2. Observe NaN values.

In [136]:
marks_df

   Marks     Normal
0     45        NaN
1     50        NaN
2     60  51.666667
3     55  55.000000
4     70  61.666667

### 3. Use min_periods=1.

In [138]:
marks_df['Min_1'] = marks_df['Marks'].rolling(3, min_periods=1).mean()
marks_df

   Marks     Normal      Min_1
0     45        NaN  45.000000
1     50        NaN  47.500000
2     60  51.666667  51.666667
3     55  55.000000  55.000000
4     70  61.666667  61.666667

### 4. Use min_periods=2.

In [139]:
marks_df['Min_2'] = marks_df['Marks'].rolling(3, min_periods=2).mean()
marks_df

   Marks     Normal      Min_1      Min_2
0     45        NaN  45.000000        NaN
1     50        NaN  47.500000  47.500000
2     60  51.666667  51.666667  51.666667
3     55  55.000000  55.000000  55.000000
4     70  61.666667  61.666667  61.666667

### 5. Use min_periods=3.

In [140]:
marks_df['Min_3'] = marks_df['Marks'].rolling(3, min_periods=3).mean()

In [141]:
marks_df

   Marks     Normal      Min_1      Min_2      Min_3
0     45        NaN  45.000000        NaN        NaN
1     50        NaN  47.500000  47.500000        NaN
2     60  51.666667  51.666667  51.666667  51.666667
3     55  55.000000  55.000000  55.000000  55.000000
4     70  61.666667  61.666667  61.666667  61.666667

#

#

## 7 — center=True

In [142]:
speed_df = pd.DataFrame({'Speed': [40, 45, 50, 55, 60, 65, 70]})

### 1. Create normal rolling mean.

In [143]:
speed_df['Normal'] = speed_df['Speed'].rolling(3).mean()

In [145]:
speed_df

   Speed  Normal
0     40     NaN
1     45     NaN
2     50    45.0
3     55    50.0
4     60    55.0
5     65    60.0
6     70    65.0

### 2. Create centered rolling mean.

In [147]:
speed_df['Centered'] = speed_df['Speed'].rolling(3, center=True).mean()
speed_df

   Speed  Normal  Centered
0     40     NaN       NaN
1     45     NaN      45.0
2     50    45.0      50.0
3     55    50.0      55.0
4     60    55.0      60.0
5     65    60.0      65.0
6     70    65.0       NaN

### 4. Create centered rolling sum.

In [149]:
speed_df['Centered_Sum'] = speed_df['Speed'].rolling(3, center=True).sum()
speed_df

   Speed  Normal  Centered  Centered_Sum
0     40     NaN       NaN           NaN
1     45     NaN      45.0         135.0
2     50    45.0      50.0         150.0
3     55    50.0      55.0         165.0
4     60    55.0      60.0         180.0
5     65    60.0      65.0         195.0
6     70    65.0       NaN           NaN

### 5. Create centered rolling max.

In [151]:
speed_df['Centered_max'] = speed_df['Speed'].rolling(3, center=True).max()

In [153]:
speed_df

   Speed  Normal  Centered  Centered_Sum  Centered_Max  Centered_max
0     40     NaN       NaN           NaN           NaN           NaN
1     45     NaN      45.0         135.0          50.0          50.0
2     50    45.0      50.0         150.0          55.0          55.0
3     55    50.0      55.0         165.0          60.0          60.0
4     60    55.0      60.0         180.0          65.0          65.0
5     65    60.0      65.0         195.0          70.0          70.0
6     70    65.0       NaN           NaN           NaN           NaN

#

#

#

## 8 — Real E-Commerce Practice

In [154]:
ecom_df = pd.DataFrame({'Orders': [120, 140, 160, 180, 200, 220, 250]})

In [155]:
ecom_df

   Orders
0     120
1     140
2     160
3     180
4     200
5     220
6     250

### 1 . Find 3-day moving average.

In [156]:
ecom_df['Avg_3'] = ecom_df['Orders'].rolling(3).mean()
ecom_df

   Orders       Avg_3
0     120         NaN
1     140         NaN
2     160  140.000000
3     180  160.000000
4     200  180.000000
5     220  200.000000
6     250  223.333333

### 2. Find 5-day moving average.

In [157]:
ecom_df['Avg_5'] = ecom_df['Orders'].rolling(5).mean()

In [158]:
ecom_df

   Orders       Avg_3  Avg_5
0     120         NaN    NaN
1     140         NaN    NaN
2     160  140.000000    NaN
3     180  160.000000    NaN
4     200  180.000000  160.0
5     220  200.000000  180.0
6     250  223.333333  202.0

### 3. Find rolling maximum orders.

In [159]:
ecom_df['Max'] = ecom_df['Orders'].rolling(3).max()

In [160]:
ecom_df

   Orders       Avg_3  Avg_5    Max
0     120         NaN    NaN    NaN
1     140         NaN    NaN    NaN
2     160  140.000000    NaN  160.0
3     180  160.000000    NaN  180.0
4     200  180.000000  160.0  200.0
5     220  200.000000  180.0  220.0
6     250  223.333333  202.0  250.0

### 4. Find rolling minimum orders.

In [161]:
ecom_df['min'] = ecom_df['Orders'].rolling(3).min()

In [162]:
ecom_df

   Orders       Avg_3  Avg_5    Max    min
0     120         NaN    NaN    NaN    NaN
1     140         NaN    NaN    NaN    NaN
2     160  140.000000    NaN  160.0  120.0
3     180  160.000000    NaN  180.0  140.0
4     200  180.000000  160.0  200.0  160.0
5     220  200.000000  180.0  220.0  180.0
6     250  223.333333  202.0  250.0  200.0

### 5. Find rolling standard deviation.

In [165]:
ecom_df['STD'] = ecom_df['Orders'].rolling(3).std()

In [166]:
ecom_df

   Orders       Avg_3  Avg_5    Max    min        STD
0     120         NaN    NaN    NaN    NaN        NaN
1     140         NaN    NaN    NaN    NaN        NaN
2     160  140.000000    NaN  160.0  120.0  20.000000
3     180  160.000000    NaN  180.0  140.0  20.000000
4     200  180.000000  160.0  200.0  160.0  20.000000
5     220  200.000000  180.0  220.0  180.0  20.000000
6     250  223.333333  202.0  250.0  200.0  25.166115

#

#

#

## 9 — GroupBy + Rolling

In [167]:
store_df = pd.DataFrame({
    'Store': ['A', 'A', 'A', 'B', 'B', 'B'],
    'Sales': [100, 200, 300, 400, 500, 600]
})

In [168]:
store_df

  Store  Sales
0     A    100
1     A    200
2     A    300
3     B    400
4     B    500
5     B    600

### 1. Create rolling mean separately for each store.

In [179]:
store_df['Mean'] = (store_df.groupby('Store')['Sales'].rolling(2).mean().reset_index(level=0, drop=True))
store_df

  Store  Sales   Mean
0     A    100    NaN
1     A    200  150.0
2     A    300  250.0
3     B    400    NaN
4     B    500  450.0
5     B    600  550.0

### 2. Create rolling sum separately for each store.

In [181]:
store_df['Sum'] = (store_df.groupby('Store')['Sales'].rolling(2).sum().reset_index(level=0, drop=True))
store_df

  Store  Sales   Mean     Sum
0     A    100    NaN     NaN
1     A    200  150.0   300.0
2     A    300  250.0   500.0
3     B    400    NaN     NaN
4     B    500  450.0   900.0
5     B    600  550.0  1100.0

### 3. Create rolling max separately for each store.

In [182]:
store_df['Max'] = (store_df.groupby('Store')['Sales'].rolling(2).max().reset_index(level=0, drop=True))

In [183]:
store_df

  Store  Sales   Mean     Sum    Max
0     A    100    NaN     NaN    NaN
1     A    200  150.0   300.0  200.0
2     A    300  250.0   500.0  300.0
3     B    400    NaN     NaN    NaN
4     B    500  450.0   900.0  500.0
5     B    600  550.0  1100.0  600.0

### 4. Create rolling min separately for each store.

In [186]:
store_df['Min'] = (store_df.groupby('Store')['Sales'].rolling(2).min().reset_index(level=0, drop=True))
store_df

  Store  Sales   Mean     Sum    Max    Min
0     A    100    NaN     NaN    NaN    NaN
1     A    200  150.0   300.0  200.0  100.0
2     A    300  250.0   500.0  300.0  200.0
3     B    400    NaN     NaN    NaN    NaN
4     B    500  450.0   900.0  500.0  400.0
5     B    600  550.0  1100.0  600.0  500.0

### 5. Create rolling std separately for each store.

In [188]:
store_df['Std'] = (store_df.groupby('Store')['Sales'].rolling(2).std().reset_index(level=0, drop=True))

In [190]:
store_df

  Store  Sales   Mean     Sum    Max    Min        Std
0     A    100    NaN     NaN    NaN    NaN        NaN
1     A    200  150.0   300.0  200.0  100.0  70.710678
2     A    300  250.0   500.0  300.0  200.0  70.710678
3     B    400    NaN     NaN    NaN    NaN        NaN
4     B    500  450.0   900.0  500.0  400.0  70.710678
5     B    600  550.0  1100.0  600.0  500.0  70.710678