# DATA CLEANING 5

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('messy_data4.csv')

In [3]:
df = data.copy(deep=True)

#

# Data Inspection

In [4]:
df.shape

(1018, 6)

In [5]:
df.head()

           Name                    Email Age    Salary       City   Join_Date
0           NaN        user229@yahoo.com  61    157964      Delhi  2020-03-02
1    Rohan Nair                      NaN  59  ₹124,974     mumbai  14/01/2020
2  Kavya  Gupta  kavyagup981@hotmail.com  -1       NaN  New Delhi  2021-06-25
3  Deepak Reddy    deepakre388@gmail.com  58   -109800  Bangalore  03/04/2020
4   Meena VERMA    meenaver888@gmail.com  47  ₹110,638       Pune  10-04-2023

In [6]:
df.tail()

,Name,Email,Age,Salary,City,Join_Date
1013,Anjali Gupta,anjaligu411@company.in,66,"172,089",Hyderabad,2023-07-14
1014,Ravi kumar,ravikuma231@outlook.com,47,"₹132,822",Kolkata,03-30-2022
1015,Rahul kumar,rahulkum700@gmail.com,59,124646.00,Mumbai,21/06/2023
1016,Vikram Kumar,vikramku969@gmail.com,33,178969.00,Hyderabad,2020/02/16
1017,Name,Email,Age,Salary,City,Join_Date

In [7]:
df.dtypes

Name         object
Email        object
Age          object
Salary       object
City         object
Join_Date    object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1018 entries, 0 to 1017
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       887 non-null    object
 1   Email      904 non-null    object
 2   Age        914 non-null    object
 3   Salary     910 non-null    object
 4   City       711 non-null    object
 5   Join_Date  1003 non-null   object
dtypes: object(6)
memory usage: 47.8+ KB

In [9]:
df.describe().T

          count unique               top freq
Name        887    362                     20
Email       904    846  user@@domain.com   21
Age         914     77                42   27
Salary      910    741                 0  159
City        711     26           Kolkata   38
Join_Date  1003    934         Join_Date    3

In [10]:
df.isnull().sum()

Name         131
Email        114
Age          104
Salary       108
City         307
Join_Date     15
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(16)

In [12]:
for col in df.columns:
    print(col, df[col].unique()[:10])
    print()

Name [nan 'Rohan Nair' 'Kavya  Gupta' 'Deepak Reddy' 'Meena VERMA'
 'Kavya Kumar' 'Pooja Verma' 'Vikram sharma' 'Amit Verma' 'Ravi sharma']

Email ['user229@yahoo.com' nan 'kavyagup981@hotmail.com' 'deepakre388@gmail.com'
 'meenaver888@gmail.com' 'kavyakum747@yahoo.com' 'poojaver68@yahoo.com'
 'vikramsh552@hotmail.com' 'amitverm164@rediffmail.com'
 'ravishar301@outlook.com']

Age ['61' '59' '-1' '58' '47' '42' '54' '45' '22' '18']

Salary ['157964' '₹124,974' nan '-109800' '₹110,638' '0' '₹97,490' '119,700'
 '171208.00' '-84045']

City ['Delhi' 'mumbai' 'New Delhi' 'Bangalore' 'Pune' 'NEW DELHI' '  Chennai'
 'Chennai' 'bengaluru' 'Bengaluru']

Join_Date ['2020-03-02' '14/01/2020' '2021-06-25' '03/04/2020' '10-04-2023'
 '2021-10-26' '09-Aug-2023' '09-Nov-2022' '2020-01-24' '08-05-2020']

In [13]:
df[df.isnull().any(axis=1)]

,Name,Email,Age,Salary,City,Join_Date
0,NaN,user229@yahoo.com,61,157964,Delhi,2020-03-02
1,Rohan Nair,NaN,59,"₹124,974",mumbai,14/01/2020
2,Kavya Gupta,kavyagup981@hotmail.com,-1,NaN,New Delhi,2021-06-25
10,Lakshmi Reddy,lakshmir553@company.in,56,20105,NaN,21/09/2021
12,rahul Gupta,rahulgup774@rediffmail.com,63,0,NaN,25-Nov-2022
...,...,...,...,...,...,...
1005,Unknown VERMA,NaN,34,35783.00,NaN,2021/01/27
1008,NaN,null727@hotmail.com,57,174728.00,new delhi,05-04-2023
1010,Ravi patel,NaN,23,"162,148",NaN,12-20-2022
1011,PRIYA VERMA,priyaver479@gmail.com,55,-107176,NaN,02-17-2020
1012,john doe,johndoe551@yahoo.com,25,NaN,Hyderabad,03-14-2023

In [17]:
df[df['Name'] == 'Name']

      Name  Email  Age  Salary  City  Join_Date
100   Name  Email  Age  Salary  City  Join_Date
606   Name  Email  Age  Salary  City  Join_Date
1017  Name  Email  Age  Salary  City  Join_Date

#

# Data Cleaning

In [18]:
# Remove blank rows

In [19]:
df = df.dropna(how='all')

In [20]:
df = df[df['Name'] != 'Name']

In [22]:
df.columns

Index(['Name', 'Email', 'Age', 'Salary', 'City', 'Join_Date'], dtype='object')

In [23]:
for col in df.columns:
    df[col] = df[col].str.strip().str.title()

In [24]:
df.drop_duplicates(inplace=True)

#

In [26]:
for col in [ 'Age', 'Salary']:
    df[col] = pd.to_numeric(df[col],errors='coerce')

In [27]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

In [28]:
df.dtypes

Name                 object
Email                object
Age                 float64
Salary              float64
City                 object
Join_Date    datetime64[ns]
dtype: object

#

In [30]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,883.0,44.744054,-1.0,30.0,45.0,58.0,200.0,19.609861
Salary,593.0,20030.917369,-199973.0,-34629.0,0.0,109119.0,199714.0,101733.548223
Join_Date,200,2022-01-10 13:48:00,2020-01-10 00:00:00,2021-01-19 00:00:00,2021-12-23 00:00:00,2023-01-13 12:00:00,2024-02-05 00:00:00,NaN

In [32]:
df.loc[(df['Age']>110) | (df['Age']<15) ,'Age'] = np.nan

In [34]:
df.loc[df['Salary']<10500,'Salary'] = np.nan

In [35]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,871.0,44.216992,18.0,30.0,45.0,58.0,70.0,15.313955
Salary,269.0,109578.486989,15044.0,58597.0,116494.0,158797.0,199714.0,54888.818884
Join_Date,200,2022-01-10 13:48:00,2020-01-10 00:00:00,2021-01-19 00:00:00,2021-12-23 00:00:00,2023-01-13 12:00:00,2024-02-05 00:00:00,NaN

In [36]:
df.head()

           Name                    Email   Age    Salary       City  Join_Date
0           NaN        User229@Yahoo.Com  61.0  157964.0      Delhi 2020-03-02
1    Rohan Nair                      NaN  59.0       NaN     Mumbai        NaT
2  Kavya  Gupta  Kavyagup981@Hotmail.Com   NaN       NaN  New Delhi 2021-06-25
3  Deepak Reddy    Deepakre388@Gmail.Com  58.0       NaN  Bangalore        NaT
4   Meena Verma    Meenaver888@Gmail.Com  47.0       NaN       Pune        NaT

In [37]:
data.head()

           Name                    Email Age    Salary       City   Join_Date
0           NaN        user229@yahoo.com  61    157964      Delhi  2020-03-02
1    Rohan Nair                      NaN  59  ₹124,974     mumbai  14/01/2020
2  Kavya  Gupta  kavyagup981@hotmail.com  -1       NaN  New Delhi  2021-06-25
3  Deepak Reddy    deepakre388@gmail.com  58   -109800  Bangalore  03/04/2020
4   Meena VERMA    meenaver888@gmail.com  47  ₹110,638       Pune  10-04-2023

In [38]:
df['Salary'] = data['Salary']

In [39]:
df['Join_Date'] = data['Join_Date']

In [40]:
df.dtypes

Name          object
Email         object
Age          float64
Salary        object
City          object
Join_Date     object
dtype: object

#

In [42]:
df['Salary'].unique()[:10]

array(['157964', '₹124,974', nan, '-109800', '₹110,638', '0', '₹97,490',
       '119,700', '171208.00', '-84045'], dtype=object)

In [43]:
df['Salary'] = df['Salary'].replace(r'\D', '', regex=True)

In [44]:
df['Salary'].unique()[:10]

array(['157964', '124974', nan, '109800', '110638', '0', '97490',
       '119700', '17120800', '84045'], dtype=object)

#

In [45]:
df['temp_date'] = pd.to_datetime(df['Join_Date'],errors='coerce')

In [47]:
df[['temp_date','Join_Date']]

      temp_date   Join_Date
0    2020-03-02  2020-03-02
1           NaT  14/01/2020
2    2021-06-25  2021-06-25
3           NaT  03/04/2020
4           NaT  10-04-2023
...         ...         ...
1012        NaT  03-14-2023
1013 2023-07-14  2023-07-14
1014        NaT  03-30-2022
1015        NaT  21/06/2023
1016        NaT  2020/02/16

[1000 rows x 2 columns]

In [48]:
df['mix_temp_date'] = pd.to_datetime(df['Join_Date'],format='mixed',errors='coerce')

In [49]:
df[['temp_date','Join_Date','mix_temp_date']]

      temp_date   Join_Date mix_temp_date
0    2020-03-02  2020-03-02    2020-03-02
1           NaT  14/01/2020    2020-01-14
2    2021-06-25  2021-06-25    2021-06-25
3           NaT  03/04/2020    2020-03-04
4           NaT  10-04-2023    2023-10-04
...         ...         ...           ...
1012        NaT  03-14-2023    2023-03-14
1013 2023-07-14  2023-07-14    2023-07-14
1014        NaT  03-30-2022    2022-03-30
1015        NaT  21/06/2023    2023-06-21
1016        NaT  2020/02/16    2020-02-16

[1000 rows x 3 columns]

In [53]:
df.drop(columns=['temp_date','mix_temp_date'],inplace=True)

In [54]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], format='mixed',errors='coerce')

#

In [55]:
df.head()

           Name                    Email   Age  Salary       City  Join_Date
0           NaN        User229@Yahoo.Com  61.0  157964      Delhi 2020-03-02
1    Rohan Nair                      NaN  59.0  124974     Mumbai 2020-01-14
2  Kavya  Gupta  Kavyagup981@Hotmail.Com   NaN     NaN  New Delhi 2021-06-25
3  Deepak Reddy    Deepakre388@Gmail.Com  58.0  109800  Bangalore 2020-03-04
4   Meena Verma    Meenaver888@Gmail.Com  47.0  110638       Pune 2023-10-04

In [56]:
df['City'].unique()

array(['Delhi', 'Mumbai', 'New Delhi', 'Bangalore', 'Pune', 'Chennai',
       'Bengaluru', nan, 'Ahmedabad.', 'Bombay', 'Ahmedabad', 'Unknown',
       'Hyderabad', 'Pune,', 'Kolkata'], dtype=object)

In [59]:
df['City'].str.replace(r'[^a-zA-Z\s]','',regex=True).unique()

array(['Delhi', 'Mumbai', 'New Delhi', 'Bangalore', 'Pune', 'Chennai',
       'Bengaluru', nan, 'Ahmedabad', 'Bombay', 'Unknown', 'Hyderabad',
       'Kolkata'], dtype=object)

In [61]:
df['City'] = df['City'].str.replace(r'[^a-zA-Z\s]','',regex=True)

In [62]:
city_map = {
    'New Delhi': 'Delhi',
    'Bangalore': 'Bengaluru',
    'Bombay': 'Mumbai'
}

In [63]:
df['City'] = df['City'].replace(city_map)

In [64]:
df['City'].unique()

array(['Delhi', 'Mumbai', 'Bengaluru', 'Pune', 'Chennai', nan,
       'Ahmedabad', 'Unknown', 'Hyderabad', 'Kolkata'], dtype=object)

#

In [66]:
pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

In [67]:
df['Email'] = df['Email'].where(df['Email'].str.match(pattern, na=False),np.nan)

#

#### Fill Missing Values

In [68]:
df.isnull().sum()

Name         116
Email        211
Age          129
Salary        93
City         292
Join_Date      0
dtype: int64

In [76]:
df["Age"] = df['Age'].fillna(df["Age"].mean().round())

In [81]:
df['Salary'] = pd.to_numeric(df['Salary'],errors='coerce')

In [82]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [83]:
df['City'] = df['City'].fillna(df['City'].ffill())

In [84]:
df.isnull().sum()

Name         116
Email        211
Age            0
Salary         0
City           0
Join_Date      0
dtype: int64

In [85]:
df.head()

           Name                    Email   Age    Salary       City  Join_Date
0           NaN        User229@Yahoo.Com  61.0  157964.0      Delhi 2020-03-02
1    Rohan Nair                      NaN  59.0  124974.0     Mumbai 2020-01-14
2  Kavya  Gupta  Kavyagup981@Hotmail.Com  44.0  107677.0      Delhi 2021-06-25
3  Deepak Reddy    Deepakre388@Gmail.Com  58.0  109800.0  Bengaluru 2020-03-04
4   Meena Verma    Meenaver888@Gmail.Com  47.0  110638.0       Pune 2023-10-04

In [86]:
df.tail()

,Name,Email,Age,Salary,City,Join_Date
1012,John Doe,Johndoe551@Yahoo.Com,25.0,107677.0,Hyderabad,2023-03-14
1013,Anjali Gupta,Anjaligu411@Company.In,66.0,172089.0,Hyderabad,2023-07-14
1014,Ravi Kumar,Ravikuma231@Outlook.Com,47.0,132822.0,Kolkata,2022-03-30
1015,Rahul Kumar,Rahulkum700@Gmail.Com,59.0,12464600.0,Mumbai,2023-06-21
1016,Vikram Kumar,Vikramku969@Gmail.Com,33.0,17896900.0,Hyderabad,2020-02-16

In [90]:
df[df['Name']=='']

    Name                   Email   Age      Salary       City  Join_Date
56                           NaN  48.0     63329.0  Hyderabad 2022-09-05
124            User309@Gmail.Com  44.0  17826600.0      Delhi 2022-10-20
176                          NaN  63.0         0.0    Unknown 2022-06-17
245          User244@Outlook.Com  21.0         0.0      Delhi 2021-04-19
248          User322@Outlook.Com  44.0   6943000.0     Mumbai 2020-09-02
296            User314@Yahoo.Com  44.0    107677.0       Pune 2024-01-30
313             User48@Gmail.Com  38.0    107677.0  Bengaluru 2023-03-26
323          User621@Hotmail.Com  42.0         0.0     Mumbai 2022-03-25
472             User32@Yahoo.Com  55.0         0.0    Chennai 2022-06-10
526            User589@Yahoo.Com  41.0         0.0    Unknown 2021-10-11
591            User152@Gmail.Com  31.0     62357.0    Unknown 2021-07-12
613          User506@Hotmail.Com  53.0    107677.0    Kolkata 2021-06-18
670            User134@Yahoo.Com  42.0     98349.0      Delhi 2021-05-15
729                          NaN  44.0         0.0  Bengaluru 2022-01-23
731                          NaN  38.0     92810.0       Pune 2020-10-28
834          User439@Hotmail.Com  56.0  12926200.0      Delhi 2023-11-11
844            User126@Gmail.Com  34.0     39320.0  Hyderabad 2021-03-01
889                          NaN  25.0     79803.0      Delhi 2020-02-20
910          User926@Hotmail.Com  39.0     30184.0  Bengaluru 2020-01-21
981       User857@Rediffmail.Com  44.0     38111.0    Kolkata 2024-02-03

In [91]:
df = df[df['Name']!='']

In [92]:
df[df['Name']=='']

Empty DataFrame
Columns: [Name, Email, Age, Salary, City, Join_Date]
Index: []

In [93]:
df.isnull().sum()

Name         116
Email        206
Age            0
Salary         0
City           0
Join_Date      0
dtype: int64

In [95]:
df[df['Name'].isna()]

     Name                   Email   Age      Salary       City  Join_Date
0     NaN       User229@Yahoo.Com  61.0    157964.0      Delhi 2020-03-02
17    NaN                     NaN  66.0   5859700.0       Pune 2022-04-01
18    NaN     User949@Outlook.Com  62.0         0.0    Chennai 2021-01-23
22    NaN                     NaN  22.0    111869.0    Unknown 2023-01-17
30    NaN  User354@Rediffmail.Com  45.0    149066.0  Bengaluru 2021-01-24
...   ...                     ...   ...         ...        ...        ...
967   NaN       Null609@Yahoo.Com  44.0     74252.0     Mumbai 2021-01-29
977   NaN                     NaN  27.0     61375.0  Ahmedabad 2020-09-01
980   NaN      Null283@Company.In  50.0         0.0     Mumbai 2021-09-29
1004  NaN        User40@Yahoo.Com  64.0   4150800.0     Mumbai 2020-06-10
1008  NaN     Null727@Hotmail.Com  57.0  17472800.0      Delhi 2023-05-04

[116 rows x 6 columns]

In [96]:
df[df['Name'].isna()][-10:]

     Name                Email   Age      Salary       City  Join_Date
929   NaN  User325@Hotmail.Com  54.0     78970.0  Bengaluru 2022-11-01
933   NaN                  NaN  53.0         0.0  Bengaluru 2020-03-10
950   NaN                  NaN  43.0  12646300.0      Delhi 2021-07-03
955   NaN    User705@Yahoo.Com  44.0         0.0    Unknown 2021-07-06
966   NaN  User154@Outlook.Com  44.0         0.0     Mumbai 2020-07-11
967   NaN    Null609@Yahoo.Com  44.0     74252.0     Mumbai 2021-01-29
977   NaN                  NaN  27.0     61375.0  Ahmedabad 2020-09-01
980   NaN   Null283@Company.In  50.0         0.0     Mumbai 2021-09-29
1004  NaN     User40@Yahoo.Com  64.0   4150800.0     Mumbai 2020-06-10
1008  NaN  Null727@Hotmail.Com  57.0  17472800.0      Delhi 2023-05-04

In [104]:
df[(df['Name'].isna()) & (df['Email'].isna())].shape

(54, 6)

In [107]:
df[~((df['Name'].isna()) & (df['Email'].isna()))]

,Name,Email,Age,Salary,City,Join_Date
0,NaN,User229@Yahoo.Com,61.0,157964.0,Delhi,2020-03-02
1,Rohan Nair,NaN,59.0,124974.0,Mumbai,2020-01-14
2,Kavya Gupta,Kavyagup981@Hotmail.Com,44.0,107677.0,Delhi,2021-06-25
3,Deepak Reddy,Deepakre388@Gmail.Com,58.0,109800.0,Bengaluru,2020-03-04
4,Meena Verma,Meenaver888@Gmail.Com,47.0,110638.0,Pune,2023-10-04
...,...,...,...,...,...,...
1012,John Doe,Johndoe551@Yahoo.Com,25.0,107677.0,Hyderabad,2023-03-14
1013,Anjali Gupta,Anjaligu411@Company.In,66.0,172089.0,Hyderabad,2023-07-14
1014,Ravi Kumar,Ravikuma231@Outlook.Com,47.0,132822.0,Kolkata,2022-03-30
1015,Rahul Kumar,Rahulkum700@Gmail.Com,59.0,12464600.0,Mumbai,2023-06-21
1016,Vikram Kumar,Vikramku969@Gmail.Com,33.0,17896900.0,Hyderabad,2020-02-16

In [108]:
df = df[~((df['Name'].isna()) & (df['Email'].isna()))]

In [109]:
df.isnull().sum()

Name          62
Email        152
Age            0
Salary         0
City           0
Join_Date      0
dtype: int64

In [112]:
df.dropna(subset='Name',inplace=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_17828\271151142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset='Name',inplace=True)

In [113]:
df.isnull().sum()

Name           0
Email        152
Age            0
Salary         0
City           0
Join_Date      0
dtype: int64

In [114]:
df['Email'].fillna('Unknown',inplace=True)

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_17828\1313365131.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Email'].fillna('Unknown',inplace=True)
C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_17828\1313365131.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Email'].fillna('Unknown',inplace=True)

In [115]:
df.isnull().sum()

Name         0
Email        0
Age          0
Salary       0
City         0
Join_Date    0
dtype: int64

In [117]:
df["Age"]  = df['Age'].astype('Int64')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_17828\642098386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]  = df['Age'].astype('Int64')

In [118]:
df.dtypes

Name                 object
Email                object
Age                   Int64
Salary              float64
City                 object
Join_Date    datetime64[ns]
dtype: object

In [119]:
df.head(20)

,Name,Email,Age,Salary,City,Join_Date
1,Rohan Nair,Unknown,59,124974.0,Mumbai,2020-01-14
2,Kavya Gupta,Kavyagup981@Hotmail.Com,44,107677.0,Delhi,2021-06-25
3,Deepak Reddy,Deepakre388@Gmail.Com,58,109800.0,Bengaluru,2020-03-04
4,Meena Verma,Meenaver888@Gmail.Com,47,110638.0,Pune,2023-10-04
5,Kavya Kumar,Kavyakum747@Yahoo.Com,42,0.0,Delhi,2021-10-26
6,Pooja Verma,Poojaver68@Yahoo.Com,54,97490.0,Chennai,2023-08-09
7,Vikram Sharma,Vikramsh552@Hotmail.Com,45,119700.0,Chennai,2022-11-09
8,Amit Verma,Amitverm164@Rediffmail.Com,22,17120800.0,Bengaluru,2020-01-24
9,Ravi Sharma,Ravishar301@Outlook.Com,18,84045.0,Bengaluru,2020-08-05
10,Lakshmi Reddy,Lakshmir553@Company.In,56,20105.0,Bengaluru,2021-09-21
11,Priya Nair,Priyanai88@Rediffmail.Com,22,154645.0,Ahmedabad,2023-01-30
12,Rahul Gupta,Rahulgup774@Rediffmail.Com,63,0.0,Ahmedabad,2022-11-25
13,Sneha Nair,Snehanai603@Company.In,32,107677.0,Delhi,2021-04-13
14,Divya Verma,Unknown,60,156356.0,Delhi,2023-03-15
15,John Doe Nair,Johndoen195@Gmail.Com,44,12603800.0,Mumbai,2020-04-20
16,Priya Patel,Priyapat112@Yahoo.Com,52,125593.0,Ahmedabad,2020-06-03
19,Rohan Verma,Rohanver766@Hotmail.Com,44,146819.0,Bengaluru,2020-06-13
20,Amit Kumar,Amitkuma123@Company.In,56,107677.0,Bengaluru,2023-09-08
21,N/A Kumar,Unknown,43,184214.0,Bengaluru,2020-05-28
23,Sharma,Sharma955@Rediffmail.Com,44,0.0,Mumbai,2021-07-31

In [120]:
df.tail(20)

,Name,Email,Age,Salary,City,Join_Date
995,Pooja Gupta,Poojagup349@Company.In,57,119380.0,Chennai,2022-10-20
996,Priya Reddy,Unknown,29,89701.0,Unknown,2022-09-11
997,Rahul Gupta,Rahulgup530@Gmail.Com,23,0.0,Unknown,2020-01-26
998,Amit Kumar Patel,Amitkuma466@Gmail.Com,60,29289.0,Mumbai,2023-07-22
999,Reddy,Reddy730@Hotmail.Com,41,107677.0,Bengaluru,2022-02-24
1000,Vikram Sharma,Vikramsh605@Hotmail.Com,70,13427200.0,Bengaluru,2021-07-30
1001,Sneha,Unknown,41,0.0,Unknown,2020-02-18
1002,Rahul Gupta,Rahulgup458@Hotmail.Com,20,0.0,Unknown,2022-03-22
1003,Anjali Kumar,Unknown,49,87009.0,Mumbai,2023-06-18
1005,Unknown Verma,Unknown,34,3578300.0,Mumbai,2021-01-27
1006,Rahul Verma,Rahulver813@Yahoo.Com,21,138972.0,Kolkata,2021-07-16
1007,Rahul Verma,Rahulver695@Hotmail.Com,44,0.0,Mumbai,2022-08-05
1009,John Doe Patel,Johndoep352@Hotmail.Com,70,0.0,Bengaluru,2023-11-29
1010,Ravi Patel,Unknown,23,162148.0,Bengaluru,2022-12-20
1011,Priya Verma,Priyaver479@Gmail.Com,55,107176.0,Bengaluru,2020-02-17
1012,John Doe,Johndoe551@Yahoo.Com,25,107677.0,Hyderabad,2023-03-14
1013,Anjali Gupta,Anjaligu411@Company.In,66,172089.0,Hyderabad,2023-07-14
1014,Ravi Kumar,Ravikuma231@Outlook.Com,47,132822.0,Kolkata,2022-03-30
1015,Rahul Kumar,Rahulkum700@Gmail.Com,59,12464600.0,Mumbai,2023-06-21
1016,Vikram Kumar,Vikramku969@Gmail.Com,33,17896900.0,Hyderabad,2020-02-16

In [121]:
df.to_csv('Clean_data_5.csv')